### ISSUE TITLE
CMake: default parameters always assumes OpenSSL to be present

### ISSUE THREAD

**Issue by kamgha** [panda3d/panda3d#1013]
## Description
The default CMake configure script always assumes OpenSSL to be present. While it checks other components to be present (e. g. in the thirdparty-dir or system-wide), it does not look like this is being done for OpenSSL. The cmake configure summary lists OpenSSL with a `+`, assuming to have it present and enabled.  An explicit `-DHAVE_OPENSSL=OFF` has to be given on the command line for `cmake` in order to have a successful build without OpenSSL being present.

Note: Unlike for many other components, the generated CMakeChache.txt does not list a `HAVE_OPENSSL` entry by default, neither.

## Steps to Reproduce
1. Create a (sub)directory for an out-of-source build and `cd` into it.
2. Make sure OpenSSL is not available in the thirdparty dir nor cmake would find it on the system
3. run `cmake -DHAVE_AUDIO=OFF -DHAVE_PYTHON=OFF ..` and look at the summary and the generated `dtool_config.h`. It will have `HAVE_OPENSSL` set.

## Environment
 * Operating system: Windows 7; FreeBSD 11
 * System architecture: x86_64
 * Panda3D version: git master 16f489a...
 * Installation method: from source
 * Python version (if using Python): 3.7
 * Compiler (if using C++): MSVC 2015; GCC 9.2

**Comment by rdb** [comment]
@CFSworks may be able to confirm, but I seem to recall that this was done on purpose for a handful of thirdparty libraries considered "essential".  The reasoning was that we want to prevent users from building Panda without these libraries by accident, by erroring if they weren't found and requiring users to explicitly disable them if they really didn't want it.

I'm a little on the fence about whether OpenSSL should be considered "essential", though.

**Comment by kamgha** [comment]
An audio library being present looks like being "essential": https://github.com/panda3d/panda3d/blob/508444d27f71fa90b9ce34646354e673133d2680/panda/src/audiotraits/CMakeLists.txt#L3 and if not found, cmake will prompt the user about it.

For the issue here with OpenSSL, it looks a bit different. `cmake -DHAVE_AUDIO=OFF ..` prints out:

```
CMake Error in contrib/src/rplight/CMakeLists.txt:
  Target "p3contribbase" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "OPENSSL_INCLUDE_DIR-NOTFOUND"


CMake Error in contrib/src/rplight/CMakeLists.txt:
  Target "p3contribbase" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "OPENSSL_INCLUDE_DIR-NOTFOUND"


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by rdb** [comment]
It looks like the error message is only being displayed on the second run, because the code to check it put *before* the code that defines the HAVE_OPENSSL variable.  This is easy to fix.

It's not an issue for OpenAL because that's handled via a different mechanism.
