### ISSUE TITLE
makepanda: MSVC 2015+ defaults to /arch:SSE2 for x86 32bit

### ISSUE THREAD

**Issue by kamgha** [panda3d/panda3d#1017]
## Description
According to the MSVC 2015/'17/'19 docs, `/arch` for the x86 (32 bit) target defaults to `/arch:SSE2` when not specified, see: https://docs.microsoft.com/en-us/cpp/build/reference/arch-x86?view=vs-2015

https://github.com/panda3d/panda3d/blob/master/makepanda/makepanda.py#L1114-L1115

would need to be rewritten in order to check whether we are building for x86 (not x64, there can be an ARM target), and whether we are not building for SSE2 to explicitly state `/arch:IA32`.

## Environment
 * Operating system: earlier than Windows 7 (W7 requires SSE2, afaik)
 * System architecture: x86 32bit
 * Panda3D version: git master 66ac3be604b6bf8cd26ebadb2103fbd3235bbd25
 * Installation method: from source
 * Python version (if using Python): 3.7.9
 * Compiler (if using C++): MSVC 2015

**Comment by rdb** [comment]
Oof.  That means that Panda 1.10 requires SSE2, effectively.  I'm wondering whether we should revert that and ensure 1.10.7 32-bit works on non-SSE2 machines, or whether we should just make it official and require SSE2 across the board.
