### ISSUE TITLE
Windows wheel is compiled against an old version of assimp. 

### ISSUE THREAD

**Issue by DustinReagan** [panda3d/panda3d#1020]
## Description
Per discussion on this thread: https://discourse.panda3d.org/t/panda3d-1-10-7-hangs-indefinitely-when-loading-obj-file-on-windows-10-works-on-macos/26440, Attempting to load an .obj file in panda3 (1.10.7) on windows 10 causes the application to hang indefinitely, while it loads the same file fine on macOs.

## Steps to Reproduce

```
from direct.showbase.ShowBase import ShowBase
from panda3d.core import ConfigVariableString
import panda3d

if __name__ == '__main__':

    print('Panda3d Version: ', panda3d.__version__)
    loadFileType = ConfigVariableString('load-file-type')
    print('load-file-type Config settings: ', loadFileType.getValue())
    base = ShowBase()
    print('loading...')
    model = loader.loadModel("../../data/Crystal_2020.06.30_L.obj")
    print('loaded!')
    model.reparentTo(render)
    base.run()
```

Output:

```
Panda3d Version: 1.10.7
load-file-type Config settings: p3assimp
Known pipe types:
wglGraphicsPipe
(all display modules loaded.)
loading…
```

## Environment
 * Operating system: Windows 10
 * System architecture: 
 * Panda3D version: 1.10.7
 * Installation method: `pip install panda3d`
 * Python version (if using Python): 3.7.7

**Comment by rdb** [comment]
Updated Assimp in 1.10.8 thirdparty packages.
