### ISSUE TITLE
Filled Wireframes do not behave as expected on ShaderTerrainMesh nodes

### ISSUE THREAD

**Issue by thetestgame** [panda3d/panda3d#1021]
## Description
with ``set_render_mode_wireframe`` on a ShaderTerrainMesh node you get the expected result of a wireframe of the terrain. https://gyazo.com/2a170966601fd5759f0e43c55a1d1005

However when using ``set_render_mode_filled_wireframe`` the wireframe is a flat sheet under the terrain and does not take into account the terrain's heightfield data. https://gyazo.com/31fdd51827dbd003cbb0d03092e66378

## Steps to Reproduce
Call ``set_render_mode_filled_wireframe`` on the Shader-Terrain sample

## Environment
 * Operating system: Windows
 * System architecture: x64
 * Panda3D version: 1.10.7
 * Installation method: pip
 * Python version (if using Python): 3.8
 * Compiler (if using C++):

**Comment by rdb** [comment]
I think the problem is that we clear the shader on the wireframe part.
