### ISSUE TITLE
No wheels available for Python 3.9

### ISSUE THREAD

**Issue by StefanAquila** [panda3d/panda3d#1030]
## Description
Hi mighty developers, problem starts when I create a virtual env and try to install in panda3d using pip.CMD constantly throws notes:
Error: Could not find a version that satisfies the requirement panda3d=1.10.7 (from vresion:none)
Error: No matching distributions found for panda3d==1.10.7

![Panda3d problem](https://user-images.githubusercontent.com/72419544/95141898-a290d900-0772-11eb-96ac-05f1a992e17c.png)

 * Operating system:Windows 10
 * Installation method: (eg. pip, wheel, SDK, built from source):pip 20.2.3
 * Python version (if using Python):3.9

Thank you!

**Comment by Moguri** [comment]
This is because there are no Python 3.9 builds of Panda 1.10.7 on PyPI: https://pypi.org/project/Panda3D/#files

**Comment by rdb** [comment]
Try again.  I have just uploaded Python 3.9 wheels for Windows and macOS, and will upload Linux wheels as soon as they are ready.

I will also update the installers on the download page to include Python 3.9 bindings.

**Comment by StefanAquila** [comment]
Thank you guys for quick reply and help.
I managed to install now with a new update.
Wish you great success in Q4 2020!
