### ISSUE TITLE
DirectX support issue on Windows 10 with fresh installation

### ISSUE THREAD

**Issue by Harshharsh2275** [panda3d/panda3d#1034]
Hi 
I recently installed panda3d on my windows 10 PC with i3 Intel HD 3000
Graphic card and DirectX version 11.1 with `pip install panda3d` command

But when I tried to run some examples
It shows me a giant error like this:
`:display(warning): unable to load libpandadx9.so: path not found`
And much more
I have edited the config.prc file and commented the pandagl and uncommented pandadx9 line.

And I don't understand why it's looking for .so file in windows os it must look for  a .dll file if I am write

**Comment by Harshharsh2275** [comment]
> Can you load `libpandadx9.dll` into Dependency Walker and see what it is missing, please?
> 
> The `.so` should just come from the message printing it (could be improved), Panda will still look for `.dll` on Windows.

@kamgha And how to do so?

**Comment by kamgha** [comment]
> And how to do so?

1. Download "Depedency Walker" from https://www.dependencywalker.com/
2. Load `Panda3D\bin\libpandadx9.dll` into it
3. Post a screenshot, that should be enough

I wonder whether Windows 10 ships with the complete set of the latest DX9. If it complains not finding D3DX9_43.dll, install this: https://www.microsoft.com/en-us/download/details.aspx?id=35

**Comment by Harshharsh2275** [comment]
Sorry for delayed reply I followed your instructions and this image of dependency walker after opening libpandadx.dll:-
![IMG20201017200021.jpg](https://user-images.githubusercontent.com/53533396/96339650-ad713500-10b3-11eb-8244-3b1460972b63.jpg)
I don't get the error so assist me please fix this

**Comment by kamgha** [comment]
Your `libpandadx9.dll` is 64bit, please use the 64bit variant of Dependency Walker.

After loading the DLL, please click on _File_ -> _Save As_ and upload the resulting `.dwi` file.

**Comment by Harshharsh2275** [comment]
I am certain that I have used the correct 64bit version and it shows the same result but although where I have to upload the .dwi file

**Comment by kamgha** [comment]
I have just tried it out myself on a fresh Windows 10 installation. It does not ship with `D3DX9_43.dll` (which no version of Windows ever did, to my knowledge). Please install https://www.microsoft.com/en-us/download/details.aspx?id=35 and report back, whether it fixes your problem.

**Comment by rdb** [comment]
I added the DirectX DLL to the extras/bin directory in the thirdparty archive, which should resolve this.
