### ISSUE TITLE
macOS: Thousand warnings from eigen when compiling with latest Xcode

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#1040]
## Description

With the latest Xcode 12 on macOS, the compilation generates thousands of warnings due to some invalid code in libeigen:

<pre>
In file included from panda/src/cocoadisplay/p3cocoadisplay_composite1.mm:1:
In file included from panda/src/cocoadisplay/config_cocoadisplay.mm:15:
In file included from panda/src/cocoadisplay/cocoaGraphicsBuffer.h:18:
In file included from built/include/glgsg.h:90:
In file included from built/include/glstuff_src.h:32:
In file included from built/include/glTextureContext_src.h:15:
In file included from built/include/textureContext.h:20:
In file included from built/include/texture.h:25:
In file included from built/include/graphicsStateGuardianBase.h:21:
In file included from built/include/luse.h:41:
In file included from built/include/aa_luse.h:24:
In file included from built/include/lsimpleMatrix.h:20:
In file included from built/include/Eigen/Dense:1:
In file included from built/include/Eigen/Core:284:
built/include/Eigen/src/Core/Assign.h:57:41: warning: converting the enum constant to a boolean [-Wint-in-bool-context]
    MaySliceVectorize  = MightVectorize && DstHasDirectAccess
                                        ^
built/include/Eigen/src/Core/Assign.h:53:57: warning: converting the enum constant to a boolean [-Wint-in-bool-context]
    MayLinearVectorize = MightVectorize && MayLinearize && DstHasDirectAccess
                                                        ^
built/include/Eigen/src/Core/Assign.h:506:78: note: in instantiation of template class 'Eigen::internal::assign_traits<Eigen::Matrix<double, 1, 2, 3, 1, 2>, Eigen::Matrix<double, 1, 2, 1, 1, 2> >' requested here
  internal::assign_impl<Derived, OtherDerived, int(SameType) ? int(internal::assign_traits<Derived, OtherDerived>::Traversal)
                                                                             ^
built/include/Eigen/src/Core/PlainObjectBase.h:414:20: note: in instantiation of function template specialization 'Eigen::DenseBase<Eigen::Matrix<double, 1, 2, 3, 1, 2> >::lazyAssign<Eigen::Matrix<double, 1, 2, 1, 1, 2> >' requested here
      return Base::lazyAssign(other.derived());
                   ^
built/include/Eigen/src/Core/Assign.h:527:97: note: in instantiation of function template specialization 'Eigen::PlainObjectBase<Eigen::Matrix<double, 1, 2, 3, 1, 2> >::lazyAssign<Eigen::Matrix<double, 1, 2, 1, 1, 2> >' requested here
  static EIGEN_STRONG_INLINE Derived& run(Derived& dst, const OtherDerived& other) { return dst.lazyAssign(other.derived()); }
                                                                                                ^
built/include/Eigen/src/Core/PlainObjectBase.h:653:69: note: in instantiation of member function 'Eigen::internal::assign_selector<Eigen::Matrix<double, 1, 2, 3, 1, 2>, Eigen::Matrix<double, 1, 2, 1, 1, 2>, false, false>::run' requested here
      return internal::assign_selector<Derived,OtherDerived,false>::run(this->derived(), other.derived());
                                                                    ^
built/include/Eigen/src/Core/PlainObjectBase.h:635:101: note: in instantiation of function template specialization 'Eigen::PlainObjectBase<Eigen::Matrix<double, 1, 2, 3, 1, 2> >::_set_noalias<Eigen::Matrix<double, 1, 2, 1, 1, 2> >' requested
      here
    EIGEN_STRONG_INLINE void _set_selector(const OtherDerived& other, const internal::true_type&) { _set_noalias(other.eval()); }
                                                                                                    ^
built/include/Eigen/src/Core/PlainObjectBase.h:630:7: note: in instantiation of function template specialization 'Eigen::PlainObjectBase<Eigen::Matrix<double, 1, 2, 3, 1, 2> >::_set_selector<Eigen::CoeffBasedProduct<const Eigen::Matrix<double,
      1, 2, 3, 1, 2> &, const Eigen::Block<const Eigen::Matrix<double, 3, 3, 3, 3, 3>, 2, 2, false>, 6> >' requested here
      _set_selector(other.derived(), typename internal::conditional<static_cast<bool>(int(OtherDerived::Flags) & EvalBeforeAssigningBit), internal::true_type, internal::false_type>::type());
      ^
built/include/Eigen/src/Core/Matrix.h:172:20: note: in instantiation of function template specialization 'Eigen::PlainObjectBase<Eigen::Matrix<double, 1, 2, 3, 1, 2> >::_set<Eigen::CoeffBasedProduct<const Eigen::Matrix<double, 1, 2, 3, 1, 2> &,
      const Eigen::Block<const Eigen::Matrix<double, 3, 3, 3, 3, 3>, 2, 2, false>, 6> >' requested here
      return Base::_set(other);
                   ^
built/include/lmatrix3_src.I:655:8: note: in instantiation of function template specialization 'Eigen::Matrix<double, 1, 2, 3, 1, 2>::operator=<Eigen::CoeffBasedProduct<const Eigen::Matrix<double, 1, 2, 3, 1, 2> &, const Eigen::Block<const
      Eigen::Matrix<double, 3, 3, 3, 3, 3>, 2, 2, false>, 6> >' requested here
  v._v = v._v * _m.block<2, 2>(0, 0);
       ^
</pre>

This is fixed in libeigen 3.3.5, see https://gitlab.com/libeigen/eigen/-/issues/1402 (The needed commits are referenced in the comments)

## Steps to Reproduce

Switch to release/1.10.x branch and download third party tools from https://www.panda3d.org/download/panda3d-1.10.7/panda3d-1.10.7-tools-mac.tar.gz

## Environment
 * Operating system: macOS
 * System architecture: x64
 * Panda3D version: 1.10.7
 * Installation method: built from source
 * Python version (if using Python): 3.7.9
 * Compiler (if using C++): Xcode 12

**Comment by kamgha** [comment]
Can you confirm that updating to the latest version of Eigen in `panda3d-1.10.7-tools-mac.tar.gz` solves the described problem?

**Comment by rdb** [comment]
I think this should be addressed in [this](https://www.panda3d.org/download/panda3d-1.10.8/panda3d-1.10.8-tools-mac.tar.gz) archive but I am unable to personally test it, since my Mac can't run Catalina and our build mac runs Mojave which can't run XCode 12.

**Comment by el-dee** [comment]
Thank you for the fix, I had not much time to look at this until now.

There are still two lines of code that generate lots of warnings, here is the patch that fixes them :

<pre>
diff -r panda3d-1.10.8/thirdparty/darwin-libs-a/eigen/include/Eigen/src/Core/Assign.h thirdparty/darwin-libs-a/eigen/include/Eigen/src/Core/Assign.h
54c54
<                        && (DstIsAligned || MaxSizeAtCompileTime == Dynamic),
---
>                        && (bool(DstIsAligned) || MaxSizeAtCompileTime == Dynamic),
diff -r panda3d-1.10.8/thirdparty/darwin-libs-a/eigen/include/Eigen/src/Core/util/XprHelper.h thirdparty/darwin-libs-a/eigen/include/Eigen/src/Core/util/XprHelper.h
154c154
<       packet_access_bit = packet_traits<Scalar>::Vectorizable && aligned_bit ? PacketAccessBit : 0
---
>       packet_access_bit = packet_traits<Scalar>::Vectorizable && bool(aligned_bit) ? PacketAccessBit : 0
 </pre>

**Comment by rdb** [comment]
Thanks!  Updated the archive with those changes, so I think this can be closed now.
