### ISSUE TITLE
Typo in MatrixLens's documentation

### ISSUE THREAD

**Issue by John71509** [panda3d/panda3d#1042]
## Description
Hello everyone, I think there is a typo in the MatrixLens's documentation. More specifically in the documentation of the `set_user_mat()` method. Indeed it is stated that `Z` should map to `[-1, 1]` where `-1` is the far plane and `1` the near plane.
I think it's the opposite.

Best regards.

**Comment by rdb** [comment]
Thanks, will fix.  It will note that it is valid to construct a matrix that puts -1 on the far plane and 1 on the near plane, though it's a bit esoteric.
