### ISSUE TITLE
"The installation failed" when installing 1.10.7 on Big Sur

### ISSUE THREAD

**Issue by tomv564** [panda3d/panda3d#1056]
## Description
Running the Panda3D.mpkg contained in Panda3D-SDK-1.10.7-MacOSX10.9.dmg appears to install the files but fail at the "postinstall" script.

<img width="623" alt="image" src="https://user-images.githubusercontent.com/4395832/99917468-c901d800-2d10-11eb-9c04-e1c6c5d33b2a.png">

Installer Log shows:

```
Nov 22 22:17:25 Toms-MacBook-Pro-2 installd[2669]: PackageKit: ----- Begin install -----
Nov 22 22:17:39 Toms-MacBook-Pro-2 installd[2669]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “base.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file:///Volumes/Panda3D%20SDK%201.10.7/Panda3D.mpkg/Contents/Packages/base.pkg, PKInstallPackageIdentifier=org.panda3d.panda3d.base.pkg, NSLocalizedDescription=An error occurred while running scripts from the package “base.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cbase.pkg\U201d.";
	    NSURL = "file:///Volumes/Panda3D%20SDK%201.10.7/Panda3D.mpkg/Contents/Packages/base.pkg";
	    PKInstallPackageIdentifier = "org.panda3d.panda3d.base.pkg";
	}
```

Running "postinstall" manually reveals pre-Catalina assumptions about /Developer 

```
❯ Scripts/postinstall
package-id: org.panda3d.panda3d.base.pkg
version: 1.10.5
volume: /
location: /
install-time: 1580138926
mkdir: /Developer: Read-only file system
ln: /Developer/Panda3D: No such file or directory
```

The OS version comparison added in makepackage.py as a result of https://github.com/panda3d/panda3d/issues/760 in https://github.com/panda3d/panda3d/blob/92e2c2495847ae32b549c0d613d241c8522ee9e9/makepanda/makepackage.py#L121 likely needs an update to also avoid running the cleanup logic on 11.0

## Steps to Reproduce
Download and run the 1.10.7 SDK installer on Mac OS 11.0.1. 

## Environment
 * Operating system: Mac OS 11.0.1 
 * System architecture: x86
 * Panda3D version: 1.10.7
 * Installation method: SDK
 * Python version (if using Python):
 * Compiler (if using C++):

**Comment by rdb** [comment]
Wait, so did you get 1.10.5 or 1.10.7?  Your output seems to suggest the former.

**Comment by tomv564** [comment]
Yes, I noticed this also in the output from postinstall and don't have a clear explanation.

I installed a Panda3D SDK earlier this year (likely 1.10.5?) and removed it manually. Perhaps the installer doesn't update the package receipts to 1.10.7 if installation fails? 

I can clean up the package files and receipts and try again, but I don't think this will change the outcome of the postinstall script.

**Comment by rdb** [comment]
@tomv564 Could you try this and let me know whether the issue still occurs?
https://buildbot.panda3d.org/downloads/aace94a52174bc214f9c44220b83b9a525cfe62b/Panda3D-SDK-1.10.8-aace94a-MacOSX10.9.dmg

**Comment by romantolkachyov** [comment]
@rdb yes, no error with this archive

**Comment by DarthNihilus1** [comment]
Can we apply this fix to 1.11.0 as well? I compiled a panda3d and got an installation failed as well
```
Nov 28 15:51:51 Michaels-MacBook-Air installd[935]: PackageKit: ----- Begin install -----
Nov 28 15:52:43 Michaels-MacBook-Air installd[935]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “base.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file:///Volumes/Panda3D%20SDK%201.11.0/Panda3D.mpkg/Contents/Packages/base.pkg, PKInstallPackageIdentifier=org.panda3d.panda3d.base.pkg, NSLocalizedDescription=An error occurred while running scripts from the package “base.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cbase.pkg\U201d.";
	    NSURL = "file:///Volumes/Panda3D%20SDK%201.11.0/Panda3D.mpkg/Contents/Packages/base.pkg";
	    PKInstallPackageIdentifier = "org.panda3d.panda3d.base.pkg";
	}
Nov 28 15:52:44 Michaels-MacBook-Air Installer[88211]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Nov 28 15:52:44 Michaels-MacBook-Air Installer[88211]: IFDInstallController 3B25240 state = 8
Nov 28 15:52:44 Michaels-MacBook-Air Installer[88211]: Displaying 'Install Failed' UI.
Nov 28 15:52:44 Michaels-MacBook-Air Installer[88211]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
```

**Comment by romantolkachyov** [comment]
@DarthNihilus1 use wheels they are better anyway. Can’t find a way to install dmg into the virtualev/ specific pyenv version, for example.

**Comment by rdb** [comment]
Sure, I'll merge this in a moment.
