### ISSUE TITLE
ALSA errors on many instances of ShowBase

### ISSUE THREAD

**Issue by alek5k** [panda3d/panda3d#1064]
## Description
I am running many instances of the engine at once and using sockets for communications. Note that in my application, **I do not need sound**. 

Once I open enough of them (around 64 instances) I get the following errors associated with the ALSA sound mixer:

```shell
AL lib: (EE) ALCplaybackAlsa_mixerNoMMapProc: Wait timeout... buffer size too low?
```

When I run more instances - around 128, I get the following errors during initialization of ShowBase:

```shell
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused
AL lib: (WW) alcSetError: Error generated on device (nil), code 0xa005
:audio(error): Couldn't open default OpenAL device
:audio(error): OpenALAudioManager: No open device or context
:audio(error):   OpenALAudioManager is not valid, will use NullAudioManager
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection terminated
...
...
AL lib: (EE) ALCplaybackAlsa_mixerNoMMapProc: Wait timeout... buffer size too low?
...
...
AL lib: (EE) ALCpulsePlayback_contextStateCallback: Received context failure!
AL lib: (EE) ALCpulsePlayback_streamStateCallback: Received stream failure!
```

Note that my initialization looks like the following:
```python
class MyGame(ShowBase):
    def __init__(self, window_type):
        ShowBase.__init__(self, windowType=window_type)
        
        base.disableAllAudio()
```

However it seems to still be querying the sound functions somewhere. Is there a way I can prevent ShowBase from worrying about sound at all? Your advice would be much appreciated!

**Comment by Yonnji** [comment]
You can completely disable sound with:
```
from panda3d.core import loadPrcFileData
loadPrcFileData('', 'audio-library-name null')
```

You need to do it before you import ShowBase.
