### ISSUE TITLE
Split out interrogate into a separate wheel

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#1074]
I would suggest that we split out interrogate into a separate wheel uploaded separately to PyPI.  The reasoning for this is twofold:

1. Most users of Panda3D don't need interrogate.  It just takes up space.  On top of that, users that need it are unlikely to find use for the Panda3D wheel to begin with, since it doesn't include the header files for Panda3D or the parser-inc headers for interrogate.
2. On the other hand, it is useful to have an easy way to get interrogate for being able to cross-compile Panda3D.  In that case, you don't need a full installation of Panda3D on the build host, but you do need to have a runnable version of the interrogate tool.

Unfortunately, the name [interrogate](https://pypi.org/project/interrogate/) is already taken, so I would suggest panda3d-interrogate.

**Comment by serkkz** [comment]
Panda3d-interrogate, the name is not quite successful. This makes the binding to the panda. You need something global, PyBindC++.

**Comment by kamgha** [comment]
>     2. On the other hand, it is useful to have an easy way to get interrogate for being able to cross-compile Panda3D.  In that case, you don't need a full installation of Panda3D on the build host, but you do need to have a runnable version of the interrogate tool.

In the past with `ppremake`, you'd just compile `dtool` natively for the build host, and use the resulting `interrogate` binary for the cross-compile. It looks like, we can still do this with the CMake scripts, by turning OFF everything except `dtool`: https://github.com/panda3d/panda3d/blob/aa0a0d6ab428f80d029c947a5b13f48d4b89163b/CMakeLists.txt#L100-L106

> 
> Unfortunately, the name [interrogate](https://pypi.org/project/interrogate/) is already taken, so I would suggest panda3d-interrogate.

Wasn't the plan to replace interrogate with a thirdparty utility, eventually?

**Comment by rdb** [comment]
> Panda3d-interrogate, the name is not quite successful. This makes the binding to the panda. You need something global, PyBindC++.

If and when we split off interrogate into its own open-source project, then we may have to think of a new name, but I'm just talking right now about splitting up the wheel package.

> In the past with `ppremake`, you'd just compile `dtool` natively for the build host, and use the resulting `interrogate` binary for the cross-compile. It looks like, we can still do this with the CMake scripts, by turning OFF everything except `dtool`:

Yes, you are accurately describing the process that I referred to as "inconvenient" (you have to configure and build the tree twice).  Is your comment meant to suggest that we don't need to split up the wheels, or are you just suggesting this as a way to build the second wheel?

> Wasn't the plan to replace interrogate with a thirdparty utility, eventually?

There was such a plan once, but an evaluation of the available tools at the time made it clear that there was no tool available that met our needs in the way that interrogate did.

**Comment by Moguri** [comment]
Sounds good to me.

**Comment by kamgha** [comment]
> Is your comment meant to suggest that we don't need to split up the wheels, or are you just suggesting this as a way to build the second wheel?

I wondered whether the resulting wheel would attract users that specifically will use interrogate outside Panda3D. Regarding cross-compiling, I wonder whether one would rather prefer to go through the whole process, including preparing the environment. In essence, my thought was to drop interrogate from the main wheel, without creating a new wheel.

**Comment by Moguri** [comment]
I don't see this getting done by 1.11, and it's not a big priority, so I'm removing the milestone

**Comment by rdb** [comment]
It's a separate wheel now:
https://pypi.org/project/panda3d-interrogate/

Built from a separate project on GitHub:
https://github.com/panda3d/interrogate

We can later work on making it less dependent on Panda3D, this is just the first step.

Next up is removing interrogate from the Panda3D codebase, which requires changing CMake and makepanda to pull it in from externally.
