### ISSUE TITLE
Remove dmodels tree in favour of single models tree

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#1075]
Currently, we have a "models" directory and a "dmodels" tree, both of which get merged into a single "models" directory in the built folder.  The "dmodels" tree is an artifact of the ppremake days, whereas "models" was a CMU addition that was never used by ppremake.

Some of the files in the dmodels tree are in OpenFlight (.flt) format and are being converted by the build system using flt2egg.  This format is obscure and I don't think there is any use in having them in this format, and I think we might as well keep them in .egg.  This also makes it easier to cross-compile Panda to due the lack of need to have flt2egg.

To remove unnecessary complexity from the build system, I suggest we simply check all the built eggs from the dmodels tree into the models tree.

**Comment by lachbr** [comment]
I think dmodels was also used as an example of how to setup a model tree using ppremake. Given that ppremake is no longer in use, I see no issue with moving combining dmodels and models, as well as storing them directly as eggs.
