### ISSUE TITLE
macOS: Cg.framework signature not valid

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#1079]
## Description

When updating the third-party libraries and tools for macOS, the next build fails because the Cg Framework is missing or invalid :

<pre>
dyld: Library not loaded: @loader_path/../Frameworks/Cg.framework/Cg
  Referenced from: /Users/ld/git/3D/panda3d/built/lib/libpanda.1.10.dylib
  Reason: no suitable image found.  Did find:
	/Users/ld/git/3D/panda3d/built/bin/../lib/../Frameworks/Cg.framework/Cg: code signature in (/Users/ld/git/3D/panda3d/built/bin/../lib/../Frameworks/Cg.framework/Cg) not valid for use in process using Library Validation: library load disallowed by system policy
	/Users/ld/git/3D/panda3d/built/bin/../lib/../Frameworks/Cg.framework/Cg: stat() failed with errno=1
	/Users/ld/git/3D/panda3d/built/lib/../Frameworks/Cg.framework/Cg: code signature in (/Users/ld/git/3D/panda3d/built/lib/../Frameworks/Cg.framework/Cg) not valid for use in process using Library Validation: library load disallowed by system policy
	/Users/ld/git/3D/panda3d/built/lib/../Frameworks/Cg.framework/Cg: stat() failed with errno=1
</pre>

The workaround is straightforward, just open "System Preferences", go to "Security and Privacy" and allow Cg.Framework or use `spctl` to add the library (not tested !)

## Steps to Reproduce

Replace the third-party libraries and tools with another version (I guess touching the file could work too, but I haven't tested)

## Environment
 * Operating system: mac0S 10.15.x
 * System architecture: x86
 * Panda3D version: release/1.10.x
 * Installation method: built from source
 * Python version (if using Python): Python 3.9
 * Compiler (if using C++): XCode 12

**Comment by rdb** [comment]
Is there a signature on that library and is it invalid, or is it just missing?  Can we call `codesign --strip-signature` on it, perhaps?

In any case, the good news is that this library is removed on the shaderpipeline branch, which will be merged to master before the 1.11 release.

**Comment by el-dee** [comment]
There is no signature found in Cg (at least not a signature readable using codesign). I guess an acceptable solution is simply to document this somewhere as a known issue.

**Comment by rdb** [comment]
What's interesting is that Apple complains about it but not about the many other libraries we have.  Perhaps because it's a Framework?  That'd be a little odd because a framework really is just a dynamic library in another shape.

Let me see if I can pretend that libCg is a shared library and produce a build that way.

**Comment by el-dee** [comment]
> What's interesting is that Apple complains about it but not about the many other libraries we have. Perhaps because it's a Framework? That'd be a little odd because a framework really is just a dynamic library in another shape.

A Framework is actually a bundle that contains, amongst other things, a library. As a bundle is something distributable it must be signed, according to Apple philosophy :)

**Comment by rdb** [comment]
In this case "bundle" translates to just a folder with a library and two headers.  Well, here is a version with the library renamed to libCg.dylib:
http://rdb.name/thirdparty-darwin-nvidiacg-dylib.tar.gz

Let's give that a try to see if it is enough to placate Apple.

**Comment by el-dee** [comment]
I fetched the latest release/1.10.x but it seems there is still a reference to built/Framework (or I messed up something) :

<pre>
[100%] Building installer
cp: built/Frameworks: No such file or directory
Storing dependency cache.
Elapsed Time: 10 min 12 sec
The following command returned a non-zero value: cp -R built/Frameworks            dstroot/base//Library/Developer/Panda3D/Frameworks
</pre>

I did remove built/ before testing.

**Comment by rdb** [comment]
Are you sure you have the latest, including eea0abe4886011827e42b8accc6372a64a0ee997?

There are also buildbot builds here:
https://buildbot.panda3d.org/downloads/eea0abe4886011827e42b8accc6372a64a0ee997/

I also updated the 1.10.8 thirdparty packages.  Even if this doesn't work to address this issue, it's still easier to just treat Cg as a library and not a framework.

**Comment by el-dee** [comment]
> Are you sure you have the latest, including [eea0abe](https://github.com/panda3d/panda3d/commit/eea0abe4886011827e42b8accc6372a64a0ee997)?

Ah no, I pulled too fast and I only got 5cd6469fd893612a36f5e86ef5ff331b7fcec37b :) With eea0abe4886011827e42b8accc6372a64a0ee997 it indeed builds correctly and the samples seem to work fine !

**Comment by rdb** [comment]
Great!  Thanks for testing and thanks for filing this, good to have this cleared up before 1.10.8.
