### ISSUE TITLE
Consider including EGL in built wheels

### ISSUE THREAD

**Issue by Clockwork-Muse** [panda3d/panda3d#1086]
## Description
Panda3d now supports using EGL for completely headless rendering (that is, no X11 required at all).
However, using it requires building it yourself, and figuring out how to integrate it into application builds/distributions (note that due to how `build_apps` works, using a private PyPI index can be difficult, especially in a CI/CD context).

## Use Case
Consider including EGL by default in built wheels, and using it as a fallback if an X11 context cannot be started, or by default if `window-type offscreen` is specified.  Several similar schemes are possible (eg, as a different plugin - `pandagl+egl` or similar).

**Comment by rdb** [comment]
Since libpandagl.so uses symbols from X11, it will require a copy of X11 on the system when compiling with X11 enabled.  I think it would be tricky to make a single libpandagl.so that works with both EGL and X11.

The easiest way for us to do this is to just build a separate version of libpandagl.so.

In the long term, we may want the ability to split the graphics API plug-in (egl) from the windowing plug-in (X11) in Panda, since there are more and more combinations possible.

**Comment by duburcqa** [comment]
Is there any news about this issue ? I'm still very very interested. Your solution is not perfect but I think it is a good start and it should be quite straightforward to step up no ? Eventually as an extra requirement [egl] to avoid increasing the size of the package for everybody.

**Comment by duburcqa** [comment]
Good to know you are working on it ! No big deal if it is not planned for 1.10.x, it can wait :)

**Comment by rdb** [comment]
I will release 1.10.9 later this week that will contain a fallback render plug-in called `p3headlessgl` that uses EGL and is automatically loaded (via an `aux-display` line in Config.prc) if the X11 display failed to open.

It should be automatic, except when deploying an application you need to make sure to explicitly include this plug-in.

This is a temporary solution, and will eventually be replaced with something better.

**Comment by Clockwork-Muse** [comment]
Muwahahaha!
Working just fine for me.

Thanks!

(it turns out you don't even have to include `pandagl` in `setup.py` at the moment, although I suppose it could be being included automatically)
