### ISSUE TITLE
Windows installer show confirmation about existing Python install when in silent mode.

### ISSUE THREAD

**Issue by Maxwell175** [panda3d/panda3d#1088]
## Description
When running the Windows installer in silent mode (with the `/S` switch), it still attempts to show a yes/no confirmation dialog regarding an existing Python installation. I would expect it to either default to "Yes" or normally default to "No" with a separate option to default to "Yes".

## Steps to Reproduce
Run `Panda3D-1.10.8-py3.8-x64.exe /S`

## Environment
 * Operating system: Windows
 * System architecture: x64
 * Panda3D version: 1.10.8
 * Installation method: (eg. pip, wheel, SDK, built from source) SDK
 * Python version (if using Python): 3.8
 * Compiler (if using C++): N/A

**Comment by Sumitbatraa** [comment]
@rdb @Maxwell175 Heyy! Can I do this for you ?
I think I can reslove this issue and do what you want with this installation
Can I?

**Comment by rdb** [comment]
@Sumitbatraa  Of course, feel free to take a stab at it. :)
