### ISSUE TITLE
Cannot open FBO with multisamples when using EGL

### ISSUE THREAD

**Issue by Clockwork-Muse** [panda3d/panda3d#1089]
## Description
I'm getting Panda3d running in a headless docker container, but it looks like FBOs aren't being returned if multi-samples are requested.  Possibly related to #601 .

## Steps to Reproduce
Assuming a copy of panda built without x11 (in my case, with `--use-egl --no-x11`):

```python
"""
Quick test module
"""
from panda3d.core import FrameBufferProperties, GraphicsPipe, WindowProperties, loadPrcFileData
from direct.showbase.ShowBase import ShowBase

class MyApp(ShowBase):
    """
    Quick test class
    """

    def __init__(self):
        super().__init__(self)

        def create_output_buffer():
            props = FrameBufferProperties(FrameBufferProperties.getDefault())
            props.set_multisamples(16)

            winprops = WindowProperties()
            winprops.setSize(800, 600)

            return self.graphicsEngine.makeOutput(
                self.win.getPipe(), "some name", -1,
                props, winprops, GraphicsPipe.BFRefuseWindow | GraphicsPipe.BFResizeable,
                self.win.getGsg(), self.win)


        buffer = create_output_buffer()

        if buffer is None:
            print("buffer is none")
        else:
            print("buffer not none")


def generate_synth():
    """
    Quick test method
    """

    loadPrcFileData("",
    """
        window-type offscreen
        audio-library-name null # Prevent ALSA errors
        show-frame-rate-meter 0
        sync-video 0
    """ )

    base = MyApp()
    base.graphicsEngine.renderFrame()

generate_synth()
```

... prints out "buffer is none".  Commenting out `props.set_multisamples(16)` (or setting the samples to 0) goes down the other path.

This has knock-on effects for simplepbr, since that enables multisamples by default (throws when attempting to build the shaders)

## Environment
 * Operating system: Ubuntu 20.04
 * Docker Container base: nvidia/opengl:1.2-glvnd-runtime-ubuntu20.04
 * System architecture: x86_64
 * Panda3D version: 1.11.0
 * Installation method: built from source, commit 25b79a2aefc5f96a4559edd5ecfc366981c7357a
 * Python version: 3.8.5

**Comment by Clockwork-Muse** [comment]
Note that one of the other knock-on effects is writing to transparent buffers yields empty lines between (triangulated) faces:
![screenshot](https://user-images.githubusercontent.com/5569508/108925214-05372400-75f1-11eb-9c8c-1ee729c5355f.png)

@Moguri - I'm not sure to what extent this particular effect could be dealt with in simplepbr.
[repro.zip](https://github.com/panda3d/panda3d/files/6032479/repro.zip)

**Comment by rdb** [comment]
This looks easy to fix.

The transparent lines look like they are caused by polygon smoothing (M_polygon antialiasing), I suspect you are using M_auto antialiasing which will revert to M_polygon if MSAA is not supported.  See #993.

By the way, don't do this:
> ```python
>             props = FrameBufferProperties(FrameBufferProperties.getDefault())
> ```
If you do this you must specifically filter out properties (like back-buffers) that make no sense to apply to an FBO.  It's better to just create a fresh FrameBufferProperties object with the props you want.

**Comment by Clockwork-Muse** [comment]
This fixes the crash and the (by default) transparent lines on the interior (as well as what I'm assuming were related graphical glitches I didn't realize I had), thank you.

That said, the outer edges of my objects are more jagged than I was anticipating, regardless of transparency.
![screenshot](https://user-images.githubusercontent.com/5569508/109054091-5519f780-7692-11eb-9051-0f73906eec20.png)

... I'm not sure whether I'm doing something wrong, or it's some limitation elsewhere:

```python
from direct.showbase.ShowBase import ShowBase
from panda3d.core import AmbientLight, AntialiasAttrib, FrameBufferProperties, GraphicsOutput, GraphicsPipe, LColor, LVector2i, Texture, WindowProperties, loadPrcFileData
import simplepbr

class MyApp(ShowBase):
    def __init__(self):
        super().__init__(self)

        simplepbr.init(
            use_normal_maps=True,
            enable_shadows=True,
            use_occlusion_maps=True,
        )

        self.cam.set_pos(7, 7, 7)
        self.cam.look_at(0, 0, 0)

        window_props = WindowProperties(size=LVector2i(1024, 768))
        flags = GraphicsPipe.BFRefuseWindow

        color_props = FrameBufferProperties()
        color_props.set_rgba_bits(8, 8, 8, 0)
        color_props.set_float_color(False)
        color_props.set_depth_bits(16)
        color_props.set_float_depth(True)
        self.color_buffer = self.graphicsEngine.make_output(self.pipe, "color buffer", -1, color_props, window_props, flags, self.win.get_gsg(), self.win)
        self.color_buffer.add_render_texture(tex=Texture(), mode=GraphicsOutput.RTMBindOrCopy, bitplane=GraphicsOutput.RTPColor)
        self.color_buffer.get_texture().set_clear_color(LColor(0, 0, 0, 0))
        color_camera = self.make_camera(self.color_buffer, camName="color")
        color_camera.reparent_to(self.render)
        color_camera.set_pos(7, 7, 7)
        color_camera.look_at(0, 0, 0)

        model = self.loader.loadModel("models/untitled.blend")
        model.reparent_to(self.render)

        light_node = AmbientLight('light')
        light_node.set_color((0.8, 0.8, 0.5, 1))
        light = self.render.attach_new_node(light_node)
        self.render.set_light(light)

        self.render.set_antialias(AntialiasAttrib.M_polygon)


def generate_synth():
    loadPrcFileData("",
    """
        win-size 1024 768
        window-type offscreen
        model-cache-dir
    """)

    base = MyApp()
    base.graphicsEngine.render_frame()
    base.graphicsEngine.render_frame()
    base.screenshot(source=base.color_buffer, namePrefix="screenshot.png", defaultFilename=False)

generate_synth()
```

... attempting to set multisamples directly on the FBO itself yields a black/transparent image:
```python
color_props.set_multisamples(4)
```
Other than setting `AntialiasAttrib.M_polygon` on something rendered to a transparent buffer, no antialias setting seems to have a noticeable effect on the image (equivalent to `AntialiasAttrib.M_none`).  This is in contrast to the actual window display (or screenshots captured from there), which appears to be properly aliased.

**Comment by Clockwork-Muse** [comment]
As a side note, I am somewhat surprised (although probably shouldn't be) to find that you can get (offscreen) window objects in an egl-only setting, where I was expecting to be required to use FBOs explicitly.  The likely provides me a workaround.

**Comment by Clockwork-Muse** [comment]
> As a side note, I am somewhat surprised (although probably shouldn't be) to find that you can get (offscreen) window objects in an egl-only setting, where I was expecting to be required to use FBOs explicitly. The likely provides me a workaround.

So far, I haven't been able to get windows working, but found that I can get the buffer to have antialiasing by initializing simplepbr and explicitly providing the created backbuffer.  Still looking at things, but since I need to render 4/5 cameras this way that might be a problem.

**Comment by rdb** [comment]
I don't think pbuffers with multisamples are a thing, so I do think you need to create an FBO, but I could be wrong.

**Comment by Clockwork-Muse** [comment]
@rdb - Yeah, I'm creating and FBO like I do in the example code, I just run `simplepbr.init` and supply the created buffer afterwards.  It works, I was just surprised that it wasn't being handled the same way by default.

**Comment by rdb** [comment]
Could you please give a new reproduction case if you're still seeing issues with multisampling in EGL?
