### ISSUE TITLE
Loading/unloading cubemap texture with manual mipmaps needs TexturePool.release()

### ISSUE THREAD

**Issue by Melan2001** [panda3d/panda3d#1091]
## Description

- Loading / unloading a cubemap texture (fed with manual mipmaps) and assigned to a model leads the texture to be loaded without any mipmaps (and ram image) after the second loading.
- If the texture is not assigned to a model, there is no issue, the texture is loaded correctly.
- If the texture is released through TexturePool, there is no issue, the texture is loaded correctly (even if assigned to a model).

## Steps to Reproduce
- Unzip the texture and put it in the same directory as the code below (format is txo.pz). This texture contains 8 levels (1 for base and 7 mipmaps)
- Use the sample below and click on F1 twice. The printed output of the texture does not contain mipmaps nor ram image after the second click ( 'no ram image' instead of '7 mipmap levels also present in ram (4194048 bytes).')
- Click on F2 (i.e. with TPool.release) and the texture is correctly loaded every time.
 

[desert_highway_radiance.txo.zip](https://github.com/panda3d/panda3d/files/5758823/desert_highway_radiance.txo.zip)
```
from direct.showbase.ShowBase import ShowBase
from panda3d.core import *

class Test(ShowBase):
    """Class to show that mipmaps are not loaded when a texture is assigned to a model and no TexturePool.release() is applied."""

    def __init__(self):
        ShowBase.__init__(self)
        self.accept('f1',self.load_cubemap_with_textures,[False])
        self.accept('f2',self.load_cubemap_with_textures,[True])
        self._texture = None
        self._model = None
        base.disable_mouse()

    def load_cubemap_with_textures(self,istp):
        if istp and self._texture is not None:
                TexturePool.release_texture(self._texture)
                print("Texture Pool release mode")
        else:
            print("No Texture Pool release mode")
        self._texture = None
        if self._model is not None:
            self._model.remove_node()
        #Original texture comes from: http://www.hdrlabs.com/sibl/archive.html and filtered with CMFT
        #licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 License.
        self._texture = self.loader.load_cube_map("desert_highway_radiance.txo")
        sampler = SamplerState()
        sampler.anisotropic_degree = 16
        sampler.magfilter = SamplerState.FT_linear
        sampler.minfilter = SamplerState.FT_linear_mipmap_linear
        sampler.wrap_u = SamplerState.WM_clamp
        sampler.wrap_v = SamplerState.WM_clamp
        sampler.wrap_w = SamplerState.WM_clamp
        sampler.max_lod = 7.0
        self._texture.set_default_sampler(sampler)
        self._model = base.loader.load_model("models/smiley")
        self._model.reparent_to(base.render)
        self._model.set_tex_gen(TextureStage.get_default(),TexGenAttrib.MEyeCubeMap)
        self._model.set_texture(self._texture,1)
        base.camera.reparent_to(self._model)
        base.camera.set_pos(0,-5,0)
        base.camera.look_at(self._model)
        print(self._texture)
        print(self._texture.num_loadable_ram_mipmap_images)
        mat = Mat4(camera.getMat())
        mat.invertInPlace()
        base.mouseInterfaceNode.setMat(mat)
        base.enableMouse()

a = Test()
a.run()
```

## Environment
 * Operating system: Win10
 * System architecture: x64
 * Panda3D version: 1.10.8
 * Installation method: SDK
 * Python version (if using Python): 3.7.9

**Comment by rdb** [comment]
Panda unloads the texture from RAM once it's been uploaded to the GPU.  This is normally not an issue because the mipmaps are still in GPU memory, so they are not going away.  However, it's an issue if you still need to access the mipmap data on the CPU.  If you want to do that, you need to disable this behaviour, by setting `keep-texture-ram true` in Config.prc, or `texture.keep_ram_image = True`.

Are you finding an issue with the mipmaps actually being removed from GPU memory as well, or is it just the texture being unloaded from CPU memory that you are noticing?

**Comment by Melan2001** [comment]
Thank you rdb. 

Texture.keep_ram_image = True works and solves the issue.

For texture.get_ram_image(), this solution works well, except for the second reload (!), where the radiance texture has no mipmap. But on the third, fourth... reload, the texture gets its mipmaps again... Probably linked to my own code, I don't know tbh.

_Just a bit of context: this is an editor where resources are loaded /unloaded at the user convenience. The mipmapped radiance texture is not explicitly unloaded when the editor unloads the scene but loaded again each time the editor starts playing a scene (user may have changed the IBL textures)_

As per your question, I notice this issue on models on which I apply a PBR shader and therefore require the radiance texture for IBL.  I would assume (guess?) that mipmaps are somehow unloaded from GPU (when the editor stops the scene,  a render.analyze() shows `0 textures, estimated minimum 0K texture memory required`.) and then not loaded again when the texture is loaded again.

**Comment by rdb** [comment]
I'm unable to reproduce that issue with your code if I add `.keep_ram_image = True`.

**Comment by Melan2001** [comment]
Yes, I confirm that your solution works. I can close the issue.
