### ISSUE TITLE
Flattening breaks get_shader()

### ISSUE THREAD

**Issue by K9Kraken** [panda3d/panda3d#1094]
After flattening a node the get_shader() function no longer returns the shader but returns None. Also if you parent any children to the node after flattening they won't inherent the shader.

```
node.set_shader(shader)
node.get_shader() #Returns the shader
node.flatten_light()
node.get_shader() #Returns None
```

## Environment
 * Operating system: Manjaro
 * System architecture: x64
 * Panda3D version: 1.10.8
 * Installation method: pip
 * Python version: 3.9.1

**Comment by K9Kraken** [comment]
I found a work around:
```
state = node.get_State()
node.flatten_light()
node.set_state(state)
node.get_shader() #It will return the shader
```

**Comment by rdb** [comment]
I am not sure that this is a bug.  Flattening will apply the state down through the scene graph into the GeomNodes.

**Comment by K9Kraken** [comment]
Makes sense, thanks.
