### ISSUE TITLE
Segfault when loading 3D texture data using set_ram_image_as("RGBA")

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#1095]
## Description

When loading raw data for a 3D floating point texture (RGBA32F) using `set_ram_image_as()` with format set to `"RGBA"` the program crashes with a segmentation fault when the texture is sent to the GPU. Using format `"BGRA"` does work fine though. Also, when printing the texture, the reported texture size in ram is wrong with `"RGBA"`

BGRA:

<pre>
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
3d_texture 
  3-d, 64 x 64 x 4 pixels, each 4 floats, rgba32
  sampler wrap(u=repeat, v=repeat, w=repeat, border=0 0 0 1) filter(min=default, mag=default, aniso=0) lod(min=-1000, max=1000, bias=0)  262144 bytes in ram, compression off
</pre>

RGBA:

<pre>
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
3d_texture 
  3-d, 64 x 64 x 4 pixels, each 4 floats, rgba32
  sampler wrap(u=repeat, v=repeat, w=repeat, border=0 0 0 1) filter(min=default, mag=default, aniso=0) lod(min=-1000, max=1000, bias=0)  65536 bytes in ram, compression off

Segmentation fault (core dumped)
</pre>

## Steps to Reproduce

Here is a small program to reproduce the issue (And ther needed date here : [texture.zip](https://github.com/panda3d/panda3d/files/5804993/texture.zip))
:

<pre>
from panda3d.core import CardMaker, Shader, Texture
from direct.showbase.ShowBase import ShowBase

class Demo(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)
        self.quad = None
        cm = CardMaker('card')
        cm.set_frame_fullscreen_quad()
        self.quad = self.render2d.attach_new_node(cm.generate())
        file = open("texture.dat", 'rb')
        data = file.read()
        self.texture = Texture()
        self.texture.setup_3d_texture(64, 64, 4, Texture.T_float, Texture.F_rgba32)
        self.texture.set_ram_image_as(data, "BGRA")
        print(self.texture)
        self.quad.set_shader_input("demo", self.texture)
        shader = Shader.make(Shader.SL_GLSL,
                       vertex="""
#version 330

in vec4 p3d_Vertex;
uniform mat4 p3d_ModelViewProjectionMatrix;

void main()
{
    gl_Position = p3d_ModelViewProjectionMatrix * p3d_Vertex;
}
""",
                       fragment="""
#version 330

uniform sampler3D demo;
out vec4 color;

void main()
{
  vec4 value = texture(demo, vec3(0.5, 0.5, 0.5));
  color = vec4(value.x, 0, 0, 1);
}

""")
        self.quad.set_shader(shader)

demo = Demo()
demo.run()
</pre>

## Environment
 * Operating system: Linux Mint 20
 * System architecture: Intel x64
 * Panda3D version: 1.10.8
 * Installation method: built from source
 * Python version (if using Python): 3.8
 * Compiler (if using C++): N/A

**Comment by rdb** [comment]
I get an assertion; are you building with assertions disabled?
```
Assertion failed: image.size() == (size_t)(cdata->_component_width * format.size() * imgsize) at line 1027 of panda/src/gobj/texture.cxx
```

It looks like set_ram_image_as isn't multiplying in the z size.  Should be easy to fix.

**Comment by el-dee** [comment]
> I get an assertion; are you building with assertions disabled?

Ah yes, I'm using an optimized build right now. I should switch to a vanilla build when investigating
