### ISSUE TITLE
Adding task object with extraArgs fails

### ISSUE THREAD

**Issue by K9Kraken** [panda3d/panda3d#1097]
## Description
When adding a taskObject back in to the task manager Panda3D crashes if the task has extraArgs.

## Steps to Reproduce
**This code works fine:**
```
def test(task):
    ship.y += 0.01
    return task.cont
task = base.add_task(test, 'test_task')
base.remove_task(task)
base.add_task(task)
```

**This code crashes Panda3D:** **(Results are the same when using task_mgr.remove and task_mgr.add)**
```
def test(ship, task):
    ship.y += 0.01
    return task.cont
task = base.add_task(test, 'test_task', extraArgs=[ship], appendTask=True)
base.remove_task(task)
base.add_task(task)
```

Console output:
> TypeError: test() missing 1 required positional argument: 'task'
> :task(error): Exception occurred in PythonTask test_task
> EXIT
> Traceback (most recent call last):
>   File "/home/will/Sync/projects/panda/game/main.py", line 44, in <module>
>     ez.run()
>   File "/home/will/.local/lib/python3.9/site-packages/direct/showbase/ShowBase.py", line 3325, in run
>     self.taskMgr.run()
>   File "/home/will/.local/lib/python3.9/site-packages/direct/task/Task.py", line 541, in run
>     self.step()
>   File "/home/will/.local/lib/python3.9/site-packages/direct/task/Task.py", line 495, in step
>     self.mgr.poll()
> TypeError: test() missing 1 required positional argument: 'task'

## Environment
 * Operating system: Manjaro
 * System architecture: x64
 * Panda3D version: 1.10.8
 * Installation method: pip
 * Python version: 3.9.1

**Comment by K9Kraken** [comment]
A work around for this is to make my own function:
```
def add_task( task ):
    base.add_task(task, task.name, extraArgs=task.get_args())
```

**Comment by rdb** [comment]
ShowBase has no method called `add_task`.  I take it you meant to write `base.task_mgr.add` and `base.task_mgr.remove`?

When you add it back, you need to pass the same arguments:
```python
task = base.task_mgr.add(test, 'test_task', extraArgs=[ship], appendTask=True)
base.task_mgr.remove(task)
base.task_mgr.add(task, extraArgs=[ship], appendTask=True)
```

**Comment by rdb** [comment]
I suppose we could default both arguments to `None` and have it use the existing values if they are `None`.  Do others have thoughts on this?

**Comment by K9Kraken** [comment]
Yeah I meant `base.task_mgr.add`, since there is a `base.remove_task` I mixed things up.

For me it would be logical if you make a task object you should be able to add/remove it by just passing that object.

**Comment by paustian** [comment]
I think that is a good plan rdb. This seems like a simple fix. Let me know if you want me to work on it.

**Comment by rdb** [comment]
@paustian feel free!
