### ISSUE TITLE
BulletGhostNode does not implement bam serialization.

### ISSUE THREAD

**Issue by Clockwork-Muse** [panda3d/panda3d#1099]
## Description
Discovered when reporting [the issue I ran into when importing blender files](https://github.com/Moguri/panda3d-gltf/issues/93).
When models are serialized, `BulletGhostNode`s are not, resulting in empty `PandaNode`s at that point in the hierarchy. 

## Steps to Reproduce
```python
from direct.showbase.Loader import Loader
from panda3d.core import LoaderOptions, NodePath, PandaNode, Vec3, load_prc_file_data
from panda3d.bullet import BulletBoxShape, BulletGhostNode

load_prc_file_data("",
"""
    model-cache-dir
    model-path .
""" )

base_path = NodePath(PandaNode("root node"))
bullet_node = base_path.attach_new_node(BulletGhostNode()).node()
bullet_node.add_shape(BulletBoxShape(Vec3(0.5, 0.5, 0.5)))

base_path.ls()

loader = Loader(base=None)
loader_options = LoaderOptions(LoaderOptions.LF_no_cache)

loader.save_model("tmp.bam", base_path, loaderOptions=loader_options)

imported_path = loader.load_model("tmp.bam", loaderOptions=loader_options)
imported_path.ls()
```
Yields:
```
PandaNode root node
  BulletGhostNode ghost (1 shapes) active
PandaNode root node
  PandaNode ghost
```

## Environment
 * Operating system: Ubuntu 20.04
 * Docker Container base: nvidia/opengl:1.2-glvnd-runtime-ubuntu20.04
 * System architecture: x86_64
 * Panda3D version: 1.11.0
 * Installation method: built from source, commit 7b83eac94312574cf6019ae7da12850c7b2626d9
 * Python version: 3.8.5

**Comment by rdb** [comment]
Fixed in #1104
