### ISSUE TITLE
FreeBSD makepanda.py doesn't produce a pkg but says successfull

### ISSUE THREAD

**Issue by thedaemon** [panda3d/panda3d#1100]
## Description
downloaded panda3d-1.10.8
ran this command:
python3.7 makepanda/makepanda.py --everything --installer --no-egl --no-gles --no-gles2
Command says it was successful, but I cannot find a pkg to install or seem to get it to work. Maybe I did something wrong? Here is the outputs and more information. Let me know if you need more details.

here is my console:
    ~/src/panda3d-1.10.8 python3.7 makepanda/makepanda.py --everything --installer --no-egl --no-gles --no-gles2
Version: 1.10.8
Platform: freebsd-12.2-STABLE-amd64
Using Python 3.7m
Target OS: freebsd
Target arch: amd64
WARNING: Could not locate thirdparty package artoolkit, excluding from build
WARNING: Could not locate thirdparty package fcollada, excluding from build
WARNING: Could not locate thirdparty package fftw, excluding from build
WARNING: Could not locate thirdparty package fmodex, excluding from build
WARNING: Could not locate thirdparty package nvidiacg, excluding from build
WARNING: Could not locate thirdparty package vrpn, excluding from build
WARNING: Could not locate thirdparty package rocket, excluding from build
Generating dependencies...
WARNING: file depends on Python but is not in an ABI-specific directory: built/bin/p3dcparse
WARNING: file depends on Python but is not in an ABI-specific directory: built/bin/deploy-stub
Storing dependency cache.
[100%] Building installer
/bin/sh: rpm: not found
/bin/sh: rpm: not found
Build successfully finished, elapsed time: 1 min 3 sec

Ran:
doas pkg install.
Error

Here is a ls -a of the directory, 

lsa                                             ✔   1m 3s  02:19:05 PM 
./                  +MANIFEST           dmodels/            models/             README.md
../                 BACKERS.md          doc/                panda/              samples/
.gitignore          built/              dtool/              panda3d-1.10.8.txz  setup.cfg
.travis.yml         contrib/            LICENSE             pandatool/          targetroot/
+DESC               direct/             makepanda/          pkg-plist           tests/

## Steps to Reproduce
ran this command:
python3.7 makepanda/makepanda.py --everything --installer --no-egl --no-gles --no-gles2

## Environment
 * Operating system: GhostBSD (FreeBSD 12.2)
 * System architecture: AMD 64
 * Panda3D version: 1.10.8
 * Installation method: build from source
 * Python version (if using Python): 3.7
 * Compiler (if using C++): clang

**Comment by rdb** [comment]
It's right there:
> panda3d-1.10.8.txz
Just do:
```bash
pkg add ./panda3d-1.10.8.txz
```
