### ISSUE TITLE
Can't install panda3d through pip

### ISSUE THREAD

**Issue by Kelvin-Lamptey** [panda3d/panda3d#1101]
Any time I try to install panda3d through pip I come up with an error that says.  "ERROR:Could not find a version that satisfies the requirements panda3d."
I use Android os with the Pydroid3 IDE.I use python version 3.8.3 .
Description

## Environment
 * Operating system:
 * System architecture:
 * Panda3D version: 
 * Installation method: (eg. pip, wheel, SDK, built from source)
 * Python version (if using Python):
 * Compiler (if using C++):

**Comment by rdb** [comment]
There is no binary wheel spec for Android yet, so there is no possible way we can support installing via pip on Android.

**Comment by Kelvin-Lamptey** [comment]
Ok thanks.
So is there any other way I can install panda3d.

**Comment by rdb** [comment]
You will need to compile Panda3D from source.  We do not yet have a turn-key distribution for Android.
