### ISSUE TITLE
PNMImage exports data to python.io.BytesIo or python.io.StringIO or numpy array

### ISSUE THREAD

**Issue by yilei0620** [panda3d/panda3d#1102]
## Description
Is it possible that PNMImage class has a method to export its data to memory whose type is supported in python like io.BtyesIO or StringIO? For example, after I use PNMImage to get a screen shot of my window, I need use `PNMImage.write` to export data to disk. If I can export PNMImage data in bytes or some other kind data structure such as np.array, I am able to do post image processing and to encode it to some image's pixel format which is suitable for video writing or streaming. The speed will be really faster than contemporary method. I'm using panda3d on a server with egl. 

## Use Case
I'm using panda3d generating an animation. However, every time that I use PNMImage to take screen shot, I need to export it to disk and use video writer reading it from disk and then concatenating to video.

**Comment by rdb** [comment]
Since you closed this issue I assume you don't need this any more, but for the record, you can actually skip the step of getting the texture into a PNMImage and instead use `tex.get_ram_image()`, which returns an object that conforms to the buffer protocol and can be exported to numpy.

**Comment by yilei0620** [comment]
Yes. After I posed this issue, I found that I am able to do this by the way
you mentioned. Thus, I closed the issue soon. Thanks for you response.

rdb <notifications@github.com> 于 2021年2月3日周三 下午7:17写道：
