### ISSUE TITLE
Feature Request: Dynamic log_filename with dates in setup.py 

### ISSUE THREAD

**Issue by rileykwok** [panda3d/panda3d#1103]
Feature Request:
log_filename in setup.py to support dynamically created string (eg strftime) which could allow users to have records of all logs sorted by date and not overwritten with the same filename. 

```
setup(
    name='my app',
    version='1.0.0',
    options={
        'build_apps': {
            'console_apps': {'My App': 'main.py'},
            'log_filename': '$USER_APPDATA/Panda3D/log/’‘YEAR’’/’‘MONTH’’/DD-HH-MM.log',
            'log_append': False,
        }
    }
)
```

**Comment by rdb** [comment]
This feature will be in 1.10.9.  You will need to pass the explicit key ``log_filename_strftime`: True`.

In 1.11.0, this flag will be enabled by default.
