### ISSUE TITLE
Sound priority will not set

### ISSUE THREAD

**Issue by K9Kraken** [panda3d/panda3d#1107]
## Description
If you set the priority on a sound then get the priority it just returns 0.

## Steps to Reproduce
```
sound.set_priority(1)
print(sound.get_priority()) #Returns 0
```

## Environment
 * Operating system: Manjaro
 * System architecture: x86_64
 * Panda3D version: 1.10.8
 * Installation method: pip
 * Python version: 3.9.1

**Comment by rdb** [comment]
OpenAL does not implement sound priority, so setting it takes no effect.

**Comment by K9Kraken** [comment]
Thanks for the info
