### ISSUE TITLE
Large OGG sound will pop when playing after stopping

### ISSUE THREAD

**Issue by K9Kraken** [panda3d/panda3d#1108]
## Description
If you play a large OGG file, stop it, then play it again it will make a popping sound when starting.
If you let the sound finish playing then play it again there is no popping.
If you convert the file to WAV and play it does not do this.

I have also noticed that when playing any sound, large or small, wav or ogg, it will make a small popping sound when stopping it about half the time.

## Steps to Reproduce
Run the following code with the [wind.ogg.zip](https://github.com/panda3d/panda3d/files/5962970/wind.ogg.zip)  file, hold space bar down to play, release the space bar to stop:
```
from direct.showbase.ShowBase import ShowBase

class MyApp(ShowBase):

    def __init__(self):
        ShowBase.__init__(self)

        self.sound = self.loader.loadSfx("wind.ogg")

        self.accept('space', self.play_sound)
        self.accept('space-up', self.stop_sound)

    def play_sound(self):
        self.sound.play()

    def stop_sound(self):
        self.sound.stop()

app = MyApp()
app.run()
```
## Environment
 * Operating system: Manjaro
 * System architecture: x86_64
 * Panda3D version: 1.10.8
 * Installation method: pip, (I also compiled the same version from the AUR and still have the issue.)
 * Python version: 3.9.1

**Comment by K9Kraken** [comment]
I tested this out in Windows 10 and it is doing the same thing.

**Comment by kamgha** [comment]
> If you convert the file to WAV and play it does not do this.

What audio backend are you using, OpenAL or FMOD? Can you provide your WAVE file as well, please?

**Comment by K9Kraken** [comment]
I am using OpenAL.
 Here is the OGG file converted to WAV:
[wind.wav.zip](https://github.com/panda3d/panda3d/files/5984885/wind.wav.zip)

**Comment by rdb** [comment]
The popping seems to disappear when I set `vorbis-seek-lap false` in Config.prc.

**Comment by kamgha** [comment]
> 
> 
> The popping seems to disappear when I set `vorbis-seek-lap false` in Config.prc.

I can confirm this on Windows 7.


> I have also noticed that when playing any sound, large or small, wav or ogg, it will make a small popping sound when stopping it about half the time.

This is probably caused by the loudspeakers. It will be more apparent at louder sections. A way to avoid that effect is to fade the audio out before stopping it.

**Comment by rdb** [comment]
I can't get `vorbis-seek-lap` to behave as it is supposed to, even when seeking while the sound continues to play, so I'm just going to disable it by default.

**Comment by kamgha** [comment]
Slightly offtopic, but because it was mentioned in opening post:

> I have also noticed that when playing any sound, large or small, wav or ogg, it will make a small popping sound when stopping it about half the time.

From the changelog of OpenAL 1.21.1 (released about 2-3 weeks ago):
> Improved click/pop prevention for sounds that stop prematurely.

From a quick test, I can confirm this improves the described effect when stopping.
