### ISSUE TITLE
Normal map works on Macbook but not on Raspberry Pi 4

### ISSUE THREAD

**Issue by katemao-151** [panda3d/panda3d#1109]
## Description

Hi! I'm trying to load normal map on my model on Raspberry Pi 4. The model and normal map worked perfectly on Macbook but the texture is not showing up on Raspberry Pi. Has anyone encountered similar issues? They both used OpenGL.

**Comment by rdb** [comment]
We don't support the standard shader generator in OpenGL ES in 1.10.  To get normal mapping in OpenGL ES, you need a shader.  In Panda 1.11, we will remedy this.

**Comment by katemaoSI** [comment]
This might be a dumb question but RPI4 uses OpenGL ES 3.1, do I still need to write the shader or can I use some library that supports ES3?

**Comment by rdb** [comment]
Yes, you need to write a shader to get normal mapping in OpenGL ES for now.

**Comment by rdb** [comment]
Closing as not actionable—we are already addressing this in the new shader pipeline.
