### ISSUE TITLE
AssertionError when selecting objects using direct tools.

### ISSUE THREAD

**Issue by Maxwell175** [panda3d/panda3d#1110]
## Description

When selecting different objects using direct tools, eventually I get an AssertionError:

```
  File "/usr/share/panda3d/direct/showbase/Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "/usr/share/panda3d/direct/directtools/DirectManipulation.py", line 116, in manipulationStart
    entry = base.direct.iRay.pickWidget(skipFlags = SKIP_WIDGET)
  File "/usr/share/panda3d/direct/directtools/DirectSelection.py", line 646, in pickWidget
    self.pick(targetNodePath)
  File "/usr/share/panda3d/direct/directtools/DirectSelection.py", line 620, in pick
    self.ct.traverse(targetNodePath)
AssertionError: !point.is_nan() at line 166 of panda/src/mathutil/boundingLine.cxx
```

## Steps to Reproduce

Add the following to the top of main.py of roaming-ralph example.

```
from panda3d.core import load_prc_file_data

load_prc_file_data('', """want-direct #t
        want-tk #t
        want-directtools #t
        want-dev #t""")
```

https://user-images.githubusercontent.com/1660330/107890637-f614ef80-6ee7-11eb-91f6-30d4db1cfd5f.mp4

## Environment
 * Operating system: Ubuntu 20.04
 * System architecture: amd64
 * Panda3D version: 1.10.9
 * Installation method: (eg. pip, wheel, SDK, built from source) Built from source
 * Python version (if using Python): 3.8.6
 * Compiler (if using C++): gcc version 9.3.0

**Comment by rdb** [comment]
I thought this was already fixed in ef6aa9d6caf0e4f68776ab15df4f5954f01419a9 and 29cdd78c4ed862a171c3209a1f632a6cafc51fde, are you *sure* you have those fixes?

**Comment by rdb** [comment]
Hi @Maxwell175, can you retest with the latest changes?

**Comment by Maxwell175** [comment]
@rdb I can confirm that bringing my source up to date with release/1.10.x fixed the issue. Thank you!
