### ISSUE TITLE
Git clone Panda3D version is 1.10.8 but makepanda generates panda3d1.11_1.11.0_armhf.deb

### ISSUE THREAD

**Issue by katemaoSI** [panda3d/panda3d#1112]
## Description

Hi! I used git clone to install panda3D on raspberry pi, then I installed all the dependencies and ran the makepanda script to build it, but the panda3d version I have is 1.10.8 yet the make panda script generates panda3d1.11_1.11.0_armhf.deb, which cannot be opened. It happened twice already.
These are the dependencies I installed: sudo apt-get install build-essential pkg-config fakeroot python-dev libpng-dev libjpeg-dev libtiff-dev zlib1g-dev libssl-dev libx11-dev libgl1-mesa-dev libxrandr-dev libxxf86dga-dev libxcursor-dev bison flex libfreetype6-dev libvorbis-dev libeigen3-dev libopenal-dev libode-dev libbullet-dev libgtk2.0-dev libassimp-dev libopenexr-dev libglew-dev libgles2-mesa-dev libsdl2-dev libsdl2-image-dev libglm-dev cmake-gui xorg-dev libglu1-mesa-dev mesa-utils libavformat-dev libavcodec-dev libswscale-dev libsquish-dev libogg-dev
This is the build script I run: python3 makepanda/makepanda.py --everything --installer
Thank you!

## Environment
 * Operating system:
 * System architecture:
 * Panda3D version: 
 * Installation method: (eg. pip, wheel, SDK, built from source)
 * Python version (if using Python):
 * Compiler (if using C++):

**Comment by rdb** [comment]
If you checked out from GitHub then you most likely checked out the "master" branch, which is labelled 1.11.0, so that seems correct.

If you wish to check out the stable 1.10 branch, you need to check out the `release/1.10.x` branch.

**Comment by katemaoSI** [comment]
Thank you!!
