### ISSUE TITLE
Mouse-confinement (possibly) not working under Windows 7

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#1115]
My game applies the "M_confined" mouse-mode. For the most part this works as expected. However, I've had a report of my game confining the mouse even when the game-window is in the background.

This was reported to happen under Windows 7.

The game was built using Panda 1.10.8, if I'm not much mistaken.

I'm afraid that I don't have a Windows 7 installation available for testing, and so am not in a position to reproduce this myself. Quick tests under both Windows 8 and Ubuntu 18.04.5 didn't evince the issue.

Here is the post that reported the issue:
https://discourse.panda3d.org/t/a-door-to-the-mists-depictions-demo/25118/131

This issue seems similar to a previous one, save that said previous issue was specific to X11 systems:
https://github.com/panda3d/panda3d/issues/393

**Comment by rdb** [comment]
If I alt-tab out of a Panda window with confined mouse mode set, it works fine.  However, if I alt-tab out of the window before it opens, it confines my mouse cursor.  Without further information, I am going to assume that is the bug reported here.

**Comment by ArsThaumaturgis** [comment]
That's very plausible.

Do you want me to double-check with my user?

**Comment by rdb** [comment]
It would be nice to have specific steps for reproduction.  In the meantime, I believe I have fixed this.  You may also choose to wait to build with the upcoming Panda release so that you can have the user test whether the problem is fixed.
