### ISSUE TITLE
ShaderGenerator makes model disappear when closing other window

### ISSUE THREAD

**Issue by Epihaius** [panda3d/panda3d#1117]
Hi,

When a model in one window is rendered with the ShaderGenerator and another Panda window is open, that model will disappear (in the first window) as soon as that secondary window is closed--but only if the closing is done using a call to `ShowBase.close_window` or `GraphicsEngine.remove_window` *and* that window is **also** rendered into using the ShaderGenerator.

Conversely, if no `close_request_event` is set for the secondary window, clicking its `Close` button doesn't cause this issue. It also doesn't happen if the ShaderGenerator is not used for rendering into both windows at once.

When having more than 2 windows open, only the window opened last (disregarding the window being closed) is affected; it does not affect minimized windows either.

Below is a code sample that should reproduce this behavior:

```python
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase


base = ShowBase()

# render the "environment" model into the default window
model = base.loader.load_model("environment")
model.reparent_to(base.render)
# uncomment the following line to make the model show up after
# closing `win2` and setting its transparency to `M_alpha` again
#model.set_transparency(TransparencyAttrib.M_none, 1)
model.set_scale(.025)
model.set_shader_auto()  # makes environment model disappear


def on_close_win2_request():
    print("Closing window2!")
    base.close_window(win2)
    # uncomment the following line to make the model show up if its
    # transparency was previously set to `M_none`
#    model.set_transparency(TransparencyAttrib.M_alpha, 1)


def on_close_win3_request():
    print("Closing window3!")
    base.close_window(win3)


# render the same model into a second window as well
wp = WindowProperties()
wp.size = (700, 500)
wp.title = "Window 2"
win2 = base.open_window(props=wp)
event_id = "close_win2_request_event"
win2.close_request_event = event_id
base.accept(event_id, on_close_win2_request)
base.accept("c", lambda: base.close_window(win2))

# create a secondary scenegraph, to which a card will be added;
# this new scenegraph will be rendered into a third window by a new camera
render2 = NodePath("render2")

cm = CardMaker("card")
cm.set_frame(-100., 100., -100., 100.)
card = base.render.attach_new_node(cm.generate())
card.set_color(1., 0., 0., 1.)
card.set_y(100.)
card.reparent_to(render2)
card.set_shader_auto()  # makes card disappear when closing `win2`

wp = WindowProperties()
wp.size = (500, 300)
wp.title = "Window 3"
win3 = base.open_window(props=wp)
cam = win3.display_regions[1].camera
cam.reparent_to(render2)
cam.set_y(-50.)
cam.set_p(-30.)
event_id = "close_win3_request_event"
win3.close_request_event = event_id
base.accept(event_id, on_close_win3_request)

base.run()
```

Press `C` on the keyboard to close the second window, or click the `Close` buttons of the 2nd and 3rd windows in different orders to see the results.

Here are some additional observations:

* Firstly, the model can be forced to show up after closing the secondary window by making sure its transparency is set to `M_none` before closing and afterwards setting it to `M_alpha`. (Other kinds of render-state change could work as well, but I haven't tested.)
* Secondly, when closing the third window in the given example (`win3`), only certain parts of the environment model disappear; closing the second window (`win2`) makes it disappear completely.

OS: Windows 10 64-bit
Panda3D version: 1.10.8
GPU: GeForce 940MX with recent drivers

**Comment by rdb** [comment]
I can't reproduce this, can you maybe record and attach an apitrace?

**Comment by Epihaius** [comment]
Here is the trace:

[multiwin_shadergen.zip](https://github.com/panda3d/panda3d/files/6017858/multiwin_shadergen.zip)

There was this warning while recording it:

> apitrace: warning: hiding program binary formats (https://github.com/apitrace/apitrace/issues/316)

but perhaps it's harmless? It's the first time I use apitrace, so I don't know much about it, sorry.

**Comment by rdb** [comment]
I can reproduce this issue on Windows with my NVIDIA card.

It goes away when you set up the other windows to share the same GSG:
```python
win3 = base.open_window(props=wp, gsg=base.win.gsg)
```

I strongly recommend doing that anyway, because otherwise there is no resource sharing between the contexts, and the assets will be uploaded more than once.

**Comment by rdb** [comment]
Seems to be caused by cgDestroyContext.  I am just adding in a hacky workaround for now, since we are replacing the Cg Toolkit soon anyway.

**Comment by Epihaius** [comment]
@rdb Sharing the GSG as you suggest does indeed fix this issue, but I just found out that it seems to force vsync (the framerate drops to a constant 60 fps), despite having set the `sync-video` config variable to `false`. After closing the secondary window(s), the framerate returns to maximal.

Should I open a new issue for this (in case it's another bug), or am I missing something?

**Comment by rdb** [comment]
Feel free, if you want it to be investigated, but issues with VSync tend to be out of our control.

**Comment by Epihaius** [comment]
Fair enough. Should framerate become a problem then the workaround is certainly good enough for my own purposes.

Thanks!
