### ISSUE TITLE
macOS: Non-universal builds no longer have Cg enabled

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#1119]
## Description

Since Panda3D 1.10.8, wheels and builds generated without using `--universal` or `--arch` no longer have Cg enabled. It seems that a18edf54b702e0ac2b72a1095f5e241df8780767 introduced a regression : If neither `--universal` or `--arch` is specified, `OSX_ARCHS` is an empty array, and so causes `NVIDIAGC` package to be disabled : 

https://github.com/panda3d/panda3d/blob/9d9337dc4d349825ee45008c440c27add9469399/makepanda/makepanda.py#L941

## Steps to Reproduce

Install Panda3D on macOS using pip and run the bump-mapping sample. The program will complain that Cg is not supported:

## Environment
 * Operating system: macOS 10.15
 * System architecture: x86_64
 * Panda3D version: 1.10/8
 * Installation method: pip, SDK, built from source
 * Python version (if using Python): 3.7.9
 * Compiler (if using C++): Xcode 12.2

See this thread for the OP  : https://discourse.panda3d.org/t/what-happened-to-my-normal-maps/27237/24

**Comment by rdb** [comment]
Thank you for catching this!  This is a severe bug, I will see if I can find the time to expediate 1.10.9.
