### ISSUE TITLE
Egg reader generates lines, which are not in file.

### ISSUE THREAD

**Issue by maassen** [panda3d/panda3d#1122]
## Description

I've some egg files with some polygons and lines drawn on outer edges of the polygons.
But the if I import the egg file, there are additional lines, which are not in the file.
![with_ghost_lines](https://user-images.githubusercontent.com/11267075/109411265-2907ba80-79a1-11eb-8c0e-130e5522a4a4.jpg)

Very funny, if I change the color of one of the polygons, these "ghost lines" disappear!
![no_ghost_lines](https://user-images.githubusercontent.com/11267075/109411302-5d7b7680-79a1-11eb-8824-aa3b23997f7a.jpg)

I think there is something wrong in the egg importer.

## Steps to Reproduce

Here I attache both egg files, with ghost lines and with one polygon in different color. The effect can easily reproduced by opening the files with pview. Rename .txt to .egg
[VP2.egg.txt](https://github.com/panda3d/panda3d/files/6056390/VP2.egg.txt)
[VP2b.egg.txt](https://github.com/panda3d/panda3d/files/6056391/VP2b.egg.txt)

 

## Environment
 * Operating system: Linux (and Windows)
 * System architecture: x64
 * Panda3D version:  1.10.8
 * Installation method: (eg. pip, wheel, SDK, built from source) pip
 * Python version (if using Python): 3.9
 * Compiler (if using C++):--

**Comment by rdb** [comment]
This may actually be an issue in the rendering system, or a driver bug.  If I set `gl-support-primitive-restart-index false` in Config.prc, it seems to work fine.

Could you let me know which GPU you are using?

**Comment by rdb** [comment]
Scratch that, it is a bug in the unifier.  A workaround for now is to set `egg-unify false` in Config.prc.  Will be fixed in 1.10.9, which will be released soon.

Thanks for reporting this!
