### ISSUE TITLE
DirectOptionMenu bug

### ISSUE THREAD

**Issue by Pignon3d** [panda3d/panda3d#1125]
## Description
https://docs.panda3d.org/1.10/python/programming/directgui/directoptionmenu#dynamic-updating-of-a-menu
There is some strange behavior in the manual 2nd example for DirectOptionMenu when adding items.

## Steps to Reproduce
Click on the button and then Add.
Click on the left part of the button again. It will select the new element on mouse-up, even if you hold the mouse and move outside the button but if you hover over the popped up menu while holding LMB, it will start working again.
It seems that the new items trigger-able area covers the whole window.

Also, while not probably a bug. It would be better if it didnt select the element that spawns under the cursor on mouse-up when you click on the right part of the button.

## Environment
 * Operating system: W7
 * System architecture:
 * Panda3D version: 1.10.8

**Comment by rdb** [comment]
Thank you for reporting.  This is indeed a bug.  When destroying the items, the unhighlight callback for the "Add" item never gets fired, so the next time you open the menu, it thinks that the mouse is still over the item with that index.

> Also, while not probably a bug. It would be better if it didnt select the element that spawns under the cursor on mouse-up when you click on the right part of the button.

The behaviour that seems to be expected here is that you click-and-hold.  This is against current user interface guidelines, so we should consider changing this for 1.11.

I also notice that replacing the items changes the initialitem, which seems a little unexpected to me.
