### ISSUE TITLE
Removing Vertex Group breaks bone placement

### ISSUE THREAD

**Issue by Germanunkol** [panda3d/panda3d#1130]
## Description
(Note that this may be an issue with blend2bam - if so, I can repost there)

When a bone has no corresponding vertex group in blender, and I convert the model with blend2bam and load it in Panda, this bone will be placed at the origin of the model instead of where it is in blender.

This can be very confusing and I don't see a reason for it - one might want to define "helper" bones, such as for IK or as targets for some lookAt call, for example, but this makes it impossible (I think) to retrieve the original position of the bone as it was in Blender from within Panda.

## Steps to Reproduce
Download the Meshes.zip, extract the meshes, and run the following script:
[Meshes.zip](https://github.com/panda3d/panda3d/files/6151808/Meshes.zip)

```python
from direct.showbase.ShowBase import ShowBase
from panda3d.core import *

app = ShowBase()

def printBones( model ):
    characterNode = model.find("-Character")
    c = characterNode.node().getBundle(0).getChild(0)
    while c:
        print(c.getName())
        if isinstance( c, CharacterJoint ):
            print(characterNode.node().findJoint( c.getName() ).getTransform())
        if c.getNumChildren() == 0:
            break
        c = c.getChild(0)

print("Tentacle.bam bones:")
model = loader.loadModel( "Tentacle.bam" )
printBones( model )

print("TentacleBroken.bam bones:")
model = loader.loadModel( "TentacleBroken.bam" )
printBones( model )

app.run()
```

You'll see that for the first model, Bone.005 will be placed at "0 1 0" from its parent, but for the second model it will be placed at "0 -9 0" from its parent. Consequently, the next bone (Bone.006) will also have an offset of 11 instead of 1 as it was before.

The only thing I changed from Tentacles.blend to TentaclesBroken.blend was removing the vertex group named "Bone.005".

## Environment
 * Operating system: Ubuntu
 * System architecture: 64 bit
 * Panda3D version: 1.10.8
 * Installation method: pip
 * Python version: 3.6.9

**Comment by rdb** [comment]
Panda is just loading what's in the bam file, so this is not a bug in Panda.
