### ISSUE TITLE
Video driver reports shaders are not supported M1 macOS.

### ISSUE THREAD

**Issue by AnMontes** [panda3d/panda3d#1133]
## Description

I've been trying to implement shadow mapping and bloom filters with an M1 MacBook Pro 13 with no success. When trying to run the example shadows (provided by panda3d team) a message is displayed that says: Shadow Demo: Video driver reports that shaders are not supported. Which is activated by the function base.win.getGsg().getSupportsBasicShaders()

<img width="803" alt="Screen Shot 2021-03-28 at 18 02 44" src="https://user-images.githubusercontent.com/47119574/112772746-cd583d80-8fef-11eb-9589-40d761bdb623.png">

## Steps to Reproduce

I currently have installed panda3d version 1.11.0.dev1953
In a M1 apple device run the basic.py script located in the samples folder. 

## Environment
 * Operating system: macOS Big Sur 11.2.3
 * System architecture: Apple M1
 * Panda3D version: 1.11.0.dev1953
 * Installation method: pip3 install --pre --extra-index-url https://archive.panda3d.org/ panda3d
 * Python version (if using Python): Python 3.9.2
 * Compiler (if using C++): No

**Comment by rdb** [comment]
This is explained here:
https://www.panda3d.org/blog/sdk-1-10-8-release/
In short, the samples in question use Cg shaders, and the Cg Toolkit is not available for arm64.

If you want shaders on a M1, your three choices are:
1. Run Python in x86_64 mode for now
2. Use GLSL shaders
3. Build Panda from the `shaderpipeline` branch on GitHub, which contains the experimental new shader pipeline that replaces the Cg Toolkit.

**Comment by rdb** [comment]
Here is a sample program that uses shadow mapping with custom GLSL shaders:
https://discourse.panda3d.org/t/sample-using-directional-lights-shadows-effectively/24424

**Comment by AnMontes** [comment]
Thanks. I Tried the sample program and it works. Just one remaining issue. I downloaded the .zip file of the shaderpipeline branch and copied the macOS third party directory into the source folder to build that particular branch. However, when trying to compile I get the following error:

`antoniomontes@MacBook-Pro-de-Antonio panda3d-shaderpipeline % python3 makepanda/makepanda.py --everything --installer
Version: 1.11.0
Platform: macosx-11.0-arm64
Storing dependency cache.
Elapsed Time: 0 sec
Could not locate Python installation at /Library/Frameworks/Python.framework/Versions/3.9
Build terminated.`

I have a homebrew installation of python3. When running a which python3 I get the following:

`antoniomontes@MacBook-Pro-de-Antonio ~ % which python3
/opt/homebrew/bin/python3
`

Which is why I get the error. I haven't installed python 3 with their installer from their webpage because I prefer homebrew. How can I fix this?

**Comment by rdb** [comment]
You can use the `--python-incdir` and `--python-libdir` flags to point to `/opt/homebrew/include` and `/opt/homebrew/lib`, I think it should work.

Please note that the 1.10.9 thirdparty packages are not sufficient to build the shaderpipeline branch, because they miss the glslang, SPIRV-Tools and SPIRV-Cross projects.  Either build and install those libraries from source as well, or use [this script](https://github.com/rdb/panda3d-thirdparty) to build all the required thirdparty packages from source in one go.

**Comment by rdb** [comment]
You may be able to just use the glslang, spirv-cross and spirv-tools Homebrew formulae.

However, the problem is that you are using the command to build the thirdparty packages on Windows.  Start over by deleting the build directory, and just run `cmake ..` without all those extra arguments.

**Comment by rdb** [comment]
After you run cmake, you also need to call `make` (or `make -j4` if you have a 4-core processor) to start the build.  CMake just configures it and generates the makefiles.

You may need to use `--glslang-incdir` and `--glslang-libdir` (same for the other libraries) to tell makepanda where to find them.

**Comment by AnMontes** [comment]
I think I found a bug... When trying to specify `--glslang-incdir` the Terminal shows that 
```
Error parsing command-line input: option --glslang-incdir not recognized
```
But when I try with `--gles-incdir` it doesn't shows that error (however it still fails with `ERROR: Could not locate thirdparty package gles in specified directory, aborting build`).

The make build generated some warnings and 4 errors...
```
[ 75%] Performing build step for 'ffmpeg'
CC	libavdevice/alldevices.o
CC	libavdevice/avdevice.o
libavdevice/avdevice.c:78:42: warning: adding 'unsigned long' to a string does not append to the string [-Wstring-plus-int]
    return LICENSE_PREFIX FFMPEG_LICENSE + sizeof(LICENSE_PREFIX) - 1;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
libavdevice/avdevice.c:78:42: note: use array indexing to silence this warning
    return LICENSE_PREFIX FFMPEG_LICENSE + sizeof(LICENSE_PREFIX) - 1;
                                         ^
           &                             [                       ]
1 warning generated.
OBJCC	libavdevice/avfoundation.o
CC	libavdevice/lavfi.o
CC	libavdevice/utils.o
AR	libavdevice/libavdevice.a
CC	libavfilter/aeval.o
CC	libavfilter/af_acrusher.o
CC	libavfilter/af_adelay.o
CC	libavfilter/af_aecho.o
CC	libavfilter/af_aemphasis.o
CC	libavfilter/af_afade.o
CC	libavfilter/af_afftfilt.o
CC	libavfilter/af_aformat.o
CC	libavfilter/af_agate.o
CC	libavfilter/af_alimiter.o
CC	libavfilter/af_amerge.o
CC	libavfilter/af_amix.o
CC	libavfilter/af_anequalizer.o
CC	libavfilter/af_anull.o
CC	libavfilter/af_apad.o
CC	libavfilter/af_aphaser.o
CC	libavfilter/af_apulsator.o
CC	libavfilter/af_aresample.o
CC	libavfilter/af_asetnsamples.o
CC	libavfilter/af_asetrate.o
CC	libavfilter/af_ashowinfo.o
CC	libavfilter/af_astats.o
CC	libavfilter/af_atempo.o
CC	libavfilter/af_biquads.o
CC	libavfilter/af_channelmap.o
CC	libavfilter/af_channelsplit.o
CC	libavfilter/af_chorus.o
CC	libavfilter/af_compand.o
CC	libavfilter/af_compensationdelay.o
CC	libavfilter/af_crystalizer.o
CC	libavfilter/af_dcshift.o
CC	libavfilter/af_dynaudnorm.o
CC	libavfilter/af_earwax.o
CC	libavfilter/af_extrastereo.o
CC	libavfilter/af_firequalizer.o
CC	libavfilter/af_flanger.o
CC	libavfilter/af_hdcd.o
CC	libavfilter/af_join.o
CC	libavfilter/af_pan.o
CC	libavfilter/af_replaygain.o
CC	libavfilter/af_sidechaincompress.o
CC	libavfilter/af_silencedetect.o
CC	libavfilter/af_silenceremove.o
CC	libavfilter/af_stereotools.o
CC	libavfilter/af_stereowiden.o
CC	libavfilter/af_tremolo.o
CC	libavfilter/af_vibrato.o
CC	libavfilter/af_volume.o
CC	libavfilter/af_volumedetect.o
CC	libavfilter/allfilters.o
CC	libavfilter/asink_anullsink.o
CC	libavfilter/asrc_anoisesrc.o
CC	libavfilter/asrc_anullsrc.o
CC	libavfilter/asrc_sine.o
CC	libavfilter/audio.o
CC	libavfilter/avf_ahistogram.o
CC	libavfilter/avf_aphasemeter.o
CC	libavfilter/avf_avectorscope.o
CC	libavfilter/avf_concat.o
CC	libavfilter/avf_showcqt.o
CC	libavfilter/avf_showfreqs.o
CC	libavfilter/avf_showspectrum.o
CC	libavfilter/avf_showvolume.o
CC	libavfilter/avf_showwaves.o
CC	libavfilter/avfilter.o
libavfilter/avfilter.c:89:42: warning: adding 'unsigned long' to a string does not append to the string [-Wstring-plus-int]
    return LICENSE_PREFIX FFMPEG_LICENSE + sizeof(LICENSE_PREFIX) - 1;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
libavfilter/avfilter.c:89:42: note: use array indexing to silence this warning
    return LICENSE_PREFIX FFMPEG_LICENSE + sizeof(LICENSE_PREFIX) - 1;
                                         ^
           &                             [                       ]
1 warning generated.
CC	libavfilter/avfiltergraph.o
CC	libavfilter/bbox.o
CC	libavfilter/buffersink.o
CC	libavfilter/buffersrc.o
CC	libavfilter/colorspacedsp.o
CC	libavfilter/drawutils.o
CC	libavfilter/dualinput.o
CC	libavfilter/f_bench.o
CC	libavfilter/f_drawgraph.o
CC	libavfilter/f_interleave.o
CC	libavfilter/f_loop.o
CC	libavfilter/f_metadata.o
CC	libavfilter/f_perms.o
CC	libavfilter/f_realtime.o
CC	libavfilter/f_reverse.o
CC	libavfilter/f_select.o
CC	libavfilter/f_sendcmd.o
CC	libavfilter/f_sidedata.o
CC	libavfilter/f_streamselect.o
CC	libavfilter/fifo.o
CC	libavfilter/formats.o
CC	libavfilter/framepool.o
CC	libavfilter/framesync.o
CC	libavfilter/generate_wave_table.o
CC	libavfilter/graphdump.o
CC	libavfilter/graphparser.o
CC	libavfilter/lavfutils.o
libavfilter/lavfutils.c:53:41: warning: 'codec' is deprecated [-Wdeprecated-declarations]
    codec_ctx = format_ctx->streams[0]->codec;
                                        ^
./libavformat/avformat.h:892:5: note: 'codec' has been explicitly marked deprecated here
    attribute_deprecated
    ^
./libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
libavfilter/lavfutils.c:79:11: warning: 'avcodec_decode_video2' is deprecated [-Wdeprecated-declarations]
    ret = avcodec_decode_video2(codec_ctx, frame, &frame_decoded, &pkt);
          ^
./libavcodec/avcodec.h:4811:1: note: 'avcodec_decode_video2' has been explicitly marked deprecated here
attribute_deprecated
^
./libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
2 warnings generated.
CC	libavfilter/lswsutils.o
CC	libavfilter/motion_estimation.o
CC	libavfilter/opencl_allkernels.o
CC	libavfilter/pthread.o
CC	libavfilter/setpts.o
CC	libavfilter/settb.o
CC	libavfilter/split.o
CC	libavfilter/src_movie.o
libavfilter/src_movie.c:524:15: warning: 'avcodec_decode_video2' is deprecated [-Wdeprecated-declarations]
        ret = avcodec_decode_video2(st->codec_ctx, frame, &got_frame, pkt);
              ^
./libavcodec/avcodec.h:4811:1: note: 'avcodec_decode_video2' has been explicitly marked deprecated here
attribute_deprecated
^
./libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
libavfilter/src_movie.c:527:15: warning: 'avcodec_decode_audio4' is deprecated [-Wdeprecated-declarations]
        ret = avcodec_decode_audio4(st->codec_ctx, frame, &got_frame, pkt);
              ^
./libavcodec/avcodec.h:4762:1: note: 'avcodec_decode_audio4' has been explicitly marked deprecated here
attribute_deprecated
^
./libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
2 warnings generated.
CC	libavfilter/transform.o
CC	libavfilter/trim.o
CC	libavfilter/vaf_spectrumsynth.o
CC	libavfilter/vf_alphamerge.o
CC	libavfilter/vf_aspect.o
CC	libavfilter/vf_atadenoise.o
CC	libavfilter/vf_avgblur.o
CC	libavfilter/vf_bbox.o
CC	libavfilter/vf_bitplanenoise.o
CC	libavfilter/vf_blackdetect.o
CC	libavfilter/vf_blend.o
CC	libavfilter/vf_bwdif.o
CC	libavfilter/vf_chromakey.o
CC	libavfilter/vf_ciescope.o
CC	libavfilter/vf_codecview.o
CC	libavfilter/vf_colorbalance.o
CC	libavfilter/vf_colorchannelmixer.o
CC	libavfilter/vf_colorkey.o
CC	libavfilter/vf_colorlevels.o
CC	libavfilter/vf_colorspace.o
CC	libavfilter/vf_convolution.o
CC	libavfilter/vf_copy.o
OBJCC	libavfilter/vf_coreimage.o
CC	libavfilter/vf_crop.o
CC	libavfilter/vf_curves.o
In file included from libavfilter/vf_curves.c:25:
In file included from ./libavutil/intreadwrite.h:25:
In file included from ./libavutil/bswap.h:38:
./libavutil/aarch64/bswap.h:31:13: error: invalid instruction mnemonic 'rev16'
    __asm__("rev16 %w0, %w0" : "+r"(x));
            ^
<inline asm>:1:2: note: instantiated into assembly here
        rev16 %dx, %dx
        ^~~~~
In file included from libavfilter/vf_curves.c:25:
In file included from ./libavutil/intreadwrite.h:25:
In file included from ./libavutil/bswap.h:38:
./libavutil/aarch64/bswap.h:31:13: error: invalid instruction mnemonic 'rev16'
    __asm__("rev16 %w0, %w0" : "+r"(x));
            ^
<inline asm>:1:2: note: instantiated into assembly here
        rev16 %r14w, %r14w
        ^~~~~
In file included from libavfilter/vf_curves.c:25:
In file included from ./libavutil/intreadwrite.h:25:
In file included from ./libavutil/bswap.h:38:
./libavutil/aarch64/bswap.h:31:13: error: invalid instruction mnemonic 'rev16'
    __asm__("rev16 %w0, %w0" : "+r"(x));
            ^
<inline asm>:1:2: note: instantiated into assembly here
        rev16 %si, %si
        ^~~~~
In file included from libavfilter/vf_curves.c:25:
In file included from ./libavutil/intreadwrite.h:25:
In file included from ./libavutil/bswap.h:38:
./libavutil/aarch64/bswap.h:31:13: error: invalid instruction mnemonic 'rev16'
    __asm__("rev16 %w0, %w0" : "+r"(x));
            ^
<inline asm>:1:2: note: instantiated into assembly here
        rev16 %dx, %dx
        ^~~~~
4 errors generated.
make[3]: *** [libavfilter/vf_curves.o] Error 1
make[2]: *** [ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-build] Error 2
make[1]: *** [CMakeFiles/ffmpeg.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by rdb** [comment]
Hmm, looks like it's using assembly when compiling FFMpeg that is not valid for arm64.  In the meantime, rerun CMake using `cmake -DBUILD_FFMPEG=OFF ..` and rebuild.

In fact, you only need it to build three packages, so you can delete the build directory and restart using the following:
`cmake -DDISABLE_ALL=ON -DBUILD_SPIRV_CROSS=ON -DBUILD_SPIRV_TOOLS=ON -DBUILD_GLSLANG=ON ..`

**Comment by rdb** [comment]
I forgot to mention that since you're building for arm64, you should pass `-DCMAKE_OSX_ARCHITECTURES=arm64` to the CMake build as well.

**Comment by AnMontes** [comment]
Nice. After using `make` three directories where generated in darwin-libs-a. I moved them into panda3d-shaderpipeline/thirdparty/darwin-libs-a. Now, instead of getting the glslang error I get a spire-cross-glsl error:

```
antoniomontes@MacBook-Pro-de-Antonio panda3d-shaderpipeline % python3 makepanda/makepanda.py --everything --installer --verbose --python-incdir /opt/homebrew/include --python-libdir /opt/homebrew/lib                                   
Version: 1.11.0
Platform: macosx-11.0-arm64
Using Python 3.9 build located at /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9
Using compiler: GCC
Host OS: darwin
Host arch: arm64
Target OS: darwin
Target arch: arm64
System library search path:
  /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib
  /opt/homebrew/Cellar/llvm/11.1.0/lib/clang/11.1.0
System include search path:
  /opt/homebrew/opt/llvm/include/c++/v1
  /opt/homebrew/Cellar/llvm/11.1.0/lib/clang/11.1.0/include
  /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/include
WARNING: thirdparty package fmodex requires one of MacOSX 10.9-10.13 SDK, excluding from build
Using thirdparty directory: thirdparty/darwin-libs-a/
Couldn't find the framework OpenGLES
Couldn't find library libGLESv1_CM
Couldn't find header file GLES/gl.h
WARNING: Could not locate thirdparty package gles, excluding from build
Couldn't find library libEGL
Couldn't find header file EGL/egl.h
WARNING: Could not locate thirdparty package egl, excluding from build
Couldn't find library libspirv-cross-core
Couldn't find library libspirv-cross-glsl
ERROR: Could not locate thirdparty package spirv-cross-glsl, aborting build
Storing dependency cache.
Elapsed Time: 0 sec
```
I checked if `libspirv-cross-core` and `libspirv-cross-glsl` are inside panda3d-shaderpipeline/thirdparty/darwin-libs-a/spirv-cross/lib and they are there:

```
antoniomontes@MacBook-Pro-de-Antonio panda3d-shaderpipeline % tree thirdparty/darwin-libs-a/spirv-cross 
thirdparty/darwin-libs-a/spirv-cross
├── include
│   └── spirv_cross
│       ├── GLSL.std.450.h
│       ├── spirv.hpp
│       ├── spirv_cfg.hpp
│       ├── spirv_common.hpp
│       ├── spirv_cross.hpp
│       ├── spirv_cross_containers.hpp
│       ├── spirv_cross_error_handling.hpp
│       ├── spirv_cross_parsed_ir.hpp
│       ├── spirv_glsl.hpp
│       ├── spirv_hlsl.hpp
│       ├── spirv_msl.hpp
│       └── spirv_parser.hpp
└── lib
    ├── libspirv-cross-core.a
    ├── libspirv-cross-glsl.a
    ├── libspirv-cross-hlsl.a
    └── libspirv-cross-msl.a

3 directories, 16 files
```

**Comment by rdb** [comment]
Hmm, maybe it expects the directory to be named thirdparty/darwin-libs-a/spirv-cross-glsl ?  I'll look into fixing this when I get home later today.

**Comment by rdb** [comment]
I pushed some fixes to the shaderpipeline branch, to add the incdir/libdir options and to look for it under the "spirv-cross" name.

Alternatively, I just built a wheel myself of the shaderpipeline branch, which you could try instead:
http://rdb.name/panda3d-1.11.0-cp39-cp39-macosx_10_9_universal2.whl

**Comment by AnMontes** [comment]
Man thanks for the patience ... Panda installed successfully with the .whl. Bloom filters are working, which didn't work previously. However, shadow mapping isn't working yet. Is there something different needed in the code of this branch to make it working in M1, or is it just that shadow mapping isn't implemented yet?

**Comment by rdb** [comment]
Shadow mapping should work.  What are you running - the basic.py or the advanced.py Shadow Mapping sample, or something else entirely?  Are there any errors in the console?

**Comment by AnMontes** [comment]
My bad... It is working with the shadows example. I maybe have an error in my other script. 

Will comment it once I found the error and close the issue afterwards. 

Thanks

<img width="801" alt="Screen Shot 2021-04-01 at 4 42 44" src="https://user-images.githubusercontent.com/47119574/113283053-fc4b0980-92a4-11eb-87cd-d29f1dc2bb76.png">

**Comment by rdb** [comment]
If you do find something that broke, let me know.  This branch is still very experimental, so any testing is greatly appreciated.
