### ISSUE TITLE
EGL doesn't support R16i buffer format (among others)

### ISSUE THREAD

**Issue by Clockwork-Muse** [panda3d/panda3d#1137]
## Description
When setting up a render buffer with 16 red bits while using EGL, it is unable to locate a usable window and `GraphicsEngine.make_output()` ends up returning null.

## Steps to Reproduce
```python
from direct.showbase.ShowBase import ShowBase
from panda3d.core import FrameBufferProperties, GraphicsOutput, GraphicsPipe, Texture, WindowProperties, loadPrcFileData

class MyApp(ShowBase):
    def __init__(self):
        super().__init__(self)

        props = FrameBufferProperties()
        props.set_rgba_bits(16, 0, 0, 0)
        props.set_float_color(False)

        wp = WindowProperties()
        wp.setSize(16, 16)

        flags = GraphicsPipe.BFRefuseWindow
        print(props)
        buffer = self.graphicsEngine.make_output(
            self.pipe, "int buffer", -1, props, wp, flags, self.win.get_gsg(), self.win)
        print(buffer.get_fb_properties())

def generate_synth():
    loadPrcFileData("",
    """
        window-type offscreen
        aux-display p3headlessgl
        win-size 1024 768
        model-cache-dir
    """)

    base = MyApp()

generate_synth()
```

Yields the following output:
```text
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
:display:x11display(error): Could not open display ":1".
:display:egldisplay(warning): Couldn't initialize the default EGL display: EGL_NOT_INITIALIZED

<audio errors removed because not interesting>

color_bits=16 red_bits=16 
:display(error): Could not get requested FrameBufferProperties; abandoning window.
  requested: color_bits=16 red_bits=16 
  got: color_bits=24 red_bits=8 green_bits=8 blue_bits=8 force_hardware 
:display(error): Could not get requested FrameBufferProperties; abandoning window.
  requested: color_bits=16 red_bits=16 
  got: color_bits=16 red_bits=5 green_bits=6 blue_bits=5 back_buffers=1 force_hardware 
Traceback (most recent call last):
  File "./repro.py", line 37, in <module>
    generate_synth()
  File "./repro.py", line 35, in generate_synth
    base = MyApp()
  File "./repro.py", line 24, in __init__
    print(buffer.get_fb_properties())
AttributeError: 'NoneType' object has no attribute 'get_fb_properties'
```

## Environment
 * Operating system: Ubuntu 20.04 in docker container based on nvidia/opengl:1.2-glvnd-runtime-ubuntu20.04
 * System architecture: x64_64
 * Panda3D version: 1.10.9
 * Installation method: pip wheel
 * Python version (if using Python): 3.9.2

**Comment by Clockwork-Muse** [comment]
This _may_ be something about nvidia's support for EGL - I think I recall UnrealEngine yelling about this as well when I was messing with that.

Note that I'm aware of `Texture.get_uncompressed_ram_image('R')`, which in theory would allow me to use a different format.  However the documentation for that method essentially states that trimming the extra components would happen _on the CPU_, which is what I'm trying to avoid in the first place.
Note also that trying to do something like float 16 bits, like this:
```python
props = FrameBufferProperties()
props.set_rgba_bits(16, 0, 0, 0)
props.set_float_color(True)
```
... ends up yielding a 32-bit wide float, which is the other conversion I'm attempting to avoid


I **can** get compute shaders to output an `R16i` format, so I have a potential workaround (assuming I can figure out why the compute shader isn't getting switched to in my actual code, whereas it works in my sketch code).

**Comment by rdb** [comment]
This is an error in Panda's renderbuffer format selection code under OpenGL.  I think it should be easy to fix.

**Comment by Clockwork-Muse** [comment]
@rdb - Sweet, thanks!
