### ISSUE TITLE
Crash when passing empty string to loadFont function

### ISSUE THREAD

**Issue by fireclawthefox** [panda3d/panda3d#1140]
## Description
Passing an empty string to the loader.loadFont function results in an out of memory crash.

## Steps to Reproduce
```
from direct.showbase.ShowBase import ShowBase
ShowBase()
loader.loadFont("")
```

## Environment
 * Panda3D version: 1.10.9
 * Installation method: pip
 * Python version: 3.9

**Comment by rdb** [comment]
This appears to be a bug in Linux or perhaps the filesystem driver.  What's happening is that it tries to load "path/to/current/directory/" + "" (ie. the directory it's in), and then tries to seek to the end to determine the size, but lseek is returning the odd value of 0x7fffffffffffffff.
