### ISSUE TITLE
More than 8 lights in a scene are ignored.

### ISSUE THREAD

**Issue by Clockwork-Muse** [panda3d/panda3d#1151]
## Description
Adding more than 8 lights to a scene results in them being ignored for rendering.
The documentation at least implies that more lights in a scene is viable.
![screenshot](https://user-images.githubusercontent.com/5569508/114798339-00b5fe80-9d4a-11eb-993e-fc984734793e.png)

(The circle should be complete here)

## Steps to Reproduce
```python
from typing import Iterable

from direct.showbase.ShowBase import ShowBase
from panda3d.core import NodePath, Point3, Spotlight, loadPrcFileData

class MyApp(ShowBase):
    def __init__(self):
        super().__init__(self)

        self.ground = self.loader.loadModel("plane.blend")
        self.ground.reparent_to(self.render)

        self.camera.set_pos(0, 0, 20)
        self.camera.look_at(0, 0, 0)

        def light_positions(origin: Point3, distance: float, n: int) -> Iterable[Point3]:
            for i in range(n):
                import math
                angle = i * (math.radians(360.0) / n)
                x = math.cos(angle) * distance
                y = math.sin(angle) * distance
                yield origin + Point3(x, y, 0)

        for i, pos in enumerate(light_positions(Point3(0, 0, 0), 1, 12)):
            light = NodePath(Spotlight(str(i)))
            light.set_pos(pos + Point3(0, 0, 4))
            light.look_at(pos * 4)
            light.reparent_to(self.render)
            self.render.set_light(light)

def generate_synth():
    loadPrcFileData("",
    """
        gl-debug #t
        audio-library-name null
        window-type offscreen
        load-display p3headlessgl
    """)

    base = MyApp()
    base.graphicsEngine.renderFrame()
    base.graphicsEngine.renderFrame()
    base.graphicsEngine.renderFrame()
    base.graphicsEngine.renderFrame()

    base.screenshot(namePrefix="screenshot.png", defaultFilename=False)

generate_synth()
```
[plane.zip](https://github.com/panda3d/panda3d/files/6314491/plane.zip)

Headless gl does not appear to make a difference one way or the other.

## Environment
 * Operating system: Ubuntu 20.04
 * Docker Container base: nvidia/opengl:1.2-glvnd-runtime-ubuntu20.04
 * System architecture: x86_64
 * Panda3D version: 1.10.9
 * Installation method: custom build, commit 69c6050fa88abf8a129657b8838be377cde8b13d for 1.10.9
 * Python version: 3.8.5

**Comment by el-dee** [comment]
It seems you are using the fixed function pipeline of OpenGL. Unless I'm mistaken it supports only a limited number of lights. You should either use Panda3D shader generator or you own shader.

To enable the shader generator, just use `self.render.set_shader_auto(True)`

**Comment by rdb** [comment]
@el-dee is correct, this is documented behaviour that can be queried using `base.gsg.max_lights`.  The highest-priority lights get selected.  Enabling the shader generator or a custom shader will fix this.

For a very, very high number of lights, deferred rendering or other tricks are needed.

**Comment by Clockwork-Muse** [comment]
... that's fine, but the documentation makes no mention of this particular wrinkle.
