### ISSUE TITLE
Multiple lights imported from blender have incorrect/missing shadows

### ISSUE THREAD

**Issue by Clockwork-Muse** [panda3d/panda3d#1153]
## Description
I'm at a bit of a loss for this one.  

When rendering a scene where multiple lights are coming from the same blender file, shadows from an object may be missing or otherwise incorrectly rendered.  For example, there are six lights in this scene, arranged in a circle around the cube, but only five shadows (and some of the shadows are wrong):
![screenshot](https://user-images.githubusercontent.com/5569508/114939369-2f3ce380-9df5-11eb-8432-5975bd76e9df.png)

The scene _should_ look like this, I believe:
![screenshot](https://user-images.githubusercontent.com/5569508/114939243-061c5300-9df5-11eb-80c7-c82a34cd698f.png)
(This scene was generated by importing a scene with a single light and placing them at runtime)

I believe this to be a panda issue (or possibly blend2bam), and not a simplepbr one due to the fact that neither sample was generated with shadow maps generated from simplepbr (those aren't loaded until the first update frame occurs).  Still cc @Moguri .  I'm able to reproduce the effect regardless of whether the simplepbr-specific shadow map shaders are used.
There appears to be no difference between an X11 window and headless gl.

Note that in my real program, I have five lights and get _three_ shadows, and primarily seems to be triggered by how "heavy" the scene is (A simple cube produces expected lights in my lit environment, but pulling in a ~50k vertex object causes the extra shadows to be dropped).

## Steps to Reproduce
I cannot reproduce this with the package on PyPi, only with my custom built package.  Unfortunately I need bugfixes added after the most recent publish.

```python
from typing import Iterable

from direct.showbase.Loader import Loader
from direct.showbase.ShowBase import ShowBase
from panda3d.core import NodePath, Point3, loadPrcFileData
import simplepbr

class MyApp(ShowBase):
    def __init__(self):
        super().__init__(self)

        def light_positions(origin: Point3, distance: float, n: int) -> Iterable[Point3]:
            for i in range(n):
                import math
                angle = i * (math.radians(360.0) / n)
                x = math.cos(angle) * distance
                y = math.sin(angle) * distance
                yield origin + Point3(x, y, 0)

        def working_scene(loader: Loader, root: NodePath):
            ground = loader.loadModel("plane.blend")
            ground.reparent_to(root)
            for i, pos in enumerate(light_positions(Point3(0, 0, 4), 3, 6)):
                light_root = self.loader.load_model("light.blend")
                light = light_root.get_child(0).get_child(0)
                light.node().set_shadow_caster(True, 512, 512)

                light_root.set_pos(pos)
                light_root.look_at(Point3(0, 0, 2))
                light_root.reparent_to(root)
                light_root.ls()
                root.set_light(light)

        def broken_scene(loader: Loader, root: NodePath):
            env = loader.load_model("env.blend")
            env.reparent_to(root)
            for light in env.find_all_matches("**/+Light"):
                light.node().set_shadow_caster(True, 512, 512)
                root.set_light(light)

        for _ in range(1):
            cube = self.loader.load_model("cube.blend")
            cube.set_pos(0, 0, 2)
            cube.reparent_to(self.render)


        # working_scene(self.loader, self.render)
        broken_scene(self.loader, self.render)

        self.camera.set_pos(0, 0, 20)
        self.camera.look_at(0, 0, 0)


        simplepbr.init(
            use_normal_maps=True,
            enable_shadows=True,
            use_occlusion_maps=True
        )

def generate_synth():
    loadPrcFileData("",
    """
        gl-debug #t
        audio-library-name null
        window-type offscreen
        load-display p3headlessgl
    """)

    base = MyApp()
    base.graphicsEngine.renderFrame()
    base.graphicsEngine.renderFrame()
    base.graphicsEngine.renderFrame()
    base.graphicsEngine.renderFrame()

    base.screenshot(namePrefix="screenshot.png", defaultFilename=False)

generate_synth()
```

[repro.zip](https://github.com/panda3d/panda3d/files/6321293/repro.zip)

## Environment
 * Operating system: Ubuntu 20.04
 * Docker Container base: nvidia/opengl:1.2-glvnd-runtime-ubuntu20.04
 * System architecture: x86_64
 * Panda3D version: 1.10.9
 * Installation method: custom build, commit 69c6050fa88abf8a129657b8838be377cde8b13d for 1.10.9
 * Python version: 3.8.5

**Comment by Clockwork-Muse** [comment]
Investigating more:
I can get the issue to repro with the officially released wheel, by adding additional cubes (changing the number in `range`).

With 2 cubes I sometimes get this:
![screenshot](https://user-images.githubusercontent.com/5569508/115068478-2b699980-9ea7-11eb-804c-a81d14a87ad6.png)

With 3+ cubes I get an identical image to the custom build:
![screenshot](https://user-images.githubusercontent.com/5569508/115068773-8bf8d680-9ea7-11eb-96e8-f879f6c5e397.png)

**Comment by Clockwork-Muse** [comment]
... I should have remembered one of my earlier issues: https://github.com/Moguri/blend2bam/issues/44 .  
Adopting the workaround there:
```python
        def broken_scene(loader: Loader, root: NodePath):
            env = loader.load_model("env.blend")
            env.reparent_to(root)
            # Adding the following line
            env.clear_light()
            for light in env.find_all_matches("**/+Light"):
                light.node().set_shadow_caster(True, 512, 512)
                root.set_light(light)
```
... causes things to render as expected.
![screenshot](https://user-images.githubusercontent.com/5569508/115079760-8656bd00-9eb6-11eb-8ee3-1c7a299f489f.png)


I think I was anticipating that 8e2c0dff4afceb6cb77303cb3e1463f3baddd1fb was going to have fixed this, but I'm not sure what caused me to think that (other than, "related commit").

@rdb - Should that have fixed it, or is there still additional work to be done.

**Comment by rdb** [comment]
Yes, the fix from that commit is only working for *some* lights. This shows that some of the assigned lights appear to be in a different scene graph:
```python
            for lnp in env.get_attrib(LightAttrib).on_lights:
                print(lnp, env.is_ancestor_of(lnp))
```

It seems to be due to a failure to sort an `ov_set` object. I'll check in a fix.

Passing `allowInstance=True` to `load_model()` is an alternative workaround.
