### ISSUE TITLE
flatten_strong scales normals of certain loaded models

### ISSUE THREAD

**Issue by Epihaius** [panda3d/panda3d#1163]
Hi,

Calling `flatten_strong` on the GeomNode of the model loaded from the .fbx file included in the .zip file below doesn't appear to preserve the unit-length of its vertex normals, but rather applies the scale set on its NodePath to those normals:

[hangar_1_cont5.zip](https://github.com/panda3d/panda3d/files/6479706/hangar_1_cont5.zip)

Code to reproduce this issue:

```python
from direct.showbase.ShowBase import ShowBase
from panda3d.core import *


loader = Loader.get_global_ptr()
loader_options = LoaderOptions(LoaderOptions.LF_no_cache)

model = NodePath(loader.load_sync("hangar_1_cont5.fbx", loader_options))
#model.ls()
child = model.find("**/+GeomNode")
v_data = child.node().modify_geom(0).modify_vertex_data()
print("Vertex format:\n", child.node().get_geom(0).get_vertex_data().format)
# setting the format explicitly (even to an identical one) fixes the issue
#v_data.format = GeomVertexFormat.get_v3n3c4()
child.flatten_strong()  # bake the transforms into the vertices
v_data = child.node().modify_geom(0).modify_vertex_data()
normal_reader = GeomVertexReader(v_data, "normal")
max_normal_length = 0

for i in range(v_data.get_num_rows()):
    normal = normal_reader.get_data3()
    max_normal_length = max(max_normal_length, normal.length())

print("max_normal_length:", max_normal_length)
```

The issue might be related to the vertex format, as explicitly setting it to one registered in Panda3D (even one that is identical to the original one) makes the flatten process preserve the normal-length.
The original vertex format used by the model does seem a bit non-standard, as it uses 4 floats instead of integers for its colors, as well as a 3-component column for its UVs. Then again, as mentioned before, when defining and registering a similar format manually and assigning it to the vertex data, the problem doesn't occur.

Note that the assimp error about no material being assigned to the mesh seems related to loading the .fbx without the use of `ShowBase.loader` (probably because some config variable isn't being set?), as using the latter doesn't generate this error message.

## Environment
 * Operating system: Windows 10 64-bit
  * Panda3D version: 1.10.9
 * Installation method: SDK
 * Python version: 3.7.9

**Comment by rdb** [comment]
Easy fix: the Assimp loader is loading the normal column as `C_vector` instead of `C_normal`.  The latter has special handling to preserve unit length normal vectors.
