### ISSUE TITLE
Not possible to resize the multiple windows with DirectX

### ISSUE THREAD

**Issue by bastak** [panda3d/panda3d#1167]
## Description
When using DirectX API instead of OpenGL,  when several windows are created, the attempt to resize any of the windows leads either to the program closing without any error or with the following error (depending on the computer):
`Process finished with exit code -1073741819 (0xC0000005)`

When I try to make the windows fullscreen from the start (by changing in Config.prc to fullscreen #t), it crashes with the following error:
`:display:wdxdisplay9(fatal): D3D CreateDevice failed for adapter #0,  at (c:\buildslave\sdk-windows-amd64\build\panda\src\dxgsg9\wdxGraphicsWindow9.cxx:686), hr=D3DERR_INVALIDCALL: Invalid call
:display:wdxdisplay9(error): Unable to create window with specified parameters.
:display:wdxdisplay9(warning): ID3D9 released but still has a non-zero refcnt(1), multi-releasing it down to zero!`

## Steps to Reproduce
New windows can be created in the simplest way: 
`base.openWindow()` which runs in the for loop.

## Environment
 * Operating system: Windows 10
 * Panda3D version: 1.10.7
 * Installation method: conda
 * Python version (if using Python): 3.8.3

**Comment by rdb** [comment]
I can reproduce the issue with the following code:
```python
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase

load_prc_file_data("", "load-display pandadx9")

base = ShowBase()
base.openWindow()
base.run()
```
And then attempting to resize the window.
