### ISSUE TITLE
Add partial update of texture array

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#1168]
## Description

Right now, when a user updates only a subset of the pages of a texture array on the CPU side, Panda3D will transfer again the whole texture array to the GPU.
Instead it should only transfer the modified pages to the GPU (as allowed by OpenGL) in order to save bandwidth. Though I believe it should be still possible to use the full transfer if the user think the overhead of the per page transfer is greater than transferring the whole array in one go.

## Use Case

This is useful when the texture array is used as a local cache in the GPU only a subset of a whole dataset (e.g. for mega or virtual textures which are too big to reside even in high end GPU), or when the array is used as an atlas with the texture generated on demand on the CPU.

See this discussion thread for more details : https://discourse.panda3d.org/t/partial-texture-array-update/27735

**Comment by rdb** [comment]
I assumed this would be easy, since we'd just have to keep a SparseArray of modified pages; but then I realised that there can be multiple TextureContexts for multiple GSGs at the same time, and each would need to keep track of which version of which page it has already uploaded.

Moving the SparseArray to TextureContext would work, but it would have to be pipeline-cycled, since otherwise it would start uploading pages already ahead of time.  This pipeline cycling would be a bit of unfortunate added complexity to the whole mechanism.

A more elegant fix would be to create a data structure like SparseArray but that can have an associated UpdateSeq per range, so we can have the existing modification versioning but on a per-page basis.

**Comment by rdb** [comment]
Implemented the "more elegant" solution in 494631ac54e8b5bd2cf72f4ffe44b1c565b62b6e and the GL implementation in bfe595f4dcfbbd8964b3ee52394ca0988fa7107b.

Any call to `load_sub_image()`, or one of the variants of `load()` or `read()` that accepts a `z=` parameter, will now cause only the modified pages to be re-uploaded to the GPU (note that you may need to set the `keep_ram_image` flag to prevent Panda from having to reload the whole texture from disk when you modify a page).  Also note that `modify_ram_image()` will still mark all pages as dirty, let me know if you need a solution for editing the RAM image of individual pages.

I have not really considered mipmapping; if you need to be able to handle partial updates of individual texture mipmap levels, let me know.

**Comment by rdb** [comment]
A quick program showing that it works; pressing "A" will cause the following to be printed:
```
:display:gsg:glgsg(debug): updating image data of texture sky_0, 512 x 512 x 6, pages [ 1-2, 5 ], mipmaps 1, uses_mipmaps = 0
```
```python
from direct.directbase import DirectStart
from panda3d.core import *
load_prc_file_data("", "notify-level-glgsg debug")

tex = loader.load2DTextureArray("sky_#.png")

cm = CardMaker("card")
cm.set_frame_fullscreen_quad()

n = 6
for i in range(n):
    card = aspect2d.attach_new_node(cm.generate())
    card.set_scale(0.14)
    card.set_x((i - (n - 1) * 0.5) * 0.3)
    card.set_tex_pos(TextureStage.get_default(), (0, 0, i))
    card.set_shader_auto()
    card.set_texture(tex)

def modify_pages():
    img = PNMImage(tex.x_size, tex.y_size)

    img.fill(1, 0, 0)
    tex.load(img, 1, 0)

    img.fill(0, 1, 0)
    tex.load(img, 2, 0)

    img.fill(0, 0, 1)
    tex.load(img, 5, 0)

def clear():
    tex.set_clear_color((1, 0, 0, 1))
    tex.clear_image()
    tex.set_loaded_from_image(False)

base.accept('a', modify_pages)
base.accept('c', clear)

base.run()
```

**Comment by el-dee** [comment]
Thank you !

Personally, I don't need to edit the ram image of the pages, I load them as a whole from the disk (or another process) and reload them if needed.
I don't need either to have custom mipmaps, I either don't use them or rely on the GPU generated ones. Though in this case I wonder if the GPU will update the mipmaps of the updated pages or not.

One question though, you say that we may have to set the `keep_ram_image` flag, is it necessary for the partial update to work ? I don't always need to have a copy of the texture in the CPU RAM so it would be a waste of memory. If it's not a problem, I guess I could then use `clear_filename()` to sever the link between the page and the source file, or load the page using PNMImage, then load it into the texture array.
