### ISSUE TITLE
3D orbit

### ISSUE THREAD

**Issue by iamThoshitha** [panda3d/panda3d#1171]
How to plot a orbit when (X,Y,Z) co-ordinates are known?

**Comment by janEntikan** [comment]
```
orbit_center = render.attach_new_node("orbit center")
satalite = render.attach_new_node("satalite")
satalite.reparent_to(orbit_center)
satalite.set_pos((X,Y,Z))

step_size = 45
steps = 360/45
for step in range(steps):
	orbit_center.set_h(center, step_size)
	print(satalite.get_pos(render))
```

**Comment by ArsThaumaturgis** [comment]
It might, of course, be a little more complicated depending on what sort of orbit is intended--a non-circular orbit would take a little more work--and how you want that orbit to be plotted.

However, this seems like a question more suited to the forum than to the issue-tracker, I feel--it's not something that calls for fixing or changing in the engine, after all.

The forum should be available at the link below, should you want to post there:
https://discourse.panda3d.org/
