### ISSUE TITLE
AssertionError when activating "pstats-unused-states"

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#1172]
## Description

When enabling pstats and activating unused states tracking, the application crashes with the following assertion error :

<pre>
Panda version: 1.10.9 (aac27409cfe3a608c1edf028af19b59d08ddc7f4) by cmu (Mar 26 2021 09:46:47)
Using deprecated DirectStart interface.
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
Assertion failed: count == state->get_cache_ref_count() at line 1065 of panda/src/pgraph/transformState.cxx
Assertion failed: count == state->get_cache_ref_count() at line 792 of panda/src/pgraph/renderState.cxx
Traceback (most recent call last):
  File "/home/ld/.local/lib/python3.7/site-packages/direct/showbase/ShowBase.py", line 2153, in __igLoop
    self.graphicsEngine.renderFrame()
AssertionError: count == state->get_cache_ref_count() at line 1065 of panda/src/pgraph/transformState.cxx
:task(error): Exception occurred in PythonTask igLoop
Traceback (most recent call last):
  File "tests/tf_state.py", line 31, in <module>
    base.run()
  File "/home/ld/.local/lib/python3.7/site-packages/direct/showbase/ShowBase.py", line 3325, in run
    self.taskMgr.run()
  File "/home/ld/.local/lib/python3.7/site-packages/direct/task/Task.py", line 546, in run
    self.step()
  File "/home/ld/.local/lib/python3.7/site-packages/direct/task/Task.py", line 500, in step
    self.mgr.poll()
  File "/home/ld/.local/lib/python3.7/site-packages/direct/showbase/ShowBase.py", line 2153, in __igLoop
    self.graphicsEngine.renderFrame()
AssertionError: count == state->get_cache_ref_count() at line 1065 of panda/src/pgraph/transformState.cxx
</pre>

## Steps to Reproduce

```python
from panda3d.core import PandaSystem, load_prc_file_data

print("Panda version: %s (%s) by %s (%s)" % (PandaSystem.getVersionString(),
                                             PandaSystem.getGitCommit(),
                                             PandaSystem.getDistributor(),
                                             PandaSystem.getBuildDate()))

load_prc_file_data("", "want-pstats #t")
load_prc_file_data("", "pstats-unused-states #t")

import direct.directbase.DirectStart
base.run()
```

## Environment
 * Operating system: Linux
 * System architecture: x86-64
 * Panda3D version: 1.10.9 and 1.11.0
 * Installation method: pip for 1.10.9, source for 1.11.0
 * Python version (if using Python): 3.7 and 3.8
 * Compiler (if using C++): n/a

**Comment by ArsThaumaturgis** [comment]
I can confirm seeing this on my own machine, too, I do believe.

OS: Ubuntu Linux 18.04.5 (64-bit)
Panda version: 1.10.9
Installation method: Pip
Python version: 3.6.9

**Comment by rdb** [comment]
More minimal test case:
```python
from panda3d.core import *
load_prc_file_data("", "garbage-collect-states true")

ca1 = ColorAttrib.make_flat((1, 0, 0, 1))
ca2 = ColorAttrib.make_flat((0, 1, 0, 1))

rs = RenderState.make(ca1)
composed = rs.compose(RenderState.make(ca2))

print(rs.get_num_unused_states())
```

I suspect this was a regression in 369f93951ffcf63dbadadd437f848883536add96, which increased the cache ref for states that are in the "regular" cache too (not just the composition cache).  Easy to fix.
