### ISSUE TITLE
MacOS: egg2maya2019 doesn't get installed

### ISSUE THREAD

**Issue by davidallan17** [panda3d/panda3d#1175]
## Description
When installing Panda3D, the binary for egg2maya2019 doesn't get installed with the rest of the egg2maya binaries. 
<img width="742" alt="Screenshot 2021-07-16 at 13 19 28" src="https://user-images.githubusercontent.com/26045000/125946296-121a0c40-bd67-4b54-a404-5ffbb83d9132.png">

## Steps to Reproduce

1. Download Panda3d from the website
2. Install panda3d
3. Look in the `Library/Developer/Panda3D/bin` directory 
4. Theres no egg2maya2019 binary

## Environment
 * Operating system: MacOS Big Sur 11.5
 * System architecture: ARM64 (M1)
 * Panda3D version: 1.10.8/1.10.9
 * Installation method: SDK (.dmg downloaded from website)
 * Python version (if using Python): 3.9

**Comment by rdb** [comment]
Fixed for 1.10.10, you can use this dev build in the meantime
http://buildbot.panda3d.org/downloads/2cc1633a772cd635bb8d95d420badf1f258b67d4/
