### ISSUE TITLE
Redundant unreferenced vertices being added after running flattenStrong()

### ISSUE THREAD

**Issue by loonaticx** [panda3d/panda3d#1185]
## Description
After running flattenStrong() on a model, I observed that the node count was indeed reduced, however, the vertices count increased significantly. As suggested on the Panda3D Discord server, this could be caused by different factors such as orphaned vertices or calculation errors. However, I noticed that all of the new vertices that were generated are unreferenced by any GeomPrimitives

Here's what an example bamfile model's hierarchy looks like this before the flattenStrong() operation:

```
PandaNode models
  ModelRoot demo.egg
    PandaNode g1
      PandaNode group1
        GeomNode pCube1 (1 geoms: S:(ColorAttrib)) T:m(pos 0.908095 2.18154 0 scale 1.12467 1.29551 1.31954)
        GeomNode pCube2 (1 geoms: S:(ColorAttrib)) T:m(pos -1.09658 2.20843 0 scale 1.12467 1.29551 1.31954)
      PandaNode group2 T:m(pos 0 -4.87035 0)
        ModelNode pCube1 T:m(pos 0.908095 2.18154 0 scale 1.12467 1.29551 1.31954)
          GeomNode  (1 geoms: S:(ColorAttrib))
        ModelNode pCube2 T:m(pos -1.09658 2.20843 0 scale 1.12467 1.29551 1.31954)
          GeomNode  (1 geoms: S:(ColorAttrib))
      PandaNode group3
        GeomNode pSphere1 (1 geoms: S:(ColorAttrib)) T:m(pos -5.29565 -1.85043 0)
        GeomNode pSphere2 (1 geoms: S:(ColorAttrib)) T:m(pos -5.29565 1.97694 0)
      GeomNode polySurface30 (1 geoms: S:(ColorAttrib TextureAttrib))
      GeomNode polySurface31 (1 geoms: S:(ColorAttrib TextureAttrib))
      GeomNode polySurface32 (1 geoms: S:(ColorAttrib TextureAttrib))
      GeomNode polySurface33 (1 geoms: S:(ColorAttrib TextureAttrib)) T:m(pos -9.98428 -6.79555 0.878145)
      GeomNode polySurface34 (1 geoms: S:(ColorAttrib TextureAttrib)) T:m(pos -9.65432 -4.02951 0.927212)
      GeomNode polySurface35 (1 geoms: S:(ColorAttrib TextureAttrib)) T:m(pos -6.49481 9.46416 0.924206)
      GeomNode polySurface36 (1 geoms: S:(ColorAttrib TextureAttrib)) T:m(pos -6.444 5.32019 0.979694)
```
Analysis of this model:
```
21 total nodes (including 0 instances); 0 LODNodes.
11 transforms; 0% of nodes have some render attribute.
13 Geoms, with 13 GeomVertexDatas and 2 GeomVertexFormats, appear on 13 GeomNodes.
1610 vertices, 1610 normals, 636 colors, 1610 texture coordinates.
GeomVertexData arrays occupy 90.6 KiB memory.
GeomPrimitive arrays occupy 11.1 KiB memory.
13 GeomVertexArrayDatas are redundant, wasting 15K.
9 GeomPrimitive arrays are redundant, wasting 7K.
1904 triangles:
  48 of these are on 24 tristrips (2 average tris per strip).
  1856 of these are independent triangles.
1 textures, estimated minimum 3.07e+03 KiB texture memory required.
```

After flattenStrong(), the model's hierarchy looks like this:
```
PandaNode models
  ModelRoot demo.egg
    GeomNode g1 (2 geoms: S:(ColorAttrib TextureAttrib))
      ModelNode pCube1
        GeomNode  (1 geoms: S:(ColorAttrib))
      ModelNode pCube2
        GeomNode  (1 geoms: S:(ColorAttrib))
```
Analysis of flattened version of model:
```
7 total nodes (including 0 instances); 0 LODNodes.
0 transforms; 0% of nodes have some render attribute.
4 Geoms, with 4 GeomVertexDatas and 3 GeomVertexFormats, appear on 3 GeomNodes.
3172 vertices, 3172 normals, 3124 colors, 3172 texture coordinates.
GeomVertexData arrays occupy 186 KiB memory.
GeomPrimitive arrays occupy 11.1 KiB memory.
1562 vertices are unreferenced by any GeomPrimitives.
3 GeomVertexArrayDatas are redundant, wasting 1K.
1 GeomPrimitive arrays are redundant, wasting 1K.
1904 triangles:
  24 of these are on 12 tristrips (2 average tris per strip).
  1880 of these are independent triangles.
1 textures, estimated minimum 3.07e+03 KiB texture memory required.
```

## Steps to Reproduce
I'm having difficulty pinpointing the exact root cause of this bug, but I've been able to replicate it in different ways.

I've provided the bamfile models+texture (both before and after flattening) from what was listed above. I've also provided a simple batch script (``flatten.bat``) that'll make two bamfiles and run flattenStrong on one of them for comparison.
[**Download it here**](https://github.com/panda3d/panda3d/files/6987199/demo.zip)

Here's a brief description of the example model from above:

I have some geometry under a group named ``g1``:
- ``group1`` contains two regular GeomNodes with no material/texture applied, no ObjectType flags, no vertex painting/colors.
- ``group2`` contains two GeomNodes that I have applied the model ObjectType to. Does not have any texture/mat nor vertex colors.
- ``group3`` has the same attributes as ``group1``
- I also have a couple of other GeomNodes (``polySurface3x``) within ``g1`` that has no ObjectType flags but has an
 applied texture and vertex painting/colors.

I make my adjustments in Maya then use egg2bam to convert to bamfile, then use a simple script (``flatten.py``) to run flattenStrong() and write it back out.

From my observations, it seems that the ModelNode could be causing a potential interference during the flattening operation. Additionally, when I removed a material off GeomNodes, the extra vertices did not generate.

## Troubleshooting Process

Here's what I've tried so far:

- Removing the material off the polySurfaces will _not_ cause the extra vertices.
- Removing the vertex color off the polySurfaces (material still on) didn't have any effect/fix the problem.
- removing group1 did not fix
- removing group2 did not fix
- removing group3 did not fix
- removing group1 and group3 did not fix
- removing group1 and group2 did not fix
- Removing group3 and all the polySurface nodes did not fix the problem
- removing group2 and group3 fixed the problem
- removing group1 group2 and group3 fixed the problem (polySurface still present with textures+vertex color)

## Environment
 * Operating system: Windows 10
 * System architecture: x64
 * Panda3D version: Panda3D-1.10.4.1-x64
 * Installation method: Installation binary
 * Python version (if using Python): 3.7.4
 * Compiler (if using C++): n/a
 * Using Autodesk Maya 2019

**Comment by rdb** [comment]
It looks like you are using quite an outdated and buggy version of Panda3D, could you please try the latest stable version?

I get this:
```python
20 total nodes (including 0 instances); 0 LODNodes.
11 transforms; 0% of nodes have some render attribute.
13 Geoms, with 13 GeomVertexDatas and 2 GeomVertexFormats, appear on 13 GeomNodes.
1610 vertices, 1610 normals, 636 colors, 1610 texture coordinates.
GeomVertexData arrays occupy 91K memory.
GeomPrimitive arrays occupy 12K memory.
13 GeomVertexArrayDatas are redundant, wasting 15K.
9 GeomPrimitive arrays are redundant, wasting 7K.
1904 triangles:
  48 of these are on 24 tristrips (2 average tris per strip).
  1856 of these are independent triangles.
1 textures, estimated minimum 3072K texture memory required.

6 total nodes (including 0 instances); 0 LODNodes.
0 transforms; 0% of nodes have some render attribute.
4 Geoms, with 3 GeomVertexDatas and 2 GeomVertexFormats, appear on 3 GeomNodes.
1610 vertices, 1610 normals, 1562 colors, 1610 texture coordinates.
GeomVertexData arrays occupy 95K memory.
GeomPrimitive arrays occupy 12K memory.
3 GeomVertexArrayDatas are redundant, wasting 1K.
1 GeomPrimitive arrays are redundant, wasting 1K.
1904 triangles:
  24 of these are on 12 tristrips (2 average tris per strip).
  1880 of these are independent triangles.
1 textures, estimated minimum 3072K texture memory required.
```

**Comment by serkkz** [comment]
I have simplified the test somewhat. However, this does not confirm the existence of a problem.

```py
from direct.showbase.ShowBase import ShowBase

class Game(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)

        model = loader.loadModel("demo")
        model.reparentTo(render)
        model.analyze()

        model.flattenStrong()
        model.analyze()

game = Game()
game.run()

```
D:\demo>D:\Panda3D-1.10.8-x64\python\python.exe main.py
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
20 total nodes (including 0 instances); 0 LODNodes.
11 transforms; 0% of nodes have some render attribute.
13 Geoms, with 13 GeomVertexDatas and 2 GeomVertexFormats, appear on 13 GeomNodes.
1610 vertices, 1610 normals, 636 colors, 1610 texture coordinates.
GeomVertexData arrays occupy 91K memory.
GeomPrimitive arrays occupy 12K memory.
13 GeomVertexArrayDatas are redundant, wasting 15K.
9 GeomPrimitive arrays are redundant, wasting 7K.
1904 triangles:
  48 of these are on 24 tristrips (2 average tris per strip).
  1856 of these are independent triangles.
1 textures, estimated minimum 3072K texture memory required.

6 total nodes (including 0 instances); 0 LODNodes.
0 transforms; 0% of nodes have some render attribute.
4 Geoms, with 3 GeomVertexDatas and 2 GeomVertexFormats, appear on 3 GeomNodes.
1610 vertices, 1610 normals, 1562 colors, 1610 texture coordinates.
GeomVertexData arrays occupy 95K memory.
GeomPrimitive arrays occupy 12K memory.
3 GeomVertexArrayDatas are redundant, wasting 1K.
1 GeomPrimitive arrays are redundant, wasting 1K.
1904 triangles:
  24 of these are on 12 tristrips (2 average tris per strip).
  1880 of these are independent triangles.
1 textures, estimated minimum 3072K texture memory required.
```

**Comment by serkkz** [comment]
However, I found how to get it.

```py
from direct.showbase.ShowBase import ShowBase

class Game(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)

        model = loader.loadModel("demo")
        model.analyze()

        model.flattenStrong()
        model.analyze()

        model.writeBamFile("test.bam")

        model = loader.loadModel("test.bam")
        model.analyze()

game = Game()
```
Additional vertexes occur at the time of writing to disk.

**Comment by rdb** [comment]
The flatten created a single GeomVertexData that is shared by two Geoms on the same GeomNode. However, the GeomVertexData in this case needs to be premunged, and the premunge (which happens on load) is duplicating out the GeomVertexData objects in the process.

The obvious fix here is to prevent the premunge from duplicating out shared GeomVertexData objects and I'll check it in for 1.10.11 momentarily. Better yet would be to add a cache to the GeomTransformer to even handle this when the GeomVertexData is shared across different GeomNodes.

That said, it'd be even more efficient if the flatten operation left the geometry in a state that didn't need premunging.

**Comment by rdb** [comment]
I'm going to revert the fix because the reason why the GeomVertexData were being split is because they were supposed to be munged differently. Both Geoms have texcoords, but only one of them has a texture, so by the current GLGeomMunger rules the texcoord column gets put in a different array.

There is no easy way to fix this in the general case, and I'm going to abandon this for the moment as it's taking up too much time for me. It may end up being fixed implicitly when we change the GLGeomMunger rules.

**Comment by rdb** [comment]
I introduced a change for 1.11 to automatically remove unused vertices during premunge, which effectively fixes this.
fc8c07a949270381d6b089527b0b28c72c868142

It can be disabled with `premunge-remove-unused-vertices false`.
