### ISSUE TITLE
PEP-8 Compliant makepanda Build Scripts

### ISSUE THREAD

**Issue by TheGrandCurator** [panda3d/panda3d#1191]
## Description
Change the *.py files under the `makepanda` directory to be PEP-8 compliment.
This would also be a good time to update the syntax and modules used to a more current standard.

## Use Case

Changing functions names to snake_case etc...
Using `with open('foobar', 'r') as f_handle:` instead of `f_handle=open('foobar', 'r');f_handle.close()`
Not using the `optparse` module but rather the `argparse` module

### Requirements
Fully compatible with Python3.6+

**Comment by Moguri** [comment]
makepanda is being replaced by cmake, so I don't believe it makes much sense to spend a lot of time on this kind of cleanup. However, PRs are still welcome.

**Comment by rdb** [comment]
Agreed, while in principle improving the code style is a good idea, makepanda is on its way out, so I think spending time on it would be a waste of time.

**Comment by TheGrandCurator** [comment]
So makepanda is deprecated? What's the status of cmake as the full replacement? I still see makepanda being used in the runners, which is one of the reasons I started this cleanup.
