### ISSUE TITLE
BulletWorld.getManifolds Memory Leak

### ISSUE THREAD

**Issue by Negdayen** [panda3d/panda3d#1193]
## Description
Calling BulletWorld.getManifolds() leaks memory.

## Steps to Reproduce
- Download the samples from https://www.panda3d.org/download/noversion/bullet-samples.zip
- Add `self.world.getManifolds()`  to the update function in 02_Shapes.py
- Run `python 02_Shapes.py` and observe the constant increase in memory usage in a process manager like `top`.

It's a small leak in 02_Shapes.py, but in a real program with many collisions, the leak is quite severe.

Also tried using the following snippet to see if I needed to manually clean up things, but it doesn't seem to fix the issue.

```
    manifolds = self.world.getManifolds()
    for manifold in manifolds:
      manifold.clearManifold()
    del manifolds
```

## Environment
 * Operating system: Linux void 5.13.19_1 SMP Sat Sep 18 18:18:26 UTC 2021 x86_64 GNU/Linux
 * System architecture: x86_64 
 * Panda3D version: 1.10.9
 * Installation method: pip
 * Python version: 3.9.7
 * Compiler (if using C++):

**Comment by K9Kraken** [comment]
I tested this out and am also getting the memory leak.
Using Manjaro with Panda3D version 1.10.10

A workaround is to use `self.world.manifolds` instead of `self.world.getManifolds()`.

**Comment by Negdayen** [comment]
Addendum:  @K9Kraken's workaround actually doesn't seem to work, it just prolongs the amount of time for the issue to appear.  I had to wait about 6 minutes before I started seeing a steady increase in memory usage.
