### ISSUE TITLE
TexturePeeker.filterRect: Assertion Error At UVs Too High or Too Low

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#1195]
## Description
It seems that TexturePeeking.filterRect, when given UV-coordinates that would include values lower than 0 or higher than 1, produces an assertion error.

Specifically, it produces the following:
```text
AssertionError: min_x >= 0 && min_x <= _x_size && max_x >= 0 && max_x <= _x_size at line 607 of panda/src/gobj/texturePeeker.cxx
```

However, the API indicates that "filterRect" should wrap the UVs passed to it, so it's surprising to encounter an assertion error that appears to stem from the overflowing of texture-bounds.

## Steps to Reproduce
Here is a minimal sample that should immediately produce the assertion error:
```python
from panda3d.core import loadPrcFile, loadPrcFileData

from direct.showbase.ShowBase import ShowBase

from panda3d.core import Vec4

from panda3d import __version__ as pandaVersion
print (pandaVersion)

import sys
print (sys.version)

class Game(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)

        self.disableMouse()

        tex = loader.loadTexture("circle.png")
        peeker = tex.peek()

        u = 0
        v = 0.5
        print (u, v)
        colour = Vec4()
        peeker.filterRect(colour, u - 0.05, v - 0.05, u + 0.05, v + 0.05)
        print (colour.x)

app = Game()
app.run()
```

And an input texture to go with it:
![e138fcec85fd1e064aa427cfbf980aaabfd861d9](https://user-images.githubusercontent.com/36933600/137168062-37852395-e69e-48f7-8b99-eb6397597d5c.png)

## Environment
 * Operating system: Ubuntu 18.04.6
 * System architecture: 64-bit
 * Panda3D version: 1.10.10
 * Installation method: Pip, I believe
 * Python version (if using Python): 3.6.9

**Comment by rdb** [comment]
Seems to be a regression in eb78e3bfaac8a443ae1f87c375138f89e37de69d.

Do you need the wrapping behaviour?  If not I am inclined to simply update the docstrings.

**Comment by ArsThaumaturgis** [comment]
Not any more, no--I think that I'm fine without it. I'd say to go ahead and update the docstrings.
