### ISSUE TITLE
FillDDTextureMipmapPixels failed when loading luminance texture in DirectX

### ISSUE THREAD

**Issue by Maxwell175** [panda3d/panda3d#1198]
## Description

When enabling either hardware animated vertices or disabling basic shaders only as well as enabling compressed textures, textures do not load properly, seemingly offset and zoomed in. The following error appears in the console:
```
:display:gsg:dxgsg9(error): FillDDTextureMipmapPixels failed for texture1, mip_level 0, D3DXLoadSurfFromMem failed at (X:\data\panda3d\panda\src\dxgsg9\dxTextureContext9.cxx:1863), hr=E_FAIL
:display:gsg:dxgsg9(error): Unable to re-create texture texture1
```

## Steps to Reproduce

[cube.zip](https://github.com/panda3d/panda3d/files/7358533/cube.zip)

In the sample script included in the ZIP, the error disappears if you either comment out `compressed-textures #t` or comment out both `hardware-animated-vertices #t` and `basic-shaders-only #f`

## Environment
 * Operating system: Windows 8.1
 * System architecture: x64
 * Panda3D version: 1.10.10
 * Installation method: (eg. pip, wheel, SDK, built from source) SDK
 * Python version (if using Python): 3.7
 * Compiler (if using C++): N/A

**Comment by rdb** [comment]
Panda is trying to pick the ATI1 compression format for luminance textures, which (1) need to be pre-compressed on the CPU, and (2) can't actually be used for luminance because they result in only a red channel being sampled.

Will fix both issues.
