### ISSUE TITLE
Bug related to Sequence.play_rate property

### ISSUE THREAD

**Issue by Epihaius** [panda3d/panda3d#1202]
## Description
Hi,

Recently I discovered an inconsistency between the behaviour of `Sequence.set_play_rate` and assigning to the `Sequence.play_rate` property.
There seems to be an issue with the latter, which becomes apparent when the Sequence contains a `Func` object. In this case, I observe the following problem:

when `Sequence.start` is called, followed by an assignment to the `Sequence.play_rate` property, the Sequence plays all of the contained intervals, until a `Func` object is encountered. At that point, the callable wrapped by the Func doesn't get called and the Sequence either:

* stops (if the `Func` object is last in the Sequence);
when closing the Panda window, the following is output to the console:
  ```
  :interval(warning): Losing outstanding events for Sequence-1 dur 4
  ```

* or crashes (if the `Func` object is followed by a non-`Func` object);
in this case an assertion error is thrown:
  ```
  File "D:\Panda3D-1.10.10-x64\direct\showbase\ShowBase.py", line 3325, in run
    self.taskMgr.run()
  File "D:\Panda3D-1.10.10-x64\direct\task\Task.py", line 546, in run
    self.step()
  File "D:\Panda3D-1.10.10-x64\direct\task\Task.py", line 500, in step
    self.mgr.poll()
  File "D:\Panda3D-1.10.10-x64\direct\showbase\ShowBase.py", line 2097, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "D:\Panda3D-1.10.10-x64\direct\interval\IntervalManager.py", line 95, in step
    self.__doPythonCallbacks()
  File "D:\Panda3D-1.10.10-x64\direct\interval\IntervalManager.py", line 121, in __doPythonCallbacks
    index = self.getNextEvent()
  AssertionError: (def._flags & F_external) != 0 at line 311 of c:\buildslave\sdk-windows-amd64\build\direct\src\interval\cIntervalManager.cxx
  ```

So it seems there's a difference in the handling of `Func` objects between the `Sequence.play_rate` property and the `set_play_rate` method, as the latter causes expected behaviour.

## Steps to Reproduce
In the following code sample, a `Func` object is placed at the end of a Sequence; although `Sequence.start` doesn't lead to an AssertionError in this case, calling `Sequence.loop` instead does:

```python
from direct.showbase.ShowBase import ShowBase
from panda3d.core import *
from direct.interval.IntervalGlobal import *


base = ShowBase()

base.disable_mouse()

base.camera.set_pos(5., -5., 7.)
base.camera.look_at(0., 5., 0.)

def say_hi():
    print("Hi!")

smiley = base.loader.load_model("smiley")
smiley.reparent_to(base.render)
ival1 = LerpPosInterval(smiley, 2., (0., 10., 0.))
ival2 = LerpPosInterval(smiley, 2., (0., 0., 0.))
seq = Sequence()
seq.append(ival1)
seq.append(ival2)
seq.append(Func(say_hi))  # this contributes to the issue occurring
seq.start()  # leads to a warning when exiting ShowBase
#seq.loop()  # leads to an AssertionError after the 1st playthrough
#seq.set_play_rate(2.)  # this does not cause the issue
seq.play_rate = 2.  # this causes the issue

def pause():
    seq.pause()

def resume():
    seq.resume()

base.accept("-", pause)
base.accept("+", resume)


base.run()
```

Note that when the Sequence gets paused (press `-`) and resumed (press `+`) before the Func is reached, the issue does *not* occur.

## Environment
 * Operating system: Windows 10 Home
 * System architecture: 64-bit
 * Panda3D version: 1.10.10
  * Python version: 3.7.9

**Comment by rdb** [comment]
It's because `play_rate` invokes the underlying C++ `set_play_rate` method, whereas `set_play_rate` itself has been overridden from Python.

We can probably fix this by redefining the `play_rate` property in the Python subclass.
