### ISSUE TITLE
Spotlight light boundaries move or stay static appearing inconsistent between platforms

### ISSUE THREAD

**Issue by rayanalysis** [panda3d/panda3d#1207]
## Description
I'm opening this issue to describe a phenomenon wherein the visible boundaries of a spotlight move relative to the scene camera position on certain hardware, yet remain static on others. Specifically, the spotlight illumination boundaries appear to move around relative to the scene camera when rendered with an NVIDIA GPU in Panda3D, and the illumination boundaries appear to remain fixed on an AMD GPU.

## Steps to Reproduce
The phenomenon may be observed, given one has both an AMD 6700 XT and a NVIDIA RTX 2060 to test with, with the following spotlight code:

    def shadow_spot():
        slight = Spotlight('shadow_spot')
        slight.set_shadow_caster(True, 4096, 4096)
        slight.set_color((2, 2, 2, 1))
        lens = PerspectiveLens()
        lens.set_near_far(0.5, 5000)
        lens.set_fov(140)
        slight.set_lens(lens)
        slight.set_priority(15)
        slight = base.render.attach_new_node(slight)
        slight.set_pos(-140, -80, 25)
        slight.look_at(0, 0, 10)
        base.render.set_light(slight)
        
    shadow_spot()

...and some camera movement code to get a camera moving around to see the phenomenon.

## Environment
 * Operating system:
 * Ubuntu 20.04.3
 * Panda3D version: 1.10.9
 * Installation method: pip3
 * Python version (if using Python): 3.8.10
* Tested on the following GPUs: AMD 6700 XT, NVIDIA RTX 2060, NVIDIA RTX 3060 (mobile)
* Tested with Ryzen 3, 5, and Intel i7 CPUs

**Comment by rdb** [comment]
Thanks for filing this issue.  Would you mind posting a complete runnable sample including any required assets?  Thanks!

**Comment by rayanalysis** [comment]
Here's a self-contained sample which you may run, I believe.
[panda3d_spotlight_test.zip](https://github.com/panda3d/panda3d/files/7575222/panda3d_spotlight_test.zip)

Press "a" to begin moving the camera. Lines 27 and 28 contain the shader application to set the "incorrect_shader" or the "correct_shader". The shaders included are the most recent public build of simplepbr with hardware skinning and shadows manually enabled, I believe. The "incorrect_shader" is set by default so that one can see the spotlight boundary movement, on NVIDIA hardware anyway.

The only difference between the "correct_shader" and the "incorrect_shader" is the order in which the transform_weight and the transform_index are set in the vert shader.

The "correct_shader":

attribute vec3 p3d_Normal;
attribute vec4 p3d_Vertex;
attribute vec4 p3d_Color;
attribute vec4 p3d_Tangent;
attribute vec2 p3d_MultiTexCoord0;

attribute vec4 transform_weight;
attribute uvec4 transform_index;

The "incorrect_shader":

attribute vec3 p3d_Normal;
attribute vec4 transform_weight;
attribute uvec4 transform_index;
attribute vec4 p3d_Vertex;
attribute vec4 p3d_Color;
attribute vec4 p3d_Tangent;
attribute vec2 p3d_MultiTexCoord0;

Perhaps this is not really an issue with Panda3D, though I do find it odd -- especially since the spotlight seems to appear fixed on AMD hardware with the "incorrect_shader" applied.

**Comment by rdb** [comment]
Yeah, can reproduce this on my NVIDIA card.  It seems that the `skin_matrix` isn't quite identity, causing not just the spotlight but also the model itself to transform strangely.  It seems that on NVIDIA, the `transform_weight` column (when absent) does not contain the OpenGL-mandated default value of (0, 0, 0, 1).  I fixed it by forcing the column to that value explicitly.

Fix will be in 1.10.11.  In the meantime, disabling hardware skinning should work around the problem.
