### ISSUE TITLE
OnscreenImage error loader

### ISSUE THREAD

**Issue by yoyoy99** [panda3d/panda3d#1209]
Je n'arrive pas à utiliser la fonction OnscreenImage. Je ne comprend pas l'erreur fin le résoudre.
Je suis un noob !
voilà l'erreur que m'affiche mon shell:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoldUpLife\HoldUpLife\SurviveInCities.py", line 27, in <module>
    vie2d = OnscreenImage(image='coeur.png', pos=(-1,0,-1))
  File "C:\Panda3D-1.10.10-x64\direct\gui\OnscreenImage.py", line 60, in __init__
    self.setImage(image, parent = parent, sort = sort)
  File "C:\Panda3D-1.10.10-x64\direct\gui\OnscreenImage.py", line 117, in setImage
    tex = loader.loadTexture(image)
NameError: name 'loader' is not defined

**Comment by rdb** [comment]
The error means that you are trying to create an OnscreenImage before ShowBase has been initialized.

I will change this for the next version of Panda3D, so that you don't need to have the ShowBase instance created before you create the image.  However, it should be easy to fix this by simply waiting with creating the OnscreenImage until after ShowBase has started.

**Comment by yoyoy99** [comment]
Merci sérieux

**Comment by yoyoy99** [comment]
@rdb Est-ce que ça veut dire que la majorité des éléments de mon jeu vont se trouver dans la classe ShowBase ?

**Comment by rdb** [comment]
I am not quite sure I understand what you are trying to ask.  You certainly won't have to put the elements of your game inside ShowBase, but some parts of Panda (such as OnscreenImage) expect that ShowBase has already been created when you first create them.  You can still put your OnscreenImage in other places, but they have to be invoked *after* ShowBase has started.

Alternatively, you can use this workaround:
```python
vie2d = OnscreenImage(image=TexturePool.loadTexture('coeur.png'), pos=(-1,0,-1))
```

**Comment by yoyoy99** [comment]
d'accord j'ai compris
