### ISSUE TITLE
PGButton on pixel_2d not responding to mouse clicks

### ISSUE THREAD

**Issue by git2323** [panda3d/panda3d#1222]
## Description
As described and discussed here: [click](https://discourse.panda3d.org/t/pgbutton-not-responding-to-a-mouse-click-on-pixel2d/28234) currently PGButtons can not be clicked on pixel_2d and therefore do not generate events. Also when hovering over the button, the look of the button does not change (to depressed).

## Steps to Reproduce
A test case is attached.

## Environment
 * Operating system: Windows 10
 * System architecture: 64 bit
 * Panda3D version: 1.10.10
 * Installation method: SDK
 * Python version (if using Python): -
 * Compiler (if using C++): MSVC 2022
[button.zip](https://github.com/panda3d/panda3d/files/7741100/button.zip)

Thanks

**Comment by rdb** [comment]
As a workaround, try:
```cpp
DCAST(PGTop, window->get_pixel_2d().node())->set_mouse_watcher(DCAST(MouseWatcher, window->get_mouse().node()));
```
