### ISSUE TITLE
Python SDK is installed in wrong site

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#1230]
## Description

With recent master builds, the Python SDK is installed in the wrong site-packages on Linux Mint 20 (And I assume Ubuntu Focal). This problem occurs since 2fcacd1bab1226ea0571c5d925daf6028a862f96

Previously, the Python SDK was installed in `/usr/lib/python3/dist-packages` but now it is in `/usr/lib/python3.8/site-packages`
However this path is not in the configured Python 3.8 site :

<pre>
$ python3.8 -m site
sys.path = [
    '/usr/lib/python38.zip',
    '/usr/lib/python3.8',
    '/usr/lib/python3.8/lib-dynload',
    '/home/ld/.local/lib/python3.8/site-packages',
    '/usr/local/lib/python3.8/dist-packages',
    '/usr/lib/python3/dist-packages',
    '/usr/lib/python3.8/dist-packages',
]
USER_BASE: '/home/ld/.local' (exists)
USER_SITE: '/home/ld/.local/lib/python3.8/site-packages' (exists)
ENABLE_USER_SITE: True
</pre>

## Steps to Reproduce

    python3.8 makepanda/makepanda.py --everything --no-gles --no-gles2 --no-egl --use-sse2 --threads=4 --optimize=3 --wheel --installer

Disclaimer: I have another version of Python (3.7) also installed on this system, but until now it was not an issue :)

## Environment
 * Operating system: Linux Mint 20
 * System architecture: amd64
 * Panda3D version: latest master
 * Installation method: built from source
 * Python version (if using Python): Python 3.8.5
 * Compiler (if using C++): n/a

**Comment by rdb** [comment]
Wow, that is annoying. I guess we have to go back to the deprecated module for now and revisit this when Python 3.12 comes around, and pray that they've fixed this bug by then.

**Comment by el-dee** [comment]
After a bit of digging, it seems that Debian is patching `distutils.sysconfig` to use their own paths for site-packages, but not (yet) `sysconfig`.

**Comment by rdb** [comment]
Reverted to `distutils.sysconfig`, with added comments not to "fix" the deprecated use.
