### ISSUE TITLE
Failed to load Default HRTF.mhr from OpenAL

### ISSUE THREAD

**Issue by alovictor** [panda3d/panda3d#1233]
## Description

I'm trying to reproduce a sound example but I'm getting some problems to load the default HRTF file from OpenAL. Other applications that use OpenAL loads sound properly.

Terminal log:
```
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
AL lib: (EE) GetLoadedHrtf: Invalid header in /usr/share/openal/hrtf/Default HRTF.mhr: "MinPHR03"
AL lib: (EE) GetLoadedHrtf: Failed to load /usr/share/openal/hrtf/Default HRTF.mhr
```

## Steps to Reproduce

The code is avaliable [here](https://github.com/Schwarzbaer/panda_examples/tree/master/3d-sound)

## Environment
 * Operating system: Manjaro Linux 21.2.1
 * System architecture: x86_64
 * Panda3D version: 1.10.10
 * Installation method:  pip
 * Python version (if using Python): 3.10.1

**Comment by rdb** [comment]
It might be that the version of OpenAL Soft we build Panda with is too old to be able to parse the HRTF files on your system.

I will see if we can build the next version of Panda3D with a more recent version of OpenAL Soft.

**Comment by rdb** [comment]
Unfortunately, I can't do that, because OpenAL 1.20.1 doesn't compile on manylinux1, which we build the wheels on.

Your best option to fix this is to build from source or wait for us to switch our minimum requirement to manylinux2010 (probably in Panda 1.11.0).

**Comment by alovictor** [comment]
I thought it was the version of OpenAL too. No problem if can't fix now. Thanks for the support!

**Comment by Max-Rodriguez** [comment]
I have also been getting this same output whenever I run panda, but audio still works fine.
Glad to know Panda is going to keep up to date 👍🏼
