### ISSUE TITLE
Suggestion: Add a "getter" for the "positional" flag of the "AudioSound" class.

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#1257]
## Description
Simply put, this issue is to suggest that a "getter" method be added to the "AudioSound" class in order to read the value of the "positional" flag.

## Use Case
There may be cases in which one wants to know whether or not an extant "AudioSound" object is set up for use with the 3D-positional system.

Indeed, a sound that is so set up may misbehave when treated as a "2D" sound, while a sound that is _not_ so set up may not respond to attempts to position it in space, if I'm not much mistaken.

(This is _not_ urgent in the case of myself, the original poster of this issue.)

**Comment by rdb** [comment]
This would require adding a new virtual `get_positional` method to AudioSound, creating a `MAKE_PROPERTY` definition there for `positional` (there's no need to expose `get_positional` to Python if we already have a `.positional` property), and implementing `get_positional` in the various audio subclasses.
