### ISSUE TITLE
PyDatagram Variable Overwrite bug

### ISSUE THREAD

**Issue by UlvFoerlev** [panda3d/panda3d#1262]
## Description
Datagrams raises:
 `Assertion failed: _current_index < _datagram->get_length() at line 147 of panda/src/express/datagramIterator.I
` 
Exception, when trying to get string (`getString()` method) using `PyDatagramIterator`, if it is held on the same  variable that previously held the PyDatagram.

## Steps to Reproduce
_Tests using pytest_

Raises exception:
```
from direct.distributed.PyDatagram import PyDatagram
from direct.distributed.PyDatagramIterator import PyDatagramIterator


def test_datagram_minimal_does_not_work():
    text = "Just Some string"

    datagram = PyDatagram()
    datagram.addString(text)

    datagram = PyDatagramIterator(datagram)
    assert datagram.getString() == text
```

Does not raise Exception:
```
from direct.distributed.PyDatagram import PyDatagram
from direct.distributed.PyDatagramIterator import PyDatagramIterator

def test_datagram_minimal_works():
    text = "Just Some string"

    datagram = PyDatagram()
    datagram.addString(text)

    iterator = PyDatagramIterator(datagram)
    assert iterator.getString() == text
```
_Notice that the only change is that the PyDatagramIterator is saved unto a variable with a different name._

## Environment
 * Operating system: Kubuntu 20.04
 * System architecture:
  KDE Plasma Version: 5.18.5
  KDE Frameworks Version: 5.68.0
  Qt Version: 5.12.8
  Kernel Version: 5.4.0-99-generic
  OS Type: 64-bit
  Processors: 8 × Intel® Core™ i7-7700HQ CPU @ 2.80GHz
  Memory: 15,5 GiB of RAM

 * Panda3D version: 1.10.9
 * Installation method: pip
 * Python version: Python 3.9.5

**Comment by UlvFoerlev** [comment]
Tested on panda3d 1.10.11
Still raises an error, but a different one:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 14: invalid continuation byte`

**Comment by rdb** [comment]
Datagram is not a reference-counted class.  It is necessary to hold a reference to it to prevent it from being deleted.

That said, it might be a good idea to have PyDatagramIterator store such a reference to it.
