### ISSUE TITLE
NodePath with a scale of 10k starts bugging out.

### ISSUE THREAD

**Issue by xTrayambak** [panda3d/panda3d#1263]
So, whenever you set a NodePath's scale to 10k or above, it starts freaking out in unintended ways... Here is a clip of a cubic skybox which is an .egg file loaded in performing unexpected behaviour when it's scale is set to 10000.

As you can see, as the camera moves around, the skybox's parts start to disappear, I wonder if it's a culling issue?

Here are the steps to reproduce.

1) Make a .egg model.
2) Import it into a boilerplate Panda3D project.
3) Set it's scale to 10000.
4) Run the game.

Here is some sample code (instance.objectloader) is my own class, it is not in Panda3D. Use `instance.loader.loadModel` instead.
(instance is a ShowBase [direct.showbase.ShowBase])
`
skybox = instance.objectLoader.loadObject("skybox")
skybox.reparentTo(instance.render)
skybox.set_two_sided(True)
skybox.set_bin("background", 0)
skybox.set_depth_write(False)
skybox.set_compass()
skybox.setScale(5000)
skybox.set_light_off(1)
skybox.set_material_off(0)
skybox.set_color_off(1)
`

https://user-images.githubusercontent.com/59499552/154198737-69c431c6-4870-4779-aaef-a6b7cf81733f.mp4

.

**Comment by janEntikan** [comment]
Not a panda3d bug. Floats become very imprecise when they become very large.  

```
skybox.set_bin("background", 0)
skybox.set_depth_write(False)
```
Calling this should be enough to have it be rendered behind everything else, you don't have to scale your skybox for that.

It's possible to compile panda3d do handle double precision floats to handle floats this big, but that is not the right solution to this problem.

**Comment by Moguri** [comment]
Closing this since, as @janEntikan mentioned, this is known limitation of 32bit floats and not an Panda3D issue.

**Comment by rdb** [comment]
This actually looks like an issue with the far distance to me.  Increase the far distance of the camera and it should work.
