### ISSUE TITLE
Unable to start Android applications due to import error

### ISSUE THREAD

**Issue by thetestgame** [panda3d/panda3d#1279]
## Description
Using the latest changes to the build_apps/bdist_apps commands Android no longer starts. Regardless of project/setup it always fails trying to import the math module

```
D/Python  (24692): Traceback (most recent call last):
D/Python  (24692):   File "__main__", line 16, in <module>
D/Python  (24692):   File "importlib._bootstrap", line 991, in _find_and_load
D/Python  (24692):   File "importlib._bootstrap", line 973, in _find_and_load_unlocked
D/Python  (24692): ModuleNotFoundError: No module named 'math'
```

## Steps to Reproduce
Compile the sample application provided here and attempt to run it

https://github.com/thetestgame/panda3d-android-sample

## Environment
 * Operating system: Android
 * System architecture: ARM
 * Panda3D version: 1.11.0
 * Installation method: (eg. pip, wheel, SDK, built from source) wheel
 * Python version (if using Python): 3.8
 * Compiler (if using C++):

**Comment by rdb** [comment]
Can't repro, works for me with the wheels I uploaded.  Do you have local changes?  Are you using an old version of commands.py / FreezeTool.py?

**Comment by Moguri** [comment]
Closing as incomplete for now. Please feel free to reopen this issue if/when the requested information is supplied.
