### ISSUE TITLE
Compiling on 2017 Intel MacBook Pro fails immediately

### ISSUE THREAD

**Issue by nate97** [panda3d/panda3d#1287]
Hi, I'm unable to compile P3D on MacOS, as soon as I run the commands to compile I get this error, have previously successfully compiled P3D on Linux.

Any help would be appreciated, thanks.

error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: in swap_object_headers(): malformed load command 0 (cmdsize not a multiple of 4)
fatal error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: internal error: swap_object_headers() failed
Storing dependency cache.
Elapsed Time: 0 sec
The following command returned a non-zero value: install_name_tool -id @loader_path/../lib/libopencv_highgui.2.4.3.dylib built/lib/libopencv_highgui.2.4.3.dylib

Panda3D commit [3084fcd]

**Comment by rdb** [comment]
Which version of the thirdparty libraries have you used?

Which exact compile command are you using?

**Comment by Moguri** [comment]
No follow up in over a month, so I am closing this as incomplete. Please feel free to reopen the issue if/when the requested information is supplied.
