### ISSUE TITLE
Unable to create floating point render target with WebGL

### ISSUE THREAD

**Issue by Kupoman** [panda3d/panda3d#1296]
## Description
It appears there are some parts of the GLES code base that has some incorrect assumptions of capabilities when trying to use OpenGL ES3. In particular, I have identified to places that require updates to create a floating point render target.

In [glGraphicsBuffer_src.cxx](https://github.com/panda3d/panda3d/blob/webgl-port/panda/src/glstuff/glGraphicsBuffer_src.cxx#L842) there is an `OPENGLES` block in the `bind_slot` function. This block has no paths for choosing a floating point texture format such as GL_RGBA16F.

In glGraphicsStateGuardian_src.cxx there is a function called `get_internal_image_format` that is unable to report a floating point format when using WebGL/GLES3. I believe this is because of two pieces of code. The first is an emscripten check that excludes any signed formats: https://github.com/panda3d/panda3d/blob/webgl-port/panda/src/glstuff/glGraphicsStateGuardian_src.cxx#L10519. Even after this there is no code path for GLES to report a floating point format such as `GL_RBA16F`
[patch.txt](https://github.com/panda3d/panda3d/files/8597769/patch.txt)

I have attached a patch to this issue containing rough hacks that allow me to create a floating point render target with the `webgl-port` branch.

## Steps to Reproduce
The following application should be sufficient to see the problems with creating a floating point render target.
```Python
from direct.showbase.ShowBase import ShowBase
from panda3d.core import *


class App(ShowBase):
    def __init__(self):
        super().__init__()

        gsg = self.win.get_gsg()
        extensions = [
            'EXT_color_buffer_float',
        ]
        for ext in extensions:
            if gsg.has_extension(ext):
                print(ext, 'is enabled')
            else:
                print(ext, 'is disabled')

        fbprops = FrameBufferProperties()
        fbprops.float_color = True
        fbprops.set_rgba_bits(16, 16, 16, 16)
        fbprops.set_depth_bits(24)

        winprops = WindowProperties()
        winprops.setSize(640, 480)

        texture = Texture()
        texture.set_format(Texture.F_rgba16)
        texture.set_component_type(Texture.T_float)

        buffer=base.graphicsEngine.makeOutput(
            self.win.getPipe(),
            'debug',
            -1,
            fbprops,
            winprops,
            GraphicsPipe.BFRefuseWindow | GraphicsPipe.BFResizeable,
            self.win.getGsg(),
            self.win
        )
        buffer.addRenderTexture(texture, GraphicsOutput.RTMBindOrCopy, GraphicsOutput.RTPColor)

App().run()
```

## Environment
 * Operating system: Arch Linux
 * System architecture: 64bit
 * Panda3D version: webgl-port branch
 * Installation method: built from source
 * Python version (if using Python): 3.8
 * Compiler (if using C++): emcc 3.1.2

**Comment by rdb** [comment]
Yeah, the format code has become a mess, with the distinction between OpenGL ES and desktop GL blurring more and more it's probably worth it to refactor at some point.

**Comment by rdb** [comment]
Would you mind checking whether it is fixed now? :)

**Comment by Kupoman** [comment]
Thank you for working on this! Unfortunately, something seems to not be quite right yet. I am digging into it to see if I can figure out what is missing.

**Comment by Kupoman** [comment]
OK, I think for some reason my browser is reporting that I do not have `EXT_color_buffer_half_float`. At least for WebGL 2, it looks like `EXT_color_buffer_float` includes half float formats: https://developer.mozilla.org/en-US/docs/Web/API/EXT_color_buffer_float. I do not know if it is the same for GLES 3.

My current patch is now much smaller than before:
```diff
diff --git a/panda/src/glstuff/glGraphicsBuffer_src.cxx b/panda/src/glstuff/glGraphicsBuffer_src.cxx
index 32e6fb4eb5..3486ced41e 100644
--- a/panda/src/glstuff/glGraphicsBuffer_src.cxx
+++ b/panda/src/glstuff/glGraphicsBuffer_src.cxx
@@ -916,7 +916,7 @@ bind_slot(int layer, bool rb_resize, Texture **attach, RenderTexturePlane slot,
                  glgsg->has_extension("GL_EXT_color_buffer_float")) {
         gl_format = GL_RGBA32F_EXT;
       } else if (_fb_properties.get_float_color() &&
-                 glgsg->has_extension("GL_EXT_color_buffer_half_float")) {
+                 glgsg->has_extension("GL_EXT_color_buffer_float")) {
         gl_format = GL_RGBA16F_EXT;
 #endif
       } else if (_fb_properties.get_color_bits() == 0) {
```

**Comment by rdb** [comment]
Yes, the `float` extension is for WebGL 2 / GLES 3 and the `half_float` extension is for WebGL 1 / GLES 2.  I need to check for both.

**Comment by rdb** [comment]
I think I've fixed this now.  Please let me know whether it works now.

**Comment by Kupoman** [comment]
That seemed to do it. Thank you very much. You may close this issue.
