### ISSUE TITLE
Add new objects by users

### ISSUE THREAD

**Issue by moon5ye** [panda3d/panda3d#1300]
## Description
Suppose I try to simulate traffic, where there exists many vehicles running on the road network.

How could I let users add vehicles by clicking the mouse?

## Use Case
For example, if I move mouse to a specific road line, what should I do to add vehicles on the specific road?

I think the first step is to find the correpoinding road line by mouse position. Could I use the CollisionNode('mouseRay') to find the correponding road?

After I find the correpoinding road line, I could spawn a car on this road.

Thanks

**Comment by rdb** [comment]
Hi there!

I think you should ask your question on the Panda3D forums, you'll probably have more luck finding help there:
https://discourse.panda3d.org/

The GitHub issue tracker is only used to track bugs and feature requests and most Panda3D users don't hang out here.
