### ISSUE TITLE
GarbageReport tries to check for old-style classes

### ISSUE THREAD

**Issue by tyteen4a03** [panda3d/panda3d#1304]
https://github.com/panda3d/panda3d/blob/master/direct/src/showbase/GarbageReport.py#L216 references `types.InstanceType`, which only exists in old-style classes. They haven't been relevant for a very long time so it should be safe to change the check to `inspect.isclass(obj)`.

**Comment by rdb** [comment]
So, fixing this while preserving current behaviour on Python 3 would mean removing these cases entirely, but perhaps GarbageReport would work better if new-style classes did get handled under this case? I have no idea what this code is for and how it is used, to be honest.
