### ISSUE TITLE
Setting the window to fullscreen on MacOS causes a blackscreen

### ISSUE THREAD

**Issue by LuigiFan25** [panda3d/panda3d#1316]
## Description

I expected the application to set the window to fullscreen mode , instead it goes to a blackscreen and I have to force quit the application.
The workaround is to use the maximize window on Mac without option clicking.
## Steps to Reproduce

Use 
```
 properties = WindowProperties()
properties.setFullscreen(True)
```

## Environment
 * Operating system: MacOS 12.2.1
 * System architecture: ARM64
 * Panda3D version:  1.11.0
 * Installation method: (eg. pip, wheel, SDK, built from source) built from source then used pip install
 * Python version (if using Python): 3.9
 * Compiler (if using C++): clang 13.1.6

**Comment by el-dee** [comment]
A black screen should never occur, either the app enters fullscreen or an error is reported. So it seems there is a display  mode that is advertised but does not support fullscreen.
Would you mind adding the following lines at the top of your test script and attach the output here ?

<pre>
from panda3d.core import load_prc_file_data
load_prc_file_data("", "notify-level-cocoadisplay spam")
</pre>

**Comment by LuigiFan25** [comment]
Interesting enough other background stuff still works as I can hear audio
```
Known pipe types:
  CocoaGraphicsPipe
(2 aux display modules not yet loaded.)
:05-31-2022 19:16:53 :display:cocoadisplay(debug): Creating CocoaGraphicsPipe for display ID 1
:05-31-2022 19:16:54 :display:cocoadisplay(debug): Pixel format has 1 virtual screens.
:05-31-2022 19:16:54 :display:cocoadisplay(debug): Created context 0x600003cc9ba0: depth_bits=32 color_bits=24 red_bits=8 green_bits=8 blue_bits=8 alpha_bits=8 multisamples=2 back_buffers=1 force_hardware 
:05-31-2022 19:16:54 :display:cocoadisplay(debug): Creating NSWindow with content rect {{0, 0}, {1440, 900}}
:05-31-2022 19:16:54 :display:cocoadisplay(debug): Created CocoaPandaView 0x121771020 for GraphicsWindow 0x122962a10


:05-31-2022 19:16:54 :display:cocoadisplay(debug): Switched to fullscreen, screen rect is now {{0, 0}, {1280, 800}}
:05-31-2022 19:16:54 :display:cocoadisplay(spam): Mouse pointer entered window
:05-31-2022 19:16:54 :display:cocoadisplay(spam): drawRect was called.
:05-31-2022 19:16:56 :display:gsg:glgsg(error): GL error 0x506 : invalid framebuffer operation
:05-31-2022 19:16:56 :display:gsg:glgsg(error): An OpenGL error has occurred.  Set gl-check-errors #t in your PRC file to display more information.
:05-31-2022 19:16:56 :display:cocoadisplay(debug): Window became key

ToontownStart: serverVersion:  staff-build-1.0
:05-31-2022 19:16:56 :display:gsg:glgsg(error): GL error 0x506 : invalid framebuffer operation
:05-31-2022 19:16:56 :display:gsg:glgsg(error): An OpenGL error has occurred.  Set gl-check-errors #t in your PRC file to display more information.

:05-31-2022 19:16:58 :display:gsg:glgsg(error): GL error 0x506 : invalid framebuffer operation
:05-31-2022 19:16:58 :display:gsg:glgsg(error): An OpenGL error has occurred.  Set gl-check-errors #t in your PRC file to display more information.
:05-31-2022 19:16:58 :display:cocoadisplay(spam): Handled keypress, character 9, keyCode 48, type 11, flags 1048840

:05-31-2022 19:16:58 :display:gsg:glgsg(error): GL error 0x506 : invalid framebuffer operation
:05-31-2022 19:16:58 :display:gsg:glgsg(error): An OpenGL error has occurred.  Set gl-check-errors #t in your PRC file to display more information.
:05-31-2022 19:16:59 :display:gsg:glgsg(error): GL error 0x506 : invalid framebuffer operation
:05-31-2022 19:16:59 :display:gsg:glgsg(error): An OpenGL error has occurred.  Set gl-check-errors #t in your PRC file to display more information.
```

**Comment by el-dee** [comment]
I tried to reproduce your problem but I have no issue switching to 1280x800 on all the screen I could test with. My assumption is that you have a display mode that has less display bits that has been initially configured for your default frame buffer.

Could you add the following code to your program :

```python
info = self.pipe.getDisplayInformation()
for idx in range(info.getTotalDisplayModes()):
    width = info.getDisplayModeWidth(idx)
    height = info.getDisplayModeHeight(idx)
    bits = info.getDisplayModeBitsPerPixel(idx)
    rate = info.getDisplayModeRefreshRate(idx)
    print(width, height, bits, rate)
```

Also could you add 

```python
load_prc_file_data("", "gl-check-errors #t")
```

And copy the output here ?

Also, do you have any specific framebuffer parameters in your prc config ?

**Comment by rdb** [comment]
I can replicate this on macOS 13.0 arm64.  Nothing odd about the display modes, only those with 32 bits are being reported.  It seems that the call to CGLSetFullScreenOnDisplay is failing with a "bad drawable" error, hmm.

**Comment by rdb** [comment]
I can replicate the issue even with an emulated x86_64 build made with `-mmacosx-version-min=10.9` built against the 10.9 SDK.

The black screen occurs because of CGCaptureDisplay.  Unfortunately we can't know about the failure until much later, in begin_frame.  I haven't been able to figure out if there is a way around the CGLSetFullScreenOnDisplay failure.  I think we just need to find the condition under which this occurs reliably and disable CGCaptureDisplay in that case.

Is the condition "running an arm64 system"?  Or is it "running macOS >=x.y"?  Can people replicate this problem on non-arm64 macOS 12+?

**Comment by el-dee** [comment]
For info, to support HiDPI mode, see #1308, i had to remove calls to CGLSetFullScreenOnDisplay() as it does not support HiDPI and in consequence also calls to CGDisplayCapture() or i would end up with black screen as well.

I will test on x86 and macOS 12 to check again, but last time I checked I didn't had the problem. My assumption is that Cocoa lists a display mode that is not usable and it slips through the tests to reject them.

**Comment by rdb** [comment]
> My assumption is that Cocoa lists a display mode that is not usable and it slips through the tests to reject them.

This is not the problem because I can replicate it even with all the display changing calls commented out.

I'm fine with switching to however Apple wants us to do things nowadays on the master branch (whether that's switchToFullscreenMode or something with CAOpenGLLayer or just a borderless on-top window), but I do need a solution for 1.10.

I would be very grateful if you could test on x86 with macOS 12, built against a recent macOS SDK.  If you can't replicate it on x86, we can conclude it's an arm64-only problem.

**Comment by laurentderu** [comment]
> The black screen occurs because of CGDisplayCapture. Unfortunately we can't know about the failure until much later, in begin_frame. I haven't been able to figure out if there is a way around the CGLSetFullScreenOnDisplay failure. I think we just need to find the condition under which this occurs reliably and disable CGDisplayCapture in that case.

I have identified a problem with the level used for the fullscreen window that could explain this (see https://github.com/panda3d/panda3d/pull/1308#issuecomment-1304638228)
I will also check if I have a black screen when building using SDK 12 instead of SDK 10.9

**Comment by el-dee** [comment]
> The black screen occurs because of CGDisplayCapture. Unfortunately we can't know about the failure until much later, in begin_frame. I haven't been able to figure out if there is a way around the CGLSetFullScreenOnDisplay failure. I think we just need to find the condition under which this occurs reliably and disable CGDisplayCapture in that case.

I have identified a problem with the level used for the fullscreen window that could explain this (see https://github.com/panda3d/panda3d/pull/1308#issuecomment-1304643154)
I will also check if I have a black screen when building using SDK 12 instead of SDK 10.9

**Comment by el-dee** [comment]
I rebuilt the latest release/0.10.x with SDK 12 and I don't experience black screen when switching to fullscreen. I will test more in the next days, but this could point towards an ARM only issue.

**Comment by rdb** [comment]
I will test again with the changes you suggested in the other thread, related to display capturing.

**Comment by rdb** [comment]
It appears that in M1, the OpenGL driver is actually based on top of Metal, which uses CAMetalLayer, which doesn't support the CGL full-screen APIs, that's why it doesn't work.

I don't know the cleanest way to detect whether this driver is used.  I would just disable the use of CGLSetFullscreenOnDisplay after the first failure, but it seems to mess up the OpenGL state.  I am just going to detect whether we're on an arm64-based Mac (so, `__aarch64__` or `__x86_64__` and running in Rosetta) and if so, disable that call.  On master, maybe we should just remove that call altogether.

I haven't needed to use CGCaptureAllDisplays to make it work, though.  @el-dee could you clarify how you discovered the need for this?

**Comment by el-dee** [comment]
> I haven't needed to use CGCaptureAllDisplays to make it work, though. @el-dee could you clarify how you discovered the need for this?

If I remember correctly, without `CGCaptureAllDisplays()` I had troubles on a multi-screen setup. Looking back at it now it is actually a separate issue that just popped up while testing :)

The CG documentation describes it well :

> If hardware or software mirroring is in effect, the easiest way to capture the primary display and all mirrored displays is to use the function [CGCaptureAllDisplays()](https://developer.apple.com/documentation/coregraphics/1455221-cgcapturealldisplays). In case of software mirroring, applications that draw directly to the display must make sure to draw the same content to all displays in the mirror set.

See https://developer.apple.com/documentation/coregraphics/1456259-cgdisplaycapture

**Comment by rdb** [comment]
So, on some Mac versions we need to use CGShieldingWindowLevel() and others we need to use NSMainMenuWindowLevel+1?  I'm guessing that would be M1-based macs only for CGShieldingWindowLevel?

Or do we need to just not use CGLSetFullscreenOnDisplay?

**Comment by el-dee** [comment]
There is not documentation whatsoever about `CGLSetFullscreenOnDisplay()` (which is deprecated) from Apple and I suspect it does many things under the hood

I could retrieve this from LWJGL (Lightweight Java Game Library) :

> In OS X v10.6 or later, this function is not deprecated, but is usually not necessary. If your application creates a window that completely covers the screen, the system implicitly creates a full-screen instance, for the same potential performance benefit.
Deprecated in OS X v10.7.

Also, I cheated a bit and looked at SDL implementation, they are not using `CGLSetFullscreenOnDisplay()` and they set the windot level to `CGShieldingWindowLevel` when in fullscreen mode.

So I would lean to remove `CGLSetFullscreenOnDisplay()` altogether.

**Comment by rdb** [comment]
You're right, it does break on Intel.  Ugh!  Fine, getting rid of `CGLSetFullscreenOnDisplay()`, pushed to release/1.10.x branch.  What a mess, Apple.
