### ISSUE TITLE
PStats: GPU Timing Not Working

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#1320]
## Description
When PStats is started with the "pstats-gpu-timing 1" PRC-option enabled in the host program, a menu-item becomes available that allows one to open a performance graph for the GPU, as expected. However, the graph so produced always reports a value of "0.0000 ms", and indeed, no plot is drawn on the graph.

![Screenshot from 2022-06-10 11-58-20](https://user-images.githubusercontent.com/36933600/173043937-e64a5e20-65fc-433a-b89f-f63fde98fe6e.png)

## Steps to Reproduce
Connect a program to PStats with the "pstats-gpu-timing 1" PRC-option applied, and open the resulting GPU-timing graph.

Here then is a simple program that demonstrates the problem, at least on my machine:
```python
from panda3d.core import loadPrcFile, loadPrcFileData
loadPrcFileData("", "want-pstats #t")
loadPrcFileData("", "pstats-gpu-timing 1")

from direct.showbase.ShowBase import ShowBase

from panda3d import __version__ as pandaVersion
print (pandaVersion)

import sys
print (sys.version)

class Game(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)

app = Game()
app.run()
```

## Environment
 * Operating system: Ubuntu 18.04.6
 * System architecture: 64-bit
 * Panda3D version: 1.10.11
 * Installation method: pip, I believe.
 * Python version (if using Python): 3.6.9
 * Compiler (if using C++): N/A
 * Graphics card: NVidia GeForce 840M
 * Graphics driver: “NVidia driver metapackage from nvidia-driver-470”

**Comment by Moguri** [comment]
I don't know what's going on here, but I'll try and run the test case on my machine soon to see if I can reproduce the issue. I suspect something with the GPU drivers is breaking query timers, so I copied over your GPU information from your forum post.

**Comment by ArsThaumaturgis** [comment]
Thank you! ^_^

In case it helps, a look at the NVidia X Server Settings program indicates that I have driver version 470.129.06.

**Comment by ArsThaumaturgis** [comment]
Thank you for this! ^_^
