### ISSUE TITLE
Make Panda3d  supported by pylance language server in vscode

### ISSUE THREAD

**Issue by BlackEagle1983** [panda3d/panda3d#1324]
## Description

Hello . Thank you for developing this framework . My friends and I are using vscode for programming python . But Pylance language server does not support your framework in its autosuggestion . I write my problem in vscode github and they told me Panda3d framework is compiled and need type stubs for being supported by pylance .
Do you have any policy for this issue or we have to change our editor ?

**Comment by rdb** [comment]
Duplicate of #1327
