### ISSUE TITLE
FT_shadow not set automatically for samplerCubeShadow

### ISSUE THREAD

**Issue by Germanunkol** [panda3d/panda3d#1332]
## Description
Panda creates a texture (samplerCubeShadow) automatically for Point Lights and I can access that through in my shaders.
However, sampling the texture with the GLSL `texture()` outputs a constant, and does not output an interpolated value (as it should per the documentation).
The only workaround I've found is to manually change the texture's filter mode _after_ it has been created for the PointLight, to FT_shadow. I expected this to be set up by Panda3d automatically, because otherwise samplerCubeShadow cannot be used appropriately (I think).

## Steps to Reproduce
I posted a minimal example in a github repository (current newest commit on master: bafc4ed627346ea5169adab6242bb7e5afb880d8).
https://github.com/Germanunkol/Panda3D-Soft-Hardware-Shadows

Before manual switch to FT_shadow filter mode (no shadows):
![Screenshot from 2022-07-17 17-10-33](https://user-images.githubusercontent.com/1830593/179404728-573405bc-b22e-44ff-92b0-e2df12c5d6c9.png)
After manual switch (correct):
![Screenshot from 2022-07-17 17-10-32](https://user-images.githubusercontent.com/1830593/179404720-ea6b1ca4-b861-4e8c-81ab-248e14d296ec.png)

## Environment
 * Operating system: Ubuntu 20.04
 * Panda3D version: 1.10.7
 * Installation method: pip
 * Python version (if using Python): 3.8.10

**Comment by rdb** [comment]
Added `shadow-cube-map-filter` config var, set it to true to enable the filter by default.  For backward compatibility, it remains false in 1.10.  Revisit for 1.11 when shaderpipeline is merged, we can default it to true then.
