### ISSUE TITLE
garbage collection problem

### ISSUE THREAD

**Issue by BMaxV** [panda3d/panda3d#1345]
## Description

Panda just crashed. No idea why. No idea how to reproduce it either, see below. I just figured I would create an issue in case someone else runs into it as well.

I'm not using any custom C++, my project is simply using panda, not changing it.

Here is what the console says:

```
:display:gsg:glgsg(error): Unknown rescale_normal mode 3
Assertion failed: _cache_ref_count == 0 at line 93 of built1.10/include/cachedTypedWritableReferenceCount.I
Traceback (most recent call last):
  File "/home/max/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 2143, in __garbageCollectStates
    RenderState.garbageCollect()
AssertionError: _cache_ref_count == 0 at line 93 of built1.10/include/cachedTypedWritableReferenceCount.I
:task(error): Exception occurred in PythonTask garbageCollectStates
main loop error <class 'AssertionError'>
Traceback (most recent call last):
  File "gamecontrol.py", line 344, in <module>
    G.main()
  File "gamecontrol.py", line 202, in main
    r = ob.main(self.game_info_d)
  File "/home/max/Documents/Python/gamecode/gamebuild/Code/panda_my_game.py", line 923, in main
    self.b.taskMgr.step()
  File "/home/max/.local/lib/python3.8/site-packages/direct/task/Task.py", line 504, in step
    self.mgr.poll()
  File "/home/max/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 2143, in __garbageCollectStates
    RenderState.garbageCollect()
AssertionError: _cache_ref_count == 0 at line 93 of built1.10/include/cachedTypedWritableReferenceCount.I
```

## Steps to Reproduce

I don't know how to reproduce this, I will update if I run into the problem again. I immediately tried again and that worked so...

## Environment
 * Operating system: linux / ubuntu / xubuntu
 * System architecture: 5.4.0-122-generic 138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 * Panda3D version: 1.10.11
 * Installation method: pip, I think
 * Python version (if using Python): Python 3.8.10
 * Compiler (if using C++): ---

**Comment by Moguri** [comment]
Unless someone like @rdb happens to suspect something based on the traceback, there is not much we can do without a repro case.

**Comment by rdb** [comment]
Are you using any particular config options other than the defaults, to change the way the state cache is operating?  Are you using threading settings?

> ```
> :display:gsg:glgsg(error): Unknown rescale_normal mode 3
> ```

I'm also curious about this, since the `M_auto` mode is supposed to be replaced in `CullResult::add_object()`.  But if the state cache is corrupted then I can imagine this happening.  Were you seeing this error when the crash wasn't happening too?

**Comment by BMaxV** [comment]
I don't think I have changed any of the defaults. And it hasn't happened again. No idea what caused it then and still no idea now.

**Comment by rdb** [comment]
No repro case and no further info means this is unactionable as-is.  We can reopen if it reoccurs and more information becomes available.
