### ISSUE TITLE
Failed to initialize display connection

### ISSUE THREAD

**Issue by BMaxV** [panda3d/panda3d#1346]
## Description
A restart fixed the problem.

Panda refuses to start as before. Other projects are affected as well. E.g. samples don't run with the same error.

I try to start my project as I usually do, no window is created and the only output is the log below.

## Steps to Reproduce

It keeps not working right now. I will try a restart. A restart did fix it.

This is the relevant part of the log:
```
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
:display:x11display(error): BadValue (integer parameter out of range for operation)
:display:glxdisplay(error): Could not find a usable pixel format.
:display:glxdisplay(error): No GLX context: cannot open window.
:display:gsg:glgsg(warning): Unable to query GL_VENDOR
:display:gsg:glgsg(warning): Unable to query GL_RENDERER
:display:gsg:glgsg(warning): Unable to query GL_VERSION
:display:gsg:glgsg(error): Unable to detect OpenGL version
:display:gsg:glgsg(warning): Unable to query GL_VENDOR
:display:gsg:glgsg(warning): Unable to query GL_RENDERER
:display:gsg:glgsg(warning): Unable to query GL_VERSION
:display:gsg:glgsg(error): Unable to detect OpenGL version
:display:egldisplay(warning): Couldn't initialize the default EGL display: EGL_BAD_ACCESS
:display:egldisplay(error): Failed to find or initialize a suitable EGL display connection.
:ShowBase(warning): Unable to open 'onscreen' window.
Traceback (most recent call last):
  File "gamecontrol.py", line 118, in __init__
    self.panda = wrapper()
  File "/home/max/Documents/Python/gamecode/gamebuild/Code/panda_my_game.py", line 288, in __init__
    self.b=ShowBase()
  File "/home/max/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 339, in __init__
    self.openDefaultWindow(startDirect = False, props=props)
  File "/home/max/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 1024, in openDefaultWindow
    self.openMainWindow(*args, **kw)
  File "/home/max/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 1059, in openMainWindow
    self.openWindow(*args, **kw)
  File "/home/max/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 804, in openWindow
    raise Exception('Could not open window.')
Exception: Could not open window.
```

## Environment
 * Operating system: linux / ubuntu / xubuntu
 * System architecture: 5.4.0-122-generic 138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 * Panda3D version: 1.10.11
 * Installation method: pip, I think
 * Python version (if using Python): Python 3.8.10
 * Compiler (if using C++): ---

**Comment by Moguri** [comment]
This likely happened after a kernel and/or driver update and required reloading one or the other, which a restart will do. This happens to all OpenGL applications on Linux and, as far as I am aware, there isn't anything that Panda can do to work around it.

**Comment by Nockda** [comment]
I have the same problem.
If anyone who has answer, plz tell me

**Comment by ArsThaumaturgis** [comment]
Have you tried a restart of the computer? That seems to have worked for the original poster.
