### ISSUE TITLE
Support for PlayStation Gamepad

### ISSUE THREAD

**Issue by cjtom10** [panda3d/panda3d#1349]
## Description
There doesn't seem to be support for PlayStation controllers ( ie Dualshock 4)

## Use Case
When I connect a PlayStation Controller and open the Device Tester sample, the controler is recognized as "Wireless Controller" but does not accept any input.

**Comment by rdb** [comment]
Which OS?  Which game controller?

**Comment by cjtom10** [comment]
The controller is DualShock 4 on Windows

**Comment by rdb** [comment]
Could you give more information?  Run `device_tester.py` in the gamepad samples folder, what do you see exactly?  And what is printed to the console?

**Comment by cjtom10** [comment]
I just ran `device_tester.py`, and it seems to be working now.
