### ISSUE TITLE
Pipelining render-to-texture bugs

### ISSUE THREAD

**Issue by lachbr** [panda3d/panda3d#1364]
## Description
The attached script demonstrates two issues with the multithreaded pipeline and render-to-texture offscreen buffers.

1) If the buffer is made inactive after creation and made active later, the render-textures that were previously added do not get attached to the OpenGL FBO.
2) If the number of depth bits in the FrameBufferProperties is something other than 32, FRAMEBUFFER_UNSUPPORTED is thrown because the "depth and stencil attachments are mismatched."

Neither issues happen when pipelining is disabled.

## Steps to Reproduce
Script demonstrating issues:
```python
# 2 issues w/ pipelining, neither happen w/ pipelining off
#
# - immediate activation with setDepthBits(1), FRAMEBUFFER_UNSUPPORTED, depth and stencil attachments
#   are mismatched, setDepthBits(32) works fine
#
# - deferred activation, render textures are not attached
#

from panda3d.core import *

prc = """
load-display pandagl
threading-model Cull/Draw
show-buffers 1
notify-level info
default-directnotify-level info
notify-level-glgsg debug
gl-debug 1
"""
loadPrcFileData("", prc)

from direct.showbase.ShowBase import ShowBase

base = ShowBase()

sm = loader.loadModel("models/smiley.egg.pz")
sm.reparentTo(base.render)

fbp = FrameBufferProperties()
fbp.clear()
fbp.setForceHardware(True)
fbp.setFloatColor(True)
fbp.setRgbaBits(16, 16, 16, 0)
fbp.setDepthBits(1) # activate buffer immediately for FRAMEBUFFER_UNSUPPORTED, 32 bits work fine

wprops = WindowProperties()
wprops.setSize(1024, 1024)

flags = GraphicsPipe.BFRefuseWindow

buffer = base.graphicsEngine.makeOutput(
  base.pipe, "buffer", -1, fbp, wprops, flags,
  base.win.getGsg(), base.win)

tex = Texture("color-tex")
buffer.addRenderTexture(tex, GraphicsOutput.RTMBindOrCopy, GraphicsOutput.RTPColor)

dtex = Texture("depth-tex")
buffer.addRenderTexture(dtex, GraphicsOutput.RTMBindOrCopy, GraphicsOutput.RTPDepth)

print(tex)
print(dtex)

dr = buffer.makeDisplayRegion()

cam = Camera("buffer-cam", base.camLens)
camNp = base.render.attachNewNode(cam)
dr.setCamera(camNp)

buffer.setActive(False)

def update(task):
    camNp.setTransform(base.cam.getTransform(base.render))
    return task.cont

def activate():
    print("activate")
    buffer.setActive(True)
    base.bufferViewer.refreshReadout()

base.acceptOnce('a', activate)
#activate()

base.taskMgr.add(update, 'updateCam')

base.run()
```

## Environment
 * Operating system: Windows 11
 * System architecture: x64
 * Panda3D version: 1.10.10
 * Installation method: SDK
 * Python version (if using Python): 3.7.9

**Comment by rdb** [comment]
What I think is happening is that Panda is creating the buffer right away but some of the information (including the list of textures to be rendered) is coming in later, via the pipeline.  There's probably a bug there when Panda switches the FBO from renderbuffers to textures, then.

But even fixing that leaves the awkward pipelining issue.  I see two options:
* Create buffers with active state "false" except for the first stage and have this active state travel down the pipeline, so that the buffer will not be activated right away. (Maybe this should apply to the main window too, since it's currently giving a grey frame at first.)
* Alternatively, we could have addRenderTexture propagate changes down the pipeline immediately, so that the list of textures to render is immediately available to the Draw thread.  This seems to have its own risks because other data might not have had the chance to travel down the pipeline either.

Thoughts?

**Comment by rdb** [comment]
You can also replicate the same issue by not using the multi-threaded pipeline:
```python
from panda3d.core import *

prc = """
load-display pandagl
show-buffers 1
notify-level info
default-directnotify-level info
notify-level-glgsg debug
gl-debug 1
"""
loadPrcFileData("", prc)

from direct.showbase.ShowBase import ShowBase

base = ShowBase()

sm = loader.loadModel("models/smiley.egg.pz")
sm.reparentTo(base.render)

fbp = FrameBufferProperties()
fbp.clear()
fbp.setForceHardware(True)
fbp.setFloatColor(True)
fbp.setRgbaBits(16, 16, 16, 0)
fbp.setDepthBits(1) # activate buffer immediately for FRAMEBUFFER_UNSUPPORTED, 32 bits work fine

wprops = WindowProperties()
wprops.setSize(1024, 1024)

flags = GraphicsPipe.BFRefuseWindow

buffer = base.graphicsEngine.makeOutput(
  base.pipe, "buffer", -1, fbp, wprops, flags,
  base.win.getGsg(), base.win)

tex = Texture("color-tex")
dtex = Texture("depth-tex")

def addRT():
    buffer.addRenderTexture(tex, GraphicsOutput.RTMBindOrCopy, GraphicsOutput.RTPColor)
    buffer.addRenderTexture(dtex, GraphicsOutput.RTMBindOrCopy, GraphicsOutput.RTPDepth)
    print(tex)
    print(dtex)

dr = buffer.makeDisplayRegion()

cam = Camera("buffer-cam", base.camLens)
camNp = base.render.attachNewNode(cam)
dr.setCamera(camNp)

def update(task):
    camNp.setTransform(base.cam.getTransform(base.render))
    return task.cont

base.acceptOnce('a', addRT)

base.taskMgr.add(update, 'updateCam')

base.run()
```
press A to add the attachments, and this fails with the same error.

I think this issue needs to be split up into 2 or 3.
