### ISSUE TITLE
Race condition dealing with NodePath from multiple threads at once

### ISSUE THREAD

**Issue by Game-Starter** [panda3d/panda3d#1366]
The error:
`Assertion failed: _ref_count == 0 || _ref_count == local_ref_count at line 108 of c:\buildslave\sdk-windows-amd64\build\built1.10\include\referenceCount.I
Assertion failed: _node != nullptr at line 37 of c:\buildslave\sdk-windows-amd64\build\built1.10\include\nodePathComponent.I`

The code:

```
from direct.showbase.ShowBase import ShowBase
from direct.task import Task
from direct.interval.IntervalGlobal import *
from panda3d.core import *
from direct.gui.DirectGui import *
from direct.particles.ParticleEffect import ParticleEffect
from panda3d.physics import *

class run_me(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)
        #Async-task to load up the collision-meshes:
        taskMgr.setupTaskChain("chain_name", numThreads = 1, tickClock = None,threadPriority = None, frameBudget = None,frameSync = True, timeslicePriority = None)
        taskMgr.add(self.worldExpandTest,"worldExpandTestNom", taskChain = "chain_name")
        #taskMgr.add(self.worldExpandTest,"worldExpandTestNom")
        #Collider:
        minimum=Point3(0,0,0)
        maximum=Point3(4,4,4)
        box=CollisionBox(minimum,maximum)
        cn=render.attachNewNode(CollisionNode('cnode'))
        cn.node().addSolid(box)
        cn.show()
        cn.node().setFromCollideMask(BitMask32.allOn())
        cn.node().setIntoCollideMask(BitMask32.allOff())
        self.boxQueue=CollisionHandlerQueue()
        self.traverser = CollisionTraverser('traverser')
        base.cTrav = self.traverser
        base.cTrav.addCollider(cn, self.boxQueue)
        #taskMgr.add(self.parseTest, 'testParse')
        
    def worldExpandTest(self,task):
        for i in range(1):
            if(not render.find("dummi_"+str(i))):
                print("NUMZ?: ",i)
                fNomWall="mesh"+str(i+1)+".bam"
                terrainTest=base.loader.loadModel(fNomWall)
                terrainTest.reparentTo(render)
                terrainTest.setName("dummi_"+str(i))
        return task.cont
w = run_me()
w.run()
```
The file to test-case-zipped-bam-file:
[mesh1.zip](https://github.com/panda3d/panda3d/files/9491975/mesh1.zip)

**Comment by rdb** [comment]
Apparently something in the collision traverser doesn't work well if the scene graph is manipulated at the same time.

This is a consequence of #1033, since holding the GIL protected the collision traverser from being run during the processing of custom Python tasks.

**Comment by rdb** [comment]
In fact, just doing the `find()` in the thread is enough to reproduce the issue, here is a simplified test case:

```python
from direct.showbase.ShowBase import ShowBase
from panda3d.core import *

base = ShowBase()

box = CollisionBox((0, 0, 0), (4, 4, 4))
cn = render.attachNewNode(CollisionNode('cnode'))
cn.node().addSolid(box)
base.cTrav = CollisionTraverser('traverser')
base.cTrav.addCollider(cn, CollisionHandlerQueue())

terrainTest = base.loader.loadModel("mesh1.bam")
terrainTest.reparentTo(render)
terrainTest.setName("dummi_0")
del terrainTest

def worldExpandTest(task):
    print(render.find("dummi_0"))
    return task.cont

taskMgr.setupTaskChain("chain_name", numThreads=1, tickClock=None, threadPriority=None, frameBudget=None, frameSync=True, timeslicePriority=None)
taskMgr.add(worldExpandTest, "worldExpandTestNom", taskChain="chain_name")

base.run()
```

It doesn't occur if a reference is kept to the original NodePath, hence the need for `del terrainTest` to reproduce the issue.

**Comment by rdb** [comment]
I've finally isolated the root cause to a race condition caused by a design flaw in NodePath. This race condition occurs when one thread simultaneously constructs a NodePath to a particular node and another thread destructs a NodePath to that same node at the same time.

The most obvious way to fix it involves grabbing the PandaNode's NodePath lock on every `unref()` call, but this will undoubtedly cause a major performance regression.

The other way I can think of fixing it is by checking that the reference count is nonzero before returning an existing NodePathComponent.  This will still be a *little* slower than before, but will not require an additional sync point, since the lock is already held at such an event.  I will pursue this, with this check being disabled when building without threading.
