### ISSUE TITLE
CollisionCapsule into CollisionPolygon test not implemented

### ISSUE THREAD

**Issue by git2323** [panda3d/panda3d#1369]
## Description
If a CollisionCapsule is next to a CollisionPolygon (for example a quad) it is reported as a collision, although it is not close to it.
The issue has also been discussed in discourse beginning with the following entry:  https://discourse.panda3d.org/t/collisionsphere-collisioncapsule-and-collisionpolygon/28765/12

![coll2](https://user-images.githubusercontent.com/44967298/189491175-98ec1c93-3f7c-4d50-8845-4ac1cc695ef9.jpg)

## Steps to Reproduce
```
 int main(int argc, char* argv[]) {

	PandaFramework framework;
	framework.open_framework(argc, argv);

	// open the window
	WindowFramework* window = framework.open_window();

	// create ground plane
	PT(CollisionPolygon) gcp = new CollisionPolygon(LVecBase3(-3, 15, -6), LVecBase3(3, 15, -6), 
												    LVecBase3(3, 15, -1), LVecBase3(-3, 15, -1));
	PT(CollisionNode) gcp_cn = new CollisionNode("coll polygon collision node");
	gcp_cn->add_solid(gcp);
	NodePath gcp_np = window->get_render().attach_new_node(gcp_cn);
	//gcp_np.set_y(10);
	gcp_np.show();
	gcp_np.flatten_light();
	//gcp_np.show_bounds();

	// add sphere
	PT(CollisionSphere) cs = new CollisionSphere(0.0f, 0.0f, 0.0f, 0.5f);
	PT(CollisionNode) sphere_cn = new CollisionNode("Sphere CN");
	sphere_cn->add_solid(cs);
	NodePath sphere_np = window->get_render().attach_new_node(sphere_cn);
	sphere_np.set_pos(-1,15,1.1);
	sphere_np.show();
	//sphere_np.show_bounds();

	// add capsule
	PT(CollisionCapsule) cc = new CollisionCapsule(-0.5f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 0.5f);
	PT(CollisionNode) capsule_cn = new CollisionNode("Capsule CN");
	capsule_cn->add_solid(cc);
	NodePath capsule_np = window->get_render().attach_new_node(capsule_cn);
	capsule_np.set_pos(1,15,1.1);	// ==> collides (as expected)
	capsule_np.show();
	//capsule_np.show_bounds();
	
	// create queue + traverser
	PT(CollisionHandlerQueue) coll_queue = new CollisionHandlerQueue();
	CollisionTraverser traverser("Collision Traverser");
	//traverser.set_respect_prev_transform(true);
	traverser.add_collider(sphere_np, coll_queue);
	traverser.add_collider(capsule_np, coll_queue);

	// traverse
	traverser.traverse(window->get_render());


	framework.main_loop();
	framework.close_framework();

	return (0);
}
```
the following config.prc setting has been used to verify the collisions:  notify-level-collide debug

## Environment
 * Operating system: Windows 10
 * System architecture: 64bit
 * Panda3D version: 1.10.13
 * Installation method: built from source on 5.09.2022
 * Python version (if using Python):
 * Compiler (if using C++): msvc 2022 v143, c++ 20
 
 Regarding @ArsThaumaturgis the issue also occurs with python on panda 1.10.12, OS: Ubuntu 18.04.6, Python: 3.6.9
Python code to reproduce has been provided here:  https://discourse.panda3d.org/t/collisionsphere-collisioncapsule-and-collisionpolygon/28765/16

Thanks

**Comment by rdb** [comment]
CollisionPolygon does not provide a from-capsule test.  See the table on this page:
https://docs.panda3d.org/1.10/python/programming/collision-detection/collision-solids

**Comment by git2323** [comment]
I have seen the update to the docu. Thanks for making it work.
