### ISSUE TITLE
MultiplexStream is garbage collected by Python but still has a pointer in C++ code to it, resulting in segfaults

### ISSUE THREAD

**Issue by Wizzerinus** [panda3d/panda3d#1371]
## Description
Unlike the NodePaths and some other variables, MultiplexStream is getting caught by garbage collector. However, when `directNotify.warning` or similar are used, the pointer to it is still held in the C++ part. That results in segmentation faults when using C++ notification system. Simply calling `directNotify.newCategory().warning` is not enough, but when ShowBase is created, it calls `WindowProperties.getDefault()` which causes a crash.

Can be fixed by creating a global variable and storing the stream in it, as described below.

## Steps to Reproduce
```py
from panda3d.core import MultiplexStream, Notify
from direct.showbase import ShowBase

preventGarbageCollection = {}
def configureLogs():
    nout = MultiplexStream()
    nout.addFile("test.log")
    Notify.ptr().setOstreamPtr(nout, 0)
    # uncomment line below to fix segfault
    # preventGarbageCollection[0] = nout


configureLogs()
ShowBase.ShowBase().run()
```

## Environment
 * Operating system: Linux (EndeavorOS/Arch based)
 * System architecture: x64
 * Panda3D version: 1.10.12
 * Installation method: (eg. pip, wheel, SDK, built from source) pipenv
 * Python version (if using Python): 3.10.7
 * Compiler (if using C++):

**Comment by rdb** [comment]
I'm just going to fix it for now by making sure that the Python bindings don't delete the underlying C++ stream pointer when the Python object goes out of scope.  It will cause a tiny one-time memory leak, but this is usually set for the lifetime of the application, so it won't typically be a problem.  You will be able to set the second parameter to True if you do want the pointer to be deleted properly at the end of the application's lifetime, at the risk that you must ensure that it's no longer being referenced from Python at that time.
