### ISSUE TITLE
Weird segfault

### ISSUE THREAD

**Issue by duburcqa** [panda3d/panda3d#1372]
## Description

I have a segfault that is blocking me but really difficult to reproduce. I manage to write a reproduction script that is repeatable but I cannot really explain why and when it is happening. What I can tell is that pretty much everything is necessary in the reproduction script for the segfault to occur. It involves repeatedly opening and closing alternatively onscreen and offscreen showbase instances, while keeping references in memory and waiting a fairly long delay between these operations...

## Steps to Reproduce
```python
import time
import multiprocessing as mp

from panda3d.core import (
    Texture, GraphicsPipe, GraphicsOutput, WindowProperties,
    FrameBufferProperties)
from direct.showbase.ShowBase import ShowBase


class Panda3dApp(ShowBase):
    def __init__(self) -> None:
        super().__init__(windowType="offscreen")
        fbprops = FrameBufferProperties()
        winprops = WindowProperties()
        flags = GraphicsPipe.BF_refuse_window | GraphicsPipe.BF_refuse_parasite
        win = self.graphicsEngine.make_output(
            self.pipe, "offscreen_buffer", 0, fbprops, winprops, flags,
            self.win.get_gsg(), self.win)
        self.winList.append(win)
        texture = Texture()
        win.add_render_texture(texture, GraphicsOutput.RTM_copy_ram)
        self.graphics_engine.render_frame()

    def open_window(self) -> None:
        print("opening onscreen...")
        self.open_main_window(type='onscreen')
        print("opened!")

    def stop(self):
        self.task_mgr.stop()

class Panda3dProxy(mp.Process):
    def __init__(self):
        super().__init__()
        self._host_conn, self._proc_conn = mp.Pipe()
        self.start()

    def __getattr__(self, name):
        def _send(*args, **kwargs):
            self._host_conn.send((name, args, kwargs))
            print(f"sending: {name, args, kwargs}")
            return self._host_conn.recv()

        return _send

    def run(self):
        app = Panda3dApp()
        self._proc_conn.send(None)

        def _execute(task):
            for _ in range(100):
                if not self._proc_conn.poll(0.001):
                    break
                name, args, kwargs = self._proc_conn.recv()
                print(f"receiving: {name, args, kwargs}")
                try:
                    reply = getattr(app, name)(*args, **kwargs)
                    self._proc_conn.send(reply)
                except Exception as error:
                    self._proc_conn.send(error)
            return task.cont

        app.task_mgr.add(_execute, "Communication task", -50)
        app.run()


for _ in range(2):
    app1 = Panda3dApp()
    time.sleep(3.0)
    app1.destroy()
    app2 = Panda3dProxy()
    app2.open_window()
    time.sleep(3.0)
    app2.stop()
    app2.destroy()
```

## Environment
 * Operating system: Ubuntu 22.04
 * System architecture: x86_64
 * Panda3D version: 1.10.12
 * Installation method: pip
 * Python version (if using Python): 3.10.4

**Comment by rdb** [comment]
Actually, you're not passing the offscreen buffer as host to the `open_main_window` call, so the main window gets its own OpenGL context, separate from the offscreen buffer.

If I use `self.open_main_window(type='onscreen', host=self.win)` I don't get a crash, can you confirm?

**Comment by duburcqa** [comment]
> Huh, so you're using a pbuffer (offscreen windowType) as the host of a regular window? Why not create a regular window and create any offscreen buffers as FBOs?

The point was to use a pbuffer by default, and if the user requests it later on, switch to a full-fledge onscreen window (completely deleting the original pbuffer that became irrelevant).

> Actually, you're not passing the offscreen buffer as host to the open_main_window call, so the main window gets its own OpenGL context, separate from the offscreen buffer.

Yes, it is not clear for me why I would like to pass the original window that is now useless. I wanted to close it and create a new one to get the best possible performance. But I'm not very familiar with Panda3d, may be it is not the way to go.

Thank you for your help, I will try your proposal.

**Comment by duburcqa** [comment]
> If I use self.open_main_window(type='onscreen', host=self.win) I don't get a crash, can you confirm?

It does not work because it does not open any window then. It raises this exception:
```
    872     flags = flags | GraphicsPipe.BFRequireCallbackWindow
    874 if host:
--> 875     assert host.isValid()
    876     win = self.graphicsEngine.makeOutput(pipe, name, 0, fbprops,
    877                                          props, flags, host.getGsg(), host)
    878 elif gsg:

AssertionError: 

```

**Comment by duburcqa** [comment]
what about doing:
```

    def open_window(self) -> None:
        print("opening onscreen...")
        self.open_main_window(type='onscreen', host=self.winList[1])
        self.close_window(self.winList[0])
        print("opened!")
```

It works just fine apparently...

**Comment by duburcqa** [comment]
Any news ? It has been blocking since two months already :/

**Comment by rdb** [comment]
Well, what you're doing is *really* obscure: you are forking a process with active GLX contexts while repeatedly creating and destroying graphics resources on them.  On top of that, on the same process and the same thread, you are creating a second graphics pipe while the first one is still active.  I am not sure if this is even expected to work, and I am not surprised that the driver is crashing because of this.

It's really hard for me to understand what you are doing or why you are doing it, aside from the fact I've never worked with forking X11 processes and can't even find documentation on the subject.  Can you change your approach not to create any graphics resources in the process that is being forked?  Or reuse the same graphics pipe rather than create a new one every time?

**Comment by duburcqa** [comment]
Thanks for having a look to my issue. Just to give a bit of context, I'm using Panda3d as graphical backend for reinforcement learning library. Each graphics pipe is attached to a given agent being trained. With the current design, many agents will be created sequentially during the learning process, some of them having a very short lifespan. The default graphics pipe is an offscreen buffer, which is used to record videos of simulations in background. Yet, sometimes the user may want to get a real-time feedback. In such a case, I still want to keep an independent offscreen buffer to record a video from a direct view angle and higher resolution, so I need both at the same time. If for some reason I know in advance that no onscreen rendering will be necessary for a given agent,  then a synchronous `Panda3dApp` is used in place of the asynchronous `Panda3dProxy` version to spare a bit of computation time and memory.

I will try to switch to spawn processes and see what happens.

**Comment by duburcqa** [comment]
I can confirm it works using spawn. Do you know if there is a way to get the same result using fork ? because having to add `if __name__ == '__main__'` guard to all scripts is quite annoying...

**Comment by rdb** [comment]
Closing as won't fix since this is a shortcoming in X11.

I have no experience with using multiprocessing so I'm not able to answer your question regarding getting the same behaviour.

**Comment by duburcqa** [comment]
Arf. I'm a bit disappointed to hear that. Let's ses if i can find à workaround by myself !

**Comment by rdb** [comment]
If there's something else you think I can do or investigate, do let me know.  As-is, I don't think there's anything to fix in Panda.
