### ISSUE TITLE
float * Vec3

### ISSUE THREAD

**Issue by hychn** [panda3d/panda3d#1374]
## Description
float * Vec3 doesnt work on mac and linux.
It works on windows.

## Steps to Reproduce
1.0 * Vec3(1,2,3)

## Environment
 * Operating system: Mac
 * System architecture: 2.8gHz Intel i7
 * Panda3D version: 1.10.12
 * Installation method: pip3
 * Python version (if using Python): 3.10.6
 * Compiler (if using C++):

**Comment by darktohka** [comment]
This was solved in the 1.11 branch as of https://github.com/panda3d/panda3d/commit/f27e9b2a86bb6ea7621d5ecfa74fc212c04dec0a

As a workaround for now on the 1.10 branch, use `Vec3(1,2,3) * 1.0`

**Comment by hychn** [comment]
Thanks. Verified that it works!
