### ISSUE TITLE
Geometry with different TexMatrixAttribs won't flatten

### ISSUE THREAD

**Issue by janEntikan** [panda3d/panda3d#1392]
Calling flattenStrong() on geometry where different texture scales are set won't flatten, where I expect them to be applied to the UVs. 
It appears this only happens to models with multiple TextureStages.

```py
from direct.showbase.ShowBase import ShowBase

base = ShowBase()
root = render.attach_new_node("root")
model = loader.load_model("cube.bam")
model.clear_model_nodes()

for i in range(1,5):
    c = model.copy_to(root)
    for stage in c.find_all_texture_stages():
        c.set_tex_scale(stage, (i,i))

root.flatten_strong()
render.ls()
render.analyze()
```

`cube.bam` here is the default blender cube with a texture applied and exported with blend2bam using gltf (thus producing a TextureStage setup for pbr). If you change `cube.bam` to `models/smiley` the flattening seems work fine.

[examp.zip](https://github.com/panda3d/panda3d/files/9996076/examp.zip)
(Zip file containing above example, the cube model and a texture.)

**Comment by rdb** [comment]
Classifying as bug.  Panda refuses to flatten a TexMatrixAttrib onto a texcoord set if this texcoord set is used by more than one stage, which is sensible if the stages have different texture transforms, but if they have the same transform, then Panda should be smart enough to detect this and apply it anyway.
