### ISSUE TITLE
Cannot import panda3d.vision on M1 Mac

### ISSUE THREAD

**Issue by ekiefl** [panda3d/panda3d#1393]
## Description

Importing panda3d vision leads to the following error:

```python
$ python
Python 3.8.13 (default, Oct 19 2022, 17:52:09)
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import panda3d.vision
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/evan.kiefl/opt/miniconda3/envs/pt/lib/python3.8/site-packages/panda3d/[vision.cpython-38-darwin.so](http://vision.cpython-38-darwin.so/), 0x0002): Library not loaded: 'lib/libopencv_imgproc.2.4.dylib'
  Referenced from: '/Users/evan.kiefl/opt/miniconda3/envs/pt/lib/python3.8/site-packages/panda3d/libopencv_highgui.2.4.3.dylib'
  Reason: tried: 'lib/libopencv_imgproc.2.4.dylib' (no such file), '/usr/local/lib/libopencv_imgproc.2.4.dylib' (no such file), '/usr/lib/libopencv_imgproc.2.4.dylib' (no such file)
```

This has been observed on two M1 macs (and doesn't occur on two other Intel macs), so I'm assuming that is the common denominator.

## Steps to Reproduce

I use `conda` to manage my python environments, so your mileage may vary.

```bash
# Make fresh python env
conda deactivate
conda env remove --name panda3d
conda create -y -n panda3d python=3.8
conda activate panda3d

# Install panda3d dev (Error also observed on 1.10.10)
pip install --pre --extra-index-url https://archive.panda3d.org/ panda3d
```

Enter python shell and import `panda3d.vision`:

```python
>>> import panda3d.vision
```

## Environment
 * Operating system: macOS Monterey (12.6)
 * System architecture: ARM64
 * Panda3D version: 1.11.0.dev2698
 * Python version (if using Python): 3.8.13

**Comment by rdb** [comment]
Thanks, will investigate.  In your application, you can work around the problem by importing from `panda3d.core` instead of from `pandac.PandaModules`, the latter is deprecated and pulls in modules that may not actually be needed in your application.

**Comment by edoson** [comment]
@rdb Thanks, the import switch workaround the problem.
