### ISSUE TITLE
Stop using distutils Python module

### ISSUE THREAD

**Issue by Moguri** [panda3d/panda3d#1395]
## Description
The `distutils` module  has been deprecated for a while and is slated for removal in Python 3.12. More information on this can be found in [PEP 632](https://peps.python.org/pep-0632/). Panda will need to stop making use of `distutils` in order to support Python 3.12.

I have identified the following that need to be addressed:
- [ ] `distutils.log` in `direct/src/dist` - replace with builtin `logging` module
- [x] `distutils.core.setup` in `contrib/src/panda3dtoolsgui` - replace with `setuptools.setup`
- [x] `distutils.sysconfig` in various locations - *should* be replace by `sysconfig`, but I am unsure if the issues from #1230 are resolved
- [x] `distutils.utils.get_platform()` in `makepanda.py` - replace with `platform` module

**Comment by Moguri** [comment]
For `distutils.sysconfig`, I am thinking we make a `locations.py` utility script that re-exports the functions we need from `sysconfig` if the Python version is at least 3.12 and from `distutils.sysconfig` otherwise. If a user is actually using 3.12 on Debian, then hopefully this mess has been sorted out.

**Comment by rdb** [comment]
One question on my mind, do we need to worry about this for 1.10? [Python 3.12 is due in October 2023](https://peps.python.org/pep-0693/), at which time I would really like to have already released Panda 1.11.  On the other hand, some users may stick with 1.10 for longer, but I'm not sure if they need Python 3.12 support.

**Comment by Moguri** [comment]
The changes seem pretty minimal, so I was thinking about targeting 1.10 just to be safe. However, if we run into any roadblocks with that, I would be fine with targeting 1.11.

**Comment by DavidACrompton** [comment]
I've had a look at #1230 which is related to this. On a fresh ubuntu install, I get the following. 
```
python3 -m site
sys.path = [
    '/home/parallels',
    '/usr/lib/python310.zip',
    '/usr/lib/python3.10',
    '/usr/lib/python3.10/lib-dynload',
    '/home/parallels/.local/lib/python3.10/site-packages',
    '/usr/local/lib/python3.10/dist-packages',
    '/usr/lib/python3/dist-packages',
]
USER_BASE: '/home/parallels/.local' (exists)
USER_SITE: '/home/parallels/.local/lib/python3.10/site-packages' (exists)
ENABLE_USER_SITE: True

python3 -m sysconfig
Platform: "linux-aarch64"
Python version: "3.10"
Current installation scheme: "posix_local"

Paths: 
	data = "/usr/local"
	include = "/usr/include/python3.10"
	platinclude = "/usr/include/python3.10"
	platlib = "/usr/local/lib/python3.10/dist-packages"
	platstdlib = "/usr/lib/python3.10"
	purelib = "/usr/local/lib/python3.10/dist-packages"
	scripts = "/usr/local/bin"
	stdlib = "/usr/lib/python3.10"
```
Changing makepanda back to https://github.com/panda3d/panda3d/commit/2fcacd1bab1226ea0571c5d925daf6028a862f96 installs panda to `/usr/local/lib/python3.10/dist-packages` which is now a recognised path by site and sysconfig

**Comment by rdb** [comment]
Which version of Ubuntu was that, and which Python distribution?  If the official Python distribution, that probably means they fixed it, and we can rely on the fix working for Python 3.12.  However, we still need to support older versions of Ubuntu.

**Comment by DavidACrompton** [comment]
It was Ubuntu 22.04 and using the official python distribution (apt-get). 
You're right though, I'll sort out older ubuntu versions (and also look to see when it was fixed/if they back ported the fix)

**Comment by rdb** [comment]
The only thing remaining here is switching from `distutils.log`.  We just use it to fetch the log levels.  The recommendation is to switch to the `logging` module, but those log levels are different - they are multiplied by 10, and the old `distutils.log` module can't handle those.

Note that there are three possible versions of `distutils.log`, depending on the version of Python and whether setuptools has been imported first:
* The Python standard library version, which uses multiples of 1 - this version no longer exists as of Python 3.12.
* The setuptools-installed one before 65.6.0, which uses multiples of 1 as well.
* The setuptools-installed one after 65.6.0, which is a wrapper around the `logging` module, using multiples of 10.

The solution in #1445 is to override `announce()` to use our own `logging` instance but I'd like to keep using the underlying `announce()` for better hooking into the verbosity levels etc.

Note that `distutils` is still available as of Python 3.12, but it requires the installation of `setuptools`.  Importing it does not cause a deprecation warning.  So is fixing this really a priority now?

I'm inclined to close this and kick the can down the road until it becomes a problem or until we can require `setuptools>=65.6.0`.  Though if someone can think of an elegant solution I'd welcome that as well.

**Comment by Moguri** [comment]
If things work with 3.12, then I agree we can kick this can down the road.

**Comment by Moguri** [comment]
Closing this for now. We can address the remaining logging piece if/when it becomes a problem.
