### ISSUE TITLE
Make ShowBase use a private DirectObject for window-event

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#1402]
ShowBase inherits from DirectObject in order to be able to catch events for its own purposes.  One of the events it catches is window-event, so it can recalculate the aspect ratio properly.

At some point in history, someone cleverly noticed that ShowBase inherits from DirectObject, and thought "Cool! I can just use `base.accept()` and not have to create my own DirectObject for event handling!" and the use of `base.accept()` instead of inheriting classes from DirectObject became commonplace.

The issue is that a particular DirectObject can only catch a particular event *once*, and further calls to `accept()` will replace the previous handler.  So, when people use `base.accept('window-event')`, this will completely override ShowBase's own handler, causing the aspect ratio to stop updating, and causing confused support requests and issue reports.

I would suggest that ShowBase creates a private DirectObject for its own handling of window-event.  Then ShowBase can just keep inheriting from DirectObject, but this object would be clean of event handlers for users to do with what they wish.

For people who solved this issue by calling `base.windowEvent()` in their own window-event handler, we need to make sure it's safe to call that method redundantly (if it's not already).

**Comment by ArsThaumaturgis** [comment]
Yes, this seems like a very good idea! A solid, clean solution to the problem of potentially-confusing event-handling, I do think. ^_^

It will call, I feel, for broadcasting the change quite comprehensively, as it seems likely to break a lot of existing code. And of course there may be samples that will call for correction.

(And I should update my "beginner's tutorial" too, for that matter...)

But yes, suffice it to say that I'm in favour of this change! ^_^

**Comment by rdb** [comment]
@ArsThaumaturgis what breakage do you foresee?  I am not planning on deprecating `base.accept()`, just making sure that `base.accept('window-event')` doesn't override ShowBase's built-in windowEvent handler.

**Comment by ArsThaumaturgis** [comment]
Ah, I think that I misread, and thus misunderstood--I thought that you were suggesting that the "accept" function of ShowBase would no longer be available.

No, what you say and what, on a re-read, the original post proposes makes more sense, I do think, and shouldn't break anything. 

My mistake and my apologies!

**Comment by rdb** [comment]
Closed by #1434
