### ISSUE TITLE
Error while launching windows build

### ISSUE THREAD

**Issue by grilledalready** [panda3d/panda3d#1409]
## Description
I am working on a panda3d game that uses numpy to work. Builds successfully on windows but the exe does not open
[output.log](https://github.com/panda3d/panda3d/files/10183856/output.log)

This is my setup file

```python
from setuptools import setup
from setuptools import find_packages

find_packages(where='scripts', exclude=['cpp'])

setup(
    name='AAD',
    options={
        'build_apps': {
            # Build asteroids.exe as a GUI application
            'gui_apps': {
                'AAD': 'MainGame.py',
            },
            'log_filename': 'E:/PandaProjects/AADSimulatorSoftware/AADSS/build/output.log',
            'log_append': False,
            # Specify which files are included with the distribution
            'include_patterns': [
                '**/*.png',
                '**/*.jpg',
                '**/*.egg',
            ],
            'exclude_patterns': [
                'cpp',
            ],
            'platforms': ['win_amd64'],
            # Include the OpenGL renderer and OpenAL audio plug-in
            'plugins': [                'pandagl','pandagles','pandagles2','pandadx9','p3tinydisplay','p3ffmpeg','p3openal_audio','p3fmod_audio','pandaegg','p3ptloader','p3assimp'
            ],
        }
    }
)
```
![hier](https://user-images.githubusercontent.com/32088062/206406576-21a81b97-1e03-4dc0-93d3-09d5b6d04cca.png)

This is my file hierarchy. Help would be much appreciated.
Thanks!!!

**Comment by rdb** [comment]
Do you have numpy added to your requirements.txt file?

**Comment by grilledalready** [comment]
File was already downloaded e:\pandaprojects\aadsimulatorsoftware\aadss\build\__whl_cache__\win_amd64_cp37m\protobuf-3.20.1-cp37-cp37m-win_amd64.whl
Successfully downloaded autopep8 bcrypt certifi cffi charset-normalizer cryptography Cython digi-xbee DirectFolderBrowser DirectGuiExtension docopt docutils Faker idna mixer mpy-cross mysql-connector-python numpy numpy-stl Panda3D paramiko Pillow pipreqs pycodestyle pycparser pygame pyglet Pygments PyNaCl PyOpenAL PyOpenGL PyOpenGL-accelerate pypiwin32 pyserial python-dateutil python-utils pywin32 requests six toml urllib3 XBee yarg typing-extensions protobuf
Building runtime for platform: win_amd64
There are some missing modules: ['DataHub', 'GPSCoords', 'System', 'System.IO.Ports', '_posixsubprocess', 'dummy.Process', 'grp', 'mathutils', 'multiprocessing.AuthenticationError', 'multiprocessing.BufferTooShort', 'multiprocessing.TimeoutError', 'multiprocessing.get_context', 'multiprocessing.get_start_method', 'multiprocessing.set_start_method', 'rotation_matrix', 'tdrdataparser', 'test', 'xbeemodule']
Copying game files for platform: win_amd64



This is the build log the missing modules are available as python files in scripts folder but it still says they are missing.

**Comment by grilledalready** [comment]
@rdb  One more observation . I tried just tried importing numpy into the asteroids example and that also started giving the same problem.

I was able to build the asteroids example successfully before importing numpy

**Comment by rdb** [comment]
Don't use find_packages.  build_apps doesn't know how to scan dependencies in that.

Just make sure that your Python scripts are available on the sys.path for build_apps to find, from your import statements, and they will be included automatically.

Otherwise, use include_modules to explicitly pick them up.

**Comment by grilledalready** [comment]
@rdb  but the issue is with numpy not being detected. is there anyway to sort that out

**Comment by rdb** [comment]
numpy isn't being detected because build_apps isn't detecting that you're using it because your entry point or modules that are referred to by your entry point aren't making imports to numpy.

As you can see rotation_matrix is showing up in the list of "missing modules", so you gotta fix that first.

Alternatively, if you want to go ahead with shipping the non-compiled .py files directly, then you have to add numpy to include_modules.

**Comment by grilledalready** [comment]
@rdb  
[output.log](https://github.com/panda3d/panda3d/files/10186005/output.log)


[main1.txt](https://github.com/panda3d/panda3d/files/10186010/main1.txt)


I have added a small modification on the main.py file of asteroids example
just added import numpy and the build stopped working

I am able to get the exe but it does not work .The log is attached here


The setup file is just this

from setuptools import setup

setup(
    name="asteroids",
    options={
        'build_apps': {
            'include_patterns': [
                '**/*.png',
                '**/*.jpg',
                '**/*.egg',
            ],
            'gui_apps': {
                'asteroids': 'main.py',
            },
            'log_filename': 'E:/panda3d/samples/asteroids/output.log',
            'log_append': False,
            'platforms': ['win_amd64'],
            'plugins': [
                'pandagl',
                'p3openal_audio',
            ],
        }
    }
)


I think at least with this example numpy should compile automatically.But it isnt.Please help me out of this.

**Comment by rdb** [comment]
Did you add numpy to the requirements.txt in the asteroids sample?

**Comment by grilledalready** [comment]
@rdb How do I include my scripts to be added to build ?
![snip](https://user-images.githubusercontent.com/32088062/206483754-57ba8e3e-8076-4621-b478-9a66c25ba88c.PNG)


Is this the right way?

**Comment by grilledalready** [comment]
@rdb  
![success](https://user-images.githubusercontent.com/32088062/206533658-d6f7bbb3-bd3b-4fd7-8c64-9058f22d91a0.PNG)


I was able to successfully build the app for windows.But I had to get all the files out of folder and put it in root folder.
Can u please guide me on how to include the py files inside child folders because I cannot have all files in the root folder.

Thanks for your support so far!
