### ISSUE TITLE
Loading gltf into Actor doesn't work

### ISSUE THREAD

**Issue by BMaxV** [panda3d/panda3d#1420]
## Description
The Actor class does not load gltf files correctly.
There is no error, the model just doesn't show
The regular loader works fine, with the same model too.

## Steps to Reproduce
I have prepared a sample for the/a blend file that doesn't work.
https://github.com/BMaxV/panda_animation_parts_sample

## Environment
 * Panda3D version: 1.10.13
 * Installation method: pip

**Comment by rdb** [comment]
Please add: are you using panda3d-gltf (and if so, which version) or the very low-quality built-in Assimp-based glTF loader?

**Comment by BMaxV** [comment]
I am not sure what you mean. I am using the code as it is in the sample.

I not importing panda3d-gltf and the file is straight from blender, so probably not.

Is there a resource describing how to use panda3d-gltf?

**Comment by BMaxV** [comment]
Sure. Then I am using it, it is installed. And my problem is not with `loader.loadModel` that works fine, it's the Actor that doesn't work.

**Comment by BMaxV** [comment]
Ok, so the problem was that the mesh object has to be parented to the armature in blender, for the blender exporter to correctly export it. Thanks @Moguri 

I also noticed that if a *fresh* copy of the .gltf is exported and loaded into panda for the first time, *all* animations break. It works fine on subsequent attempts. Not sure if you want discuss that here, the original problem is solved.

Thank you!

**Comment by ShivamKR12** [comment]
@rdb so, no solution to the issue yet ? i am facing the same issue and would love to get some help/advice !
