### ISSUE TITLE
get_best_parent_from_Set is scripting unfriendly

### ISSUE THREAD

**Issue by Frangwhuf** [panda3d/panda3d#1421]
## Description
While working on the JNI binding, I encountered this method on TypeHandle. I could find no evidence of it being exported into Python (either Native for classic), even though it is in the `PUBLISHED` block. This makes sense as modeling the behavior of `set<...>` in other languages could be challenging.

I am proposing moving this method out of the `PUBLISHED` block, while keeping it `public`.

## Use Case
As I can find no evidence of usage of this method outside of C++, and scripting integration would be challenging at best, taking this out of published API simplifies the task of authoring a binding at no current loss of generality.

## Notes
I have a nearly trivial PR for this that I will post shortly. As such this can be assigned to me.

**Comment by rdb** [comment]
Do we actually use this method anywhere?  Should we simply remove it?

**Comment by Frangwhuf** [comment]
`TypedObject`, `TypeRegistry`, and `TypeHandle` all express this API. I find no call to it within this codebase. Sadly it has been far too long for me to remember if there was any reasonable intent for it. Though I will admit that I haven't spent much time trying to imagine scenarios where I might want this information, or if it could easily be computed with existing API.

At a minimum it is probably worth starting a list of deprecation targets.

**Comment by rdb** [comment]
It looks like it was vestigial as of e6f870ece6f973fd57ecf57c62ec96a4a898cc6c.  It is not a public API (as it has never been exposed in Python) so I removed it in 2d606c07e3fe6c5fb8dd9353f0fe62753f324ab2
