### ISSUE TITLE
Implement Directional Sound for OpenAL

### ISSUE THREAD

**Issue by git2323** [panda3d/panda3d#1429]
## Description
I would like to use the directional sound feature of OpenAL as described in the [specification](http://openal.org/documentation/openal-1.1-specification.pdf) on page 38 (Direction and Cone). I tried to implement that on 1.10.x and it worked. Would you accept an PR for that?

## Use Case
This will allow developers to add attenuation based on the orientations of the 3D sound sources.

**Comment by rdb** [comment]
This sounds useful.  What did you have in mind for the interface, ie. how will users set the direction and cone?

**Comment by rdb** [comment]
Does FMOD support this feature, or would it be OpenAL only?

**Comment by git2323** [comment]
FMOD also has this feature, although my current code affects OpenAL only.

**Comment by rdb** [comment]
That all sounds fine.  As long as the parameterisation is defined such that someone will be able to go and implement the FMOD side later.

Note that the new arguments to set_3d_attributes should be optional.  The default could be the forward direction.

**Comment by git2323** [comment]
Can you take a look at pull request #1451? Thanks.

**Comment by git2323** [comment]
PR #1451 has been merged. This issue can be closed.

**Comment by rdb** [comment]
For future reference, put "Fixes #1429" at the bottom the PR text and/or the commit description and the issue is closed automatically when the changes are merged.
