### ISSUE TITLE
Marking more constructors as `explicit`

### ISSUE THREAD

**Issue by WMOkiishi** [panda3d/panda3d#1431]
C++ constructors not marked `explicit` that can be called with a single parameter allow for implicit conversion (aka coercion) of the parameter type to the type to which the constructor belongs. Panda3D extends this behavior to its Python bindings. This feature is sometimes useful, but sometimes masks bugs. I have compiled a list of coercions supported by these "converting constructors" whose value seems dubious:

- Coercing a matrix (of either size) to an `LRotation` or `LOrientation`, both of which are `LVecBase4` subclasses
- Coercing a string to an `HTTPDate`
- Coercing a `TypeHandle` to a `PointerToArray`
- Coercing a string to a `MovieVideo`
- Coercing a `Thread` to a `GeomVertexReader`, `GeomVertexWriter`, or `GeomVertexRewriter`
- Coercing a string to a `Spotlight`
- Coercing an integer to an `PNMImageHeader::PixelSpec`
- Coercing a float to a `BulletTickCallbackData`
- Coercing an `OdeWorld` to various ODE classes
- Coercing a string to a `ConfigVariableColor`, `ConfigVariableList`, or `ConfigVariableString` (These seem to have been missed when some other `ConfigVariable` constructors were marked `explicit`.)
- Coercing a 3-vector to a 4-vector (These might have value, but I've decided to list it for completeness.)
- Coercing a single to number to a vector of any size

I would suggest considering marking the constructors supporting these coercions as `explicit`. There are almost certainly more, but these were the ones that stood out to me from the list I generated with `interrogatedb`.
Additionally, constructors not marked `explicit` that require multiple parameters allow for implicit conversion from a sequence of values. This is extended to Python as coercion from a tuple. I suspect that the only constructors requiring multiple parameters that _shouldn't_ be marked explicit are those converting a sequence of numbers to a vector or a sequence of vectors to a matrix.

Of course, there would be some backwards-compatibility concerns. I suspect that, for most of these coercions, most use "in the wild" is accidental. If any of them are being used deliberately, the workaround is simply converting the value explicitly before passing it to a function.

**Comment by rdb** [comment]
I agree with almost all of these, and they should be easy to fix.  I invite people to make a PR for this.

Here are the ones that I don't necessarily agree with, but I might be convinced otherwise:
* Converting a string to an HTTPDate.  However, I might agree even more with just deprecating this constructor and making a static `HTTPDate.parse(...)` instead, which is more explicit about what it does.
* Converting a 3-vector (of Vec3 of Point3 type, *not* VBase3) to a VBase4 is meaningful, because Vec3 and Point3 really are implicitly 4-vectors with the fourth coordinate being 0 or 1, respectively.
* Converting a single number to a vector of any size is something that notably GLSL also offers.  It allows doing things like `1.0 - vec`, which is useful.  GLSL also supports this.  Change my mind.

**Comment by WMOkiishi** [comment]
These opinions seem reasonable to me. General conversion of a `VBase3` to a `VBase4` is already marked `explicit` (which I think you were implying), which seems sufficient to me. I'm coming from a background of more linear algebra than rendering, so I'll take your word for the utility of the other coercions you've brought up (especially if that's the way it's been done elsewhere to good effect). Practicality (and standardization) beat purity in this case.

For clarity, do you also agree with the idea of marking most multi-parameter constructors as explicit?

**Comment by rdb** [comment]
> For clarity, do you also agree with the idea of marking most multi-parameter constructors as explicit?

Yes, absolutely.

**Comment by jalajk24** [comment]
Can I work on this one? I am pretty new to open-source-related stuff.

**Comment by rdb** [comment]
@jalajk24 Go for it!
