### ISSUE TITLE
Shader generator: Support cube map TexGenAttribs 

### ISSUE THREAD

**Issue by janEntikan** [panda3d/panda3d#1437]
According to [the manual ](https://docs.panda3d.org/1.10/python/programming/shaders/shader-generator#known-limitations) and the error below, the shader generator does not support generated texture coordinates for cube maps when it probably should.

`:pgraphnodes(error): Unsupported TexGenAttrib mode: 1`
`:pgraphnodes(error): Unsupported TexGenAttrib mode: 2`

**Comment by rdb** [comment]
High priority in my book.  This is a pretty significant omission.

Possible reference to help with implementing this: https://www.khronos.org/opengl/wiki/Mathematics_of_glTexGen
