### ISSUE TITLE
Feature Request: Abillity to set "Wireframe Minimum Color" in RenderModeAttrib

### ISSUE THREAD

**Issue by lifelandman** [panda3d/panda3d#1447]
## Description
It would be nice to be able to set the minimum Red, Blue, Green, and Alpha levels that a wireframe rendered with in RenderModeAttrib M_wireframe mode, so that the wireframe still matches the color of the object, until the object color dips below a certain threshold or is transparent.
## Use Case
![image](https://user-images.githubusercontent.com/77763745/213843182-9ef69434-19de-46f8-8d29-535fcd3e97d7.png)
As seen in the image above, transparent or dark areas of a object or flat texture card will either not be visible or blend into the background.
This can create an annoying ambiguity when using wireframe mode for utility purposes.
Perhaps the wireframe_color property could be used for setting the minimum color.

**Comment by rdb** [comment]
Wireframe mode is just rendered with the same state as everything else.  I don't think it should be wrapped up into the same attribute.

In fact, you can probably use the ColorBlendAttrib::M_max mode to achieve what you want, right?

**Comment by lifelandman** [comment]
Ah Thanks!

I didn't even know that ColorBlendAttrib existed...
That said, even when I try configuring the operands, M_max only seems to "frost the tips" of wireframes that dip into transparency:
![image](https://user-images.githubusercontent.com/77763745/213880805-28c71a8c-185b-4553-9714-9480315a6f20.png)
Compared to:
![image](https://user-images.githubusercontent.com/77763745/213880826-c4e5bc0a-29bc-4c5a-9cbb-bf4f0d1adc9e.png)
So the large parts of the wireframes for (in this example) the texture cards in environment.egg.pz remain invisible. Is there something I might be doing wrong here?

**Comment by rdb** [comment]
I think you have to disable alpha testing as well.

**Comment by lifelandman** [comment]
(I also reset the clear color to the default, just to make sure it wasn't the wires blending into the background)
adding `AlphaTestAttrib.make(RenderAttrib.M_none,1)` to my render state didn't seem to change much:
![image](https://user-images.githubusercontent.com/77763745/213882365-b676d15f-900e-4714-9ec5-69d97e0351b3.png)
I'm sorry if this if the cause of this ends up being something silly on my part.

**Comment by lifelandman** [comment]
I'll continue this as a proper question on the forums. Thanks for your help so far!

**Comment by lifelandman** [comment]
I'll continue this as a proper question on the forums. Thanks for your help so far!
