### ISSUE TITLE
config variable multisamples not considered

### ISSUE THREAD

**Issue by git2323** [panda3d/panda3d#1455]
## Description
When requesting a specific number of multisamples the window will get a display with the maximum number of multisamples possible.

## Steps to Reproduce
Add the following lines to the Config.prc file:

`framebuffer-multisample true`
`multisamples 4`
on GPUs with 16 max. 16 multisamples, the command

`window->get_graphics_output()->get_fb_properties().get_multisamples()`

will return 16 and not the requested 4.

## Environment
 * Operating system: Windows
 * System architecture: 64bit
 * Panda3D version: 1.11.0
 * Installation method: built from source
 * Python version (if using Python):
 * Compiler (if using C++): MSVC 14.3

**Comment by rdb** [comment]
Yes, extra multisamples is a waste of memory

Note that we should allow the special value 1 to mean "as many as possible"
