### ISSUE TITLE
Failed to query GL_MAX_VERTEX_ATTRIB_STRIDE

### ISSUE THREAD

**Issue by git2323** [panda3d/panda3d#1459]
## Description
After building from source today (1.11.0), I get the following errors during startup and a model does not load:
:display:gsg:glgsg(error): glGetIntegerv parameter <pname> has an invalid enum '0x82e5' (GL_INVALID_ENUM)
:display:gsg:glgsg(warning): Failed to query GL_MAX_VERTEX_ATTRIB_STRIDE.
:display:gsg:glgsg(debug): max vertex attrib stride = 2048 (guessed)

## Steps to Reproduce
build from source as of today (1.11.0)
start pview
(it is not affecting all systems. On another system it works fine)
Affected system: Asus Laptop with AMD Radeon HD 6300M GPU (glview report is attached)

## Environment
 * Operating system: Windows 10
 * System architecture: 64 bit
 * Panda3D version: 1.11.0 built today from source
 * Installation method: installer
 * Python version (if using Python):
 * Compiler (if using C++): MSVC 14.3
 
[glview-AMD Radeon HD 6300M Series-12.zip](https://github.com/panda3d/panda3d/files/10726224/glview-AMD.Radeon.HD.6300M.Series-12.zip)

**Comment by rdb** [comment]
Please show output with `notify-level-glgsg debug`

**Comment by git2323** [comment]
this is the ouput:

:event(debug): Throwing event TaskManager-addTask(GenericAsyncTask)
:event(debug): Throwing event TaskManager-addTask(GenericAsyncTask)
:event(debug): Throwing event TaskManager-addTask(GenericAsyncTask)
:event(debug): Throwing event TaskManager-addTask(GenericAsyncTask)
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
:event(debug): Throwing event TaskManager-addTask(GenericAsyncTask)
:event(debug): Throwing event window-event(wglGraphicsWindow)
:display:gsg:glgsg(debug): HAS EXT WGL_ARB_pixel_format 1
:display:gsg:glgsg(debug): HAS EXT WGL_ARB_multisample 1
:display:gsg:glgsg(debug): HAS EXT WGL_ARB_create_context 1
:display:gsg:glgsg(debug): GL_VENDOR = ATI Technologies Inc.
:display:gsg:glgsg(debug): GL_RENDERER = AMD Radeon HD 6300M Series
:display:gsg:glgsg(debug): GL_VERSION = 4.5.13399 Compatibility Profile/Debug Context 15.200.1062.1004
:display:gsg:glgsg(debug): GL_VERSION decoded to: 4.5
:display:gsg:glgsg(debug): GL_SHADING_LANGUAGE_VERSION = 4.40
:display:gsg:glgsg(debug): Detected GLSL version: 4.40
:display:gsg:glgsg(debug): Using compatibility profile
:display:gsg:glgsg(debug): GL Extensions:
  GL_AMDX_debug_output                   GL_AMDX_vertex_shader_tessellator
  GL_AMD_conservative_depth              GL_AMD_debug_output
  GL_AMD_depth_clamp_separate            GL_AMD_draw_buffers_blend
  GL_AMD_multi_draw_indirect             GL_AMD_name_gen_delete
  GL_AMD_performance_monitor             GL_AMD_pinned_memory
  GL_AMD_query_buffer_object             GL_AMD_sample_positions
  GL_AMD_seamless_cubemap_per_texture    GL_AMD_shader_stencil_export
  GL_AMD_shader_trace                    GL_AMD_texture_cube_map_array
  GL_AMD_texture_texture4                GL_AMD_transform_feedback3_lines_triangles
  GL_AMD_vertex_shader_layer             GL_AMD_vertex_shader_tessellator
  GL_AMD_vertex_shader_viewport_index    GL_ARB_ES2_compatibility
  GL_ARB_ES3_1_compatibility             GL_ARB_ES3_compatibility
  GL_ARB_arrays_of_arrays                GL_ARB_base_instance
  GL_ARB_blend_func_extended             GL_ARB_buffer_storage
  GL_ARB_clear_buffer_object             GL_ARB_clear_texture
  GL_ARB_clip_control                    GL_ARB_color_buffer_float
  GL_ARB_compatibility                   GL_ARB_compressed_texture_pixel_storage
  GL_ARB_compute_shader                  GL_ARB_conditional_render_inverted
  GL_ARB_conservative_depth              GL_ARB_copy_buffer
  GL_ARB_copy_image                      GL_ARB_cull_distance
  GL_ARB_debug_output                    GL_ARB_depth_buffer_float
  GL_ARB_depth_clamp                     GL_ARB_depth_texture
  GL_ARB_derivative_control              GL_ARB_direct_state_access
  GL_ARB_draw_buffers                    GL_ARB_draw_buffers_blend
  GL_ARB_draw_elements_base_vertex       GL_ARB_draw_indirect
  GL_ARB_draw_instanced                  GL_ARB_enhanced_layouts
  GL_ARB_explicit_attrib_location        GL_ARB_explicit_uniform_location
  GL_ARB_fragment_coord_conventions      GL_ARB_fragment_layer_viewport
  GL_ARB_fragment_program                GL_ARB_fragment_program_shadow
  GL_ARB_fragment_shader                 GL_ARB_framebuffer_no_attachments
  GL_ARB_framebuffer_object              GL_ARB_framebuffer_sRGB
  GL_ARB_geometry_shader4                GL_ARB_get_program_binary
  GL_ARB_get_texture_sub_image           GL_ARB_gpu_shader5
  GL_ARB_gpu_shader_fp64                 GL_ARB_half_float_pixel
  GL_ARB_half_float_vertex               GL_ARB_imaging
  GL_ARB_instanced_arrays                GL_ARB_internalformat_query
  GL_ARB_internalformat_query2           GL_ARB_invalidate_subdata
  GL_ARB_map_buffer_alignment            GL_ARB_map_buffer_range
  GL_ARB_multi_bind                      GL_ARB_multi_draw_indirect
  GL_ARB_multisample                     GL_ARB_multitexture
  GL_ARB_occlusion_query                 GL_ARB_occlusion_query2
  GL_ARB_pipeline_statistics_query       GL_ARB_pixel_buffer_object
  GL_ARB_point_parameters                GL_ARB_point_sprite
  GL_ARB_program_interface_query         GL_ARB_provoking_vertex
  GL_ARB_query_buffer_object             GL_ARB_robust_buffer_access_behavior
  GL_ARB_sample_shading                  GL_ARB_sampler_objects
  GL_ARB_seamless_cube_map               GL_ARB_seamless_cubemap_per_texture
  GL_ARB_separate_shader_objects         GL_ARB_shader_atomic_counters
  GL_ARB_shader_bit_encoding             GL_ARB_shader_image_load_store
  GL_ARB_shader_image_size               GL_ARB_shader_objects
  GL_ARB_shader_precision                GL_ARB_shader_stencil_export
  GL_ARB_shader_storage_buffer_object    GL_ARB_shader_subroutine
  GL_ARB_shader_texture_image_samples    GL_ARB_shader_texture_lod
  GL_ARB_shading_language_100            GL_ARB_shading_language_420pack
  GL_ARB_shading_language_packing        GL_ARB_shadow
  GL_ARB_shadow_ambient                  GL_ARB_stencil_texturing
  GL_ARB_sync                            GL_ARB_tessellation_shader
  GL_ARB_texture_barrier                 GL_ARB_texture_border_clamp
  GL_ARB_texture_buffer_object           GL_ARB_texture_buffer_object_rgb32
  GL_ARB_texture_buffer_range            GL_ARB_texture_compression
  GL_ARB_texture_compression_bptc        GL_ARB_texture_compression_rgtc
  GL_ARB_texture_cube_map                GL_ARB_texture_cube_map_array
  GL_ARB_texture_env_add                 GL_ARB_texture_env_combine
  GL_ARB_texture_env_crossbar            GL_ARB_texture_env_dot3
  GL_ARB_texture_float                   GL_ARB_texture_gather
  GL_ARB_texture_mirror_clamp_to_edge    GL_ARB_texture_mirrored_repeat
  GL_ARB_texture_multisample             GL_ARB_texture_non_power_of_two
  GL_ARB_texture_query_levels            GL_ARB_texture_query_lod
  GL_ARB_texture_rectangle               GL_ARB_texture_rg
  GL_ARB_texture_rgb10_a2ui              GL_ARB_texture_snorm
  GL_ARB_texture_stencil8                GL_ARB_texture_storage
  GL_ARB_texture_storage_multisample     GL_ARB_texture_swizzle
  GL_ARB_texture_view                    GL_ARB_timer_query
  GL_ARB_transform_feedback2             GL_ARB_transform_feedback3
  GL_ARB_transform_feedback_instanced    GL_ARB_transform_feedback_overflow_query
  GL_ARB_transpose_matrix                GL_ARB_uniform_buffer_object
  GL_ARB_vertex_array_bgra               GL_ARB_vertex_array_object
  GL_ARB_vertex_attrib_64bit             GL_ARB_vertex_attrib_binding
  GL_ARB_vertex_buffer_object            GL_ARB_vertex_program
  GL_ARB_vertex_shader                   GL_ARB_vertex_type_10f_11f_11f_rev
  GL_ARB_vertex_type_2_10_10_10_rev      GL_ARB_viewport_array
  GL_ARB_window_pos                      GL_ATI_draw_buffers
  GL_ATI_envmap_bumpmap                  GL_ATI_fragment_shader
  GL_ATI_separate_stencil                GL_ATI_texture_compression_3dc
  GL_ATI_texture_env_combine3            GL_ATI_texture_float
  GL_ATI_texture_mirror_once             GL_EXT_abgr
  GL_EXT_bgra                            GL_EXT_bindable_uniform
  GL_EXT_blend_color                     GL_EXT_blend_equation_separate
  GL_EXT_blend_func_separate             GL_EXT_blend_minmax
  GL_EXT_blend_subtract                  GL_EXT_compiled_vertex_array
  GL_EXT_copy_buffer                     GL_EXT_copy_texture
  GL_EXT_direct_state_access             GL_EXT_draw_buffers2
  GL_EXT_draw_instanced                  GL_EXT_draw_range_elements
  GL_EXT_fog_coord                       GL_EXT_framebuffer_blit
  GL_EXT_framebuffer_multisample         GL_EXT_framebuffer_object
  GL_EXT_framebuffer_sRGB                GL_EXT_geometry_shader4
  GL_EXT_gpu_program_parameters          GL_EXT_gpu_shader4
  GL_EXT_histogram                       GL_EXT_multi_draw_arrays
  GL_EXT_packed_depth_stencil            GL_EXT_packed_float
  GL_EXT_packed_pixels                   GL_EXT_pixel_buffer_object
  GL_EXT_point_parameters                GL_EXT_polygon_offset_clamp
  GL_EXT_provoking_vertex                GL_EXT_rescale_normal
  GL_EXT_secondary_color                 GL_EXT_separate_specular_color
  GL_EXT_shader_image_load_store         GL_EXT_shader_integer_mix
  GL_EXT_shadow_funcs                    GL_EXT_stencil_wrap
  GL_EXT_subtexture                      GL_EXT_texgen_reflection
  GL_EXT_texture3D                       GL_EXT_texture_array
  GL_EXT_texture_buffer_object           GL_EXT_texture_compression_bptc
  GL_EXT_texture_compression_latc        GL_EXT_texture_compression_rgtc
  GL_EXT_texture_compression_s3tc        GL_EXT_texture_cube_map
  GL_EXT_texture_edge_clamp              GL_EXT_texture_env_add
  GL_EXT_texture_env_combine             GL_EXT_texture_env_dot3
  GL_EXT_texture_filter_anisotropic      GL_EXT_texture_integer
  GL_EXT_texture_lod                     GL_EXT_texture_lod_bias
  GL_EXT_texture_mirror_clamp            GL_EXT_texture_object
  GL_EXT_texture_rectangle               GL_EXT_texture_sRGB
  GL_EXT_texture_sRGB_decode             GL_EXT_texture_shared_exponent
  GL_EXT_texture_snorm                   GL_EXT_texture_storage
  GL_EXT_texture_swizzle                 GL_EXT_timer_query
  GL_EXT_transform_feedback              GL_EXT_vertex_array
  GL_EXT_vertex_array_bgra               GL_EXT_vertex_attrib_64bit
  GL_IBM_texture_mirrored_repeat         GL_KHR_context_flush_control
  GL_KHR_debug                           GL_KHR_robust_buffer_access_behavior
  GL_KHR_robustness                      GL_KTX_buffer_region
  GL_NV_blend_square                     GL_NV_conditional_render
  GL_NV_copy_depth_to_color              GL_NV_copy_image
  GL_NV_depth_buffer_float               GL_NV_explicit_multisample
  GL_NV_float_buffer                     GL_NV_half_float
  GL_NV_primitive_restart                GL_NV_texgen_reflection
  GL_NV_texture_barrier                  GL_OES_EGL_image
  GL_SGIS_generate_mipmap                GL_SGIS_texture_edge_clamp
  GL_SGIS_texture_lod                    GL_SUN_multi_draw_arrays
  GL_WIN_swap_hint                       WGL_AMDX_gpu_association
  WGL_AMD_gpu_association                WGL_ARB_buffer_region
  WGL_ARB_context_flush_control          WGL_ARB_create_context
  WGL_ARB_create_context_profile         WGL_ARB_extensions_string
  WGL_ARB_make_current_read              WGL_ARB_multisample
  WGL_ARB_pbuffer                        WGL_ARB_pixel_format
  WGL_ARB_pixel_format_float             WGL_ARB_render_texture
  WGL_ATI_pixel_format_float             WGL_ATI_render_texture_rectangle
  WGL_EXT_extensions_string              WGL_EXT_framebuffer_sRGB
  WGL_EXT_pixel_format_packed_float      WGL_EXT_swap_control
  WGL_EXT_swap_control_tear              WGL_I3D_genlock
  WGL_NV_DX_interop                      WGL_NV_DX_interop2
  WGL_NV_float_buffer                    WGL_NV_swap_group
:display:gsg:glgsg(debug): HAS EXT GL_EXT_debug_marker 0
:display:gsg:glgsg: gl-debug enabled.
:display:gsg:glgsg(debug): HAS EXT GL_ARB_vertex_program 1
:display:gsg:glgsg(debug): HAS EXT GL_ARB_fragment_program 1
:display:gsg:glgsg(debug): HAS EXT GL_NV_gpu_program5 0
:display:gsg:glgsg(debug): HAS EXT GL_NV_gpu_program4 0
:display:gsg:glgsg(debug): HAS EXT GL_NV_vertex_program3 0
:display:gsg:glgsg(debug): HAS EXT GL_NV_vertex_program2 0
:display:gsg:glgsg(debug): HAS EXT GL_NV_vertex_program1_1 0
:display:gsg:glgsg(debug): HAS EXT GL_NV_framebuffer_multisample_coverage 0
:display:gsg:glgsg(debug): Occlusion query counter provides 32 bits.
:display:gsg:glgsg(debug): HAS EXT GL_EXT_texture_mirror_clamp 1
:display:gsg:glgsg(debug): max texture dimension = 16384, max 3d texture = 2048, max 2d texture array = 2048, max cube map = 16384
:display:gsg:glgsg(debug): max_elements_vertices = 2147483647, max_elements_indices = 16777215
:display:gsg:glgsg(debug): vertex buffer objects are supported.
:display:gsg:glgsg(debug): Supported compressed texture formats:
  GL_COMPRESSED_RGBA_BPTC_UNORM
  GL_COMPRESSED_SRGB_ALPHA_BPTC_UNORM
  GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT
  GL_COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT
  GL_COMPRESSED_RGB_S3TC_DXT1_EXT
  GL_COMPRESSED_RGBA_S3TC_DXT1_EXT
  GL_COMPRESSED_RGBA_S3TC_DXT3_EXT
  GL_COMPRESSED_RGBA_S3TC_DXT5_EXT
  GL_COMPRESSED_RGB8_ETC2
  GL_COMPRESSED_SRGB8_ETC2
  GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2
  GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2
  GL_COMPRESSED_RGBA8_ETC2_EAC
  GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC
  GL_COMPRESSED_R11_EAC
  GL_COMPRESSED_SIGNED_R11_EAC
  GL_COMPRESSED_RG11_EAC
  GL_COMPRESSED_SIGNED_RG11_EAC
:display:gsg:glgsg(debug): HAS EXT GL_EXT_texture_filter_anisotropic 1
:display:gsg:glgsg(debug): HAS EXT GL_ARB_bindless_texture 0
:display:gsg:glgsg(debug): HAS EXT GL_EXT_stencil_two_side 0
:display:gsg:glgsg(debug): HAS EXT GL_ARB_polygon_offset_clamp 0
:display:gsg:glgsg(debug): HAS EXT GL_EXT_polygon_offset_clamp 1
:display:gsg:glgsg(debug): max lights = 8
:display:gsg:glgsg(debug): max clip planes = 8
:display:gsg:glgsg(debug): max texture stages = 8
:display:gsg:glgsg(error): glGetIntegerv parameter <pname> has an invalid enum '0x82e5' (GL_INVALID_ENUM)
:display:gsg:glgsg(warning): Failed to query GL_MAX_VERTEX_ATTRIB_STRIDE.
:display:gsg:glgsg(debug): max vertex attrib stride = 2048 (guessed)
:display:gsg:glgsg(debug): Supported program binary formats:
:display:gsg:glgsg(debug):   0x901E
:display:gsg:glgsg(debug): Supported Cg profiles:
:display:gsg:glgsg(debug):   arbvp1
:display:gsg:glgsg(debug):   arbfp1
:display:gsg:glgsg(debug):   glslv
:display:gsg:glgsg(debug):   glslf
:display:gsg:glgsg(debug):   glslg
:display:gsg:glgsg(debug): Cg GLSL version = CG_GL_GLSL_120
:display:gsg:glgsg(debug): Cg latest vertex profile = arbvp1
:display:gsg:glgsg(debug): Cg latest fragment profile = arbfp1
:display:gsg:glgsg(debug): Cg latest geometry profile = unknown
:display:gsg:glgsg(debug): basic-shaders-only false
:display:gsg:glgsg(debug): Cg active vertex profile = glslv
:display:gsg:glgsg(debug): Cg active fragment profile = glslf
:display:gsg:glgsg(debug): Cg active geometry profile = glslg
:display:gsg:glgsg(debug): shader model = 5.0
:display:gsg:glgsg(debug): HAS EXT WGL_EXT_swap_control 1
:display:gsg:glgsg(debug): HAS EXT WGL_ARB_pbuffer 1
:display:gsg:glgsg(debug): HAS EXT WGL_ARB_pixel_format 1
:display:gsg:glgsg(debug): HAS EXT WGL_ARB_multisample 1
:display:gsg:glgsg(debug): HAS EXT WGL_ARB_render_texture 1
:event(debug): Throwing event r()
:event(debug): Throwing event connect-device(InputDevice)

**Comment by rdb** [comment]
Looks like a driver bug.  It's clearly in the GL 4.5 spec.

However, Panda is falling back to 2048 correctly.  I don't think it's related to the model loading issue.

**Comment by git2323** [comment]
ok, thanks.
