### ISSUE TITLE
CMake does not find the specified python version

### ISSUE THREAD

**Issue by serkkz** [panda3d/panda3d#1472]
When trying to build Panda3D on Windows using CMake with support for selected version python, the minimum version of the interpreter from the thirdparty folder is used.

Build parameters.

cmake -D HAVE_PYTHON=YES -D WANT_PYTHON_VERSION=3.11 ..

However there will be a minimum version installed which is available in the thirdparty folder, In my case 3.9
Quick tests showed that this can be fixed by hard-setting the `Python_ROOT` variable with the value of the path of the directory where the desired version of the python interpreter is located.

Examining the logic of `Python_ROOT`, we can come to the conclusion that only the first directory from the list is used after inversion.

'D:/panda3d-master/thirdparty/win-python3.9-x64;D:/panda3d-master/thirdparty/win-python3.8-x64;D:/panda3d-master/thirdparty/win-python3.7-x64;D:/panda3d-master/thirdparty/win-python3.6-x64;D:/panda3d-master/thirdparty/win-python3.5-x64;D:/panda3d-master/thirdparty/win-python3.4-x64;D:/panda3d-master/thirdparty/win-python3.11-x64;D:/panda3d-master/thirdparty/win-python3.10-x64;D:/panda3d-master/thirdparty/win-python-x64'

And it looks like the `WANT_PYTHON_VERSION` parameter is not actually applied.

https://github.com/panda3d/panda3d/blob/4da2059758267a91cfa7fc91bc77b9332eb280dd/dtool/Package.cmake#L43

 * Operating system: Windows 10
 * System architecture: x64

**Comment by rdb** [comment]
Yes, if WANT_PYTHON_VERSION is set, we should set this based on this value.  Otherwise we should pick the latest and/or recommended version of Python.

If a suitable thirdparty python is available we should probably also set ` -DPython_FIND_REGISTRY=NEVER` automatically to prevent an installed version of Python from overriding this.

**Comment by rdb** [comment]
The sorting is also incorrect, as 3.9 is sorted higher than 3.11. Checking in a fix shortly.

If you want to build for multiple Python versions, you need to run CMake multiple times, with a different value for `WANT_PYTHON_VERSION` every time.
