### ISSUE TITLE
Sensitive files directory is Public

### ISSUE THREAD

**Issue by masim1888** [panda3d/panda3d#1475]
Hello,

I am Asim , I am IT security researcher during research i found that your Internal directory of website is open that could be misuse by the attacker . 

As a responsible researcher i thought that i should informed you about this vulnerability of the website . I believe this Internal directory information should not be public and this should be restricted by your IT department team. These directory contains important internal files that should not be authorized by any other users.

IMPACT

Disclosure of confidential, sensitive or embarrassing information can result in loss of credibility, reputation, market share, and competitive edge. The most common threat in a networked system is unauthorized access to information and computer resources. This may cause the loss of confidentiality, integrity, and availability of the information technology assets. To ensure business continuity and minimize potential damage, companies need to establish a computer-based access control to protect their proprietary information from intentional or accidental disclosure, modification, erasure, or copying, as well as their IT resources from misuse. This control provides an organization with the ability to restrict, monitor, and protect the confidentiality and integrity.

STEPS TO REPRODUCE
Visit the below link so you found that Internal directory is public. I am able to directly view these files without admin login ID or password.

https://runtime-dev.panda3d.org/sqlite/cmu_1.8/

**Comment by rdb** [comment]
This is not a sensitive or internal directory, it is public by design. Closing.

**Comment by rdb** [comment]
For future reference, disclosure of (potential) security vulnerabilities should be done privately, via the email address listed here:

https://www.panda3d.org/contact/
