### ISSUE TITLE
tinydisplay not built by CMake

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#1481]
When building with CMake, the tinydisplay module is not built.

A CMakeLists.txt file needs to be created for the tinydisplay directory.

**Comment by rdb** [comment]
Please do @toadkarter!  Feel free to join #engine-dev on our [Discord server](https://discord.gg/UyepRMm) if you have any questions.

**Comment by pmp-p** [comment]
i think static build does not pass in all cmake cases
narrowed it down to
```
cmake  -DHAVE_EGL=NO -DHAVE_GL=NO -DHAVE_GLX=NO -DHAVE_X11=YES -DHAVE_GLES1=NO -DHAVE_GLES2=NO -DHAVE_TINYDISPLAY=1
```
where the default (and only) renderer whould be offscreen tinydisplay
