### ISSUE TITLE
Files Within VFS-Mount Don’t "Exist"

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#1493]
## Description
It appears that the "exist" methods of the Filename and VirtualFileSystem class don't recognise files within a mounted multifile: they report that the file does not exist, even though such a file can nevertheless be opened and read.

## Steps to Reproduce
Here follows a short test-program, as well as the simple multifile that it accesses. To perform the test, just copy the multifile into the same directory as the program, and then run the latter: it should produce a few lines of output, in particular one that starts with "Does the file exist?", followed by one that starts with "File contents:".

The program:
```python

from direct.showbase.ShowBase import ShowBase

from panda3d.core import VirtualFileSystem, Filename

from direct.stdpy.file import *

import math

from panda3d import __version__ as pandaVersion
print (pandaVersion)

import sys
print (sys.version)


class Game(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)

        vfs = VirtualFileSystem.getGlobalPtr()
        vfs.mount(Filename("./mew.mf"), Filename("./Mew"), VirtualFileSystem.MFReadOnly)
        
        fileName = Filename("Mew/cat.txt")
        print ("Does the file exist?", fileName.exists())
        fileObj = open("Mew/cat.txt")
        print("File contents:", fileObj.read())
        fileObj.close()


app = Game()
app.run()

```

And the multifile (zipped, as GitHub objects to “.mf” files):

[mew.zip](https://github.com/panda3d/panda3d/files/11347582/mew.zip)

The multifile should contain just one file, that being a text-file named “cat.txt” which itself contains the text “Cat!”.

On my machine, at least, this prints the following:

```text
Does the file exist? False
File contents: Cat!
```

So the file is deemed to not exist–and yet can nevertheless be read. :/

## Environment
 * Operating system: Ubuntu 18.04.6 LTS
 * System architecture: 64-bit
 * Panda3D version: 1.10.13
 * Installation method: Pip, I think.
 * Python version (if using Python): 3.6.9
 * Compiler (if using C++): N/A

**Comment by rdb** [comment]
Filename does not know about the VFS.  Use `vfs.exists(fn)` to determine whether a given filename exists.

**Comment by ArsThaumaturgis** [comment]
Aah, right you are!

I think that I had been under the impression that I had tried that--but it would seem not, as using "vfs.exists(fileName)" in the above program _does_ indeed produce an output of "True"!

Thank you for so answering! ^_^

I do think that I'd like then to advocate for this as something to be clarified somewhere: Filename's API entry somewhat-vaguely indicates that it checks whether the file exists on the disk (a meaning clear in retrospect, but unclear at the time, as I recall), while VirtualFileSystem's API entry indicates that its own version of "exists" is merely a convenience function. Further, I don't see--at least on an admittedly-quick search--mention somewhere that Filename is unaware of the VFS.

As a result, this remains unexpected behaviour, I feel.

**Comment by rdb** [comment]
Maybe the API documentation can be clearer.

What is meant by a "convenience function" is that it actually is a shortcut for doing `vfs.getFile(...)` and checking that it isn't None.

**Comment by ArsThaumaturgis** [comment]
> Maybe the API documentation can be clearer.
> 
> What is meant by a "convenience function" is that it actually is a shortcut for doing `vfs.getFile(...)` and checking that it isn't None.

Ah, I see.

I suppose that my question then is: why is it a shortcut for "vffs.getFile", rather than one for "vfs.exists"...? The latter would seem more intuitive, and should--I would think--produce the expected results.

**Comment by rdb** [comment]
I'm referring to `vfs.exists()` being a convenience function for `vfs.getFile()`.

**Comment by ArsThaumaturgis** [comment]
Aah, I see--thank you for clarifying! Fair enough!
