### ISSUE TITLE
Freeze when using tkinter with multithreading

### ISSUE THREAD

**Issue by MosesofEgypt** [panda3d/panda3d#1494]
## Description
Using tkinter with threading-model set to anything other than single-threaded causes the render window to freeze. Using the snippit below should create an empty, fully functional tk window, and a frozen, native, panda3d window. Setting disable-message-loop to true or false does not have an effect on the issue. If not using tkinter, the issue is not present, and the render window is not frozen.

Link to related panda3d scripting issues forum post: https://discourse.panda3d.org/t/freeze-when-using-tkinter-with-multithreading/29292

## Steps to Reproduce
I can produce the freeze with the following snippit:

````python
from panda3d.core import ConfigVariableBool, ConfigVariableString
from direct.showbase.ShowBase import ShowBase

ConfigVariableBool("want-tk").setValue(True)
ConfigVariableString("threading-model").setValue("Cull/Draw")

ShowBase().run()
````

## Environment
AMD 64bit Python 3.8.0 on Windows 10
v1.10.13 of Panda3d installed through pip
v8.6.9 of Tk

**Comment by DioExtreme** [comment]
Just encountered this, the reason disable-message-loop has no effect is because it gets overridden in spawnTkLoop of ShowBase. Setting it to False there fixes the issue.

**Comment by MosesofEgypt** [comment]
@DioExtreme that DOES fix the issue in the specific example I have provided, but it doesn't fix the issue I was trying to illustrate. The application I'm writing is setup to have a panda renderer displayed in a tkinter window, which this example doesn't do. Here's a link to the application main class(please ignore the cruft, things change rapidly as I learn how the game's intended to load resources):
https://github.com/MosesofEgypt/gdl_tools/blob/particle_system_support/gdl/rendering/scene.py

I thought the issues would be related, but it appears not, because when I reworked this example to do that, it froze regardless of whether or not disable-message-loop was set. I'll see if I can recreate the example in a simple enough way to copy here.

**Comment by MosesofEgypt** [comment]
Here is a better example that properly illustrates the issue I am facing in my application:
```python
import Pmw
from tkinter import *
from panda3d.core import ConfigVariableBool, ConfigVariableString, WindowProperties
from direct.showbase.ShowBase import ShowBase

ConfigVariableString("threading-model").setValue("Cull/Draw")

class TestBase(ShowBase):
    def __init__(self, **kwargs):
        # initialize showbase without creating a window
        super().__init__(windowType='none')

        # create the tkinter window to stuff the panda3d renderer in
        self.tkRoot = Pmw.initialise(Tk())
        self.tkRoot.geometry("300x300")

        ConfigVariableBool("want-tk").setValue(True)
        self.tkRoot.update()

        props = WindowProperties().get_default()
        props.setParentWindow(self.tkRoot.winfo_id())
        self.openDefaultWindow(startDirect=False, props=props)
        self.startTk(True)

        props = WindowProperties()
        props.setOrigin(0, 0)
        props.setSize(300, 300)
        self.win.requestProperties(props)

TestBase().run()

```

**Comment by serkkz** [comment]
I conducted an investigation and found out that the hang occurs when the Panda3D window is specified as a child of tkinter.

`props.setParentWindow(self.tkRoot.winfo_id())`

This line is causing the problem. However, I couldn't get this code to work, I was testing on my own application template based on this: https://discourse.panda3d.org/t/using-panda3d-without-direct/26845.

**Comment by rdb** [comment]
I think there are two issues here: the first is that disable-message-loop shouldn't really be set when using the threaded pipeline (because Panda's message loop takes place in its own thread then, and message loops are per-thread), and the second is whatever happens with setParentWindow, which I'll have to investigate.

**Comment by rdb** [comment]
The second issue is I think due to the fact that the main thread needs to process the WM_PARENTNOTIFY message, because CreateWindow on the draw thread will hang waiting for it.  But the main thread isn't running a message pump, because it is waiting for the child window to finish opening.  Deadlock!

Either we need to call CreateWindow on the main thread or we need to somehow introduce some mechanism for the main thread to enter a temporary message pump while the windows are being opened.

**Comment by rdb** [comment]
I got somewhere by setting the `WS_EX_NOPARENTNOTIFY` style when opening the window and commenting out the `set_focus();` call, but I'm running into hangs inside Tk whenever I try to do anything to the Tk window, such as resize it.

I think having a parent and child window in different threads is just a minefield.  Running Tk in its own thread doesn't seem to be an option either.

This is becoming a time sink and I'm going to close this as "wontfix".  We should document that using tkinter with Panda3D is not supported with the multithreaded pipeline on Windows.
