### ISSUE TITLE
class direct.showbase.PythonUtil.SerialMaskedGen not included in direct.showbase.PythonUtil.__all__

### ISSUE THREAD

**Issue by Souzooka** [panda3d/panda3d#1496]
## Description
The `__all__` list in direct.showbase.PythonUtil ([here](https://github.com/panda3d/panda3d/blob/master/direct/src/showbase/PythonUtil.py)) does not contain the variable "SerialMaskedGen", which is defined within the file.

**Comment by rdb** [comment]
Doesn't look like it's ever been part of `__all__`.  Presumably because the module already adds it to the built-in scope (ugh).

What problem does this cause for you, specifically?

**Comment by Souzooka** [comment]
I actually specifically check to see if the keys in `builtins` that PythonUtil populate exist and if they do, delete them, to reduce global name pollution. This also means for an extension of the PythonUtil module I have I have to both use a star import, and a second import to specifically import `SerialMaskedGen`.
