### ISSUE TITLE
dcparser: segfault with nested struct or switch 

### ISSUE THREAD

**Issue by NathaanTFM** [panda3d/panda3d#1499]
## Description
dcParser.yxx is causing a segfault because it's assigning an invalid address to `current_class` or `current_switch` when they're nested.
https://github.com/panda3d/panda3d/blob/53f32e440e3d21ff8148119770b9016a64f4d1b8/direct/src/dcparser/dcParser.yxx#L305
https://github.com/panda3d/panda3d/blob/53f32e440e3d21ff8148119770b9016a64f4d1b8/direct/src/dcparser/dcParser.yxx#L409
https://github.com/panda3d/panda3d/blob/53f32e440e3d21ff8148119770b9016a64f4d1b8/direct/src/dcparser/dcParser.yxx#L1251

Could be fixed by using some kind of stack (tested and worked with std::stack, direct seems to behave correctly with nested structs or unions). 

Maybe the `current_class` or `current_switch` could store a reference to its "parent" while it's parsing the dc file, which would remove the need for a stack.

I do not know Bison enough to create a pull request.

## Steps to Reproduce
```py
from panda3d.direct import DCFile
from panda3d.core import Filename
dcFile = DCFile()
dcFile.read(Filename("demo.dc"))
```
demo.dc:
```c
struct Struct1 {
    uint8 field1;
    struct Struct2 {
        uint8 field;
    } field2;
};
```
also crashing with nested switches:
```c
switch Switch1 (uint8) {
    case 0:
        uint8 field1;
        break;
        
    case 1:
        switch (uint16) {
            case 0:
                break;
            case 1:
                uint8 field;
        } field2;
        
        break;
};
```

## Environment
 * Operating system: Windows
 * System architecture: x64
 * Panda3D version: 1.10, 1.11 (and probably more)
 * Installation method: pip for 1.10, source for 1.11
 * Python version (if using Python): 3.8
 * Compiler (if using C++): MSVC

**Comment by rdb** [comment]
Well, trying to understand the intent of the original code, I think the intent was that the $$ for the midrule should store the parent class.  I think it just needs:

```yacc
struct:
        KW_STRUCT optional_name
{
  $<u.dclass>$ = current_class; // ADDED
  current_class = new DCClass(dc_file, $2, true, false);
}
        struct_derivation '{' struct_fields '}'
{
  $$ = current_class;
  current_class = $<u.dclass>3;
}
        ;
```

Will make the fix.
