### ISSUE TITLE
Panda3D-SDK-1.10.13-MacOSX10.9.dmg cannot be opened on MacOSX 10.9

### ISSUE THREAD

**Issue by rosssokanna** [panda3d/panda3d#1502]
## Description
I appreciate very much that you are making panda3d available for older versions of operating systems. I'm using Mac OS X 10.9.5 and ran into the following problem:
The disk image for the Panda3D SDK (downloaded from www.panda3d.org) cannot be opened on my system.
Double-clicking it gives: 'no mountable file systems'

Probable cause:
'hdiutil imageinfo Panda3D-SDK-1.10.13-MacOSX10.9.dmg' says that a partition is formatted as 'Apple_APFS'. Since APFS was introduced only in Mac OS 10.13, Mac OS X 10.9 can't read it.

Solution:
The dmg should be formatted as 'Apple_HFS'.

The disk image 'Panda3D-SDK-1.10.13-MacOSX10.6.dmg' (formatted as 'Apple_HFS') is working but the included version of panda3d has only bindings for Python up to version 3.7 and I'd like to use a newer version of Python.

## Steps to Reproduce
1. use Mac OS X 10.9
2. double-click Panda3D-SDK-1.10.13-MacOSX10.9.dmg

## Environment
 * Operating system: Mac OS X 10.9.5
 * System architecture: i386
 * Panda3D version: 1.10.13
 * Installation method: not applicable
 * Python version (if using Python): 3.11.
 * Compiler (if using C++):

**Comment by rdb** [comment]
Thanks for bringing this to light.  We need to figure out the correct `hdiutil` command for producing a .dmg that is compatible with OS X 10.9.

**Comment by rdb** [comment]
Can you please test this build and let me know whether it works for you?
https://buildbot.panda3d.org/downloads/d4d4aefbce08335b8afb13109a7001263a874763/Panda3D-SDK-1.10.14-d4d4aef-MacOSX10.9.dmg
