### ISSUE TITLE
Egg-trans works on Linux on Panda3D 1.10.12 but not on 1.10.13

### ISSUE THREAD

**Issue by Wizzerinus** [panda3d/panda3d#1504]
## Description
I am trying to run the `egg-trans` tool because it's widely used in our workflow. If I install the (closed-source) version of Panda3D we use in our organization, it works. If I install a 1.10.12 wheel from PyPI, it also works. However, if I install 1.10.13 or 1.10.13.post1 from PyPI, it does not work. I will also add that I'm running it on Linux.

When it works, it makes an output like this when it's launched without arguments:
```
You must specify the egg file(s) to read on the command line.

Usage:
  egg-trans [opts] -o output.egg input.egg
  egg-trans [opts] input.egg >output.egg
```

When it does not, it outputs an empty string.

Tools like `bam2egg`, `egg2bam`, and `pview` work in all versions, I am not aware if some other tools broke.

## Steps to Reproduce
 * Install the latest Panda3D from PyPI
 * Run `egg-trans`

## Environment
 * Operating system: Linux
 * System architecture: x64 (not ARM)
 * Panda3D version: 1.10.13 (or 1.10.13.post1)
 * Installation method: pip

**Comment by rdb** [comment]
Version of Python?

**Comment by Wizzerinus** [comment]
I'm using Python 3.11, idk how much it matters though

**Comment by rdb** [comment]
This seems to be due to patchelf corrupting some Panda3D executables, see pypa/manylinux#1421 and NixOS/patchelf#446 - we need to downgrade patchelf when building the Panda3D wheels.

Fixed wheels available here:
https://buildbot.panda3d.org/downloads/3f3819e7faf9f9d26095506a3ffb748f0bba80cf/

**Comment by Wizzerinus** [comment]
Wow I love linux architecture quirks. Fantastic. /j
