### ISSUE TITLE
Errors with the pstats-python-profiler when using Metaclasses

### ISSUE THREAD

**Issue by theMajorWiccana** [panda3d/panda3d#1505]
## Description

The pstats-python-profiler option breaks when attempting to create a new class via custom metaclasses or type()

## Steps to Reproduce

step 0: install python and panda3d
step 1: set up a pstats server.
step 2: run the code below.
 ```python
from direct.showbase.ShowBase import ShowBase
from panda3d.core import loadPrcFileData

variablesConfig = '''
want-pstats 1
pstats-python-profiler 1
'''
loadPrcFileData('', variablesConfig)

class NewType(type):
    def __new__(typ, name, bases, dct):
        return super().__new__(typ, name, bases, dct)

    def getCopy1(cls):
        return super().__new__(type, f'Copy{cls.__name__}', (cls,), {})

    def getCopy2(cls):
        return super().__new__(type(cls), f'Copy{cls.__name__}', (cls,), {})

    def getCopy3(cls):
        return type(f'Copy{cls.__name__}', (cls,), {})

class NewClass(metaclass = NewType):...

class Main(ShowBase):
    def __init__(self):
        super().__init__()
        NewClass.getCopy1()
        NewClass.getCopy2()
        NewClass.getCopy3()

Main().run()
```
step 3: watch getCopyX() throw an error.

in this configuration getCopy1 will throw a
`SystemError: <class 'super'> returned a result with an exception set`
and getCopy2 and 3 will throw a
`TypeError: bad argument type for built-in operation`

however if NewType didn't define a `__new__` instead
getCopy1 and 2 will throw the TypeError and getCopy3 will not throw an error

## Environment
 * Operating system: Windows 11
 * System architecture: x64
 * Panda3D version: 1.10.13
 * Installation method: via pip
 * Python version (if using Python): 3.11.4

**Comment by rdb** [comment]
Please try new wheels from here:
https://buildbot.panda3d.org/downloads/94ebd7c953eb7ab048d3fd239374d6d4d7284a97/
