### ISSUE TITLE
Equivalent of ShowBase's aspect2d child nodes in C++ interface

### ISSUE THREAD

**Issue by maxrdz** [panda3d/panda3d#1508]
## Description
Implement an equivalent of the aspect2d child nodes (e.g. `a2dTopRight`, `a2dBottomCenter`) that are created by `ShowBase` in the Python API, for the C++ interface of Panda. 

## Use Case
Recently I was looking to create a PGui object that is positioned relative to the top right corner of the window. The `ShowBase` class in the Python API creates aspect2d child nodes such as `a2dTopRight`, `a2dTopCenter`, etc. as a quick solution to this problem. It is incredibly convenient (and is most likely used in most Panda applications), so I'm surprised the C++ interface does not implement this when aspect2d is created by the engine.

Currently I've written an alternative on my own application, but it took some time to get it right and I would like to avoid having others spending time on this hack as well.

**Comment by Max-Rodriguez** [comment]
I'm also thinking of resolving this issue as my first contribution to Panda. Will submit a PR soon.
