### ISSUE TITLE
pzip/punzip do nothing at all

### ISSUE THREAD

**Issue by caco3** [panda3d/panda3d#1511]
## Description
I installed `1.10.13` using `pip install -U panda3d`.

When I call `punzip maze.egg.pz` in `samples/ball-in-maze/models`, simple nothing happens.
No file gets extracted and no error gets shown.

## Environment
 * Operating system: Ubuntu 22.04
 * System architecture: AMD64

**Comment by caco3** [comment]
So I got this working now by uninstalling it again (pip) and installing it instead as a deb file.

**Comment by rdb** [comment]
Duplicate of #1504
