### ISSUE TITLE
Source file for samples/ball-in-maze/models/maze.egg.pz

### ISSUE THREAD

**Issue by caco3** [panda3d/panda3d#1512]
Dear @rdb 

I would like to create  a game based on the `ball-in-maze` example.

Sadly only the egg file is provided ([samples/ball-in-maze/models/maze.egg.pz](https://github.com/panda3d/panda3d/blob/master/samples/ball-in-maze/models/maze.egg.pz)) but not the source maya file. Would you be able to provide the source files or show how to create different maps. Else it seems almost impossible to create a custom map.

**Comment by rdb** [comment]
I didn't make this sample, I don't have the source assets.

**Comment by caco3** [comment]
Thanks for your quick response!
