### ISSUE TITLE
<Collide> causes a segmentation fault if the group has Lines inside of it

### ISSUE THREAD

**Issue by Wizzerinus** [panda3d/panda3d#1515]
## Description
Using a <Line> object inside a group with <Collide> in any mode causes a segmentation fault when `pview`, `egg2bam` etc. is run. This happens even if the collide mode does not need to look at the line (i.e. Plane type is used)

## Steps to Reproduce
 * Create an egg file like this:
```
<CoordinateSystem> { Z-Up }

<VertexPool> Scene {
  <Vertex> 0 {
    1 0 0
  }
  <Vertex> 1 {
    0 1 0
  }
  <Vertex> 2 {
    1 1 1
  }
  <Vertex> 3 {
    0 0 1
  }
}
<Group> test {
  <Collide> test { Plane descend }
  <Group> inside {
    <Polygon> {
      <VertexRef> { 0 1 3 <Ref> { Scene } }
    }
    <Line> {
      <VertexRef> { 1 2 <Ref> { Scene } }
    }
  }
}
```
 * Save as `file.egg`
 * Run `pview file.egg`

If `<Line>` or `<Collide>` is removed everything works, having both causes a segmentation fault 

## Environment
 * Operating system: Linux
 * System architecture: 64x
 * Panda3D version: 1.10.12 (just tested, 1.10.13 also has this issue)
 * Installation method: pip
 * Python version (if using Python): 3.11.3

**Comment by Wizzerinus** [comment]
Btw: I do not know if non-polygon objects also have this problem. It seems that the other two egg nodes that can exist in a group are Patch and PointLight (and theres that one technical type that should not be in an egg), but I don't know how theyre used, nor if they're common, and nor if they crash.

**Comment by rdb** [comment]
It's composite primitives that can't be triangulated, which is just lines - the egg loader enters an infinite loop trying to "triangulate" the lines.
