### ISSUE TITLE
assimp importer animation import buggy: no name, wrong fps

### ISSUE THREAD

**Issue by darktjm** [panda3d/panda3d#1516]
I am evaluating panda3d-1.10.13 for a project, which uses animated models.  There are a number of issues importing the files.  I have tested using Quaternius' public domain models (https://quaternius.com/?i=2).  The obj format screws up some times (parts missing or in the wrong place), and the fbx format is copletely unusable (a twisted wreck).  Assimp doesn't support animations in .blend files anyway, so I exported them from Blender to .glb (gltf2).  I noticed two immediate, obvious problems, even after updating just the assimp importer from 1.10.13 to the most recent git.  Animations have useless names, rather than taking their name from the animation.  FPS was completely wrong.

For the first issue, I just changed the "new AnimBundle" and "new AnimBundleNode" lines to use ai_anim.mName instead of the mesh/bone name, respectively.  This may not be the preferred way, so I am not providing a patch.  I suppose the AnimBundle is supposed to match the mesh name for automatic binding (I have to bind with the obnoxiously long-winded PartGroup::HMF_ok_wrong_root_name flag as well).  For now, this is good enough for me.

For the second issue, I fixed the FPS calculation formula.  Using just units, the original was obviously wrong:
 
    frames / (ai_anim.mTicksPerSecond * ai_anim.mDuration)
    n / (t/s * t) == n/t^2/s) = ns/t^2

The correct formula is:

    frames * ai_anim.mTicksPerSecond / ai_anim.mDuration
    n * t/s / t = n/s

Since it's a one-liner, I didn't bother providing a patch, either.

**Comment by darktjm** [comment]
Since I wrote this, I discovered the quirkiness of the binding API, and see that the name loss was intentional.  As such, the name should probably be added as a tag.

**Comment by Maxwell175** [comment]
For importing blender assets it is recommended to use the semi-official blend2bam utility: https://github.com/Moguri/blend2bam

The assimp integration definitely leaves much to be desired.

**Comment by darktjm** [comment]
No thanks.  "Use pip.."  "Blender 2.8...".  Non-starter.  No guarantee anyway it would be any better, since some things (such as the loss of animation names mentioned above) seem to be a design decision.
I rejected 5 other engines because they couldn't import models properly.  Do I have to abandon panda3d as well, after investing so much time and effort into it already?  I guess so.
To the Panda3D developers:  either fix it or remove it.  Don't make me think I can actually use it unless I can.  It would be sad to see it go, but that way it doesn't factor into my evaluation of the library.

**Comment by serkkz** [comment]
I think you are confusing utilities and engine functionality. However, note that in any case you need to use some kind of 3D modeling package, perhaps you prefer 3D max or something else from this price range, a joke. Also note that at the output you get a bam file, you don't need any python plugin to download it. You can use it in C++ without any problems. And yes, the blender uses python... and it doesn't bother anyone. It's just an intermediate stage in your game development process.

**Comment by darktjm** [comment]
Panda3d purports to be more than just a graphics library.  I can write my own importer, which i have done for several other libraries.  I won't do it yet again for this library.   I do not want to put that much effort into it, if it doesn't buy me anything.  My decision to use or not use a library has nothing to do with what **you** think I should expect from it.  Given your other responses, you also seem to think that doing anything in C++ should be intentionally more difficult than it needs to be.  Perhaps to discourage the use of C++?   In any case, my desire not to use Python for my application has **absolutely nothing** to do with why I reject the blend2bam utility, and also has **absolutely nothing** to do with the assimp importer I wrote this bug report against.  I already listed my reasons, but to clarify:  I won't install an unmaintainable mini-distro just to install a single utility (i.e., I won't use pip unless absolutely necessary), and the documentation only mentions Blender 2.8, which leaves me to doubt that it works with later versions (I have 3.4 on my system).  I don't know what any of the rest of your comment has to do with anything.

**Comment by loblao** [comment]
Those whose needs are not suited by Panda3D are free not to use it.

**Comment by rdb** [comment]
Oh come on, guys. Let's keep discussion civil, kind, and focused on the issue at hand.

This is a valid issue. The recommendation is still to use pip and panda3d-gltf or blend2bam, because it is a better importer. If you insist on using Assimp, we'll fix this bug, but you're making things difficult for yourself by not using panda3d-gltf.

**Comment by BMaxV** [comment]
> using panda3d-gltf or blend2bam (yes, they do work with later versions).

I'd like to point out that I've opened multiple issues in panda and the gltf importer repo because panda3d gltf doesn't work reliably.

https://github.com/panda3d/panda3d/issues/1420

https://github.com/Moguri/panda3d-gltf/issues/119

So, animations is a somewhat open problem in general.

**Comment by darktjm** [comment]
I will not be able to log into github any more as of tomorrow, for failure to comply with their 2FA policy.  I can't track or comment on this issue any more except via email, and I'm not sure that has ever worked right for me.  Given that an official, documented response was given ("don't use assimp"), I'll go ahead and close this issue.  It'd be nice for the assimp importer to be marked as unmaintained/known broken (and, to be fair, assimp itself has reported regressions that haven't been addressed in years), but that isn't really a fix, either.
