### ISSUE TITLE
Disable Assimp glTF loader by default

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#1537]
The Assimp-based glTF loader is not of great quality.  People should use panda3d-gltf instead, which gives better results.  It causes support issues when people forget to install panda3d-gltf and get an incorrect conversion.  Installing panda3d-gltf after making this mistake also does not appear to solve the issue because the old Assimp-based conversion sticks around in the model-cache.

I suggest we disable the Assimp-based glTF loader by default, hiding it behind an `assimp-enable-gltf` config flag or something like that.

We can add the config switch for 1.10.14, but I'm wondering if disabling it by default is okay in a patch release - it's technically a breaking change.

**Comment by Moguri** [comment]
I agree with this. I am tempted to call Assimp doing glTF conversion a bug/unexpected-behavior coming from an Assimp update adding glTF support. I am pretty sure Panda's Assimp loader pre-dates gltf support in Assimp, and I don't know if we ever properly vetted it.

That said, most of the issues here are probably with Panda's Assimp loader rather than Assimp's gltf code.

**Comment by rdb** [comment]
I'm making it a bit more flexible, with a variable that can be used to disable an arbitrary list of extensions from being loaded using Assimp.  You'll want this:
```
assimp-disable-extensions glb gltf
```

I'm going to set this as the default in master, but leaving it empty in 1.10.14 for now.

**Comment by TV4Fun** [comment]
I'm curious, as this still doesn't seem to be the default behavior in the released Panda3D binaries installed through `pip` and is not set in your default config file. Is this default behavior still not in any released versions?

**Comment by rdb** [comment]
Correct, you can set `assimp-disable-extensions glb gltf` in Config.prc to achieve this in stable versions.
