### ISSUE TITLE
Can't find libGL after updates

### ISSUE THREAD

**Issue by JusticeOF666** [panda3d/panda3d#155]
After updating from Debian 9 to Debian 10 (Kernel 4.8 to 4.11) and updating NVidia driver to 375.66, the next restart makeDefaultPipe() fails with 

> Unable to load: libGL.so.1

Although I can still find it in

> libGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGL.so

I'm running Panda3D version 1.10.0.dev1142 on Python 3.6.1.
libgl-mesa-glx 13.0.6-1 + b2

**Comment by rdb** [comment]
Can you verify that you can run other OpenGL applications, such as `glxgears`?

**Comment by JusticeOF666** [comment]
I'm not able to run those either, same error.
Where do you suggest I look for solving this problem?

**Comment by rdb** [comment]
I'm not sure; it appears to be an issue with how your drivers are set up.  Perhaps try reinstalling your driver package.
