### ISSUE TITLE
Add method for querying current display mode

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#1550]
DisplayInformation has methods to query a list of display modes, as well as the current display mode's width and height and bits per pixel, but this does not provide a way to get the current refresh rate.

There should just be a method to get the current display mode index in the list of display modes.

**Comment by serkkz** [comment]
A good point, but in this regard, another question arises. How can I change the refresh rate of the display in the future if necessary?

**Comment by rdb** [comment]
> A good point, but in this regard, another question arises. How can I change the refresh rate of the display in the future if necessary?

This is a separate problem (feel free to file an issue).  We could create a configuration variable or a WindowProperties value but I think we need a better API that can handle multiple displays better as well.
