### ISSUE TITLE
RawInputDevice gets added, although it probably shouldn't

### ISSUE THREAD

**Issue by git2323** [panda3d/panda3d#1559]
## Description
I had the issue where the function GetRawInputDeviceInfoA from [winGraphicsWindow.cxx](https://github.com/panda3d/panda3d/blob/78f8e1eaa95071ae21c2f6d8f16768c7330c5f15/panda/src/windisplay/winGraphicsWindow.cxx#L704) returns -1 for a device (In my case it is a "Remote Desktop Mouse Device" ). Because of the data types, the -1 is not respected in the if and the device ends up being added although it probably shouldn't. If we put a (int) in front of the GetRaw... function(s) it works. GetRawInputDeviceInfoA is also a little strange since it is defined to return an UINT, but it returns -1 (s.a. [learn.microsoft.com](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getrawinputdeviceinfoa#return-value))

## Steps to Reproduce

- [ ] Connect via remote desktop to a computer to install the "Remote Desktop Mouse Device" by windows.
- [ ] Start the Debugger with an optimize 1 build of panda3d and the startup will fail with an assertion failure.
- [ ] On a 'normal' panda3d installation the device gets added to "_input_devices" although no assertion failure happens.

## Environment
 * Operating system: Windows 10
 * System architecture: 64 bit
 * Panda3D version: latest master release
 * Installation method: built from source
 * Python version (if using Python): -
 * Compiler (if using C++): MSVC 2022, v143, c++20

**Comment by git2323** [comment]
Additional info from rdb:  -1 means the buffer is not large enough, but that's odd, because we ask it for the size first
I guess we ought to check for UINT_MAX
there is more info here [stackoverflow](https://stackoverflow.com/questions/67028399/getrawinputdeviceinfo-indicates-a-buffer-size-of-1-character-for-ridi-devicename)

**Comment by Moguri** [comment]
Closed by 7277199
