### ISSUE TITLE
can someone help me build debug version panda?

### ISSUE THREAD

**Issue by lhbemt** [panda3d/panda3d#1566]
can someone help me? i want build debug version of panda, first, i download python3.12 and install with debug library, which have _d version, so i build panda use: makepanda\makepanda.bat --everything --msvc-version=14.2 --windows-sdk=10 --optimize=1 --threads=6
but in python_d.exe，i import panda3d.core，it cant use like this: ModuleNotFoundError: No module named 'panda3d.core'
i can import panda3d, but cant import panda3d.core

**Comment by lhbemt** [comment]
my sys.path is : ['', 'D:\\git_code\\lemt_client\\lemt_client\\3rd\\panda3d\\built_x64\\python\\python312_d.zip', 'D:\\git_code\\lemt_client\\lemt_client\\3rd\\panda3d\\built_x64\\python\\DLLs', 'D:\\git_code\\lemt_client\\lemt_client\\3rd\\panda3d\\built_x64\\python\\Lib', 'D:\\git_code\\lemt_client\\lemt_client\\3rd\\panda3d\\built_x64\\python', 'D:\\git_code\\lemt_client\\lemt_client\\3rd\\panda3d\\built_x64', 'D:\\git_code\\lemt_client\\lemt_client\\3rd\\panda3d\\built_x64\\bin', 'D:\\git_code\\lemt_client\\lemt_client\\3rd\\panda3d\\built_x64\\python\\Lib\\site-packages']

**Comment by rdb** [comment]
I suspect the .pyd files in built_x64/panda3d need a special suffix to import correctly with debug builds, and makepanda isn't giving them the right name...

**Comment by lhbemt** [comment]
yes, i just print the build var, is all correct: python running ver11111111111111111: 3.12, build ver: 3.12, exe: thirdparty/win-python3.12-dbg-x64/python_d.exe
the output name is : interrogatedb.cp312-win_amd64.pyd
but import can't found

**Comment by lhbemt** [comment]
finally,i solved it with change makepandacore.dy GetExtensionSuffix() function, thanks

**Comment by rdb** [comment]
How did you change the function? Please share your fix so that others may benefit.

**Comment by rdb** [comment]
@lhbemt can you please explain what you had to change so that we can apply the fix to makepanda?

**Comment by lhbemt** [comment]
I'm sorry for only getting back to you this late.

**Comment by lhbemt** [comment]
if sys.version_info >= (3, 5) and target == 'windows':
    if GetTargetArch() == 'x64':
        return '.cp%d%d-win_amd64.pyd' % (sys.version_info[:2])
    else:
        return '.cp%d%d-win32.pyd' % (sys.version_info[:2])
to：
if sys.version_info >= (3, 5) and target == 'windows':
    if GetTargetArch() == 'x64':
        if GetOptimize() <= 2:
            return '_d.cp%d%d-win_amd64.pyd' % (sys.version_info[:2])
        else:
            return '.cp%d%d-win_amd64.pyd' % (sys.version_info[:2])
    else:
        if GetOptimize() <= 2:
            return '_d.cp%d%d-win32.pyd' % (sys.version_info[:2])
        else:
            return '.cp%d%d-win32.pyd' % (sys.version_info[:2])
