### ISSUE TITLE
Camera Len’s FOV Changes When Switching Between Applications

### ISSUE THREAD

**Issue by asmsulaiman** [panda3d/panda3d#1567]
## Description
When I use command tab to switch between applications the FOV changes. The vertical FOV changes when setting the film size and focal length. The horizontal FOV changes when just setting the film size. When not setting the film size and focal length the FOV doesn't change in the checkFOV() function.
## Steps to Reproduce
```
from direct.showbase.ShowBase import ShowBase
from direct.task import Task 
class Bug(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)
        self.disableMouse()
        w=36
        h=24 
        self.camLens.setFilmSize(w,h)
        l=24
        self.camLens.setFocalLength(l)
        self.taskMgr.add(self.checkFOV, "checkFOV")
    def checkFOV(self,task):
        print(self.camLens.getFov())
        return Task.cont
app = Bug()
app.run()
```
## Environment
 * Operating system: macOS 14.1
 * System architecture: 64-bit
 * Panda3D version: Panda3D 1.10.13.post1
 * Installation method: pip
 * Python version (if using Python): 3.12.0
 * Compiler (if using C++):

**Comment by kamgha** [comment]
Looks like a feature, not a bug: You're using `ShowBase`. Have you tried `base.setAspectRatio(ar)` instead of manipulating the Lens directly?

`Sets the global aspect ratio of the main window.  Set it to None to restore automatic scaling.`

**Comment by ArsThaumaturgis** [comment]
I'll note that this behaviour doesn't seem to appear for me, under Ubuntu Linux (specifically, 18.04.6); it may thus be Mac-specific. (Presuming that it doesn't appear under Windows, of course.)

**Comment by asmsulaiman** [comment]
@kamgha What I'm trying to do is represent a real camera and do some calculations but when the aspect ratio changes. It changes my calculations. I want the window to be an exact representation of what the camera should see.

```
   def checkAspectRatio(self,task):
        print(self.camLens.getAspectRatio())
        print(self.camLens.getFov())
        return Task.cont
```

I added a print statement for the camera len's horizontal and vertical FOV. Again, when switching between applications whilst the panda3d app is running using macOS the vertical FOV changes.

**Comment by asmsulaiman** [comment]
@ArsThaumaturgis Thanks for trying it on Ubuntu Linux. I'm planning to try it on windows to see if it is just a macOS problem. I'll update about this.

**Comment by rdb** [comment]
To disable the default aspect ratio adjustment:

```python
        self.setAspectRatio(self.getAspectRatio())
```

Or maybe:

```python
    def adjustWindowAspectRatio(self, aspectRatio):
        pass
```

**Comment by kamgha** [comment]
Hi @asmsulaiman , I find your report confusing. You have now renamed it and **silently altered** the initial description and your code sample! You were mentioning aspect ratio at first, now you mention FOV only. I've augmented your code with the scenery from the tutorial, to see it in action:

```
        self.scene = self.loader.loadModel("models/environment")
        self.scene.reparentTo(self.render)
        self.scene.setScale(0.25, 0.25, 0.25)
        self.scene.setPos(-8, 42, 0)
```


On Windows, there is no visible change in FOV. Something can be observed in macOS with your code, but this is due to the `window-event` from `ShowBase` being triggered around the creation of the window on Windows (but later on macOS).

It looks like your calculation is wrong: Change to `w=32` in your new/current code sample to match to the default window-size of 800x600.

**Comment by asmsulaiman** [comment]
Hi, sorry for the delayed response. I have switched to Windows now, and this problem no longer occurs. @rdb, I think this sounds like the solution I needed at the time.
