### ISSUE TITLE
bind_thread cannot be used on win32 debug (asserts enabled) code

### ISSUE THREAD

**Issue by johnnyapol** [panda3d/panda3d#1575]
## Description

`AssertionError: thread != nullptr at line 67 of panda3d\panda\src\pipeline\threadWin32Impl.cxx` when using bind_thread on Windows on 1.11 dev builds.

Looking at the source of bind_thread, I see a call to get_current_thread()

```
PT(Thread) Thread::
bind_thread(const std::string &name, const std::string &sync_name) {
  Thread *current_thread = get_current_thread();
  if (current_thread != get_external_thread()) {
    // This thread already has an associated thread.
    nassertr(current_thread->get_name() == name &&
             current_thread->get_sync_name() == sync_name, current_thread);
    return current_thread;
  }

  PT(Thread) thread = new ExternalThread(name, sync_name);
  ThreadImpl::bind_thread(thread);
  return thread;
}
```

```
/**
 *
 */
Thread *ThreadWin32Impl::
get_current_thread() {
  Thread *thread = _current_thread;
  return (thread != nullptr) ? thread : init_current_thread();
}
```

Since _current_thread is a TLS variable it's going to be nullptr in the case of a new thread,  so we go down to init_current_thread()
```
/**
 * Called by get_current_thread() if the current thread pointer is null; checks
 * whether it might be the main thread.
 * Note that adding noinline speeds up this call *significantly*, don't remove!
 */
static __declspec(noinline) Thread *
init_current_thread() {
  Thread *thread = _current_thread;
  if (!_main_thread_known.test_and_set(std::memory_order_relaxed)) {
    // Assume that we must be in the main thread, since this method must be
    // called before the first thread is spawned.
    thread = Thread::get_main_thread();
    _current_thread = thread;
  }
  // If this assertion triggers, you are making Panda calls from a thread
  // that has not first been registered using Thread::bind_thread().
  nassertr(thread != nullptr, nullptr);
  return thread;
}
```
And we'll be unable to avoid the nassertr there since the thread does not exist yet.

As a potential fix that keeps the assert in place, I think bind_thread can just be written as:

```
PT(Thread) Thread::
bind_thread(const std::string &name, const std::string &sync_name) {
  Thread *currentThread = _current_thread;
  if ((current_thread != nullptr) && (current_thread != get_external_thread())) {
    // This thread already has an associated thread.
    nassertr(current_thread->get_name() == name &&
             current_thread->get_sync_name() == sync_name, current_thread);
    return current_thread;
  }

  PT(Thread) thread = new ExternalThread(name, sync_name);
  ThreadImpl::bind_thread(thread);
  return thread;
}
```
where we just use the TLS variable directly instead of going through the getter.

## Steps to Reproduce
Call bind_thread in a python-created thread using the native python threading facilities.

## Environment
 * Operating system: Windows
 * System architecture: x86 + x86_64
 * Panda3D version: 1.11 master
 * Installation method: (eg. pip, wheel, SDK, built from source): pip and source builds
 * Python version (if using Python): 3.8
 * Compiler (if using C++):

**Comment by rdb** [comment]
The Thread class shouldn't really access the TLS value directly, that's in ThreadImpl. I thought about the cleanest way to fix this, ultimately I decided on having `ThreadImpl::bind_thread()` do nothing if there is already a thread associated and return the current thread instead.
