### ISSUE TITLE
Split off Maya and 3ds Max exporters to separate packages

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#1584]
At the moment, public builds of the Panda3D SDK contain tools for 3ds Max and Autodesk Maya, which rely on proprietary SDKs that may not be distributed publicly.  This requires us to build the public SDK on a private buildbot that is run on machines that CMU hosts for us, rather than something like GitHub Actions that can be performed publicly.

This is a significant constraint on our release automation process.  It is difficult to involve others, who need to be given access to private machines, and who need to be aware of how they are managed.  It is also not done out in the open, so even though the [buildbot configuration](https://github.com/panda3d/buildbot-panda3d/) is public, there is little verifiability.  Furthermore, our buildbot infrastructure needs to be maintained, and this can only be done properly with access to the infrastructure.  Ideally, I'd move the release infrastructure to GitHub Actions, where everyone can see and help maintain it, but this is not possible.  (Even self-hosted Actions runners are coupled with too many security issues that make this option a no-go.)

This is why I would propose that we stop building the public SDK with Maya and 3ds Max tools included.  Instead, we make this available as a separate add-on package, similar to how you need a separate plug-in for Blender conversion.  This allows us to significantly reduce the complexity of Panda3D release maintenance.

**This should _not_ be seen as a suggestion to deprecate the Maya or 3ds Max tools.**  That is not the intention here.  We would still provide these exporters and treat these tools as fully supported, making new builds where necessary.  However, these tools do not need to follow the same update schedule as the rest of Panda3D; they are updated only rather infrequently.  That means it's also okay if the build process is more manual.  It also needs to happen for fewer platforms, since we do not have Maya conversion tools for Linux.

Other benefits are a significant size reduction of the download (many users do not need these tools--especially when building for release) and that we can make the default distribution consist entirely of open-source software.

**Comment by serkkz** [comment]
In general, the idea is good, but more needs to be done to complete it. I think we need to separate the SDK tools and the Panda3D core. The final idea should be a separate repository with all the tools.

**Comment by ArsThaumaturgis** [comment]
I think that so separating out the Maya and Max exporters sounds like a good idea!

> I think we need to separate the SDK tools and the Panda3D core. The final idea should be a separate repository with all the tools.

While tempting, this would complicate things for pretty much all new Panda devs. It's more convenient to have at least the basic tools be included with the SDK, I feel.

**Comment by serkkz** [comment]
Actually, I don't mean to abandon binary tool builds. Often, such tools with releases do not change from release to release of Panda3D. For example, tools such as "egg" practically remain unchanged from release to release, it is strange to store the code in a shared repository and build them every time. I am almost sure that they can be built once and left alone until a certain point, until it is actually needed for binary compatibility or making changes to the format.

**Comment by kamgha** [comment]
@serkkz The scope of this issue is to disable those proprietary thirdparty components, in a way that a SDK configuration can be built in public.

> I think we need to separate the SDK tools and the Panda3D core. The final idea should be a separate repository with all the tools.

It already is separated into the `pandatool` tree. It wouldn't really be a game engine SDK anymore if you remove all importers.  I think what you are requesting is a build for your game runtime that is tailored to your needs.  Since only you know what you need, you'd do that with CMake or makepanda, e. g. debug level 4, disable all components you don't need, custom ConfigRC encryption key, ...


> it is strange to store the code in a shared repository and build them every time

I don't think this is an issue nowadays, the tree builds in seconds or a few minutes.  On the other hand, you can disable building metalibs, so you have an even more fine granular build of the components and less to compile/link on changes.

**Comment by serkkz** [comment]
Personally, this is not a problem for me. I can actually configure the build configuration for myself, but on the other hand, we have instructions on how to build a panda... Oh SDK, every new user is practicing building a panda with a bunch of junk...

https://github.com/panda3d/panda3d#building-panda3d

What is misleading at the moment is to build a panda or SDK...

**Comment by kamgha** [comment]
> What is misleading at the moment is to build a panda or SDK...

This is almost off-topic here, in short:
SDK = maximum features enabled (incl. tools, profiling & debug features for game development)
Runtime = optimized, with minimum features enabled needed to run your individual game

Books about game engine architectures should cover this.

Your game will work of course when distributing with the SDK binaries. Back to topic: The website offers a SDK build, aimed at beginners and for quick start. Until a beginner has finished developing their game, they'll likely have figured this aspect out (or have someone on their team that is keen with this), or they'll just continue using the SDK binaries.

**Comment by Wizzerinus** [comment]
Pretty sure the 3dsmax tool for example is considered obsolete anyway and not really needed for development even

**Comment by rdb** [comment]
First step has been made, the Maya source is here:
https://github.com/panda3d/maya-egg
Next step is to remove it from the Panda3D codebase.

And then do the same with the 3ds Max tools.

**Comment by rdb** [comment]
Maya and 3ds Max plug-ins have been removed.
Max now lives here:
https://github.com/panda3d/max-egg-plugin

However, it appears we haven't built with 3ds Max since 3ds Max 2014 and never for 64-bit Windows, so I guess we can conclude that it is already dead.  I'm therefore not going to put in effort to revive it and add CMake build files.  If someone wants to revive it, be my guest.
