### ISSUE TITLE
man pages installed from .deb package have the wrong permissions

### ISSUE THREAD

**Issue by kjcole** [panda3d/panda3d#159]
The package `panda3d1.9` installed from

```
deb http://archive.panda3d.org/ubuntu xenial main
```

sets the permission of the man pages to 600. This prevents normal users from accessing the pages and also prevents `mandb` from updating the manual page index caches.

Simple fix (while waiting for the package to be changed):

```
for i in $(dpkg -L panda3d1.9 | grep "/usr/share/man/man1/")
do
  sudo chmod +r $i
done
```

**Comment by rdb** [comment]
I've just built a `1.9.4+post3` version with fixed permissions for the include and man directories and published it on the package archive as well as the 1.9.4 download page.
