### ISSUE TITLE
Direction option for OnscreenText does not appear to do anything

### ISSUE THREAD

**Issue by Augustifolia** [panda3d/panda3d#1591]
## Description

Changing the value of the direction option for OnscreenText does not appear to do anything. I am guessing it is supposed to specify if the text goes from right to left or left to right. But it always appears to go from left to right.

## Steps to Reproduce

```
from direct.showbase.ShowBase import ShowBase
from direct.gui.DirectGui import OnscreenText

ShowBase()
OnscreenText(text="text", direction="rtl")
# the allowed options for direction is "rtl" and "ltr". Neither appears to change anything.

base.run()
```

## Environment
 * Operating system: Linux Mint
 * System architecture: x86_64
 * Panda3D version:  1.10.14
 * Installation method: pip
 * Python version (if using Python): 3.12
 * Compiler (if using C++):

**Comment by Augustifolia** [comment]
As rdb wrote on discord, the direction setting requires harfbuzz to be enabled.

By adding this to the example it works:
```
from panda3d.core import loadPrcFileData
loadPrcFileData(
    "",
    """
    text-use-harfbuzz #t
    """)
```

Perhaps this should be enabled by default? Otherwise it would be nice if the manual would mention that enabling harfbuzz is required for direction to work.

**Comment by rdb** [comment]
Implemented explicit direction setting without Harfbuzz (no automatic bidi detection is implemented) and also enabled Harfbuzz by default, if support is compiled in.
