### ISSUE TITLE
Buffer texture causes glgsg crash when using immutable texture storage mode

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#1602]
## Description

Using latest master commit, https://github.com/panda3d/panda3d/commit/9517ffb320fbd30f401e1550c6413a25f355e273, the glgsg throws an Assertion error when a buffer texture is used by a shader and the texture storage mode is set to immutable.

## Steps to Reproduce

```python
from array import array
from direct.showbase.ShowBase import ShowBase
from panda3d.core import CardMaker, GeomEnums, NodePath, Shader, Texture
from panda3d.core import load_prc_file_data


load_prc_file_data("", "gl-immutable-texture-storage true")


def shader():
    return Shader.make(Shader.SL_GLSL,
                       vertex="""

#version 460

in vec4 p3d_Vertex;

uniform mat4 p3d_ModelViewProjectionMatrix;
uniform mat4 p3d_ModelMatrix;
uniform samplerBuffer instances_offset;

void main()
{
    vec4 offset_data = texelFetch(instances_offset, 0);
    gl_Position = p3d_ModelViewProjectionMatrix * (p3d_Vertex * offset_data.x);
}
""",
                       fragment="""
#version 460

out vec4 color;

void main()
{
    color = vec4(1, 1, 1, 1);
}
""")

base = ShowBase()

cm = CardMaker('card')
card: NodePath = base.render.attach_new_node(cm.generate())
card.setPos(-0.5, 3, -0.5)
card.set_shader(shader())

texture = Texture()
texture.setup_buffer_texture(1, Texture.T_float, Texture.F_rgba32, GeomEnums.UH_static)
data = array("f", [1.0, 2.0, 3.0, 4.0])
texture.set_ram_image(data.tobytes())
card.set_shader_input("instances_offset", texture)

base.run()
```

The output is :

<pre>
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Assertion failed: !gtc->_immutable at line 14584 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx
:display:gsg:glgsg(error): Could not load 
Traceback (most recent call last):
  File "/usr/share/panda3d/direct/showbase/ShowBase.py", line 2250, in __igLoop
    self.graphicsEngine.renderFrame()
AssertionError: !gtc->_immutable at line 14584 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx
:task(error): Exception occurred in PythonTask igLoop
Traceback (most recent call last):
  File "tests/test_load_array.py", line 50, in <module>
    base.run()
  File "/usr/share/panda3d/direct/showbase/ShowBase.py", line 3440, in run
    self.taskMgr.run()
  File "/usr/share/panda3d/direct/task/Task.py", line 630, in run
    self.step()
  File "/usr/share/panda3d/direct/task/Task.py", line 579, in step
    self.mgr.poll()
  File "/usr/share/panda3d/direct/showbase/ShowBase.py", line 2250, in __igLoop
    self.graphicsEngine.renderFrame()
AssertionError: !gtc->_immutable at line 14584 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx
</pre>

## Environment
 * Operating system: Ubuntu
 * System architecture: x86_64
 * Panda3D version: master 9517ffb320fbd30f401e1550c6413a25f355e273
 * Installation method: Built from source
 * Python version (if using Python): 3.8
 * Compiler (if using C++): N/A

**Comment by rdb** [comment]
Probably a regression in 07f9f9d89722a82234e0d111e61b7ff98e88e2db.

We don't support immutable buffer storage yet, so this flag should never be set for buffer textures.
