### ISSUE TITLE
setTime does not work on MacOS when a sound is loaded as a sample into RAM

### ISSUE THREAD

**Issue by gabeklavans** [panda3d/panda3d#1607]
## Description
I'm trying to seek to a position in a ogg file before playing it, using `setTime`. I also would like to load the sound into RAM instead of streaming it from disk.

On my Windows machine, this works as expected. However, on my Mac-Mini, `setTime` doesn't do anything specifically when the audio is loaded into RAM instead of streaming from disk.

In my [example project](https://github.com/gabeklavans/p3d-settime-bug) for this bug, I have uploaded an ogg file of me counting roughly once a second. If you run it on MacOS, you will hear that the audio starts from the beginning, no matter what you input into `setTime`. If you comment out the line setting the `audio-preload-threshold` config variable, you'll notice the file is loaded as a stream, and `setTime` works properly. None of this happens on Windows, and `setTime` always sets the proper time.

## Steps to Reproduce
- Checkout [this repo](https://github.com/gabeklavans/p3d-settime-bug)
- Install latest panda3d with `pip install panda3d`
- Run the main file with `python3 main.py`

## Environment
 * Operating system: MacOS Sonoma 14.2.1
 * System architecture: Apple M1 (arm)
 * Panda3D version: 1.10.14 (I also tried on the last 1.10.13xxx)
 * Installation method: pip
 * Python version (if using Python): 3.11.6
 * Compiler (if using C++): N/A

**Comment by gabeklavans** [comment]
I believe I've identified the problem to be with the Apple OpenAL framework. For whatever reason, I believe the framework that comes with my macOS version (arm 14.x.y) does not support setting the `AL_SEC_OFFSET` value via `alSourcef`. When I link openal-soft 1.23.1, installed via homebrew, using the `--openal-{inc,lib}dir` flags with makepanda.py, then `setTime` works as expected. I think it may be time to start including openal builds in the prebuilt thirdparty download, given https://github.com/panda3d/panda3d/issues/1613

**Comment by rdb** [comment]
I was going to say that we should try to fix this given that considerable effort has been put into making the OpenAL framework work, but if it is deprecated anyway, I suggest we don't fix this and simply go with openal-soft.

**Comment by rdb** [comment]
It looks like `alSourcePlay` is resetting the offset.  Specifying the AL_SEC_OFFSET after this call fixes the problem.  I will apply this as a short-term solution, and we can switch to openal-soft for 1.11.
