### ISSUE TITLE
how to use LerpFunctionInterval and functools.partial not working

### ISSUE THREAD

**Issue by BMaxV** [panda3d/panda3d#1623]
## Description

https://docs.panda3d.org/1.10/python/reference/direct.interval.LerpInterval#direct.interval.LerpInterval.LerpFunctionInterval

It's a bit unclear how to use this function, but it's also not working correctly.

The expected behavior is this:

 * I provide a function
 * I set the lerp to start
 * panda will lerp over the value and change the value as specified by the function
 * the unclear part is how the function gets access to the object to change it's properties
 * as part of that, it is unclear from the docs how `function` needs to be defined to do this.
 
One solution was identified on discord and confirmed as working is this:

```
def my_custom_function(self,value):
    # something
    self.value = value

m = MyPandaObject()
MyPandaObject.my_custom_function = my_custom_function # assign the function to the *class* not the instance
my_lerp = LerpFunctionInterval(m.my_custom_function,2,15,30) # instance now has the function as a method
my_lerp .start()
```
E.g. I used it to change the framesize of a DirectFrame like this:

```
def lerpmyframesize(self,x_val):
    self["frameSize"] = (-x_val, x_val ,-0.05, 0.05)
DirectFrame.lerpmyframesize = lerpmyframesize
my_lerp = LerpFunctionInterval(F.lerpmyframesize, 0.2, 0, 0.4)
my_lerp.start()
```

-------------------

The bugged behavior is this: It was also suggested that `functools.partial` should work, but it produces this error message:

```
  File "/home/myuser/.local/lib/python3.10/site-packages/direct/interval/LerpInterval.py", line 845, in __init__
    (function.__name__,
AttributeError: 'functools.partial' object has no attribute '__name__'. Did you mean: '__ne__'?
```

there was conversation around this here:

https://discord.com/channels/524691714909274162/1057767450843824198/1213462368093208698

## Steps to Reproduce
run this:
```
import functools
from direct.showbase.ShowBase import ShowBase
from direct.interval.LerpInterval import LerpFunctionInterval

def testf(test_string, value):
    # hello should be set as static by functools, val should change and be printed to console
    print(test_string, value)


class Wrapper:
    def __init__(self):
        self.b = ShowBase()

        # this part fixes the test_string
        my_partial = functools.partial(testf, "hello")
        my_lerp = LerpFunctionInterval(my_partial, 2, 0, 1)
        my_lerp.start()


def main():
    W = Wrapper()
    while True:
        W.b.taskMgr.step()


if __name__ == "__main__":
    main()
```

## Environment
 * Operating system: linux/ubuntu
 * System architecture: -
 * Panda3D version: 1.11.0.dev3233
 * Installation method: ?
 * Python version (if using Python): Python 3.10.12 (main, Nov 20 2023, 15:14:05)
 * Compiler (if using C++): -

**Comment by rdb** [comment]
Will fix, but you you can work around this by passing a custom name to LerpInterval, ie. `name="my interval"`

**Comment by rdb** [comment]
A lambda would have also worked, by the way, as a more elegant way to do this:
```python
my_partial = lambda value: testf("hello", value)
```
