### ISSUE TITLE
font.setPixelsPerUnit crashes when values get too high

### ISSUE THREAD

**Issue by BMaxV** [panda3d/panda3d#1626]
## Description

If a value somewhere higher than 200 gets specified, panda crashes without error trace.

## Steps to Reproduce
```
from direct.showbase import ShowBase
from direct.gui.DirectGui import DGG
from panda3d.core import TextNode

class Wrapper:
	def __init__(self):
		
		
		self.b = ShowBase.ShowBase()
		tl = TextNode("name")
		font = tl.getFont()
		font.setPixelsPerUnit(500)# 200 works
		
		mytext="Hello There"
		tl.set_text(mytext)
		
		textNodePath = aspect2d.attachNewNode(tl)
		textNodePath.setPos((0.1,0,-0.1))
		textNodePath.setScale(1)
		
		
def main():
	W = Wrapper()
	while True:
		W.b.taskMgr.step()
		dt = W.b.clock.dt

if __name__=="__main__":
	main()
```

## Environment
 * Operating system: Windows 10
 * System architecture: 64
 * Panda3D version: 1.10.13
 * Installation method: sdk
 * Python version (if using Python): 3.8.2
 * Compiler (if using C++):

**Comment by rdb** [comment]
I think the problem is that your characters are too large to fit into a single page of the atlas, you should increase the values of `text-page-size` so that it fits.

Panda should be issuing an error message or a warning and resize the page for you, I think.

**Comment by BMaxV** [comment]
I agree that it should do that, but it doesn't do it right now.

**Comment by rdb** [comment]
Yes, I will add an error message, and just make the text render as boxes instead of crashing.

In the meantime, call `font.setPageSize(1024, 1024)`.
