### ISSUE TITLE
unclear error with possibly non BMP character 

### ISSUE THREAD

**Issue by BMaxV** [panda3d/panda3d#1629]
## Description
cuneiform, e.g. 𒀙 is cool and I would like to use it in panda. Unfortunately, something with the font loading or rendering or something else goes wrong, so that even a font that should support it, doesn't display the symbol correctly.

So the code below should display "hello [2x strange box for missing character] world" instead of "hello 𒀙 world"

Needs a font to display the symbol, to be loaded, I used this one:
https://fonts.google.com/noto/specimen/Noto+Sans+Cuneiform

## Steps to Reproduce
```
from direct.showbase import ShowBase
from panda3d.core import TextNode


class Wrapper:
	def __init__(self):
		
		self.b = ShowBase.ShowBase()
		tl = TextNode("name")
		position=(0,0,0)
		
		font=self.b.loader.loadFont('NotoSansCuneiform-Regular.ttf')
		font.setPixelsPerUnit(150)
		
		tl.setFont(font)
		font = tl.getFont()
		font.clear()
		
		tl.set_text("hello 𒀙 there ")
				
		textNodePath = aspect2d.attachNewNode(tl)
		textNodePath.setScale(0.05)
		textNodePath.setPos(position)

def main():
	W = Wrapper()
	while True:
		W.b.taskMgr.step()

if __name__=="__main__":
	main()
```

## Environment
 * Operating system: Windows 10
 * System architecture: 64
 * Panda3D version: 1.10.13
 * Installation method: sdk
 * Python version (if using Python): 3.8.2
 * Compiler (if using C++):

**Comment by rdb** [comment]
This renders fine for me on macOS:
<img width="135" alt="image" src="https://github.com/panda3d/panda3d/assets/194842/a5569e42-98de-4885-9cc6-e148ec7b2f6c">
Going to assume this is a Windows-specific bug

**Comment by BMaxV** [comment]
I can confirm this works out of the box with linux as well. Didn't even need to install the font.

**Comment by rdb** [comment]
Surrogate pairs weren't handled on platforms with UTF-16 in wchar_t, that is to say, Windows.

Try this build: http://buildbot.panda3d.org/downloads/5da013e2e9a991c993532cc6886c53e4c38bccc0/
