### ISSUE TITLE
direct.stdpy.threading Threads stay alive

### ISSUE THREAD

**Issue by kamgha** [panda3d/panda3d#164]
Threads created by `from direct.stdpy import threading` don't terminate once the `run()`-Method reaches its end. Replacing that with `import threading` or `from direct.stdpy import threading2 as threading` shows the expected behaviour.

Sample program:

```
from direct.showbase.ShowBase import ShowBase

#import threading
from direct.stdpy import threading
#from direct.stdpy import threading2 as threading

import panda3d.core
from tkinter import Button


class TestWindow:

    def __init__(self):
        base.startTk()
        Button(base.tkRoot, text='Click me', command=self.run_thread).pack()
        Button(base.tkRoot, text='Show num', command=self.show_num).pack()

    def run_thread(self):
        thread = TestThread()
        thread.start()
        # thread.join()     # uncomment this
        print(len(threading.enumerate()))

    def show_num(self):
        print(len(threading.enumerate()))


class TestThread(threading.Thread):

    def __init__(self):
        threading.Thread.__init__(self)

    def run(self):
        a = panda3d.core.PNMImage(8192, 8192)
        a.addAlpha()
        a.fill(0.5)

        print('End run()-Method of TestThread')


class Main:
    def __init__(self):

        base = ShowBase(windowType='none')

        TestWindow()
        base.run()


if __name__ == '__main__':
    Main()
```

Observation:
The current number of active threads can be printed out by `print(len(threading.enumerate()))`. Every time a thread is started, this number increases by 1 and should decrease, once the thread finished. Pythons `threading`-Module and the `threading2`-Module show the expected behaviour.

`.join()`-ing the Thread causes it to terminate, the counter will decrease.

Tested on Windows 7 64bit, Python 3.6.2 and a custom compiled Panda3D (current git master).

---
Here is a simple sample, not involving ShowBase and tkinter. Uncomment the import-statements at the top to switch through the `threading`-modules:

```
#import threading
from direct.stdpy import threading
#from direct.stdpy import threading2 as threading

import time


class TestThread(threading.Thread):

    def __init__(self):
        threading.Thread.__init__(self)

    def run(self):
        print('End run()-Method of TestThread')


if __name__ == '__main__':
    thread = TestThread()
    thread.start()
    # thread.join()     # uncomment this
    print(len(threading.enumerate()))

    time.sleep(5)
    print(len(threading.enumerate()))
```

**Comment by rdb** [comment]
Thanks for reporting.  The reason why they showed up in `enumerate()` (and `active_count()`) was that `is_alive()` erroneously still reported `True` even after the thread had run.  I also suspect there was a circular reference preventing the thread from being properly destructed.

This is now fixed.

**Comment by kamgha** [comment]
Thanks for the improvement. Unfortunately, Python will raise an exception for each Thread that has been in existence upon program termination (with the ```direct.stdpy.threading``` module). The output of the second code-sample from above looks like this:

```
2
End run()-Method of TestThread
1
Exception ignored in: <bound method Thread.__del__ of <__main__.TestThread object at 0x0000000001ED22E8>>
Traceback (most recent call last):
  File "C:\panda3d\direct\stdpy\threading.py", line 120, in __del__
  File "C:\panda3d\direct\stdpy\thread.py", line 226, in _remove_thread_id
TypeError: 'NoneType' object is not subscriptable
 
Process finished with exit code 0
```

Although `threading.active_count()` will report the expected number, this looks like the Thread or some leftover is still residing somewhere.

**Comment by rdb** [comment]
Hmm, it seems to be a weird implementation detail in older Python versions that cause some globals to set to None upon destruction:
https://stackoverflow.com/a/25649713/2135754

I'll check in a change that simply checks whether the globals that function uses are None.

**Comment by kamgha** [comment]
There is still a memory leak with the `direct.stdpy.threading`-module. Pythons `threading`-module and `direct.stdpy.threading2` do not show this behaviour. The following code will demonstrate it:

```
#import threading
from direct.stdpy import threading
#from direct.stdpy import threading2 as threading


class TestThread(threading.Thread):

    def __init__(self):
        threading.Thread.__init__(self)

    def run(self):
        pass


if __name__ == '__main__':
    input('Press enter to begin')

    for i in range(1000000):
        TestThread().start()
        #a = TestThread()
        #a.start()
        #a.join()

    # This will make sure, that we don't proceed after the last Thread has run
    thread = TestThread()
    thread.start()
    thread.join()
    print(threading.active_count())

    input('Press enter to shutdown the interpreter')
```

I guess (but don't know!) `obj = None` (like `self.__thread = None`) may be problematic, since a reference will be left over and can never be garbage collected. Wouldn't `del obj` be better, instead? The Thread should be removed from memory once it has finished and no reference to it exists anymore/no variable points to it anymore. I think it's a bit scary that a clean up will take place once the interpreter shuts down, not before.

The code will create 1.000.000 threads and you can observe that its memory usage will grow (a bit over 1.6GB). Once the interpreter shutdown is initiated, you can watch how the memory will be freed over a period of a few seconds until the process ends. Switching over to Pythons `threading` or to `direct.stdpy.threading2` will result in a constant memory usage (about 5 - 15MB), no pile up.

**Comment by rdb** [comment]
OK, my last fix wasn't thorough enough (I had tried to keep it minimal).  Thanks for the helpful test case.  I am checking in a fix that should address these issues right now.

For what it's worth, `del obj` and `obj = None` are functionally identical.  Both destroy the reference to whatever object `obj` references.
