### ISSUE TITLE
PStats: Scrubbing Through Flame-Charts

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#1658]
## Description
I've been using the new version of PStats, and I really really like it! ^_^

Of the things that I so like, two are relevant to this feature-request:

First is the flame-chart view, which I find really illustrates well how the components of a frame relate to each other, and how they change over time.

And second, is the fact that one can examine a session after the program has exited, allowing for analysis after-the-fact.

To that latter end, it looks to me like it could be very helpful to be able to scrub back and forth in a session’s history while within a flame-chart.

Now, I see the timeline view–but I’m having a little trouble orienting myself there, especially as I end up zooming out in order to move at a reasonable pace, which makes it difficult to see what the flame charts are doing.

What I really find myself wanting is to watch the flame-chart “animate” as it does when live, but rather than in response to the passage of time, doing so in response to my adjusting a slider at the bottom, or some such.

## Use Case
The one that prompted this thought in me, as I recall, was a situation in which the major components of a frame changed over time. One set of elements would predominate, then be replaced by another.

While this was happening live, it was hard to catch what was going on. I suppose that I could have paused the output--but I didn't think of it. Further, that doesn't help much with comparing and contrasting different parts of the run.

But going to the timeline, I found it hard to tell which parts were which: When zoomed out enough for (mouse-)navigation, the flame-charts all looked rather similar; when zoomed in enough to distinguish the charts, (mouse-)navigation was too slow. On top of that, there were gaps between charts (from dropped frames, I gather), and seeing the charts side-by-side made the changes over time less clear to me than seeing them animate one frame to the next.

What _would_, I think, work would be to show the flame-chart as usual, and to then allow the user to scrub back and forth--I'm imagining a timeline-slider at the bottom--loading frames to the chart in-place. This should allow quick navigation regardless of zoom-level (although perhaps the slider could be zoomed independently), and the animation thus produced should, I think, be easier (for me) to parse.

**Comment by rdb** [comment]
Yes, I ran into this recently.  I wanted to look at the flame graph for a moment where the frame rate was slow, but I was too late and the moment had passed.  It would be great to be able to go back in time.

I think the ideal would be something like this, where you can set the range of the moving average:
![](https://raw.githubusercontent.com/lizashkod/react-time-range-slider/HEAD/demo.gif)

However, I'm probably not likely to implement that any time soon, it'd be a fair amount of work and there's too much for me to do to get distracted by this.  Maybe we can come up with an easier, low-effort way to achieve this?  Maybe we could have a way to just right-click in the Timeline view and "open flame graph for frame #n", which opens the flame graph positioned at a certain frame?

**Comment by ArsThaumaturgis** [comment]
>  It would be great to be able to go back in time.

Ah, that would be amazing--oh, wait, you mean in the Flame Graph. Yes, that too. :P

> I think the ideal would be something like this, where you can set the range of the moving average ...

Indeed, that could be very useful, I daresay!

> However, I'm probably not likely to implement that any time soon, it'd be a fair amount of work and there's too much for me to do to get distracted by this. 

This is fair! I do daresay that you have rather more pressing matters to attend to!

> Maybe we could have a way to just right-click in the Timeline view and "open flame graph for frame #n", which opens the flame graph positioned at a certain frame?

That seems like it would work well, too, indeed!

Hmm... Would it be worth building on that to produce a static graph averaging a given time-frame? To keep it relatively simple, maybe specified simply by numeric input-boxes.

**Comment by rdb** [comment]
Implemented this in a very simple manner.  You can now hold the arrow keys or use a horizontal scroll input to scrub through the frames, or press Home / End to go to the first / last frame, respectively.  If you open the flame graph using the context menu on a Timeline bar, it will also open at the corresponding frame.

If there are other low-hanging quality-of-life improvements, feel free to share.

**Comment by ArsThaumaturgis** [comment]
Ah, wonderful, and thank you! Once there's a new build with this change I'll likely grab it! ^_^

As to other quality-of-life improvements, one that seems like it might be useful is the ability to go "up a level" in flame charts.

Let me explain: As things stand, the developer can click on strips within the flame-chart to have the view encompass them and their children. However, there's no way (that I see, at least) to then return to the previous, more-expansive view--short of opening the chart afresh.

So I'd like to suggest perhaps just a button that moves the view up one level (where available), thus allowing the developer to step back to wherever they had previously been.

It's a small thing, but one that might reduce friction in the use of the flame chart a little bit, I feel.

**Comment by ArsThaumaturgis** [comment]
Just confirming that I've tried the new PStats, and that the new changes--including the ability to go back--are working and much appreciated! ^_^

(I didn't see the horizontal scrollbar that you mentioned--but the arrow keys work, so that's a minor thing.)

Thank you very much! ^_^

**Comment by rdb** [comment]
Great!

There's no horizontal scrollbar, I meant the horizontal scroll wheel on the mouse / touch pad.

I also added a shortcut to go back in the flame graph, as you asked - there was one on macOS but I never added a button for that on other platforms. It's Alt+Left, the same as going back in the browser.

It was also already possible to double-click in the background of the graph to go all the way to the root.

**Comment by ArsThaumaturgis** [comment]
> There's no horizontal scrollbar, I meant the horizontal scroll wheel on the mouse / touch pad.

Aah, I see!

Well, as I don't have a horizontal wheel, that much at least I'm not in a position to test.

> I also added a shortcut to go back in the flame graph, as you asked - there was one on macOS but I never added a button for that on other platforms. It's Alt+Left, the same as going back in the browser.

Indeed, I saw that, and it works very well! Thank you so much for it--that feature has been one that I've been wanting when examining active flame charts! ^_^

> It was also already possible to double-click in the background of the graph to go all the way to the root.

Aah, that one I didn't know about!
