### ISSUE TITLE
Implement Khronos' reference PBR tone mapping operator

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#1659]
Khronos released a reference PBR tone mapper that gives decent results without excessive need for tweaking, such as is the case with Filmic tone mappers. It might be a good default for Panda3D.

The current ACES tone mapper is fine, but it looks rather desaturated by default and requires application of custom LUTs in order to get good results.

We can add a parameter to the appropriate CommonFilters method to select the tone mapping operator.

I would be inclined to include this in the next minor release, it seems fairly harmless.

See:
https://www.khronos.org/news/press/khronos-pbr-neutral-tone-mapper-released-for-true-to-life-color-rendering-of-3d-products

Community contribution welcome.

**Comment by raytopianprojects** [comment]
This should be easy to implement once #1643 is merged (I need to finish up my changes though). 

The example GLSL is only 13 lines so super easy to add. https://github.com/KhronosGroup/ToneMapping/blob/main/PBR_Neutral/pbrNeutral.glsl
