### ISSUE TITLE
`Python 3.12.3`: No found distribution for panda3d

### ISSUE THREAD

**Issue by BBBmau** [panda3d/panda3d#1660]
## Description

     
 Despite their being support for Python 3.12 from the latest release, I still am unable to install it on Python 3.12. The error message that I get:
 ```py
 batman ➜ /workspaces/openpilot/tools/sim (pyenv-py3-12) $ pip install panda3d
ERROR: Could not find a version that satisfies the requirement panda3d (from versions: none)
ERROR: No matching distribution found for panda3d
batman ➜ /workspaces/openpilot/tools/sim (pyenv-py3-12) $ python3 --version
Python 3.12.3
batman ➜ /workspaces/openpilot/tools/sim (pyenv-py3-12) $ python --version
Python 3.12.3
```
My guess is that it doesn't support `3.12.3`?

## Steps to Reproduce

Setup up a pyenv using `Python 3.12.3`
`pip install panda3d`
Error is outputted

## Environment
 * Operating system: macosx (running in a ubuntu devcontainer)
 * System architecture: ARM
 * Panda3D version: 1.10.14
 * Installation method: `pip`
 * Python version (if using Python): `3.12.3`
 * Compiler (if using C++):

**Comment by Moguri** [comment]
The `cp312` wheels should work with any 3.12 bug fix release (including 3.12.3). There is an ARM wheel for macOS, but I don't see an ARM wheel available for Linux.

**Comment by rdb** [comment]
Oops, an oversight. It seems that the buildbot didn't update the image properly and the one it had didn't have Python 3.12.

I poked the buildbot and will upload a wheel shortly.

**Comment by rdb** [comment]
I just uploaded an aarch64 wheel for Python 3.12 on Linux, can you try again?

Note that the aarch64 builds don't have Cg/shader generator support in Panda 1.10.
