### ISSUE TITLE
Is this license a BSD one or a different one?

### ISSUE THREAD

**Issue by shyamalschandra** [panda3d/panda3d#1665]
## Environment
 * Operating system: macOS Somona
 * System architecture: Intel
 * Panda3D version: latest from the repo

**Comment by Wizzerinus** [comment]
From README:
> Panda3D is licensed under the Modified BSD License. See the LICENSE file for more details.

"modified" here removes the advertisement clause present in the OG BSD license, so it is "more free" than the OG BSD license.
