### ISSUE TITLE
TextNode 'set_small_caps' does not work on 1.11.0

### ISSUE THREAD

**Issue by Benjamin8693** [panda3d/panda3d#1666]
## Description
The 'set_small_caps' method of TextNode does not work. It does set the 'small_caps' field successfully (evident if you call 'get_small_caps'), but it does not have any visual impact on text once generated. This works as intended on 1.10.14.

Functional example:
![2024-06-18_21-27](https://github.com/panda3d/panda3d/assets/11221724/b8a81fda-1f32-4bcc-b217-cd8865b27701)

Non-functional example:
![2024-06-18_21-28](https://github.com/panda3d/panda3d/assets/11221724/5e766e82-8421-426c-804b-3630b4aeb023)

## Steps to Reproduce

1. Create this file:

```py
from direct.showbase.ShowBase import ShowBase
from panda3d.core import NodePath, TextNode

class Demo(ShowBase):

    def __init__(self):
        ShowBase.__init__(self)

        styling = TextNode('status')
        styling.set_align(TextNode.ACenter)
        styling.set_text_color(1, 1, 1, 1)
        styling.set_shadow(0.075, 0.075)
        styling.set_small_caps(True)
        styling.set_text("Testy McTest!")

        letter = NodePath(styling.generate())
        letter.reparent_to(aspect2d)
        letter.set_scale(0.25)

demo = Demo()
demo.run()
```
2. Run it
3. Note that the lowercase letters have not changed as expected ([see documentation](https://docs.panda3d.org/1.11/python/reference/panda3d.core.TextNode#panda3d.core.TextNode.set_small_caps))

## Environment
 * Operating system: Linux Mint 21.3
 * System architecture: x64
 * Panda3D version: 1.11.0 latest master
 * Installation method: pip
 * Python version (if using Python): 3.10.12
 * Compiler (if using C++): N/A

**Comment by rdb** [comment]
Feel free to look into it, thank you!
