### ISSUE TITLE
Shadows not working propperly since built 1144

### ISSUE THREAD

**Issue by maiklof** [panda3d/panda3d#167]
Hi,
I have some issues when activating shadows after the last updates from the built 1144. They do not work as before. Previously they looked realistic and propperly calculated, while now, it seems like shadows are applied to objects just inside a radius, and actually, quite wrong. I have not changed the code, and installing back the built 1144 everything works fine again. I attach some pictures of a scene with just one cube and a point light (placed where the arrows).
![image](https://user-images.githubusercontent.com/12116367/29956104-0149aba2-8ee5-11e7-8044-64fcf2b8e289.png)
![image](https://user-images.githubusercontent.com/12116367/29956122-190af318-8ee5-11e7-89fb-d5f363bd0b7d.png)
![image](https://user-images.githubusercontent.com/12116367/29956136-2e388f0c-8ee5-11e7-8103-87c6737adc06.png)

**Comment by rdb** [comment]
Would you be willing to share your code with me?

**Comment by maiklof** [comment]
Hi,
This is part of a quite big project (www.simumatik.com). If you cannot reproduce the same I will try to create the equivalent code to reproduce the issue, But basically is a scene with a plane and a cube, ambient light and a point light with shadows activated.
Thanks rdb!

**Comment by rdb** [comment]
No need, I think I managed to reproduce it.  I'm on it.

**Comment by rdb** [comment]
Thanks for the report!  I believe I've checked in a fix.  Let me know if you still have trouble.

**Comment by maiklof** [comment]
Hi, It works fine now!
Thanks,
Mikel

Den 4 sep. 2017 1:05 em skrev "rdb" <notifications@github.com>:
