### ISSUE TITLE
Unreliable collision information for spheres

### ISSUE THREAD

**Issue by WMOkiishi** [panda3d/panda3d#1673]
## Description
When colliding with a cube, a collision sphere will be reported as having collided from the side, even if it's closer to the top. A collision capsule, on the other hand, is always reported as colliding with the closest side. Setting `CollisionTraverser.respect_prev_transform = True` and having the sphere actually collide form the top does not change this. I would expect the sphere to have identical behavior to a capsule with `respect_prev_transform` disabled and "better" behavior with it enabled (since only spheres use this flag at the moment).

## Steps to Reproduce
Using a `CollisionHandlerPusher` to push both a sphere and a capsule colliding identically with boxes shows that their reported collisions are drastically different.
```python
import panda3d.core as p3d
from direct.showbase.ShowBase import ShowBase

base = ShowBase()

box_node_1 = p3d.CollisionNode('box_1')
box_node_1.add_solid(p3d.CollisionBox((-1, -1, -1), (1, 1, 1)))
box_path_1 = base.render.attach_new_node(box_node_1)
box_path_1.set_pos(0, -2, 0)
box_path_1.show()

box_node_2 = p3d.CollisionNode('box_2')
box_node_2.add_solid(p3d.CollisionBox((-1, -1, -1), (1, 1, 1)))
box_path_2 = base.render.attach_new_node(box_node_2)
box_path_2.set_pos(0, 2, 0)
box_path_2.show()

sphere_node = p3d.CollisionNode('sphere')
sphere_node.add_solid(p3d.CollisionSphere((0, 0, 0), 1))
sphere_path = base.render.attach_new_node(sphere_node)
sphere_path.set_pos(0, -2.1, 1.25)
sphere_path.set_prev_transform(p3d.TransformState.make_pos((0, -2.1, 2)))
sphere_path.show()

capsule_node = p3d.CollisionNode('capsule')
capsule_node.add_solid(p3d.CollisionCapsule((0, 0, 0), (0, 0, 0), 1))
capsule_path = base.render.attach_new_node(capsule_node)
capsule_path.set_pos(0, 2.1, 1.25)
capsule_path.set_prev_transform(p3d.TransformState.make_pos((0, 2.1, 2)))
capsule_path.show()

traverser = p3d.CollisionTraverser()
handler = p3d.CollisionHandlerPusher()
handler.add_collider(sphere_path, sphere_path)
handler.add_collider(capsule_path, capsule_path)
traverser.add_collider(sphere_path, handler)
traverser.add_collider(capsule_path, handler)
traverser.respect_prev_transform = True
base.cTrav = traverser

base.cam.set_pos(12, 0, 1)
base.cam.look_at(0, 0, 0)

base.run()
```

## Environment
 * Operating system: Windows 10
 * System architecture: x64
 * Panda3D version: 1.10.14
 * Installation method: pip
 * Python version (if using Python): 3.12.1

**Comment by WMOkiishi** [comment]
It appears that the only collision tests that actually check the `respect_prev_transform` flag are box-into-polygon and capsule-into-polygon, which explains why enabling that flag doesn't have any affect in this scenario. The sphere-into-box test checks the transform delta regardless, though, so I'd still expect different behavior than what happens in practice.

**Comment by WMOkiishi** [comment]
It looks like the issue might be that the sphere is colliding with two of the box's faces, and only the first one found is reported. I would suggest instead testing all faces and reporting whichever happens earliest, since collision time is also calculated for this test. This could perhaps be gated behind the `respect_prev_transform` flag for optimization purposes.

**Comment by rdb** [comment]
sphere-into-box does check the respect_prev_transform flag (by checking if the wrt prev space is different from the prev space).

I think it ought to check which side it has penetrated the least.

I gave it a go but I'm struggling with the current box code. I think it's too risky for 1.10.15. I would rather just rewrite the test for 1.11 based on the capsule or the box-into-sphere test, which I rewrote recently based on Arvo's algorithm and computationally much, much simpler.

**Comment by rdb** [comment]
I rewrote the sphere-into-box test from scratch and it seems to be quite reliable now. It should be faster too, in the normal case. In the respect-prev-transform case, it performs a capsule-into-box test that handles all the edge cases.

Let me know if you still encounter issues.

**Comment by WMOkiishi** [comment]
It does seem to work as expected now. I do still think that the ability to detect which face collides *first* would be useful, but that's an issue of its own.
