### ISSUE TITLE
Debugging code inside a task often crashes the program

### ISSUE THREAD

**Issue by Souzooka** [panda3d/panda3d#1680]
## Description
Using the extension Python Debugger in Visual Studio Code, debugging code running in a Python Task is likely to crash the program with the AssertionError `AssertionError: _function != nullptr at line 589 of panda/src/event/pythonTask.cxx`. While this is likely to happen, the crash does not consistently happen, suggesting the presence of some sort of race condition.

## Steps to Reproduce
Using Visual Studio Code and the Python Debugger extension (which can be installed/managed using the Ctrl+Shift+X hotkey), the following code can be run using the "Python Debugger: Python File" run and debug command:

```py
from direct.showbase.ShowBase import ShowBase
from direct.task.TaskManagerGlobal import taskMgr, Task

class GameBase(ShowBase):
    def run(self):
        taskMgr.doMethodLater(1.0, self.update, "update_task")
        super().run()

    def update(self, task):
        print("Hello World")
        return Task.again

game = GameBase()
game.run()
```

By placing a breakpoint on a line in update (ex: `print("Hello World")`) and pressing F5 to continue whenever the program pauses, the program will likely crash within 1-20 continues with either the AssertionError above, or just completely silently. This error is far more likely to happen with more complicated code than the provided snippet, making debugging an actual project impossible.

## Environment
 * Operating system: Windows 10 Professional
 * System architecture: x86 Intel 9th gen
 * Panda3D version: 1.11.0.dev3444
 * Installation method: pip
 * Python version (if using Python): Python 3.12
 * Compiler (if using C++): N/A

**Comment by Souzooka** [comment]
Also of note is that when marking `update` with the `async` keyword to turn it into a coroutine and then reproducing the steps to cause the program to crash, it will always silently crash when it does instead of any exception being raised in the output.

**Comment by Souzooka** [comment]
Additionally, upon further testing I found that if I include the line `import gc; gc.disable()` at the bottom of the import statements for the snippet above, I cannot reproduce this crash.

I believe there may be some sort of issue with the garbage collection implementation introduced in this commit:
https://github.com/panda3d/panda3d/commit/e5bd00f91f9ef1522f65bd6ebfa23dbe41abdf5e

**Comment by Souzooka** [comment]
Disabling the garbage collector actually doesn't seem to completely fix this issue, though it does appear to make it less frequent.

**Comment by ksadgum** [comment]
I tried the same code multiple times and it works fine. I use python 3.11 and panda 1.10.14

**Comment by ksadgum** [comment]
![Uploading Screenshot 2024-09-11 181630.png…]()

**Comment by Souzooka** [comment]
Commit https://github.com/panda3d/panda3d/commit/e5bd00f91f9ef1522f65bd6ebfa23dbe41abdf5e doesn't exist in 1.10.14 (1.10.14 was released on Jan 8, while the commit was Mar 29), which leads me to believe more that there is something problematic with the commit and that it should likely be reverted for the time being.

**Comment by johnnyapol** [comment]
I've opened #1681 to possibly fix this. In my testing, it fixed the premature garbage collection and also just seems more correct now.
