### ISSUE TITLE
Prevent window size from being set to zero

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#1689]
Reported on behalf of a forum user:
https://discourse.panda3d.org/t/window-size-singularity-in-windows-7/30351

## Description
Prevent the window from being resized to a height or width of 0.

## Use Case
This prevents the occurrence division-by-zero errors, creation of invalid textures, etc.

**Comment by kekwlboy12469** [comment]
Hey can i contribute to this issue  ?

**Comment by burningbuffer** [comment]
I would like to contribute.

This issue also occurs on Windows 10. I solved something very similar in one of my applications. Could you assign it to me?

**Comment by rdb** [comment]
Feel free to contribute, of course. See the [Contributing Guidelines](https://github.com/panda3d/panda3d/blob/master/CONTRIBUTING.md). Maybe suggest your implementation strategy here first or discuss it in the [Discord server](https://discord.gg/UyepRMm) in #engine-dev, before working on a pull request. That is especially helpful to coordinate if you both want to work on it so you don't do duplicate work. :-)

**Comment by rdb** [comment]
I tested that macOS indeed already prevents a window from being zero-sized. The only remaining case is Linux; we need to test the current behaviour for an X11 window and possibly adjust the size hints we already give the WM to set a particular min size.

**Comment by burningbuffer** [comment]
> I tested that macOS indeed already prevents a window from being zero-sized. The only remaining case is Linux; we need to test the current behaviour for an X11 window and possibly adjust the size hints we already give the WM to set a particular min size.

I tested with a default x11 application and a panda3d sample in linux. Looks like the default is already width  = 1 x height = 1.
![Image](https://github.com/user-attachments/assets/4da676d4-b6a6-4744-9ba0-54e491f247d2)
