### ISSUE TITLE
CMake Build Failure on macOS (M2, ARM64) Due to Linker Error in C++ Compilation

### ISSUE THREAD

**Issue by ZzzhHe** [panda3d/panda3d#1692]
## Description

I attempted to build from source using CMake on my MacBook with an M2 chip. The build step failed with the following linker error:

```
ld: unknown options: --exclude-libs --exclude-libs 
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libp3prc.1.11.0.dylib] Error 1
make[1]: *** [cmake/dtool/src/prc/CMakeFiles/p3prc.dir/all] Error 2
make: *** [all] Error 2
```

## Steps to Reproduce

1. Clone 
2. Download the 3rd party libraries and copy to the project folder.
3. Followed the instruction in the `cmake/README.md`
```
mkdir build
cd build
cmake ..
cmake --build . --config Standard --parallel 6
```

## Environment
 * Operating system: macOS 14
 * System architecture: ARM64 (Apple Silicon M2)
 * Panda3D version: 1.10.14 (latest one)
 * Installation method: built from source
 * Python version (if using Python): Python 3.11.5
 * Compiler (if using C++): Clang 19.1.1 (LLVM)

**Comment by ZzzhHe** [comment]
According to the error info, I tried to update the code in `dtool/src/prc/CMakeLists.txt`.

https://github.com/panda3d/panda3d/blob/61f8df2d7d64dc3ad29eab16659dd96311501735/dtool/src/prc/CMakeLists.txt#L104-L108

to

```
if(HAVE_OPENSSL AND CMAKE_CXX_COMPILER_ID MATCHES "^(GNU|Clang)$")
  if(NOT APPLE)
    # Do not re-export symbols from these libraries, but only on non-macOS systems.
    target_link_options(p3prc PRIVATE "LINKER:--exclude-libs,libssl.a")
    target_link_options(p3prc PRIVATE "LINKER:--exclude-libs,libcrypto.a")
  endif()
endif()
```

This resolved the linker error, but I then encountered another issue related to deprecated functions,  along with an error involving Eigen during the build. 

The new error is as follows:

```
In file included from /Users/Programming/GitRepo/panda3d/thirdparty/darwin-libs-a/eigen/include/Eigen/Core:276:
/Users/Programming/GitRepo/panda3d/thirdparty/darwin-libs-a/eigen/include/Eigen/src/Core/Functors.h:973:28: error: no member named 'binder2nd' in namespace 'std'
...
make: *** [all] Error 2
```

**Comment by rdb** [comment]
I build Panda all the time on my Apple M2 MacBook without problems. Can you tell me more about your compiler version, CMake version, XCode version, etc.?

`CMAKE_CXX_COMPILER_ID` is supposed to be `AppleClang` for Apple's version of clang, so it should not match that regex.

**Comment by rdb** [comment]
The binder2nd error suggests that it is building in C++17 mode (or something) even though we are telling CMake to request C++11 mode, so there might be something wrong with your compiler or with CMake. The output you pasted cuts off the compiler commands, could you share them? I'd like to know what version of the C++ standard it's requesting.

**Comment by ZzzhHe** [comment]
+ Compiler Version
```
❯ clang++ --version                                                   
Homebrew clang version 19.1.1
Target: arm64-apple-darwin23.6.0
Thread model: posix
InstalledDir: /opt/homebrew/Cellar/llvm/19.1.1/bin
```

+ CMake Version
```
❯ cmake --version                               
cmake version 3.30.5
```

+ Xcode Version
```
❯ xcodebuild -version   
Xcode 16.0
```

**Comment by rdb** [comment]
Ah.  I think you're the first person to try and build Panda using a version of clang installed from Homebrew.

We do all our builds with Apple's clang.  I suggest instead installing the XCode Command-Line Tools, and uninstalling clang from Homebrew.

That said, if you have a good reason to use the Homebrew clang, I'll help you figure it out if you contribute back the changes.

**Comment by ZzzhHe** [comment]
Oh! Thanks! I switched back to Apple Clang, and the linker error disappeared.  However, I’m still encountering the `binder2nd` error.

**Comment by rdb** [comment]
I suggest --no-eigen for a quick fix, or updating the Eigen that's in the thirdparty directory.

**Comment by ZzzhHe** [comment]
Since I’m using cmake (according to `cmake/README.md`) instead of `makepanda.py`, it seems the `--no-eigen` option doesn't apply. Or am I misunderstanding something?

**Comment by rdb** [comment]
Yes, sorry. Look for a CMake define to disable Eigen. Not sure which off the top of my head, probably HAVE_EIGEN=OFF.

**Comment by ZzzhHe** [comment]
Thanks! I was able to build it successfully without Eigen (`cmake -DHAVE_EIGEN=NO`). I’m going to try updating Eigen manually to see if that resolves the issue.

**Comment by ZzzhHe** [comment]
After updating Eigen, I encountered a new error, followed by several errors, like `no member named 'XXX' in namespace 'std'`

```
/Users/Programming/GitRepo/panda3d/thirdparty/darwin-libs-a/eigen/include/Eigen/src/Core/util/Macros.h:716:2: error: Eigen requires at least c++14 support.
  716 | #error Eigen requires at least c++14 support.
      |  ^
```

This has left me a bit confused.

**Comment by rdb** [comment]
Hmm, it appears that you're using an unreleased development version of Eigen, which requires compiling in C++14 mode.  Panda compiles in C++11 mode.

Maybe it's about time we updated from C++11 to C++14 in Panda.

In the meantime you can change CMAKE_CXX_STANDARD from 11 to 14 in dtool/CompilerFlags.cmake.

**Comment by ZzzhHe** [comment]
Oh, thanks! I was able to build with the latest released version of Eigen.
