### ISSUE TITLE
Add owner property to CollisionNode storing custom Python object

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#1703]
One of the problems nearly every game has to solve is to find a way to access the original game object instance corresponding to a collision node when processing a collision. Commonly used solutions for this are: a mapping based on a unique collision node name or tag somewhere, a reference to the game object stored as a Python tag, or something like that. These approaches are problematic:
- Extra stuff to manage like unique id generation and maintaining dictionary of game objects, which is annoying extra work.
- Python tags have their own problems: they create circular references which need to be broken manually.
- It's often ambiguous on which node the tag should be looked up (I often see some chain of .parent.parent in code, determined by trial-and-error).

I suggest solving all these problems by adding an `owner` property to CollisionNode, permitting a custom Python object to be stored there. When processing collision entry, it is easy to use `entry.into_node.owner` or `entry.from_node.owner` to access the original game object.

To avoid circular reference counts, the class should store a weak reference. The name `owner` heavily suggest that it stores an object which "owns" this node. In this use case it would be very uncommon (and usually indicative of a coding error) for the CollisionNode to outlast the owning Python game object, which would indicate that the game object didn't properly clean up its collision nodes.

Nonetheless, if the CollisionNode _were_ to outlive the Python game object, the owner property would return None, which can be handled by user code if this corner case were to arise. (An alternative would be to raise an exception, but returning None seems more consistent with existing weakref semantics).

While many Python (and Panda) objects are not weakreffable and could therefore not be assigned as an `owner`, custom classes are all weakreffable by default, suggesting that weakref is an acceptable solution for this use case, even if they are not suitable for the general use cases of Python tags.

There can not be confusion about which node the property should be set on, since the property only exists on CollisionNode. There should also be a `set_collide_owner` on NodePath to set the `owner` property recursively on any CollisionNodes thereunder, as a convenience, similar to how we have `set_collide_mask`.

**Comment by DylanCheetah** [comment]
This sounds like a great enhancement. Making `owner` a weakref would help avoid memory leaks caused by circular references. And adding a `set_ collide_owner` method that operates recursively would simplify data access.
