### ISSUE TITLE
TextureAttrib of loaded .bam file randomly ignores off-stage

### ISSUE THREAD

**Issue by Epihaius** [panda3d/panda3d#179]
When loading a .bam file containing a hierarchy of 2 GeomNodes, where the child GeomNode has a TextureAttrib that turns off specific texture stages used by the parent GeomNode, it can happen (randomly, it seems) that one of the stages is set to "on" for the child - at least in the *net* render state, even though in the local render state it is correctly turned off.

So if the texture stages used for the parent GeomNode are called "stage1" and "stage2", then the expected results for the child GeomNode would be:

child texture stages off: ["stage1", "stage2"]
child texture stages on: []

And while that is indeed always the case for the local render state, it can happen that for the net render state I get this:

child texture stages off: []
child texture stages on: ["stage2"] # this should be empty

Related topic containing more info and sample code can be found [here](https://www.panda3d.org/forums/viewtopic.php?f=4&t=19643).

As mentioned before, it can take a few runs of the code to see different results.

**Comment by rdb** [comment]
Have you tested this with 1.10?  I continue to be unable to reproduce this issue.

**Comment by Epihaius** [comment]
Just tried it on another, newer machine, with a very recent Panda3D version (8a35f36 from 2017-10-18) and yes, it definitely still happens. If anything, the frequency with which the results vary seems to have increased; it now gives a wrong result like 1 time out of 2, while it only went wrong 1 time out of 5 or so with older Panda versions, IIRC.

[Here](https://vimeo.com/240279603) is a short video I recorded to show exactly what happens.

Since I get the same results on three different machines (1 laptop and 2 desktops), it seems doubtful that it has anything to do with a specific graphics card (although they are all NVIDIA), but perhaps you want the output when I set "gl-debug true" and "notify-level-glgsg debug" in Config.prc, just in case?
Here is already the last part of it, just after loading the textures, therefore perhaps the most relevant part:

```
:display:gsg:glgsg(debug): loading uncompressed texture rockwall_diffuse
:display:gsg:glgsg(debug): loading new texture object for rockwall_diffuse, 1024 x 1024 x 1, z = 0, mipmaps 1, uses_mipmaps = 0
:display:gsg:glgsg(debug): Buffer detailed info: Buffer object 1 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.
:display:gsg:glgsg(debug): Buffer detailed info: Buffer object 2 (bound to GL_ELEMENT_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.
:display:gsg:glgsg(debug): loading uncompressed texture Brick_105
:display:gsg:glgsg(debug): loading new texture object for Brick_105, 1024 x 1024 x 1, z = 0, mipmaps 1, uses_mipmaps = 0
:display:gsg:glgsg(debug): Buffer detailed info: Buffer object 3 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.
:display:gsg:glgsg(debug): Buffer detailed info: Buffer object 4 (bound to GL_ELEMENT_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.
:display:gsg:glgsg(debug): GLGraphicsStateGuardian 0000000003D4FE00 destructing
```

The above output is always the same, regardless of the result.

Perhaps there is something wrong with the way the .bam file itself is created, so I attached it below, including the textures used:
[model_hierarchy.zip](https://github.com/panda3d/panda3d/files/1424218/model_hierarchy.zip)


The newest machine I tested this on runs Windows 10 64-bit and has an NVIDIA GeForce GTX 750 Ti graphics card.

**Comment by rdb** [comment]
I managed to reproduce it at last.  The issue is that the compose mechanism relies on the states being sorted by pointer, but loading it from .bam removes the guarantee that the state pointers are sorted (since the texture stages are loaded in no particular order).  All that's needed is one line to sort the pointers. :)

Thanks for the test case and reporting this issue!

**Comment by Epihaius** [comment]
Great news! Thank you for fixing this!
