### ISSUE TITLE
Moving panda3d globals outside of builtins

### ISSUE THREAD

**Issue by DokahlSoZoor** [panda3d/panda3d#182]
While compiling my application with Cython it hit a snag when trying to locate the variables panda3d adds to the global namespace. I'm pretty sure this is because they are added during runtime so Cython has no clue about their existence during compile time. A simple but ugly workaround is accessing them through the builtins module explicitly e.g. `builtins.loader.loadTexture(...)` instead of just `loader.loadTexture(...)`.

This made me think, wouldn't it be better to do something like this instead of modifying the python bultins?
```
from panda3d.globals import loader
loader.loadTexture(...)
```
It doesn't complicate the application code whatsoever, the only change is having to explicitly import the variable at the top of the file, everything else stays as is. Requiring the explicit import is a good thing I think, this way no variables appear out of thin air which is a lot more transparent for the user.

Just my 2 cents :)

**Comment by darktohka** [comment]
If your ShowBase is created as "base" in builtins, you can use this syntax:

`base.loader.loadTexture(...)`

**Comment by fnadalt** [comment]
I subclass ShowBase to a kindo of App class, and I pass this class to other objects in their constructor

**Comment by DokahlSoZoor** [comment]
@darktohka That doesn't really help since `base` is also added to the builtins at runtime, so you run into the exact same problem.

**Comment by wezu** [comment]
I think the buildins are here to stay till Panda3d 2.0, removing them will probably break most existing code. But ShowBase is just a Python class and you don't even have to use it. Here's an alternative with no buildins https://github.com/wezu/panda3dapp

**Comment by DokahlSoZoor** [comment]
They don't have to necessarily be removed. We can just add an additional way to access them without having to use builtins or passing a reference around everywhere.

**Comment by rdb** [comment]
I just checked in a change that lets one access `base` and some other builtins from here:
```from direct.showbase import ShowBaseGlobal

ShowBaseGlobal.base.whatever()```

This isn't implemented for `loader` since it's already accessible via `ShowBaseGlobal.base.loader`; it seemed unnecessary to also add `ShowBaseGlobal.loader`.  That can be added later if desired.

As has been pointed out, the long term plan is to remove the reliance on builtins entirely, probably by replacing ShowBase with a new system (only leaving ShowBase as a compatibility module).
