### ISSUE TITLE
Installed Panda3D in win7 but it changed default way to open python files

### ISSUE THREAD

**Issue by Howld** [panda3d/panda3d#184]
I installed Panda3D from Panda3D-SDK-1.9.4.exe, but I found it changed my default way to open my python files. It took my half day to found this problem. When I type 'main.py' in win7 CMD,  it says 'no module named xxx' with wrong path in 'sys.path' when I use python3 to coding again.

**Comment by rdb** [comment]
Do you remember the installer asking you to make Panda's Python the default? It's programmed to not simply override your existing Python installation without asking you.

**Comment by Howld** [comment]
Yes, no asking. I installed again after uninstalled it, and it's ok to use python3 again, No idea how it happend.

**Comment by montreal91** [comment]
@Howld, is this issue still relevant to you?

**Comment by Moguri** [comment]
Assigning to myself to see if I can reproduce this.

**Comment by Moguri** [comment]
I was not able to reproduce this. I used Windows 7 and Panda3D-SDK-1.9.4.exe.

**Comment by Moguri** [comment]
@rdb Should we close this task as inactive?

**Comment by drewc5131** [comment]
the poster definetly just accidently hit to overwrite...

**Comment by rdb** [comment]
I'm about to make some changes to the way the Windows installer registers the Panda paths with Python, so I'm going to close this; we can open a new issue if we still see issues with the new installer.
