### ISSUE TITLE
Incorrect variable in animation interpolation of ActorInterval

### ISSUE THREAD

**Issue by bluekyu** [panda3d/panda3d#187]
https://github.com/panda3d/panda3d/blob/a26662ce4609753d464ed042ca867320b3a12dde/direct/src/interval/ActorInterval.py#L82-L86

Hello, I found incorrect codes in animation interpolation of ActorInterval, but I'm not sure.
I think that the `duration` variable should be `endTime` in Line 86.
Is it right?

**Comment by rdb** [comment]
Yes, it certainly looks like it should be `endTime`.  Well spotted!
