### ISSUE TITLE
How do you use the Panda3D Vulkan tree?

### ISSUE THREAD

**Issue by Jimbow500** [panda3d/panda3d#190]
I'm still new to anything that is low level. I know Vulkan is better than OpenGl in some cases, but how do I add or use the Vulkan tree?

When I try build it I get this error too
```bash
[ 20%] Building C++ object built/tmp/p3gobj_composite2.o
In file included from panda/src/gobj/p3gobj_composite2.cxx:10:0:
panda/src/gobj/shader.cxx:30:26: fatal error: vulkan/spirv.h: No such file or directory
compilation terminated.
Storing dependency cache.
Elapsed Time: 1 sec
The following command returned a non-zero value: g++ -std=gnu++0x -ftemplate-depth-70 -fPIC -c -o built/tmp/p3gobj_composite2.o -Ibuilt/tmp -Ibuilt/include -I/usr/include/eigen3 -Ipanda/src/gobj -fvisibility=hidden -pthread -fno-exceptions -msse2 -fno-strict-aliasing -ffast-math -fno-stack-protector -fno-finite-math-only -O2 -DBUILDING_PANDA panda/src/gobj/p3gobj_composite2.cxx
Build terminated.
```
I did install the newest version of the VulkanSDK. I don't know what else to do for it.

Another thing I'm running "Mint 18.2 Sonya"

**Comment by rdb** [comment]
I do warn that the Vulkan branch is not at all feature-complete.  Some simple programs will run, but more advanced shaders will not.  At this stage, there is very little to gain from using Vulkan with Panda3D.

In this case, you need to download the [spirv.h](https://raw.githubusercontent.com/KhronosGroup/SPIRV-Headers/master/include/spirv/1.2/spirv.h) header from the Khronos website, and place it inside `/usr/include/vulkan` or whichever directory your distribution uses.

To enable the Vulkan renderer you will need to put `load-display p3vulkandisplay` in your Config.prc.  The code currently expects SPIR-V shaders present to be present in your model-path; I'd be happy to share the shaders on request.

**Comment by Jimbow500** [comment]
@rdb I'm slowly trying to get the Vulkan branch more functional. Ill start making comments maybe around next week.
