### ISSUE TITLE
OSX: Latest version not compatible with sierra 10.12.6

### ISSUE THREAD

**Issue by tavurth** [panda3d/panda3d#196]
![image](https://user-images.githubusercontent.com/100964/32753578-75126ca8-c8de-11e7-86c3-d0730f7e4c36.png)

When I tried installing the downloaded runtime from [here](https://www.panda3d.org/download.php), it gives the error: "Incompatible with your system, would you like to try to install anyway", which then fails.

SDK installs OK, and I can install via pip.

`python my-app.py` runs ok, but I'm trying to build a `my-app.p3d` file to test distribution. 

```bash
> locate packp3d
/Developer/Panda3D/direct/p3d/ppackage.py
/Users/Tavurth/projects/panda3d/panda3d-1.9.4/built/direct/p3d/ppackage.py
/Users/Tavurth/projects/panda3d/panda3d-1.9.4/direct/src/p3d/ppackage.py
/usr/local/lib/python3.6/site-packages/direct/p3d/__pycache__/ppackage.cpython-36.pyc
/usr/local/lib/python3.6/site-packages/direct/p3d/ppackage.py
```

Upon running one of these files with python, I get the message:

```bash
This script must be run using a version of Panda3D that has been built
for distribution.  Try using ppackage.p3d or packp3d.p3d instead.
If you are running this script for development purposes, you may also
set the Config variable panda-package-host-url to the URL you expect
to download these contents from (for instance, a file:// URL).
```

Any ideas on how I can build a `p3d` file on this version?

**Comment by rdb** [comment]
The packp3d deployment pipeline unfortunately does not work with Python 3.  If you intend to distribute an application written in Python 3, I would encourage you to check out the new deploy-ng system we are working on in 1.10.

For what it's worth, the ppackage script was not intended to be run directly; it is rather packaged into a ppackage.p3d which can be downloaded and run from https://runtime.panda3d.org/.  However, we do not intend to support this path going forward.

**Comment by tavurth** [comment]
Ah Ok, I'll take a look at the deploy-ng when I have a free moment.

The main issue then would be that I can't run any `p3d` files, because the Panda3d runtime doesn't install correctly on `OSX 10.12.x`, (It shows a `your system is unsupported` warning window, and then fails to install).

**Comment by tavurth** [comment]
I should mention that I tried to build from source the other day, which took about an hour on my old mac. The build failed at around 93% with an error, I'll try the build again later this evening if I have the time and post the error here.

**Comment by rdb** [comment]
Closing this since we are focusing on deploy-ng going forward.

**Comment by tavurth** [comment]
@rdb Any references on how to use `deploy-ng`, documentation on the web is so far sparse.
