### ISSUE TITLE
On fullscreen, rendering freezes when NVIDIA GeForce Experience is used

### ISSUE THREAD

**Issue by bluekyu** [panda3d/panda3d#197]
I found a issue that rendering window freezes using NVIDIA GeForce Experience.
(This issue does not happen in my simple OpenGL app using GLFW.)

This issue happens when fullscreen mode and NVIDIA Geforce Experience are used.
The rendering window is freezing after 5~7 seconds using **Overlay in Game** option.
If the option is **off**, then the freezing disappear.

I think that the issue may be caused by recording and overlay feature in GeForce Experience.
In old drivers, this issue does not exist, but freezing happens after game recording is started.

I tested the issue in the following conditions:
- Windows 10 64-bit
- Panda3D Windows x64 v1.9.4, master commit
- NVIDIA 385.69, 387.92, 388.31 drivers
- NVIDIA 980Ti, 1080, 1080Ti

**Comment by bluekyu** [comment]
I found more precise conditions.
Window freezes when any overlay is notified by GeForce Experience.
If the notifications is off, the freezing does not happen although "In-Game Overlay" option is ON.
However, if the overlay is opened by shortcut (Alt+Z), the window becomes freezing.

**Comment by bluekyu** [comment]
I performed some tests in GLFW App. I pressed ALT+Z key to open the overlay, then window proc message was presented as follow:

```
WM_SYSKEYDOWN (wParam: VK_MENU)
WM_KEYUP (wParam: VK_MENU)
WM_KEYUP (wParam: Z)
WM_KEYUP (wParam: VK_LMENU)
WM_NCHITTEST
WM_SETCURSOR
WM_NULL
// then, overlay opens.
```

And the window style and extended window style were not changed.
However, in Panda3D, "ChangeDisplaySettings failed to restore Windowed mode" warning message was printed when the key is pressed.
I guess that the crash happens because of minimizing window by losing focus.

**Comment by rdb** [comment]
Curious.

Could you include the sequence of events in the Panda window, by setting `notify-level-windisplay spam` ?

**Comment by bluekyu** [comment]
I attached the log file: [panda3d.log](https://github.com/panda3d/panda3d/files/1485553/panda3d.log)

I started app with `fullscreen #t` and `win-size 800 600`.
(Note that the app is Panda3D C++, not Python.)
After Line 700, alt key and z key were pressed. In Line 771, the warning message was printed.

**Comment by bluekyu** [comment]
I checked the issue is resolved in https://github.com/panda3d/panda3d/commit/0edac2e94af5a8adc5719a72e205bf98b021ff03

**Comment by bluekyu** [comment]
I checked the issue is resolved in https://github.com/panda3d/panda3d/commit/0edac2e94af5a8adc5719a72e205bf98b021ff03. Thank you!

However, in Panda3D Render Pipeline, the issue still happens.
I could solve it by removing `color-bits 0` config OR adding `reqs._property[FBP_color_bits] == 0` condition into the commit.
I don't know whether `color-bits 0` is meaningless, or `reqs._property[FBP_color_bits] == 0` condition is omitted.

**Comment by rdb** [comment]
Wow, are you sure?  I was trying to fix a completely different issue; I'm surprised it seemed to fix this one as well.

I didn't realise the framebuffer properties behaved differently when 0 bits were requested.  I've just included that in the condition.

Please close this issue if you can no longer reproduce it with the latest changes, thanks!

**Comment by bluekyu** [comment]
I also had another issue that the screen is washed out on full screen, but I thought it was not related to this issue. However, the commit resolved both washed out issue and this issue.

Now, the problem does not happen. NVIDIA overlay and recording works well. Thanks again!
