### ISSUE TITLE
ShowBase class lacks any sort of member descriptions or type info

### ISSUE THREAD

**Issue by etc0de** [panda3d/panda3d#198]
The ShowBase API reference lacks any sort of member descriptions or type info: https://www.panda3d.org/reference/devel/python/direct.showbase.ShowBase.ShowBase

Since this class is so super central (and I very vividly recall ending up on this page very quickly after starting out with Panda3D as a beginner) I think this is a huge shortcoming of the current documentation which should be addressed at least for the important members. This is especially bad since lots of the functionality available through ShowBase members *does have* extensive documentation, except that people cannot find it through this page since it doesn't have a return type for any of the members which would link to the API reference page that has the details on that specific subsystem / engine component.

Edit: actually some attributes have a short description which I missed, but none of the member methods do and no types are linked to the according type-specific / class-specific detail API reference

**Comment by JonasT** [comment]
Just to be more clear on this, I think the types are much more important than adding more description blurbs since it actually allows clicking the return type / variable type to get to the often well-documented detail subsystem page. So I would suggest any improvements should focus on that first.

**Comment by rdb** [comment]
The API documentation is directly generated from comments in the source code.  I'm not quite sure how well Doxygen supports including type information in the comments, but there may be some syntax for that.  If there is, patches would be very welcome.

This may be something we can more easily address when we switch to having the API reference generated by Sphinx rather than doxygen.

**Comment by JonasT** [comment]
After short googling, it appears doxygen has both `@return` (for a descriptive string that explains what is returned) and `@rtype` (for specifying the return type) which sounds like the right thing to use here. It has been a while since I used doxygen though so I might be wrong

**Comment by rdb** [comment]
In the Python modules, I would be in favour of using reST/sphinx style `:returns:` and `:rtype:`. To satisfy doxygen until we eventually switch to sphinx, we could use a regex or script to convert it to the other format.
