### ISSUE TITLE
TypeError decoding NodePath from BAM stream

### ISSUE THREAD

**Issue by Epihaius** [panda3d/panda3d#199]
When trying to unpickle a NodePath from a previously pickled string, I get the following TypeError:

`TypeError: py_decode_NodePath_from_bam_stream() takes exactly one argument (2 given)`

When using cPickle instead of the regular pickle module, the error report is basically the same, but more verbose:

`TypeError: ('py_decode_NodePath_from_bam_stream() takes exactly one argument (2 given)', <built-in function py_decode_NodePath_from_bam_stream>, (<type 'panda3d.core.NodePath'>, 'pbj\x00\n\r\x06\x00\x00\x00\x06\x00*\x00\x01\x00\x05\x00\x00\x00\x00\x01\x00\x00\x00\x91\x00\x00\x00\x004\x00\t\x00PandaNode\x023\x00\x1b\x00TypedWritableReferenceCount\x022\x00\r\x00TypedWritable\x01\x03\x00\x0b\x00TypedObject\x00\x04\x00\x0e\x00ReferenceCount\x00\r\x00\x07\x00Namable\x00\x01\x00\x00\x00\x02\x00\x03\x00\x04\x00\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Z\x00\x00\x00\x02\x9f\x00\x0b\x00RenderState\x01\x9e\x00\x18\x00NodeCachedReferenceCount\x017\x00!\x00CachedTypedWritableReferenceCount\x013\x00\x02\x00\x00\x00\x1c\x00\x00\x00\x02\xae\x00\x0e\x00TransformState\x01\x9e\x00\x03\x00\x05\x00\x01\x00\x19\x00\x00\x00\x02\x9c\x00\r\x00RenderEffects\x013\x00\x04\x00\x00\x00\x01\x00\x00\x00\x01'))`

The following code sample demonstrates the problem:

```
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase
import pickle


class MyApp(ShowBase):

    def __init__(self):

        ShowBase.__init__(self)

        np = NodePath("")
        s = pickle.dumps(np, -1)
        loaded_np = pickle.loads(s)


app = MyApp()
app.run()
```

This issue occurs using version 46c8852 of Panda3D with Python 2.7 64-bit.

**Comment by rdb** [comment]
Thanks, this was an oversight in a recent bugfix.
