### ISSUE TITLE
MAKE_MAP_PROPERTY and MAKE_SEQ_PROPERTY conflicting in some objects ?

### ISSUE THREAD

**Issue by consultit** [panda3d/panda3d#203]
Working with animations, I've noticed that with AnimGroup and PartGroup is impossible to get the sequence of the children, i.e. use code like this:
```
for child in animGroup.children:
    process(child)
    ...
```
I think this is because  `children` is defined in both MAKE_MAP_PROPERTY and MAKE_SEQ_PROPERTY, and if this is correct, other objects suffer from similar problems too (GeomVertexFormat, TextureAttrib ...)
If it not the case, which is the correct way to use these properties?

**Comment by rdb** [comment]
This is indeed possible and indicates you're supposed to be able to do both `children["name"]` and `children[index]`.  However, it's not intended to break the sequence interface.  I'll look into it.

**Comment by rdb** [comment]
The `np.nodes` interface is a very recent addition, intending to replace the old `get_nodes()` interface, after community feedback that property interfaces are considered to be cleaner.

**Comment by consultit** [comment]
OK, thanks
