### ISSUE TITLE
Dtool_SequenceWrapper compile error

### ISSUE THREAD

**Issue by theclashingfritz** [panda3d/panda3d#206]
I get this error on the latest commit building statically. From the looks of it, Interrogate does not generate proper wrappers in some fashion.

> built/tmp/libp3dtoolbase_igate.cxx(1115) : error C2039: '_setitem_func' : is not
 a member of 'Dtool_SequenceWrapper'
        c:\users\theclashingfritz\documents\tticodedumper\panda3d\built\include\
py_wrappers.h(29) : see declaration of 'Dtool_SequenceWrapper'
built/tmp/libp3dtoolbase_igate.cxx(1169) : error C2039: '_setitem_func' : is not
 a member of 'Dtool_SequenceWrapper'
        c:\users\theclashingfritz\documents\tticodedumper\panda3d\built\include\
py_wrappers.h(29) : see declaration of 'Dtool_SequenceWrapper'
built/tmp/libp3dtoolbase_igate.cxx(2225) : error C2039: '_setitem_func' : is not
 a member of 'Dtool_SequenceWrapper'
        c:\users\theclashingfritz\documents\tticodedumper\panda3d\built\include\
py_wrappers.h(29) : see declaration of 'Dtool_SequenceWrapper'
built/tmp/libp3dtoolbase_igate.cxx(2287) : error C2039: '_setitem_func' : is not
 a member of 'Dtool_SequenceWrapper'
        c:\users\theclashingfritz\documents\tticodedumper\panda3d\built\include\
py_wrappers.h(29) : see declaration of 'Dtool_SequenceWrapper'

**Comment by rdb** [comment]
Are you sure the version of interrogate.exe that's being used is the one that produced the build?

**Comment by theclashingfritz** [comment]
Yes, There is no other interrogate for it to use

**Comment by theclashingfritz** [comment]
However i will check and see if it's pulling from some temp folder that didn't get deleted or the like.

**Comment by theclashingfritz** [comment]
Alright it was pulling a temp old version from the temp folder in AppData... How it found it there is beyond me but the issue is gone.
