### ISSUE TITLE
Deploy-ng's importing

### ISSUE THREAD

**Issue by cflavio** [panda3d/panda3d#208]
This is a minimal program _main.py_ that shows the issue:
```
import direct.directbase.DirectStart
from xml.etree import cElementTree
from datetime import datetime; datetime.strptime('1970-01-01', '%Y-%m-%d')
run()
```
This is my _requirements.txt_:
```
--pre --extra-index-url https://archive.panda3d.org/branches/deploy-ng
panda3d
```
This is my _setup.py_:
```
from setuptools import setup
 setup(
    name='ng_example',
    options = {
        'build_apps': {
            'gui_apps': {'ng_example': 'main.py'},
            'plugins': ['pandagl'],
            'platforms': ['manylinux1_x86_64'],
        }
    }
)
```
If I run _main.py_ from SDK it works. If I run a build which has been built with the latest deploy-ng I receive this error from line 2:
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "/usr/lib/python2.7/xml/etree/cElementTree.py", line 3, in <module>
    from _elementtree import *
  File "<string>", line 5, in <module>
ImportError: No module named ElementTree
```
and this error from line 3 (if I comment the line 2):
```
Traceback (most recent call last):
  File "main.py", line 3, in <module>
ImportError: No module named _strptime
```

**Comment by Moguri** [comment]
I haven't gotten around to debugging this yet (hoping to do that this weekend), but it looks like cElementTree has a hidden import (https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-xml.etree.cElementTree.py). Try adding the following to your setup.py under 'build_apps' options:
```python
'include_modules': {
    '*': [
        'xml.etree.ElementTree',
    ]
}
```

Not sure what's going on with datetime though. Maybe try adding 'datetime._strptime' or '_strptime' to the include_modules as well?

**Comment by cflavio** [comment]
Hi Moguri, thanks! This solves the issue:
```
'include_modules': {'*': ['xml.etree.ElementTree', '_strptime']}
```

**Comment by Moguri** [comment]
I have pushed some fixes and I can now get a build of the supplied example working with Python2 without specifying the include_modules in setup.py.

@cflavio Can you verify that the new fixes solve the issue for you too?

**Comment by cflavio** [comment]
Thanks Moguri,erything works now! :)
