### ISSUE TITLE
arabic

### ISSUE THREAD

**Issue by Omaranwa** [panda3d/panda3d#209]
how can i add arabic lang if possible?
thanks

**Comment by rdb** [comment]
To get proper Arabic text shaping, you need to compile Panda3D with HarfBuzz support enabled.  (On Windows, this means you need to put a suitable version of the Harfbuzz library inside the thirdparty directory.)

Then, you need to enable `text-use-harfbuzz true` in your Config.prc file.  That should make it detect the text direction automatically as well as use the proper contextual form of each letter, although you can override the direction of a particular text element (eg. in OnscreenText you can pass `direction="rtl"`, or on TextNode you can use `set_direction(TextProperties.D_rtl)`).

The plan is to provide HarfBuzz with the downloadable builds soon.  This will require someone to add instructions to build the library to [this file](https://github.com/rdb/panda3d-thirdparty/blob/master/CMakeLists.txt).

**Comment by rdb** [comment]
Actually, I see we have been building the development builds with HarfBuzz for a while now.  Could you try a development build and let me know whether you're still having issues using Arabic?  Thanks!

**Comment by theclashingfritz** [comment]
It's a shame development builds don't include the thirdparty files they were built with.

**Comment by rdb** [comment]
That would make them too large.  But I regularly upload the prebuilt thirdparty files that are used to make the development builds (search the forums).  Also, you can build them yourself with a single command using the CMake files in here:
https://github.com/rdb/panda3d-thirdparty

**Comment by theclashingfritz** [comment]
Awesome thanks.

**Comment by rdb** [comment]
Closing due to lack of response; I'll assume the original question has been answered to satisfaction until I hear otherwise.

**Comment by bambier** [comment]
> That would make them too large. But I regularly upload the prebuilt thirdparty files that are used to make the development builds (search the forums). Also, you can build them yourself with a single command using the CMake files in here: https://github.com/rdb/panda3d-thirdparty

I tried to do as `README` described there but I got lots of error and couldn't build it. (I should mentionn that I know absolutely nothing about [those command](https://github.com/rdb/panda3d-thirdparty/blob/main/README.md))
Maybe uploading specific build to pypi is better solution so you let users choose which one should be downloaded. For example we can enable specific features for [`Twisted`](https://pypi.org/project/Twisted/) by [`pip install 'Twisted[tls,http2]'`](https://stackoverflow.com/a/70991928/12160182) while there are not enabeld by default when we use `pip install 'Twisted[tls,http2]'`

Anyway I got this error without installing harfbaz built and just using `bidi` and `arabic_reshaper`
```
:text(warning): No definition in  for character U+fee1
:text(warning): No definition in  for character U+fefc
:text(warning): No definition in  for character U+feb3
:text(warning): No definition in  for character U+fee1
:text(warning): No definition in  for character U+fefc
:text(warning): No definition in  for character U+feb3
:text(warning): No definition in  for character U+fee1
:text(warning): No definition in  for character U+fefc
:text(warning): No definition in  for character U+feb3
:text(warning): No definition in  for character U+fee1
:text(warning): No definition in  for character U+fefc
:text(warning): No definition in  for character U+feb3
```
This will not appears when I use `OnscreenImage` but not while using `DirectButton` shouldn't they use same engine for text rendering?

**Comment by rdb** [comment]
This issue is from 2018.  You don't need to build Panda from source or use development builds—the stable versions of Panda3D available on PyPI and the download page already include harfbuzz support included.

The error means you just have not selected a suitable font with Arabic characters. Load a ttf or otf font with Arabic characters and the problem should go away.

**Comment by bambier** [comment]
Well you got me in to bigger problem by these explanations.
It seems using `font` attr in `DirectButton` is not possible, so it uses my default system font (I think so) how ever after the explanations you gave I set these in my config file
```prc
text-use-harfbuzz #t
text-encoding utf8
text-default-font assets/fonts/MjOld.ttf
window-title بابک خرمدین
```
And I got in to this broken text (the title is broken but button seems OK)
![image](https://github.com/panda3d/panda3d/assets/22503761/7bf9c5a1-c57e-4d4b-8897-5ddee572bab9)
Well I'm not able to change font of specific button to custom font! 


Regardless of the `DirectButton` font, how can I fix title broken text? As my system default font is `Dejavu` and supports Persian glyph very well.

**Comment by rdb** [comment]
You should be able to use `text_font=` attribute in DirectButton.

The window title not being set properly looks like a bug in our X11 code. I will look into that.

**Comment by bambier** [comment]
Tnx.

**Comment by rdb** [comment]
Could you please try the build here and let me know whether the problem is fixed?
http://buildbot.panda3d.org/downloads/a655784d8d36b4fefd0e926a18c2bea52c3271fa/

**Comment by bambier** [comment]
Yes, it fixed the problem.
Here is the result
![image](https://github.com/panda3d/panda3d/assets/22503761/b01a3a4e-943a-46af-a081-f2d864605c5a)

Thank you.
