### ISSUE TITLE
`panda3d: No such file or directory` when running `packp3d` on macOS

### ISSUE THREAD

**Issue by lmcgrath** [panda3d/panda3d#215]
OS: macOS High Sierra 10.13.2
Panda3D SDK version: 1.9.4
Download: Panda3D-SDK-1.9.4-MacOSX10.7.dmg

Running `packp3d` gives `panda3d: No such file or directory`.

Searching the filesystem shows no command `panda3d`.

**Comment by rdb** [comment]
`panda3d` is part of the Panda3D Runtime, which you would need to install alongside the SDK.
