### ISSUE TITLE
Bullet's segmentation fault with multithreaded rendering

### ISSUE THREAD

**Issue by cflavio** [panda3d/panda3d#220]
Running [yorg](https://github.com/cflavio/yorg) with multithreaded rendering (to enable it set _development:multithreaded_render_:1 in the file _options.yml_) produces the attached fault after 15 seconds more or less.

[backtrace.txt](https://github.com/panda3d/panda3d/files/1601875/BYs487M5.txt)

**Comment by rdb** [comment]
@deflected has graciously done the work to add locks to the bullet code in 9afdb78d947e51ce84e09a4885ff3c3895f8bc4e.  Could you test to see whether this solves the crash for you?

**Comment by cflavio** [comment]
Great! It works now, thank you very much!
