### ISSUE TITLE
Strange behavior on start

### ISSUE THREAD

**Issue by artygrand** [panda3d/panda3d#224]
Hello, I'm new in python and panda, so question may be stupid.
If I first time (after computer is turned on) runs simple project in pycharm

    class App(ShowBase):
        pass

    if __name__ == '__main__':
        app = App()
        app.run()

and wait about 10 sec, windows is freezing for 5 seconds.
If I run project in second time and more, after 10 seconds windows is freezing again, but I always see "screenshot" of previous thing

Also if I runs in fullscreen, python is crashed with log:

    Known pipe types:
      wglGraphicsPipe
    (all display modules loaded.)
    AL lib: (EE) alc_cleanup: 1 device not closed

widows 7
python 3.6
panda 1.10 (through pip)

I can't record it on video. GeforceExperiens ends recording just before start of project, GyazoGif can't see it.
done it on phone https://youtu.be/8Jyr-T43yEM look at time

**Comment by theclashingfritz** [comment]
Very odd indeed...

**Comment by rdb** [comment]
Can you check whether running 'pview' gives the same problem?

Also, could you specify what graphics hardware you are using?

**Comment by bluekyu** [comment]
I guess this issue is similar to https://github.com/panda3d/panda3d/issues/197.
If the issue disappears when you turn off "in-game overlay" in GeforceExperience, then the guess is right.
And the issue was fixed after panda3d-1.10.0.dev1252 build.

**Comment by artygrand** [comment]
Yes pview does the same thing
```
C:\Users\Arty>pview
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
:display:gsg:glgsg(warning): Driver possibly misreported GL_VERSION!  Unable to
detect correct OpenGL version.
1097 frames in 19.6298 seconds.
55.8843 fps average (17.8941ms)
```
NVIDIA GeForce GTX 1060
driver NVIDIA 387.92

And yes, GeforceExperience is guilty, although the symptoms are different. So I'll wait for the update to be released in PyPI. Thanks!

---

It is normal that if I `wprop.setSize(1920, 1080)`, window goes to fullscreen automatically, even with `wprop.setFullscreen(False)` after it?
It is normal that all colors and textures are 2 times lighter in fullscreen?

**Comment by rdb** [comment]
The "lighter colours" issue was also part of #197 bug and was already fixed.

To upgrade to the latest devel version with pip, use:
```
pip install --pre --upgrade --extra-index-url https://archive.panda3d.org panda3d
```
```
