### ISSUE TITLE
libeigen can cause models to load rotated in odd ways

### ISSUE THREAD

**Issue by JonasT** [panda3d/panda3d#228]
Building and running panda3d with libeigen can cause models to load rotated in odd ways. Sadly, I couldn't reproduce it with git master ba9ea065e4701c823b05928e0c3269b284847388 for some reason, but it should probably be investigated further if the problem is truly gone.

**Comment by rdb** [comment]
I finally found it, I think.  It's an error in the Eigen matrix invert function for double-precision when `-ffast-math` (specifically `-funsafe-math-optimizations`) is given as compiler argument to GCC.  It must be either a GCC or an Eigen bug.  It does not occur with Clang, or with single-precision math, or when compiling without optimizations.

For the record, here is a C++ program to reproduce the issue with plain Eigen, without Panda3D:
```cpp
#include <Eigen/Dense>
#include <iostream>

typedef Eigen::Matrix<double, 4, 4, Eigen::RowMajor> Mat4;

int main(int argc, char *argv[]) {
  Mat4 m;
  m(0, 0) = 1.0;
  m(0, 1) = 0.0;
  m(0, 2) = 0.0;
  m(0, 3) = 0.0;
  m(1, 0) = 0.0;
  m(1, 1) = 1.0;
  m(1, 2) = 0.0;
  m(1, 3) = 0.0;
  m(2, 0) = 0.0;
  m(2, 1) = 0.0;
  m(2, 2) = 1.0;
  m(2, 3) = 0.0;
  m(3, 0) = 1.0;
  m(3, 1) = 2.0;
  m(3, 2) = 3.0;
  m(3, 3) = 1.0;

  Mat4 mi;
  bool invertible;
  m.computeInverseWithCheck(mi, invertible, 1e-24);
  assert(invertible);

  Mat4 mp;
  mp.noalias() = m * mi;
  std::cerr << mp << std::endl;

  return 0;
}
```
Compile with these flags to reproduce:
```
g++ main.cpp -std=c++11 -o main -I /usr/include/eigen3 -funsafe-math-optimizations -O2
```
It should print out the identity matrix.  If it does not, the invert was buggy.
