### ISSUE TITLE
Unable to install via pip

### ISSUE THREAD

**Issue by ZedCode** [panda3d/panda3d#231]
When trying to install via pip, I first create a new virtualenv and then attempt to execute the command on the home page:
```
$ virtualenv p3d         
Running virtualenv with interpreter /usr/bin/python2
New python executable in p3d/bin/python2
Also creating executable in p3d/bin/python
Installing setuptools, pip...done.
```
Then:
```
$ p3d/bin/pip install --pre --extra-index-url https://archive.panda3d.org/simple panda3d
Downloading/unpacking panda3d
  Could not find any downloads that satisfy the requirement panda3d
Cleaning up...
No distributions at all found for panda3d
Storing debug log for failure in /home/{$USER}/.pip/pip.log
```
It looks like it iterates over all of the available versions and subsequently states that each package it finds is not compatible with the version of python installed. I've tried using both Python 3.4 and 2.7.

Can someone tell me what's being searched for?

**Comment by rdb** [comment]
Could you share the `~/.pip/pip.log` file?

**Comment by ZedCode** [comment]
Hey rdb,

I put it in a gist here: https://gist.github.com/ZedCode/683f0f77ffd6610365f4423bcb4398d6

Thanks!

**Comment by rdb** [comment]
Hmm, that doesn't quite contain the information I was hoping for, could you run this instead?
```
p3d/bin/python -c "from pip import pep425tags;print('\n'.join([str(t) for t in pep425tags.supported_tags]))"
```

**Comment by ZedCode** [comment]
I sure can!

Python 3:
```
p3d/bin/python -c "from pip import pep425tags;print('\n'.join([str(t) for t in pep425tags.supported_tags]))"
('cp34', 'cp34m', 'linux_x86_64')
('cp34', 'abi3', 'linux_x86_64')
('cp34', 'none', 'linux_x86_64')
('cp34', 'none', 'any')
('cp3', 'none', 'any')
('cp33', 'none', 'any')
('cp32', 'none', 'any')
('cp31', 'none', 'any')
('cp30', 'none', 'any')
('py34', 'none', 'any')
('py3', 'none', 'any')
('py33', 'none', 'any')
('py32', 'none', 'any')
('py31', 'none', 'any')
('py30', 'none', 'any')
```
Python 2.7:
```
p3d/bin/python -c "from pip import pep425tags;print('\n'.join([str(t) for t in pep425tags.supported_tags]))"
('cp27', 'none', 'linux_x86_64')
('cp27', 'none', 'any')
('cp2', 'none', 'any')
('cp26', 'none', 'any')
('cp25', 'none', 'any')
('cp24', 'none', 'any')
('cp23', 'none', 'any')
('cp22', 'none', 'any')
('cp21', 'none', 'any')
('cp20', 'none', 'any')
('py27', 'none', 'any')
('py2', 'none', 'any')
('py26', 'none', 'any')
('py25', 'none', 'any')
('py24', 'none', 'any')
('py23', 'none', 'any')
('py22', 'none', 'any')
('py21', 'none', 'any')
('py20', 'none', 'any')
```
If you're doing any kind of OS detection, I'm on Bunsen linux, which is a fork of debian, but under the various `/etc/*-release` files, they put their own name in the most irritating places. It wouldn't be the first time that's been the root cause of a fairly automated installer to crash and burn.

**Comment by rdb** [comment]
Hmm, what's telling is that neither version claims to be manylinux-compatible, and the Python 2.7 build in particular oddly claims support for no ABI tag altogether.

Could you try dropping a `_manylinux.py` file in site-packages or wherever it will be importable in the virtualenv, containing this:
```
manylinux1_compatible = False
```
…and let me know whether it works with either version?

**Comment by ZedCode** [comment]
Hi rdb,

Neither version seemed to work for me. I tried both putting the `_manylinux.py` under `{venv}/lib/python{ver}/site-packages` as well as `{venv}/lib/python{ver}/site-packages/_manylinux` to no avail.

**Comment by rdb** [comment]
Strange.  (You set it to `True`, right?  I had originally submitted my reply saying it should be `False`, but edited my post subsequently.)

In the supported platform tags list for Python 3.4, I would have expected adding the file `{venv}/lib/python{ver}/site-packages/_manylinux.py` would have caused this to be added to the list of the command I gave previously:
```
('cp34', 'cp34m', 'manylinux1_x86_64')
```
Can you verify whether this is the case?  If not, please also verify whether you can import the `_manylinux` module from the Python interpreter.

**Comment by ZedCode** [comment]
My apologies, I did it before I saw the edit. Trying again now.

**Comment by ZedCode** [comment]
Same results, and the file is definately being picked up:
```
p3d/bin/python
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _manylinux
>>> dir(_manylinux)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'manylinux1_compatible']
>>> _manylinux.manylinux1_compatible
True
```

**Comment by rdb** [comment]
Hmm, well, something in your distribution's Python configuration is preventing it from being identified as a manylinux1-compatible distribution.  I don't know why the change to override the manylinux detection isn't working, assuming your version of pip is up-to-date, and your distribution doesn't ship modified files.

The information output by this script might help us narrow down what's weird about your distribution:
```python
import pip.pep425tags as tags
print(tags.get_abi_tag())
print(tags.get_platform())
print(tags.is_manylinux1_compatible())

from pip.utils import glibc
print(glibc.glibc_version_string())
```

**Comment by ZedCode** [comment]
So, before I went any further, I decided I should actually make sure I need everything to consume a wheel file in the manylinux specification and ran:
```
$ p3d/bin/pip install --upgrade pip setuptools wheel
```
After doing so, I was able to install. (Perhaps ensuring you've done that when using a virtual environment would be a helpful note if this issue exists outside of my snowflake OS)
