### ISSUE TITLE
panda3d lua 

### ISSUE THREAD

**Issue by xseano** [panda3d/panda3d#238]
hi when will u rewrite panda3d for lua, i need for my roblox plugin mod thingy thx

**Comment by theclashingfritz** [comment]
Really? Come on dude. Roblox?

**Comment by rdb** [comment]
Rewriting Panda3D is exceedingly unlikely.  It may be possible to create lua bindings for Panda3D, but this will have to be a community effort as all our development focus is on supporting Python as scripting language.

**Comment by xseano** [comment]
o ok thank

**Comment by JoelStienlet** [comment]
You could consider using the urho3d engine which has lua bindings:
https://urho3d.github.io/documentation/1.7/_lua_scripting.html
Other engines may also have support for lua though, best is to try out a few before making a decision.

**Comment by drewc5131** [comment]
![joke_over_head](https://user-images.githubusercontent.com/31282527/35411213-ef6c715c-01e5-11e8-988d-a5bcac989c93.jpg)

**Comment by xseano** [comment]
^

**Comment by rdb** [comment]
I've deleted some off-topic comments on this issue.  This is not a discussion forum, but a system for tracking issues and tasks.  Please bear in mind that there are many people watching this repository for important issues who get e-mailed on every comment, so there is absolutely zero room here for off-topic or frivolous comments.

Please take banter to the discussion forum, IRC or another medium.  All off-topic comments on the issue tracker will be deleted without warning and I will not hesitate to permanently block users upon repetition.
