### ISSUE TITLE
FMOD incompatible with statically-built applications

### ISSUE THREAD

**Issue by nosyliam** [panda3d/panda3d#240]
In lieu of OpenAL's instability (on OSX, atleast) I am attempting to use the FMOD sound library as a replacement. Its support on Panda3D does not support static applications, however, as it attempts to load a so library. Example log:
```
:audio(error):   load_dso(libp3fmod_audio.so) failed, will use NullAudioManager
:audio(error):     No error.
```

I'm fairly certain that this can be solved by a commit similar to 288452a8613cf4c0a1b31e7dc927d05be8b94cb0 but with FMOD instead.
(also as a side note for the same commit there should probably be support for loading a so, dylib, or dll based on platform)

**Comment by nosyliam** [comment]
Just to note, I was able to fix the issue myself on my panda branch by simply implementing the same fix as 288452a8613cf4c0a1b31e7dc927d05be8b94cb0.

**Comment by rdb** [comment]
Would you be willing to put that in the form of a pull request?

**Comment by nosyliam** [comment]
See #241
