### ISSUE TITLE
ODE math normalize issue, possible negative values?

### ISSUE THREAD

**Issue by AnythingTechPro** [panda3d/panda3d#247]
```
ODE INTERNAL ERROR 1: assertion "bNormalizationResult" failed in _dNormalize4() [../../include/ode/odemath.h:443]
Abort trap: 6
```

**Comment by Moguri** [comment]
Do you have an example file (or at least steps) to reproduce the issue with?

**Comment by rdb** [comment]
Or any information at all?  Without description, it's hard to tell whether you're trying to report a perceived bug in Panda3D or whether you're asking for help on the meaning or cause of the error.  The error is thrown by ODE and could indicate many issues, possibly in your models, application, or possibly Panda.

Note that when distributing your application, I would strongly recommend that you compile ODE in Release mode, which will disable such assertion errors.

**Comment by rdb** [comment]
Closing due to lack of response from reporter.
