### ISSUE TITLE
BulletVehicle wheels not rendered in sync with chassis

### ISSUE THREAD

**Issue by tophatpanda** [panda3d/panda3d#250]
I have created a bullet vehicle with four wheels, following the [manual](https://www.panda3d.org/manual/index.php/Bullet_Vehicles) -- specifically the chassis is parented to the vehicle's rigid body node and the wheels use BulletWheel.setNode() to assign a model to them.

The problem is that as the vehicle picks up speed, the wheels move ahead of the chassis:

When stationary:
![carwheelbug-stationary](https://user-images.githubusercontent.com/36481025/36340121-4ee8a1bc-13d6-11e8-8475-2a3b66a12b22.PNG)

When traveling at speed:
![carwheelbug-speeding](https://user-images.githubusercontent.com/36481025/36340122-520fcf78-13d6-11e8-9b93-cb796a8b9122.PNG)

Searching for the cause I didn't find anything on the forums or on GitHub. I did however find [a bullet forum post](https://pybullet.org/Bullet/phpBB3/viewtopic.php?f=9&t=1586&p=5984&hilit=chassis+position+bug#p5984) with a similar problem, which was caused by not properly handling bullet's interpolation.

I then had a look through the [bullet ForkLiftDemo](https://github.com/bulletphysics/bullet3/blob/master/examples/ForkLift/ForkLiftDemo.cpp), and noticed the following lines:

     //synchronize the wheels with the (interpolated) chassis worldtransform
     m_vehicle->updateWheelTransform(i,true);

Which sounds like it could be what's missing. (For reference, the function called is [btRaycastVehicle::updateWheelTransform](http://bulletphysics.org/Bullet/BulletFull/classbtRaycastVehicle.html#adf67ae421334225c886c3dc4c12fe1f2).)

I then started looking through the Panda3d code (mainly [bulletVehicle.cxx](https://github.com/panda3d/panda3d/blob/3eed7bc0427aa533db16fdcf0af402c1aaf11e35/panda/src/bullet/bulletVehicle.cxx) and
[bulletWheel.cxx](https://github.com/panda3d/panda3d/blob/3eed7bc0427aa533db16fdcf0af402c1aaf11e35/panda/src/bullet/bulletWheel.cxx)) and I can't seem to find the function updateWheelTransform() being called anywhere.

I don't have any experience with building panda from source so I haven't been able to test anything yet, but I suspect adding a call to updateWheelTransfom() in [BulletVehicle::sync_b2p](https://github.com/panda3d/panda3d/blob/3eed7bc0427aa533db16fdcf0af402c1aaf11e35/panda/src/bullet/bulletVehicle.cxx#L199) as such:

    for (int i=0; i < get_num_wheels(); i++) {
        _vehicle->updateWheelTransform(i, true);  // <==

        btWheelInfo info = _vehicle->getWheelInfo(i);
        ...

would solve the problem. Does this sound like a possible solution, and if so can anyone help me test it?

**Comment by tophatpanda** [comment]
I've put as minimal an example as I can make it on pastebin: https://pastebin.com/LgV3JXJq (using builtin models). Because of the size of the "wheels", its a bit hard to see the bullet debug renders until the "car" has reached sufficient speed. But eventually the blue lines appear:
![pandamobile](https://user-images.githubusercontent.com/36481025/36342538-7dfababa-1400-11e8-9478-99e6189301f5.PNG)

Tested with python 3.6 and panda3d 1.10.0.dev1333 (from

**Comment by JoelStienlet** [comment]
@tophatpanda I tried the change you suggested:
_vehicle->updateWheelTransform(i, true);
Its looking like the wheels keep a correct relative position to the red bounding box, but the panda is going out of the box now...
![screenshot from 2018-02-24 18-25-06](https://user-images.githubusercontent.com/9025534/36633143-71422b88-1990-11e8-924e-0e72439cfe9d.png)

**Comment by tophatpanda** [comment]
I've now managed to build panda3d from source.

Adding `_vehicle->updateWheelTransform(i, true);` does actually help lessen the problem, but as @JoelStienlet already said it does not solve them.

What `updateWheelTransform()` does remove is the kind of slow rubber-banding I would expect if the wheels weren't interpolated correctly. But they still gradually move ahead of the chassis.

So I tried an additional "fix": forcibly delaying the position of the wheels by one frame: and the problem disappeared.

Something is causing the wheels to be rendered one frame ahead of the chassis, but I don't yet now what...

One thing that may mean more to someone else: before delaying the wheel one frame, I noticed that they would every now and then "jump back" and be rendered in the correct place for a single frame. Because my second "fix" always delays the wheels, I would have expected them to still jump every now and then to be behind the chassis. But this does not happen, if I delay them then they are always rendered in the correct place.

(I'll continue to look into this, trying to find the differences between the rendering of the wheels and the chassis. Maybe it's something about btTransform/MotionState...)

**Comment by rdb** [comment]
This may be a silly question, but you are not using the multi-threaded rendering pipeline, are you?  This type of temporal glitch has popped up in the past with pipelined rendering, so it would be good to ensure you're not setting any kind of `threading-model` to rule that out as the issue.

**Comment by keithbriantomo** [comment]
http://www.mlmrecruitondemand.com/freevideo.php?id=jesrelgarcia21

On Thursday, May 10, 2018, tophatpanda <notifications@github.com> wrote:
> No, I'm not using the multi-threaded rendering pipeline.
>
> Although I'm not very familiar with it, so what I mean specifically is
that there is no threading-model in built_x64/etc/Config.prc or
built_x64/etc/Confauto.prc (I run panda directly from the build directory
once I've compiled it).
>
> I just tried temporarily adding a threading-model Cull/Draw line in
Config.prc (to see if anything would change), but I can't see any
difference. Except that windows tells me I'm using two more threads ;).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/XNajBGxT1mhQRbOepAdjwkGqYPWwHNbiwMMuG2Pl01UCqKHRF_WqaZcxIDjYRV5JYgLsEk3LM3Ib1j4ZNze9TbPFvp1Pmp5IkiOmKRzKtjX9gCcv0LI192Cgrv2n2KsVYhW_KodIZMxkb0pNirmEPzQpetXnbA=s0-d-e1-ft#https://github.com/notifications/beacon/AHN8yIeDS3yXc7MaybpQuCaUqXiyHpPjks5twytNgaJpZM4SJRJV.gif>

**Comment by tophatpanda** [comment]
The reason the wheels appeared to be one frame ahead of the chassis was that I had parented them to the chassis. Instead parenting them to `base.render` (as well the `updateWorldTransform()` call) solves the issue completely.

The reason you can't parent them to the chassis is that the wheels are synced before the chassis. First the wheels are moved to their new (global) position, moving them ahead of the chassis. Then the chassis is moved to its new (global) position -- but if the wheels are children of the chassis they will stay in the same position relative to the chassis: roughly one frame ahead of it.

**Comment by rdb** [comment]
Since parenting the wheels to the chassis does not sound unreasonable, perhaps we could prevent others from running into this issue by changing Panda to sync the chassis before the wheels?

**Comment by tophatpanda** [comment]
Yes that's easy enough, I already changed the order things are synced in briefly when debugging the problem.

Should I just move the wheels to be synced last? I just double checked that doing so makes the wheel keep their correct position regardless of whether they are parented to the chassis or `base.render`.

For reference, the new sync order would then be:
1. rigid bodies
2. soft bodies
3. ghosts
4. characters
5. vehicles (which only sync their wheels)

**Comment by rdb** [comment]
That would sound good to me, unless @enn0x has an objection to that.

**Comment by tophatpanda** [comment]
I added the change to the pull request, but noticed the sync-loops have been switched to range-based for loops. I'll merge and fixed those conflicts on my end before updating the pull request again.

**Comment by tophatpanda** [comment]
All done now, #349
