### ISSUE TITLE
rpmbuild fails: no *.desktop file

### ISSUE THREAD

**Issue by JoelStienlet** [panda3d/panda3d#260]
Hello,
I got a bug while building the panda3d rpm from 01b083579 (bug possibly much older) in fedora 27: rpmbuild in fakeroot complains about not finding *.desktop files.

Build command:
python3 makepanda/makepanda.py --threads 2 --nothing  --installer --rpmrelease 1 --verbose --use-sse2 --use-gl --use-python --use-direct --use-bullet --use-eigen --use-png --use-jpeg --use-zlib --use-x11 --use-pandatool --use-freetype --use-harfbuzz --use-egg --use-contrib

suggested fix: in panda3d.spec: remove /usr/share/applications/*.desktop

**Comment by JoelStienlet** [comment]
I also suggest a small change to the compiler options:
replace -std=gnu++11 by -std=c++11 in makepanda/makepanda.py
because the code doesn't require gnu extensions (it compiles well with c++11, with the options I enabled anyway) and it will avoid including code using them by mistake.

**Comment by rdb** [comment]
Hmm, does makepanda not write a `usr/share/applications/pview.desktop` file to the temporary directory created for packaging the RPMs?

We do use GNU extensions in the code, even though we don't strictly require them.  I see no reason to disable those.

**Comment by rdb** [comment]
Oh, I see, you are building with implicit `--no-pview`.  We should change makepanda to remove that line from the .spec file when building without pview enabled.
