### ISSUE TITLE
Generating Windows on Different X11 Displays

### ISSUE THREAD

**Issue by callendorph** [panda3d/panda3d#261]
I'm using Panda3d to create an emulation environment for a robot. I've been very successful using it for that purpose to date. I'm now at the point where I would like to emulate a USB camera by piping a Panda3d Camera that is viewing a scene through to a v4l2 loopback device that can be opened like a camera. 

My current path towards this was as follows: 
1.  Use [v4l2loopback](https://github.com/umlaeute/v4l2loopback) to create a V4L2 dummy device
1.  Generate a virtual buffer using Xvfb: `Xvfb :1 -screen 0 640x480x24`
2.  Use ffmpeg to capture this virtual buffer display and pipe it to a v4l2loopback 
```
$> ffmpeg -f x11grab -draw_mouse 0 -r 30 -s 640x480 -i :1.0 \
  -vcodec rawvideo -pix_fmt rgb24 -threads 0 -f v4l2 /dev/video1
```
4.  Run panda3d with `DISPLAY=:1.0 python emulator.py`

This all works as expected if the only open window in my emulator is the one camera that I want to drive. Frame rate is stable at 30 fps. Life is golden. 

Now I want to generate two stereo cameras. My first thought was generate two of all the things in steps 1-3 and then have my emulator create a new window in `DISPLAY=:1.0` and another window in `DISPLAY=:1.1` for each of the cameras. Unfortunately, I'm running into the issue that I can't really generate the two windows that I want to generate. In python, the `GraphicsPipe` is abstracted away depending on what `load-display` says and there is no way for me to pass an argument to `glxGraphicsPipe` to select `:1.1` or otherwise.

Honestly, I can't even find where the constructor for `glxGraphicsPipe` is being called. I'm guessing it is buried somewhere in the build code so that when you build for windows/mac/linux the appropriate library gets linked in and called. I have to say that in general, I've been super impressed by this project's documentation. But the docs for understanding how the build works, I either haven't found them or they don't exist. It makes it rather frustrating as someone new to looking at the code. I could probably get what I want by hacking the C++, if you could give me a hint as to where the constructor for the instantiated pipeline gets called.

I think there is another way to get what I want, which would be to use [Xpra](https://en.wikipedia.org/wiki/Xpra). This would act as a proxy between the panda emulator and each of the X11 displays and I think I could subsequently route to the display of my choosing. I really don't want to go this route because it adds yet another layer of indirection. My previous attempts have all incurred significant overhead and caused my frame rate at the output of the emulated USB camera to drop due to heavy OS layer interaction. 

Am I overlooking some simple way to do this? Is there a way to drive a `/dev/video*` video capture device directly with panda3d?

My use case is rather non-standard. The other use case I see for wanting to be able to set the `DISPLAY` variable is for unit testing on a server with xvfb. Additionally, I think that if I were making say, an arcade game, there may be cases where multiple displays would be involved (think [Time Crisis](https://en.wikipedia.org/wiki/Time_Crisis) for any kids of the 90's out there). 

Thanks in advance.

**Comment by callendorph** [comment]
K - I'll try that and see if I can't get something to work.

**Comment by callendorph** [comment]
Ok - So I tried what you suggested and I've had mixed success. If I run with `load-display p3tinydisplay` in my config file, then everything works exactly as I had planned. Unfortunately, it is very slow - as to be expected.

I think that I may have remembered incorrectly what I had previously accomplished with the single camera. I don't think I did that through xvfb, I think it was completed through the normal x server with opengl. When I try with xvfb, it is not able to run and has the following errors:

```
Xlib:  extension "XFree86-DGA" missing on display ":1.0".
:display:x11display(error): BadValue (integer parameter out of range for operation)
:display:glxdisplay(error): Could not find a usable pixel format.
:display:glxdisplay(error): No GLX context: cannot open window.
:display:gsg:glgsg(warning): Unable to query GL_VENDOR
:display:gsg:glgsg(warning): Unable to query GL_RENDERER
:display:gsg:glgsg(warning): Unable to query GL_VERSION
:display:gsg:glgsg(error): Unable to detect OpenGL version
:display:gsg:glgsg(warning): Unable to query GL_VENDOR
:display:gsg:glgsg(warning): Unable to query GL_RENDERER
:display:gsg:glgsg(warning): Unable to query GL_VERSION
:display:gsg:glgsg(error): Unable to detect OpenGL version
Assertion failed: removed at line 449 of panda/src/display/graphicsEngine.cxx
Traceback (most recent call last):
  File "src/sim/RobotEmu.py", line 989, in <module>
    gui = RobotVisApp(use_stereo = opts.stereo_mode)
  File "/home/callendorph/src/.../src/sim/RobotVis.py", line 80, in __init__
    self.setup_split_cameras()
  File "/home/callendorph/src/.../src/sim/RobotVis.py", line 175, in setup_split_cameras
    self.setup_separate_cam_windows(camNodes)
  File "/home/callendorph/src/.../src/sim/RobotVis.py", line 207, in setup_separate_cam_windows
    requireWindow=True
  File "/home/callendorph/src/.../venv/local/lib/python2.7/site-packages/direct/showbase/ShowBase.py", line 673, in openWindow
    win = func()
  File "/home/callendorph/src/.../venv/local/lib/python2.7/site-packages/direct/showbase/ShowBase.py", line 668, in <lambda>
    callbackWindowDict = callbackWindowDict)
  File "/home/callendorph/src/.../venv/local/lib/python2.7/site-packages/direct/showbase/ShowBase.py", line 794, in _doOpenWindow
    props, flags)
AssertionError: removed at line 449 of panda/src/display/graphicsEngine.cxx
```
Note that the XFree86-DGA warning exists in both the tiny display and pandagl display configurations. 

So I tried instead to load `pandagl` for the main app and use `tinydisplay` for just the emulated camera view by trying: 
```
	disps = [":1.0", ":1.1"]

	props = WindowProperties.getDefault()
	props.setOrigin(0,0)
	props.setSize(640,480)
	props.setFixedSize(True)

	loadPrcFileData("","load-display p3tinydisplay")
	loadPrcFileData("", "display {}".format(disps[i]))
	base.pipe = None
	base.makeDefaultPipe()


	win = base.openWindow(
		props, makeCamera=False, type="onscreen",
		requireWindow=True
	)
```
 
But this fails as well because it seems that the attempt to load `p3tinydisplay` gets ignored. It seems that because `pandagl` was previously loaded for the main app, it doesn't attempt the `tinydisplay` for the secondary windows. Maybe I'm doing something wrong.

If I run `glxinfo -display :1.0` I get similar errors to above so it seems to me like xvfb is not including the GLX extension. I've updated the invocation of xvfb to:

```
$> Xvfb :1 -screen 0 640x480x24 -screen 1 640x480x24 +extension GLX +extension RANDR +extension XFIXES +render
```
But I still can't seem to get it to work. As it stands I think this is not a Panda3d issue but a xvfb issue.

Anyway, please feel free to close as you wish. I do think a nicer interface for selecting the display to run a window on would be nice but not super high priority.

**Comment by rdb** [comment]
You may want to try a software implementation of OpenGL.

Rather than using `makeDefaultPipe`, you could use `base.makeModulePipe('p3tinydisplay')` to pass in the desired render plugin.  However, you need to manually assign the result to `base.pipe`.

**Comment by callendorph** [comment]
> You may want to try a software implementation of OpenGL.

Yes - I'm working on trying [virtualgl](https://virtualgl.org/) next. 
  
> base.makeModulePipe('p3tinydisplay')

Got it - I'll try that too. 

Thanks for all your help!

**Comment by callendorph** [comment]
Setting the default pipe using `makeModulePipe` does work but it is still painfully slow (3fps).

It seems that others are [having this same problem](https://unix.stackexchange.com/questions/410443/xvfb-glxgears-fails) which indicates a xvfb problem. Anyway - thanks for the help.
