### ISSUE TITLE
Error with argparse's importing [deploy-ng]

### ISSUE THREAD

**Issue by cflavio** [panda3d/panda3d#264]
If I create this file _main.py_:

```
import argparse
```

With this file _setup.py_:

```
from setuptools import setup


setup(
    name='example',
    options = {
        'build_apps': {
            'gui_apps': {'example': 'main.py'},
            'platforms': ['manylinux1_x86_64']
        }
    }
)
```

With this file _requirements.txt_:

```
--pre --extra-index-url https://archive.panda3d.org/branches/deploy-ng
panda3d
```

Then I make a build with _deploy-ng_:

```
$ python setup.py bdist_apps
```

It is correctly built. But, when I run the build, I obtain this:

```
$ ./example 
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "/usr/lib/python2.7/argparse.py", line 85, in <module>
    import collections as _collections
  File "/usr/lib/python2.7/collections.py", line 20, in <module>
    from _collections import deque, defaultdict
ImportError: No module named _collections
```

I've tested it with the last build of deploy-ng.

**Comment by Moguri** [comment]
I am having trouble reproducing this on my system (Arch Linux). I'm guessing you saw this on Ubuntu? I will try to spin up a Docker container to test this. I suspect our logic to handle differences in builtins is not working quite right.

**Comment by cflavio** [comment]
Yes, it happens on Ubuntu. Thanks!

**Comment by rdb** [comment]
@cflavio could you verify whether it is fixed in the latest builds?

**Comment by cflavio** [comment]
Yes, it works, thank you!
