### ISSUE TITLE
"Freeze" in "BulletHelper.fromCollisionSolids"?

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#265]
In the current state of the "main" branch (as of a few hours ago at time of writing, I think), attempting to load a large level results in the game seemingly doing nothing: the level-loading never finishes, as though it were frozen, but there also seems to be very little CPU activity.

Attempting to load a smaller level seems to succeed.

It _looks_ as though the problem lies with "BulletHelper.fromCollisionSolids", as commenting out that line, and the section that relies on it, allows the large level to load successfully. (Commenting out the latter section but leaving in the call to "fromCollisionSolids" seems to confirm that the problem lies with that call, and not somewhere in the aforementioned section.)

Based on a "git bisect", the problem appears to have been introduced in commit with the following ID: 9afdb78d947e51ce84e09a4885ff3c3895f8bc4e. (Which I believe was made on Wednesday, the 21st of February.)

**Comment by Moguri** [comment]
This sounds like dead lock to me (especially looking at the commit you pointed out). Do you have an example that can be used to reproduce the issue?

**Comment by ArsThaumaturgis** [comment]
Right, I think that I've isolated it enough for a minimal example. As far as I see at the moment, it seems to turn up when "fromCollisionSolids" is given a collision object that both is intangible (i.e. has the "intangible" key-word in the "Collision" tag of its egg-file) and has a non-identity transformation matrix. Removing either of those points--either making the matrix the identity, or making the object no longer "intangible"--seems to result in the error not arising.

Minimal example:
A relevant egg file (zipped):
[cube.egg.zip](https://github.com/panda3d/panda3d/files/1771611/cube.egg.zip)

Loading it with the following short program should show the bug--specifically, it should print "Starting...", but not print "Done! :D".

Code:
`from direct.showbase.ShowBase import ShowBase
from panda3d.bullet import BulletHelper

class GameFramework(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)
        base.disableMouse()

        print "Starting..."

        model = loader.loadModel("cube")
        collection = BulletHelper.fromCollisionSolids(model, True)
        print collection

        print "Done! :D"

# Let the game begin!
gameFramework = GameFramework()
gameFramework.run()`

**Comment by rdb** [comment]
@deflected, perhaps you are willing to take this on?

**Comment by deflected** [comment]
@rdb, It should be fixed in #266.

**Comment by rdb** [comment]
Merged #266 into master, many thanks!  Thaumaturge, please close the issue if you find it to be fixed.

**Comment by ArsThaumaturgis** [comment]
Ah, wonderful! It does indeed seem to be working now! Thank you very much, all! ^_^

May I request that this fix be merged into the "deploy-ng" branch? I'm trying to produce a build using deploy-ng, which I believe means working with that branch.

**Comment by rdb** [comment]
@ArsThaumaturgis done in 43914f4e758524f2583dd3bb60bc83529195dcb7.  Linux buildbots are up-to-date, others are still building.
