### ISSUE TITLE
ConnectionRepository issue with Python 3.5

### ISSUE THREAD

**Issue by Ghost-0** [panda3d/panda3d#268]
Hi, i'm using the latest Panda3D from the devel area on website but whenever my program nears the end of reading the DC file, i get:
`  File "C:\Panda3D-1.10.0\direct\distributed\ConnectionRepository.py", line 336, in readDCFile`
   ` if type(classDef) != types.ClassType and type(classDef) != types.TypeType:`
`AttributeError: module 'types' has no attribute 'ClassType'`

Wondering if there's some simple fix i can do? It appears to be removed in Python 3.5 all together..

**Comment by CFSworks** [comment]
You are correct that `types.ClassType` is removed in Python 3 - all classes in Python 3 are actually first-class types. So, deleting `type(classDef) != types.ClassType and ` from line 336 of that file will suffice as a workaround.

I'll commit a fix that'll get worked into the next devel build, if you'd prefer to wait instead. :)

**Comment by CFSworks** [comment]
Fixed by ac8417ffdf0f253d8c2653b9a27becee1833778c
