### ISSUE TITLE
"Confined" mouse-mode seems to be lost after focus-loss

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#280]
If the game-window is set to use the "confined" mouse-mode, and then subsequently loses focus, the confinement seems to be lost: after returning focus, the mouse can be moved out of the game-window freely.

(This also happens if the window is dragged, I think.)

A minimal example:

Code:
```
from direct.showbase.ShowBase import ShowBase
from panda3d.core import WindowProperties

class GameFramework(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)
        base.disableMouse()

        wp = WindowProperties()
        wp.setMouseMode(WindowProperties.M_confined)
        base.win.requestProperties(wp)

gameFramework = GameFramework()
gameFramework.run()
```

Test:
Run the program above. You should find that the mouse is confined as expected. Now, press alt-tab to switch focus, then press it again to return focus. You should find (if the issue is present on your side) that the window now has focus, but with the mouse free to move beyond its bounds.

**Comment by rdb** [comment]
I could reproduce this easily on X11, which I assume you're testing this on.

Could you check whether it's fixed now?

**Comment by ArsThaumaturgis** [comment]
It'll be a few hours before I'm in a good position to download, but I'll get back to you once I've done so, I intend! Thank you for the speedy fix! ^_^

However, I should note that I've seen this under both Ubuntu and Windows (8.1), I believe. (If Windows 8.1 uses X11, then ignore! ^^; )

**Comment by ArsThaumaturgis** [comment]
Okay, I've tested it, and it doesn't seem to work on my side, I'm afraid. :/

Based on some simple testing, it appears that it's getting to the new code, but that the "if (_properties.get_mouse_mode() == WindowProperties::M_confined)" test is failing.

**Comment by Moguri** [comment]
@ArsThaumaturgis a5ad186a663c15d1d3cf3832a3c2ee95417ee917 appears to fix the issue for me. Can you see it if fixes this issue for you as well?

Windows does not use x11, so we will still need to look into this on the Windows side.

**Comment by ArsThaumaturgis** [comment]
I can confirm that the mouse's behaviour seems to be as expected now! Thank you very much for your work on this. ^_^
