### ISSUE TITLE
HTTPChannel sends unwanted Content-Type header

### ISSUE THREAD

**Issue by nosyliam** [panda3d/panda3d#296]
Every time an HTTPChannel begins a new request, it'll call `reconsider_proxy` in turn calling `make_headers` which will write an unwanted Content-Type header. This is particularly detrimental to web applications that specifically require different content types, such as `application/json`. https://github.com/panda3d/panda3d/blob/f5f51c5d5b82e19993fe002282884a08bc694a10/panda/src/downloader/httpChannel.cxx#L3627

**Comment by rdb** [comment]
It looks like it would be a simple change to add getters and setters for the content type to HTTPChannel.  Anyone willing to submit a PR?
