### ISSUE TITLE
Calling base.loader.loadSfx crashes Panda

### ISSUE THREAD

**Issue by ksmit799** [panda3d/panda3d#303]
I'm using build [753ae39](https://github.com/panda3d/panda3d/commit/753ae3974079ec54a49315381cecc091f25692ff) from the Panda3D snapshot builds. When attempting to call `base.loader.loadSfx(<someAudioResource.mp3>)`, the window stops responding within seconds. Using an older build of 1.10.0 doesn't seem to have the same issue.

This problem can be duplicated using the following code (Python 2.7):

> from panda3d.core import *
> from direct.showbase.ShowBase import ShowBase
> 
> base = ShowBase()
> 
> testSound = base.loader.loadSfx('exampleAudio.mp3')
> 
> base.run()

**Comment by rdb** [comment]
I am unable to reproduce this. Could you share a bit more information?
* Which operating system / architecture are you using?
* Does it happen for all .mp3 files, or only some?
* Does it also happen for .ogg or .wav files?

**Comment by ksmit799** [comment]
Tested on two different PC's running Windows 10 64-bit. The crash happens when trying to load an mp3 file (ogg works fine) that is under ~6 seconds in length.

**Comment by kamgha** [comment]
Can you provide your `exampleAudio.mp3`, please?

**Comment by Moguri** [comment]
@ksmit799, do you have a sample file that you can provide?
