### ISSUE TITLE
Add the ability to initiate a callback event when an interval is complete. 

### ISSUE THREAD

**Issue by AnythingTechPro** [panda3d/panda3d#307]
I’ve found that it would be quite useful to add the ability to specify a callback event when an interval is complete, this goes for any kind of intervals...

**Comment by rdb** [comment]
This already exists:
```python
interval.setDoneEvent("event")`
```

Not only that, but [as of recently](https://www.panda3d.org/blog/november-2017-development-update/), `interval.start()` returns a future, which is even more flexible. It lets you specify a callback function to call, or an event to throw upon completion, you can even await it from a coroutine or block a thread waiting for the interval to finish if you so like.

```python
fut = interval.start()
fut.setDoneEvent("my_event")
fut.addDoneCallback(myPythonFunction)
```

The difference between the first approach (interval.setDoneEvent) and the latter approach (via the future returned by `start()`) is that the former will persist even when the interval is done, ie. it will be called a second time when the interval is started and finishes a second time, whereas the future will only work once.
