### ISSUE TITLE
Bam file export of Bullet node crashes when the transform cache is disabled

### ISSUE THREAD

**Issue by rrssl** [panda3d/panda3d#310]
Hi, 

I'm running panda3d version 1.10.0.dev1505 with python 3.5 on Ubuntu 16.04.

For reasons similar to those described in [this thread](https://discourse.panda3d.org/t/memory-leak-in-bullet-code/13303/9), I disabled the transform cache. This worked fine until I tried to export the scene to a bam file. I got the following error: 

```
Assertion failed: !(*si).second._written_seq.is_initial() at line 530 of panda/src/putil/bamWriter.cxx
Segmentation fault (core dumped)
```

Upon inspection, it appears that the offender is a BulletRigidBodyNode with a BulletShape initialized with a TransformState. Here's a minimal example:

```python
from panda3d.bullet import BulletRigidBodyNode, BulletBoxShape
from panda3d.core import NodePath, TransformState

from panda3d.core import load_prc_file_data
load_prc_file_data("", "transform-cache 0")
# Also fails with
# load_prc_file_data("", "garbage-collect-states 0")

body = BulletRigidBodyNode("body")
shape = BulletBoxShape((1, 1, 1))
body.add_shape(shape, TransformState.make_pos((1, 0, 0)))
np = NodePath(body)
np.write_bam_file("crash.bam")
```

Thanks in advance.

**Comment by rdb** [comment]
Thanks, this should be fixed now.
