### ISSUE TITLE
FFmpeg: Warning at EOF due to API change

### ISSUE THREAD

**Issue by kamgha** [panda3d/panda3d#315]
FFmpeg will emit a warning when a video file is being played and reaches its EOF since this commit at FFmpeg: http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=a606f27f4c610708fa96e35eed7b7537d3d8f712

`:ffmpeg(warning): Invalid return value 0 for stream protocol`

To fix this issue, line 228 in panda/src/ffmpeg/ffmpegVirtualFile.cxx needs to be changed from `return 0;` to `return AVERROR_EOF;`.

It may need to be elaborated whether that code block needs to be put into a #ifdef checking libavformat being in a version before/after the 29th October 2017.

**Comment by rdb** [comment]
Has libav made a similar change?

**Comment by kamgha** [comment]
No, the parts in libav look like being unchanged.

**Comment by keithbriantomo** [comment]
http://www.mlmrecruitondemand.com/freevideo.php?id=jesrelgarcia21

On Tuesday, May 8, 2018, kamgha <notifications@github.com> wrote:
> No, the parts in libav look like being unchanged.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/282XEp37YGXuFbnZN88bZU9h4OYgkrS4e9lPYFDeRkGZkTKCyNR3q6Yq0Boerxb5d41_wAiPGv3e0dJPhNdYdEzKXzZcpBatC6pyIZyYsCD2U2VyW65aFV7xo-iYQZM6IQOm7OEaex0wkExGwPchr_yhZicM8w=s0-d-e1-ft#https://github.com/notifications/beacon/AHN8yNOiZyuX7e9Sqzh-TEB8yib7Jhtiks5twYl_gaJpZM4T0MhX.gif>

**Comment by CFSworks** [comment]
Both FFmpeg 1.1 and libav 9.20 (the oldest versions supported by Panda) treat a negative return value from `read_packet` the same as zero (i.e. they always test the return value with `len > 0` or `len <= 0`)

The AVERROR codes are always negative, so returning an AVERROR (of any kind) will be treated by these old versions the same as zero.

I'll go ahead and commit the suggested change.
