### ISSUE TITLE
PandaAI : P3D App crashes if an AICharacter instance in not stored in some form.

### ISSUE THREAD

**Issue by UFaction** [panda3d/panda3d#318]
If an instance of AICharacter is not 'stored' outside of the function calling it, the Panda3D app crashes as soon as 'AIWorld.update()' is run.
The app will freeze with a 'Python has stopped working' message, and returns `Process finished with exit code -1073741819 (0xC0000005)`, `Process finished with exit code 255` or sometimes an `AssertionError` in the console upon forceful exit. Whichever it is has tended to change seemingly at random.

By 'stored', I mean to write...
`self.AIchar = AICharacter("seeker",self.seeker, 100, 0.05, 5)`
...instead of just:
`AIchar = AICharacter("seeker",self.seeker, 100, 0.05, 5)`
'self' is used as an example. One can store it in anything. This works, for example:
```
class Storage():
    AIchar = None

def makeaichar():
   Storage.AIchar = AICharacter("seeker",self.seeker, 100, 0.05, 5)
```

Even just storing the instance in the initial call is enough to prevent crashes. I.e., this works:
```
Storage.AIchar = AIchar = AICharacter("seeker",self.seeker, 100, 0.05, 5)
AIworld.addAiChar(AIchar)

```

I'm not sure if this is just a logical consequence of how PandaAI is structured and thus works as intended,  but since storing the AICharacter is not mentioned as necessary in the manual, I assume not.

I've not done too much testing, maybe performing or not performing similar operations on other PandaAI modules might either break it further or fix this issue.

The issue should be reproduceable with the "PandaAI Basic Tutorial" provided in the P3D manual. Simply remove any storage for 'AIchar' in 'setAI' and it should crash on start.

**Comment by rdb** [comment]
This looks to be a design issue in PandAI; the AICharacter class is not reference counted and therefore it will be destroyed when the last Python reference to it goes out of scope, even if there are still references to it in the C++ code.

The fix here is fairly simple; making AICharacter inherit from ReferenceCount and replace pointers to it with smart pointers.  Anyone willing to take on this task?

**Comment by theclashingfritz** [comment]
@rdb Seems simple. I'll see if i can if i have time.

**Comment by rdb** [comment]
I have checked in a fix and added some safety checks, could you please test whether it is working well for you now?

**Comment by UFaction** [comment]
@rdb I can confirm, it seems to work now. P3D doesn't crash anymore if the AI character is exclusively local to the function creating it. Thank you very much for your work!
