### ISSUE TITLE
Remove `using namespace std;`

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#335]
It's not considered good style to indiscriminately pull in everything from `std`, especially not in a public header that is included by user code.

I would propose the following steps towards phasing this out:
- [x] 1. Replace `using namespace std;` in `dtoolbase.h` with `using std::x;` for each x that we use from `std` without prefix.  This may be a pretty long list at first.
- [x] 2. Start using `std::` prefix for most std types in all `.h` and `.I` files, with few exceptions (eg. swap).
- [ ] 3. As we finish affixing `std::` to our use of standard types in headers, move the relevant `using` declarations for the respective types to the C++ files that use them, or better yet, to the function bodies that would benefit from it.

@cfsworks thoughts?  Good idea or waste of time?

**Comment by CFSworks** [comment]
@rdb Any kind of "best practice" cleanup gets my approval. I've also been pondering the idea of going even further and putting all Panda3D symbols in a `panda3d::` namespace, or perhaps even `panda3d::core::` to mimic the Python namespacing (we could have a `using namespace panda3d;` in our public headers to avoid breaking existing user code).

Regarding step 3: I think we should only have a `using` in a C++ file if the symbol in question is used enough times that it makes sense. (For example, `using std::atomic` makes sense in the context of threading code, but not in the context of a file that only ever creates one `std::atomic`.)

I'd be happy to get on this after I finish my nullptr changes.

**Comment by rdb** [comment]
I've just addressed 1 in e0245d2777f096fd4cb1c1ea852dd7d3ef34c197; there is a list of `using` declarations in `dtoolbase_cc.h`:
https://github.com/panda3d/panda3d/blob/e0245d2777f096fd4cb1c1ea852dd7d3ef34c197/dtool/src/dtoolbase/dtoolbase_cc.h#L164-L189

**Comment by CFSworks** [comment]
Checking second box per 7790f84.

As for the third box: As I mentioned elsewhere I have a local branch that doesn't even use `using`, but it messes up alignment in a few cases and leads to very verbose constructs like `std::cout << std::setw(2) << std::hex << std::setfill('0') << ... << std::dec << std::endl;` so in many cases, I'd say `using` is still appropriate.

The challenge is figuring out where a `using` makes more sense than `std::` qualification, in a programmatic way. I was thinking I'd just identify files that would have 3 or more lines changed by the `std::` qualification and instead give a `using`, but this leads to weird cases where std::cout might have a using but std::cerr is qualified (if std::cerr appears only twice). So, I'm thinking I should first try to identify "related" std names and lump them all together. For example, cout/cerr would be related - a file that uses both would either have a `using` for both or `std::cout`/`std::cerr` and never mix the two.

@rdb Any thoughts on this? Or is the suggestion of `using` more of a shortcut and I'm defeating the point of the shortcut by overanalyzing it?

**Comment by rdb** [comment]
I don't think we're going to find a clear-cut answer to where using `std::` makes sense vs. where using `using` makes sense, so it doesn't make much sense to spend too much time thinking about it.  There might be a point to make to avoid unnecessary changes to existing source files, so what you proposed makes sense, but I'd be equally fine if you decided to spend less time on this and chose to use either `using` or 'std::' for every occurrence of cerr and cout.
