### ISSUE TITLE
Feature request: Particle "burst emission"

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#340]
There are cases in which it's handy to be able to generate a "burst" of particles, potentially more than one in a given frame. Think of weapons-fire impacts; for multiple in a frame, imagine a hit-scan shotgun.

To my mind, the obvious approach to handling this is to have a "template" particle effect, and to simply have it emit briefly at each of the desired points.

Panda's particle system doesn't currently support this (as far as I'm aware). There is at least one workarounds (using "softstop" and a "doMethodLater" call, I think it was), but it's awkward, and seems unlikely to work for multiple "bursts" per frame.

What I suggest, then, is a new method in ParticleEffect. This would take a position parameter, and for each system in the effect, create a single "litter" of particles placed relative to that point. Ideally, multiple calls in a single frame would create multiple "litters".

What do you think?

**Comment by ArsThaumaturgis** [comment]
All right, I've looked into this, and I have a proposed patch to implement it.

One thing that I'll say is that I haven't examined the code carefully, so it's possible that something that I've done is a bad idea in some way or another. If so, then please correct me as called for!

The core change is to expose "ParticleSystem"'s "birth_litter" method to Python. One concern is that it seems possible to me that this was excluded from Python access for some particular reason. Since I don't know what that reason was, I am a little hesitant to expose it. However, right now it looks like the best approach, to me.

The "induce_labor" method does exist--but it works by setting the timer variable that the system uses during its update method to determine when to spawn particles. It might be possible to work around thus to allow for multiple "bursts" (perhaps by calling "update" in the proposed "burst" method), but it doesn't seem ideal.

Finally, a big question (for me, at least) is that of how to approach an effect's parent and render-parent. With normal particle-emission, this is handled by the call to "start". We could do the same for burst emission, but since it's intended to be called often, I've opted for a more lightweight approach. Instead, what I've done is added a separate method intended to be called before the use of "burst emission", which both sets the parent and render-parent, and enables the effect.

With all that said, my patch:
[patch.txt](https://github.com/panda3d/panda3d/files/2130329/patch.txt)


And a quick test-program:
```
from direct.showbase import ShowBase as showBase
from direct.particles.ParticleEffect import ParticleEffect
from panda3d.core import Vec3, PandaNode

import random

class game(showBase.ShowBase):

    def __init__(self):
        showBase.ShowBase.__init__(self)

        self.setBackgroundColor(0, 0, 0)

        self.enableParticles()

        self.effect = ParticleEffect()
        self.effect.loadConfig("mew.ptf")

        self.effect.prepareForBurstEmission(render, render)

        self.accept("space", self.emitBurst)

    def emitBurst(self):
        for i in xrange(random.randint(3, 10)):
            pos = Vec3(random.uniform(-5, 5), 15, random.uniform(-5, 5))
            self.effect.setPos(pos)
            self.effect.emitBurst()


app = game()
app.run()
```

With a simple test particle-effect:
(It's a ".ptf" file--I've just renamed it to ".txt" so that GitHub will accept it.)
[mew.txt](https://github.com/panda3d/panda3d/files/2130330/mew.txt)

Does this seem good?

**Comment by BMaxV** [comment]
Hey, can you create a pull request? Makes it easier to see what you changed and to review the change.

**Comment by ArsThaumaturgis** [comment]
I can try--I'm honestly not all that familiar with GitHub. If I get this wrong, then my apologies! ^^;

**Comment by rdb** [comment]
Yes, that's the way to do it.

**Comment by ArsThaumaturgis** [comment]
Okay. In that case, I think that after the work that I'm doing at the moment, I'll download a build to see whether the solution given in #388 works for that issue, then update my local repository and start figuring out how to do the above. Give me some time! I'll hopefully report back when I have news.

**Comment by ArsThaumaturgis** [comment]
It occurs to me that I should perhaps have left a comment to mention that I've created the requested "pull request". It should be found here: #389
