### ISSUE TITLE
CollisionTube is a misnomer

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#347]
It should be called CollisionCapsule, because the shape is mathematically a capsule (aka spherocylinder) and not a tube.

I suggest we rename it but keep a type alias for older code and for compatibility with older .bam files.

**Comment by CFSworks** [comment]
:+1:

To be clear to others who might take on this issue: This will need a .bam minor bump, and the writing code will need to be sure to use the CollisionTube type when writing earlier bams.

**Comment by Moguri** [comment]
+1 from me. Seems confusing to call a capsule a tube. Capsule is also what Bullet calls this shape.

**Comment by theclashingfritz** [comment]
On that note including a actual Tube collision type would be quite nice for the future. +1 from me.

**Comment by Moguri** [comment]
@rdb do we want to tackle this for 1.10?

**Comment by rdb** [comment]
I was hoping to.  Main obstacle is having some system for writing the type out with an older name when writing older .bam files.
