### ISSUE TITLE
FFmpeg: Add 1-component pixel format

### ISSUE THREAD

**Issue by kamgha** [panda3d/panda3d#352]
The current implementation for FFmpeg supports 3-component (`BGR24`) and 4-component (`BGRA`) pixel formats. A 1-component pixel format (e. g. `GRAY8`) would reduce the load on the system for 1-component video streams and complement other existing texture formats (e. g. `F_luminance` or `F_alpha`).

A use-case is a multi-textured face with a video stream in `BGR24` format and second video-texture for alpha-transparency in `GRAY8`. The current implementation would convert the `GRAY8` video to `BGR24`, hence using more memory and bandwidth.

**Comment by rdb** [comment]
Could you provide a grayscale video for testing?

**Comment by kamgha** [comment]
This contains a grayscale video (FFV1 codec in NUT container): A gray box moving on a black background.

[gray.zip](https://github.com/panda3d/panda3d/files/2098860/gray.zip)

Created with:

`ffmpeg -framerate 25 -i sequence%03d.png -pix_fmt gray -c:v ffv1 gray.nut`
