### ISSUE TITLE
weak pointer issues (c++)

### ISSUE THREAD

**Issue by consultit** [panda3d/panda3d#367]
In the last commits I found that some polymorphic conversions between `PointerTo` and `WeakPointerTo` do not work as before and are no longer equivalent to the conversions between `std::shared_ptr` and `std::weak_ptr`, as was the case before.
Here I reported the `main.cpp` file that shows this:
```
#include <memory>
#include <modelNode.h>

using namespace std;
class B
{
public:
	virtual ~B()
	{
	}
};
class D: public B
{
};

int main(int argc, char** argv)
{

	// panda3d polymorphism
	{
		PT(PandaNode)sB;
		PT(ModelNode) sD(new ModelNode("geomnode"));
		sB = sD; //conversion shared D -> shared B

		WPT(PandaNode) wB;
		WPT(ModelNode) wD(sD);
//		wB = wD; //conversion weak D -> weak B - doesn't work anymore
		wB = sB;//shared to weak assign
//		wB = sD;//conversion shared D -> weak B - doesn't work anymore
	}

	// c++11 polymorphism
	{
		shared_ptr<B> sB;
		shared_ptr<D> sD(new D());
		sB = sD; //conversion shared D -> shared B

		weak_ptr<B> wB;
		weak_ptr<D> wD(sD);
		wB = wD;//conversion weak D -> weak B
		wB = sB;//shared to weak assign
		wB = sD;//conversion shared D -> weak B
	}

	return 0;
}

```
As indicated the cases `wB = wD` and `wB = sD` (commented) no longer work with panda3d.
I ask if it is a deliberate choice or a mistake casually introduced in the last changes?
Bye

PS: command used to build `main.cpp`:
`g++ -I/usr/include/panda3d -I/usr/include/eigen3 -O0  -std=c++11 -L/usr/lib/x86_64-linux-gnu/panda3d/ -lpanda -lp3dtool -lp3dtoolconfig -lpandaexpress -o main main.cpp`

**Comment by rdb** [comment]
Thanks for bringing this issue to light.  It looks like WeakPointerTo will need new constructor templates similar to the ones PointerTo has now.

**Comment by consultit** [comment]
Perhaps this can help solve.
In `express/weakPointerTo.h` I removed the keyword `explicit` from
```
INLINE operator const T * () const;
```
both for `WeakPointerTo` and for `WeakConstPointerTo` and everything is back to work.

**Comment by rdb** [comment]
No, you should not do that.  That cast is not at all thread-safe so the `explicit` keyword was added to prevent it from being invoked by accident.  Using it could invoke spurious crashes and assertions in your application.  The thread-safe `lock()` method was added as alternative to the cast, mirroring `std::weak_ptr`, although it is primarily for weak→shared conversion and would be overkill to use for weak→weak conversion.

It also would not fix the conversion from shared D to weak B in your example.  I think what we need here is to create WeakPointerTo template constructors, mirroring PointerTo and the C++11 `std::weak_ptr` [constructor overloads](https://en.cppreference.com/w/cpp/memory/weak_ptr/weak_ptr).

**Comment by consultit** [comment]
OK thanks.
I will wait for the official implementation, and in the meantime I will use the previous version to continue developing.
Bye

**Comment by rdb** [comment]
Should be fixed now.  Apropos, I have also added a C++11-style `owner_before` method to WeakPointerTo as well as `std::owner_less` specializations for using weak pointers as keys in a map or set.

**Comment by consultit** [comment]
@rdb unfortunately there are still some problems. The previous program, with the addition of some other tests, does not build correctly:

```
#include <memory>
#include <modelNode.h>
using namespace std;
class B
{
public:
	virtual ~B()
	{
	}
};
class D: public B
{
};

int main(int argc, char** argv)
{

	// panda3d polymorphism
	{
		PT(PandaNode) sB(new ModelNode("m1"));
		PT(ModelNode) sD(new ModelNode("m2"));
		PT(PandaNode) sB1(sD);
		sB = sD;

		{
			WPT(PandaNode) wB(sD);
			WPT(ModelNode) wD(sD);
			WPT(PandaNode) wB1(wD);//XXX
			WPT(PandaNode) wB1rr(move(wD));//XXX
			wB = wD;//XXX
			wB = move(wD);//XXX
			wB = sB;
			wB = sD;
		}

		//constness
		{
			WPT(PandaNode) wB(sD);
			WPT(ModelNode) wD(sD);
			WCPT(PandaNode) wCB(sD);
			WCPT(ModelNode) wCD(sD);
			WCPT(PandaNode) wCB1(wCD);//XXX
			WCPT(PandaNode) wCB1rr(move(wCD));
			wCB = wCD;//XXX
			wCB = move(wCD);
			wCB = sB;
			wCB = sD;
			wCB = wB;
			wCB = move(wB);
			wCB = wD;//XXX
			wCB = move(wD);
		}
	}

	// c++11 polymorphism
	{
		shared_ptr<B> sB(new D());
		shared_ptr<D> sD(new D());
		shared_ptr<B> sB1(sD);
		sB = sD;

		{
			weak_ptr<B> wB(sD);
			weak_ptr<D> wD(sD);
			weak_ptr<B> wB1(wD);
			weak_ptr<B> wB1rr(move(wD));
			wB = wD;
			wB = move(wD);
			wB = sB;
			wB = sD;
		}

		//constness
		{
			weak_ptr<B> wB(sD);
			weak_ptr<D> wD(sD);
			weak_ptr<const B> wCB(sD);
			weak_ptr<const D> wCD(sD);
			weak_ptr<const B> wCB1(wCD);
			weak_ptr<const B> wCB1rr(move(wCD));
			wCB = wCD;
			wCB = move(wCD);
			wCB = sB;
			wCB = sD;
			wCB = wB;
			wCB = move(wB);
			wCB = wD;
			wCB = move(wD);
		}
	}

	return 0;
}

```
Places with errors are indicated with XXX.

**Comment by rdb** [comment]
Thanks for the great test case!  I've checked in some fixes, can you try it now?

**Comment by consultit** [comment]
I have tested and everything seems to work. ;)
