### ISSUE TITLE
Model has T_vertex color type after calling set_color_off

### ISSUE THREAD

**Issue by Epihaius** [panda3d/panda3d#371]
Any model, even one without vertex colors, will report having `T_vertex` as its color type after calling `set_color_off` on it:

```
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase


class MyApp(ShowBase):

    def __init__(self):

        ShowBase.__init__(self)

        smiley = self.loader.load_model("smiley")
        smiley.reparent_to(self.render)
        smiley.set_color_off()
        # the following returns 0, i.e. T_vertex, while T_off seems more appropriate
        # (the model doesn't even have any vertex colors)
        print("color attrib:", smiley.get_state().get_attrib(ColorAttrib).get_color_type())


app = MyApp()
app.run()
```

Shouldn't it be `T_off` instead?

Tested with Panda version 91b01e5, Python 3.6 64-bit on Windows 10.

**Comment by rdb** [comment]
It looks like this behaviour is intended, judging from the documentation of `set_color_off`.  I'll let others weigh in on whether this behaviour is desirable.

Note that if the ColorAttrib is set to `T_vertex`, it will still effectively be `T_off` (ie. white) if the model has no vertex colours.

**Comment by rdb** [comment]
That said, even if I do add a ColorAttrib with mode `T_off`, it seems that the vertex colours are still used, instead of ignored as I would expect.  There seems absolutely no difference between `T_off` and `T_vertex`.  I am of mind to change this; I think `T_off` really should make Panda3D ignore the vertex colours altogether.

**Comment by Epihaius** [comment]
That does seem to make sense. In that case, the current behaviour of `set_color_off` should not be changed, or it would no longer be possible to make it show the vertex colours of a GeomNode whose parent has a scene-graph colour.

On a related note, I just noticed that calling this method with a priority value higher than zero behaves in a strange way:
when I create a hierarchy of 4 cards that are each parented to the previously created card, setting the priority to any value higher than zero always leads to the exact same situation, namely that all descendent cards lose their colour. It doesn't matter what card I call this method on, what cards I apply a scene-graph colour to, or what value I pass in for the priority parameter (1, 2, 3, ...). Is this normal? (Huh, it happens with `NodePath.set_color` too. Maybe I just don't understand how priorities work?)

**Comment by rdb** [comment]
Yeah, I'm going to make `T_vertex` the default, and keep that as what is set when you do `set_color_off`, despite the confusing naming.

That sounds like how I'd expect the priorities to work.  The attribute with priority value higher than 0 will take precedence over all the other nodes which have a priority value of 0 set on the attribute.

**Comment by Epihaius** [comment]
Ah, I see! My understanding was indeed flawed as I thought that the priority value referred to the place (lower level) a node occupies in a hierarchy. Thanks for the explanation!

**Comment by rdb** [comment]
I think I'm going to close this now as `wontfix`, but I'm keeping the option open of fixing the method call name in the future.
