### ISSUE TITLE
Case for T_half_float missing in gobj Texture::do_get_clear_data()

### ISSUE THREAD

**Issue by Moguri** [panda3d/panda3d#374]
Can this just share the same case as T_float?

```
In file included from panda/src/gobj/p3gobj_composite2.cxx:14:                                     
panda/src/gobj/texture.cxx:5599:11: warning: enumeration value 'T_half_float' not handled in switch
      [-Wswitch]                                                                                   
  switch (cdata->_component_type) {                                                                
          ^                                                                                        
```

**Comment by rdb** [comment]
No, a half float is a 16-bit float, so this would require code to pack a regular floating-point value into a 16-bit float (which will involve some fiddly bitshifting).

We could also just add the case for now, have it zero the data and print an error message saying that clearing half-float textures with a non-zero value is not currently supported.
