### ISSUE TITLE
Compilation error in Visual Studio 2017 15.8

### ISSUE THREAD

**Issue by bluekyu** [panda3d/panda3d#379]
https://github.com/panda3d/panda3d/blob/5147674980d3d81314bbe3e5ddbad4c01e9ffc21/panda/src/egg/eggVertexPool.cxx#L680

In recent Visual Studio 2017 15.8, the code occurs compilation error.
(this did not happen in the previous version.)

In "putil/iterator_types.h", `second_of_pair_iterator` class does not have `operator++(int)` overloading, so returning value of post-increment operator is `pair_iterator`, not `second_of_pair_iterator`.
Therefore, while copying, `*iterator` will return `std::pair` value, not second value of pair.

This can be resolved by simple changes:
```cpp
for (const IndexVertices::value_type& v: _index_vertices)
    verts.push_back(v.second);
```
But I did not make a patch because I did not know if it is suitable.

**Comment by rdb** [comment]
I think we should just provide properly overloaded increment operators on `second_of_pair_iterator` (and the others defined in that file).

**Comment by bluekyu** [comment]
However, I found template instantiation problem in `std::copy`.
In compiler output, some template arguments are not correct, so `second_of_pair_iterator` adaptor disappears.

I think increment operator overloading may not solve this issue.
After further analysis, I will reply again.

**Comment by bluekyu** [comment]
I found the same issue in VS developer community: https://developercommunity.visualstudio.com/content/problem/311111/iterators-unwrapped-to-raw-pointers-bypassing-deri.html

This issue is caused by only MSVC 15.8 because of STL implementation.
