### ISSUE TITLE
PandaFramework should call init_memory_hook()

### ISSUE THREAD

**Issue by CFSworks** [panda3d/panda3d#381]
Got a segfault while trying to run a statically-built Debug-built pview binary, because it constructs `PandaFramework` at static initialization time, which in turn uses the `new` operator to create an `EventHandler` - this can happen before `init_memory_hook()` has a chance to make the `new` operator valid.

I would change it myself, but am not fully decided on whether `PandaFramework` should call `init_memory_hook()` directly, or if the `EventHandler`/`EventQueue` should do it in their `make_*` methods.

**Comment by rdb** [comment]
The latter.  I think anything that might be run at static init time that needs to use `operator new` should first call `init_memory_hook();`.  It would also catch cases where these might be invoked in other user code at static init time.  `AsyncTaskManager::make_global_ptr` should probably do it too.

For what it's worth, we should really discourage creating a PandaFramework at static init time.  It's just a bad idea for reasons like this one.  But we've had this so long in sample code that it's worth fixing these kinds of issues.
