### ISSUE TITLE
[bug] [Ubuntu 18.04] Confined mouse mode restricts mouse movement even when a panda3d application is not in the foreground

### ISSUE THREAD

**Issue by ibispi** [panda3d/panda3d#393]
My panda3d version: panda3d-1.10.0.dev1756+deployng
My OS: Ubuntu 18.04

After Alt-Tabbing into another application on Ubuntu 18.04, the mouse is still restricted as in the panda3d application with the confined mouse mode enabled.

**Comment by ArsThaumaturgis** [comment]
Oddly, I'm using the same version of Panda, I believe, but I don't seem to see that behaviour: I can move the mouse freely once I've alt-tabbed to another program. (I do, however, have other issues under confined mode.)

I'm using Ubuntu 16.04 ("Xenial")--perhaps some change was made between versions of Ubuntu?

That said, I've only tested this when running from the IDE--I haven't tested it with a distributable build of my game.

**Comment by Moguri** [comment]
Assigning to myself to see if I can reproduce this. I am pretty sure I have run into this before.

**Comment by Moguri** [comment]
I can reproduce this on Arch Linux with KDE/KWin by running the mouse-modes sample program.
