### ISSUE TITLE
Error loading model files bundled with Panda3D

### ISSUE THREAD

**Issue by Epihaius** [panda3d/panda3d#395]
It seems that since build 3ac50a2 of Panda3D, the models distributed with Panda can't be found anymore when trying to load them, even though the resulting error message lists the directory where they are indeed residing (`<panda_dir>/etc/../models`).
When I move e.g. `smiley.egg.pz` to the Panda install directory itself (`<panda_dir>/etc/..`) it is also not found.
Moving the model file to the current working directory fixes the problem, so it's only with those two specific directories that things go wrong.

Now I do see there were some changes related to prc searchpath vars (d6b7abe) and DSearchPath (aacafe7) in this build, so these might be the cause.

A simple call to `base.loader.load_model("smiley")` should throw an error similar to the following:

`:loader(error): Couldn't load file smiley.egg: not found on model path (currently: "/d/my_project;/d/Panda3D-1.10.0-x64/etc/..;/d/Panda3D-1.10.0-x64/etc/../models")`

Haven't tried all the samples, but at least the teapot model can't be loaded when trying to run the looking-and-gripping sample.

This happens on Windows 10 with Panda3D build 3ac50a2 (Python 3.6 64-bit).

**Comment by rdb** [comment]
Could it be that the paths with `$THIS_PRC_FILE` aren't working correctly?

**Comment by Epihaius** [comment]
> Could it be that the paths with `$THIS_PRC_DIR` aren't working correctly?

Yes, `$THIS_PRC_DIR/..` and `$THIS_PRC_DIR/../models` are the paths that were causing the error.

> Could you check if the latest commit fixes this issue? It fixes a crash I found reading out the search path; but I wonder if in your case you were simply getting undefined behaviour instead of the same crash.

It all works fine now, so it must have been due to that same crash then.
Thank you very much for the fix!
