### ISSUE TITLE
How should we deliver optimized wheels?

### ISSUE THREAD

**Issue by Moguri** [panda3d/panda3d#396]
Currently wheels are built with optimize=3, which is good for development. However, we should offer builds that use optimize=4 when users want to publish/deploy their applications. This is particularly important for deploy-ng. As far as I remember, we have discussed the following approaches in the past:

* Different index - deploy-ng can use a different index-url to grab optimized wheels. This keeps the package and versions the same. However, [pip does not have a way to enforce order of search paths](https://pip.pypa.io/en/stable/reference/pip_install/#finding-packages).
* Different version -  we could manipulate versions to give preference to optimized builds (e.g., 1.10.0.0 for SDK vs 1.10.0.1 for optimized). This would have to be combined with a different index to avoid having to lock down version numbers for requirements (e.g., could use 1.10.* vs 1.10.0.0).
* Different package - if the optimized builds are under a different package name (e.g., panda3d-opt) then deploy-ng can swap out panda3d requirements for panda3d-opt when building. This adds the overhead of maintaining two packages.

I am not really thrilled with these options, and I think this will mostly come down to picking the "least bad" option. Using a different package seems the cleanest and least hacky way (from an abusing pip perspective), but could result in a lot of duplicated effort to maintain two packages. Maybe we can write scripts to help facilitate this? The different index+version could be fairly simple to implement, but we'll need to make sure the versioning scheme works with dev builds (especially non-master dev builds).

If this is a requirement for 1.10 (which I think it should be), we'll need to get this resolved sooner rather than later.

**Comment by rdb** [comment]
> * Different index - deploy-ng can use a different index-url to grab optimized wheels. This keeps the package and versions the same. However, [pip does not have a way to enforce order of search paths](https://pip.pypa.io/en/stable/reference/pip_install/#finding-packages).

One way to address this is to add a [local version tag](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers), such as `+opt`, to the builds on the separate index. This would ensure they always sort as "more recent" than the non-optimized builds, but less recent than a version number increment. I don't really like using a version number increment for something that is just a different build configuration; it seems the local version tags were meant exactly for that.

> The different index+version could be fairly simple to implement, but we'll need to make sure the versioning scheme works with dev builds (especially non-master dev builds).

Would we want an optimized version of master commit N to sort as more or less recent than a non-master build that branched off at commit N?  If we go with the above, we could probably decide this by how we choose the local version tag.  That said, I suppose people should not be adding both the index for optimized builds *and* the index for whatever non-master branch they use to their `requirements.txt`.

**Comment by Moguri** [comment]
+1 for using local version tags. Since these get added to the end, I believe they should have no impact on our version strings for dev builds.

I think optimized wheels should take precedence. I agree that both optimized and non-optimized should not be present in requirements.txt files, but I plan to just have deploy-ng add the optimized index, which would have the same effect (both indexes being searched).

**Comment by Moguri** [comment]
Optimized wheels are now available on archive.panda3d.org (e.g., http://archive.panda3d.org/branches/deploy-ng/opt)
