### ISSUE TITLE
Memory leak in MovieTexture.read()

### ISSUE THREAD

**Issue by kamgha** [panda3d/panda3d#398]
It looks like `MovieTexture.read()` has a memory leak.  This is very significant when higher resolution video files are involved.  See attached sample for reproduction.

[ml-MT-GH.zip](https://github.com/panda3d/panda3d/files/2428948/ml-MT-GH.zip)

**Comment by rdb** [comment]
I can confirm.  I looked into this for a while but the only thing I managed to find out so far was that it's an issue in the ffmpeg decoder, and that it stops happening when I take out the call to `avcodec_receive_frame` (which is a critical step of the decoder).  It might be a bug in ffmpeg, but more likely it's some ffmpeg-related structure that we should be flushing or freeing.
