### ISSUE TITLE
mutexPosixImpl.I:54

### ISSUE THREAD

**Issue by c0pypasten1nja** [panda3d/panda3d#402]
greetings

may i request help on the error encountered:

python: built-cp27-cp27mu/include/mutexPosixImpl.I:54: void MutexPosixImpl::acquire(): Assertion `result == 0' failed.
Aborted (core dumped)

trying to execute 
https://github.com/art-programmer/FloorplanTransformation/blob/master/rendering/renderer.py

on ubuntu 16.04 with Python 2.7.12 and Panda version: 1.9.4

many thanks in advance

**Comment by rdb** [comment]
I think this issue has already been fixed.  I would suggest updating to the latest development version.

**Comment by c0pypasten1nja** [comment]
got it thank you very much
