### ISSUE TITLE
Assertion failed: _pipe == nullptr & window == nullptr

### ISSUE THREAD

**Issue by c0pypasten1nja** [panda3d/panda3d#403]
greetings

may i request help on the error encountered:

Assertion failed: _pipe == nullptr at line 173 of panda/src/display/graphicsOutput.cxx
Assertion failed: _window == nullptr at line 61 of panda/src/display/displayRegion.cxx
Assertion failed: _window == nullptr at line 61 of panda/src/display/displayRegion.cxx

trying to execute
https://github.com/art-programmer/FloorplanTransformation/blob/master/rendering/renderer.py

on ubuntu 16.04 with Python 2.7.12 and Panda version: 1.10.0

**Comment by rdb** [comment]
Are there any other errors?  I just ran into this, and I will check in a fix momentarily, but the issue happens for me when buffers are prematurely closed due to the existence of other errors.

**Comment by c0pypasten1nja** [comment]
here are the errors for https://github.com/art-programmer/FloorplanTransformation/blob/master/rendering/renderer.py :

E0602:Undefined variable 'loadPrcFileData'
E0602:Undefined variable 'NodePath'
E0602:Undefined variable 'AmbientLight'
E0602:Undefined variable 'VBase4'
E0602:Undefined variable 'base'
E0602:Undefined variable 'Texture'
E0602:Undefined variable 'PointLight'
E0602:Undefined variable 'render'
E0602:Undefined variable 'PNMImage'
W0612:Unused variable 'i'

i am not sure i have the panda3d core module installed...

i had replaced the file panda/src/display/graphicsEngine.cxx with the fix but the Assertion failed errors persist

**Comment by c0pypasten1nja** [comment]
i can execute the sample programs even though there are errors as well:
E0611:No name 'TextNode' in module 'panda3d.core'
E0611:No name 'TransparencyAttrib' in module 'panda3d.core'
E0611:No name 'LPoint3' in module 'panda3d.core'
E0611:No name 'LVector3' in module 'panda3d.core'
E0602:Undefined variable 'loader'
E0602:Undefined variable 'camera'
E0602:Undefined variable 'base'
E0602:Undefined variable 'taskMgr'
E0602:Undefined variable 'globalClock'

**Comment by rdb** [comment]
What are these errors coming from?  They look like warnings coming from a linter about unused variables in your code, not errors from Panda3D or Python.

I'm going to need to see the actual program output from Panda3D and Python, not the output from your linter tool.

**Comment by c0pypasten1nja** [comment]
like this?
~/FloorplanTransformation-master/rendering$ python renderer.py
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
LVecBase2f(1, 1)
(600, 351)
(11, 5)
(11, 2)
Assertion failed: _pipe == nullptr at line 173 of panda/src/display/graphicsOutput.cxx
Assertion failed: _window == nullptr at line 61 of panda/src/display/displayRegion.cxx
Assertion failed: _window == nullptr at line 61 of panda/src/display/displayRegion.cxx

**Comment by rdb** [comment]
Closing due to no response (and due to the fact that I already fixed a bug that produced the same error messages).  I will reopen if someone tells me the bug still occurs in latest master.
