### ISSUE TITLE
Setting a colour-scale overrides vertex-colours.

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#404]
It seems that, when a colour-scale is applied via "NodePath.setColorScale", the new colour-scale is applied as expected, by vertex-colours are lost. (Visually, at least; I haven't tested to see whether they remain accessible either from a shader or by attempting to access the data within the geometry.)

(It seems that this issue was[ reported a few years ago on the forum](https://discourse.panda3d.org/t/setcolorscale-destroys-vertex-colors/13629), but the original poster didn't follow up on it.)

A simple test-case:
[BugHunt.zip](https://github.com/panda3d/panda3d/files/2440090/BugHunt.zip)

Contents:
 - "cube.egg"--A simple model of a cube, made in Blender. It has arbitrary vertex-colours, and a material applied to it.
 - "bugHunt.py"--A short test-program. It loads two copies of "cube.egg" and places them side-by-side. One is left as loaded, while the other has a grey colour-scale applied.

On my system, the un-scaled cube shows up with the expected colours. The other, however, instead of showing dimmed colours, appears entirely grey, I believe.

Panda version: 1.10.0.dev1756+deployng.236
OS: Ubuntu 16.04 ("Xenial")

**Comment by Epihaius** [comment]
If you don't mind my input on this matter, I would like to report that after altering your code sample by adding a light source to illuminate the model with the colour scale, the vertex colours do show up dimmed as expected.
Removing the MaterialAttrib from the RenderState associated with the Geom of that model also fixes the problem, although that is probably not what you want.

So there does appear to be some inconsistency going on with the effect of a material on vertex colours in the absence of lighting, although I'm not sure this qualifies as a genuine bug in Panda, as materials really do need a light source to work correctly.

Not entirely unexpected, it seems that a call to `NodePath.set_alpha_scale()` (with an alpha value other than 1.0) also causes this issue to occur.

**Comment by ArsThaumaturgis** [comment]
Very interesting! Thank for your that input. ^_^

Annoyingly, it looks as though YABEE (or the version thereof that I have, at least) requires that a material be present in order to export vertex-colours--even if the "Force export vertex colors" option is checked. That makes it awkward to export a model with vertex colours that are intended to be tinted, but not lit--especially if the model in question is also intended to have a texture applied. (As in the case of a tintable backdrop that I intend.) But perhaps in this case the answer is for me to further modify my copy of YABEE.

As to the inconsistency, it does seem unexpected, and thus perhaps worth addressing.

**Comment by rdb** [comment]
Note that you can also tick the "Shadeless" option in the Material (together with "Vertex Color Paint") in order ot get an unlit material that takes vertex colours into account.  However, it sounds like a YABEE bug that it requires a material to export vertex colours even with "Force export vertex colors" selected, and you should probably report that there.

**Comment by ArsThaumaturgis** [comment]
Ah, I didn't know about that option! Thank you very much for mentioning it--I can confirm that it does indeed produce a model that both has vertex colours and tints as expected! :D

As to YABEE, perhaps I should do that, indeed. It may perhaps be worth suggesting some of my other changes to my local copy of YABEE for integration into the project (perhaps with some cleaning up), come to that.

**Comment by ArsThaumaturgis** [comment]
So, that just leaves the question of whether the inconsistent behaviour of non-shadeless materials is something worth fixing, or whether this issue should be closed. I'm inclined to think that the inconsistency is likely to be surprising to users (as it was to me). However, since materials aren't intended to be used without lights, save when specified as "shadeless", it might be argued that it's undefined behaviour anyway.

**Comment by rdb** [comment]
Hmm, this is more complicated than I thought.

The material specified in the .egg file contains an ambient colour, but not a diffuse colour.  This is supposed to mean that the diffuse colour is taken from the vertex colours, whereas the ambient colour is as specified (all-white, in this case).

What seems to be going on here is that when you have no lights applied, and no colour scale, Panda3D simply ignores the material, displaying the vertex colours.  The moment you apply a colour scale, Panda3D enables the lighting pipeline in order to apply that colour scale by pretending there is an ambient light with color (1, 1, 1, 1).  All of a sudden this means that the material is no longer ignored, which now overrides the vertex colours.

(Incidentally, when I manually apply an AmbientLight, it seems to no longer care about the color scale and just displays the vertex colours, which seems like a different bug altogether—applying an ambient light should actually be producing the behaviour you are seeing.)

Since it seems established behaviour that the material is ignored altogether when there is no light applied, I think we should continue to do this even if there is a colour scale applied.

**Comment by ArsThaumaturgis** [comment]
I think that what you say makes sense, in particular that last paragraph: that would seem to be a reasonably expectable behaviour.

That said, it also seems odd to me that the material is overriding the vertex colours entirely, as described in the second paragraph of your last post above. And as you say further above, those colours are used elsewhere.

So, I'm inclined to support changing the behaviour of the engine in both cases (and of course in the "manual ambient light" bug, too), such that vertex colours are used consistently.

As to YABEE, I see that the latest commit on the project's GitHub page is two years old. Is it still being maintained?

**Comment by ArsThaumaturgis** [comment]
Just a quick note to mention that I've created a fork and a pull request on the YABEE GitHub repository. I have a few proposed changes in the pull request, including the exportation of vertex-colours when no material is present, I believe.

**Comment by ArsThaumaturgis** [comment]
That sounds excellent--thank you for the work done here! ^_^
