### ISSUE TITLE
Feature request: Python tags in bam files

### ISSUE THREAD

**Issue by wezu** [panda3d/panda3d#409]
Any json serializable (to keep them safe) python tags should also be kept when writing (and later reading) bam files

**Comment by rdb** [comment]
This is doable, but also opens a bit of a can of worms.  Which types do we and don't we need to support here?  This depends on how we serialize:

* The obvious answer might be to pickle whatever is thrown at it, but this has security issues as .bam files downloaded from the internet may contain malicious code.
* JSON works, but it's clumsy to embed a text-based format inside a binary file, and JSON is also limited.  Users might get confused why the ints they put into it get returned as floats, or the tuples as lists.
* We could use *insert serialization library here*, but I would strongly prefer not to make a dependency on thirdparty libraries just to be able to read .bam files with this particular feature.
* We could use some custom, very simple binary serialization scheme.  Then the question becomes how far we want to go with this.  Do we want to support dictionaries?  Frozensets?  Pointers to other TypedWritable objects?  Classes?  Custom serialization functions?  This becomes a bit of a slippery slope, so I would not like going ahead with this without setting some strict limits on what we intend to make achievable using this feature.

**Comment by wezu** [comment]
I asked for this under the assumption that one can't put a json serialized string in a tag (node.set_tag() not node.set_python_tag()), but I was wrong, you can do that - for this new perspective, I think it would require too much effort to make it safe and would offer little more then node.set_tag('python_tags', json.dumps(node.get_python_tags())).  
I think the issue can be closed, at least until Python has a safe, sandbox pickle module.
