### ISSUE TITLE
Support DirectX 12?

### ISSUE THREAD

**Issue by theclashingfritz** [panda3d/panda3d#413]
I noticed DirectX 9 is supported but 12 is not. Would be nice to have DirectX 12 support in the future.

**Comment by Moguri** [comment]
If someone was willing to write and (more importantly) maintain a DX12 backend, I'm sure a PR would be welcome. However, the current efforts are around a Vulkan backend.

**Comment by rdb** [comment]
There seems to be no good reason to spread our development efforts and support Direct3D 12 when we can instead support Vulkan, which is at least as powerful and far more widely supported (even on Windows).

Closing this for now, although we can reopen it if our plans change.  Also see #339.
