### ISSUE TITLE
Window flickers on macOS Mojave 10.14 with included Python 2.7.10

### ISSUE THREAD

**Issue by jwcotejr** [panda3d/panda3d#414]
So this is a bit of an interesting issue, but luckily there is at least one solution. After building Panda3D successfully after resolving the issue noted on #412, I encountered an issue where the window would flicker, demonstrated [here](https://www.youtube.com/watch?v=CeJW6-WPdaA). This video demonstrates two scenarios: the first scenario is attempting to run a ShowBase instance using /usr/bin/python2.7 (The included copy of Python 2.7 in macOS, which on Mojave is 2.7.10), and the second scenario is attempting to run a ShowBase instance using python (Python 2.7 installed via Homebrew, which is 2.7.15). You'll notice that running Panda3D under the copy of Python 2.7 installed via Homebrew works as intended, but running Panda3D under the copy of Python 2.7 provided by Apple results in window flickering. This will likely be something worth noting in the README for macOS.

**Comment by xseano** [comment]
Brilliance.

**Comment by rdb** [comment]
This is quite odd.  I have no idea how it might be possible for the Python version to affect rendering issues like this.

**Comment by PiotrDabkowski** [comment]
I have the same issue, but with both the homebrew installed Python and the Apple suplied Python.

**Comment by xseano** [comment]
@PiotrDabkowski Are you sure you're using Homebrew installed Python v2.7.15? I've tested this temporary solution on multiple platforms and it works.

**Comment by PiotrDabkowski** [comment]
@xseano yes, I have installed the SDK for Mac before running pip install so maybe this caused the problem...

**Comment by PiotrDabkowski** [comment]
It seems the cause is not the version of the python but the compiler version.
The newest brew python (that I have installed) and the built-in python **both** were built under `[... LLVM 10.0.0 (clang-1000.0.42)]`. Your brew python you were testing was built with older clang 9xx, I guess if you update your python to the newest build it it will start flickering as well. 
I have downgraded to older 2.7.15 build (clang 600) and it works fine now.

**Comment by treamology** [comment]
I am seeing the same issue with the built in LLVM 10 python. My homebrew LLVM 9.1 python does not have this issue, however. I'm going to try futzing around with this later.

**Comment by jwcotejr** [comment]
Indeed, Python 2.7 that is built with LLVM 10 is ultimately what results in the flickering window, though I am unsure as to how this should be handled. For now, using Python 2.7 that is built with LLVM 9.1 isn't an issue, and likely won't be for some time, but that means installing a very specific build of Python 2.7, which is less than desirable.

**Comment by jason-kane** [comment]
The ppython from 10.7 dmg at http://www.panda3d.org/download.php?platform=macosx&version=1.9.4&sdk flickers like crazy in the demos (mojave 10.14, AMD Radeon R9 M370X 2048 MB, Intel Iris Pro 1536 MB)

**Comment by treamology** [comment]
This fix is in the 1.10 release. You can download it from the releases page here on GitHub or wait for the prebuilt version, which will presumably be up on the main site in the next day or two.

**Comment by jason-kane** [comment]
I can confirm that 1.10 from https://github.com/panda3d/panda3d/releases is a massive improvement, no visible flicker.
