### ISSUE TITLE
Changing an undecorated window produces freeze

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#415]
It seems that, on my machine at least, attempting to set window-properties (via a call to "requestProperties") on a window that has been made "undecorated" can result in the computer freezing. (Specifically, the mouse still moves, but the computer doesn't respond to keyboard or mouse inputs, in the Panda program or otherwise. This seems to be a not-uncommon set of symptoms in freezes under Ubuntu.)

This only seems to happen if the call to "requestProperties" happens after the program's "`__init__`" function--at a guess, this may be because the window has yet to be created during "`__init__`".

Operating system: Ubuntu 16.04 ("Xenial")

I'm using a deploy-ng build downloaded on the 12th of September, I believe.

[edit]
Since this involves windowing, it may be worth mentioning that I use the Cinnamon front-end for Ubuntu. Specifically, I believe that I have version 2.8.6.
[/edit]

The following is a short test-progam that displays this behaviour on my system. I haven't tested which of the "loadPrcFileData" calls are important, beyond the one that sets the "undecorated" value, or whether other window-properties than setting the size prompt it: this behaviour locks up my computer, and I'm not sure of how to recover control without forcibly shutting down the machine.

On being run, the program should be responsive for about two seconds, at which point the method that changes the window-properties should be run, resulting in the computer freezing (with my machine, at least).

```
from panda3d.core import loadPrcFile, loadPrcFileData
from direct.task import Task
loadPrcFileData("", "undecorated 1")
loadPrcFileData("", "win-origin 1400 -2 ")
loadPrcFileData("", "win-size 800 600")


from direct.showbase import ShowBase as showBase
from panda3d.core import WindowProperties

class game(showBase.ShowBase):

    def __init__(self):
        showBase.ShowBase.__init__(self)

        self.accept("escape", self.userExit)

        self.model = loader.loadModel("panda")
        self.model.reparentTo(render)
        self.model.setPos(0, 50, -5)

        taskMgr.doMethodLater(2.0, self.mew, "mew")

    def mew(self, task):

        wp = WindowProperties()
        wp.setSize(1280, 1024)
        base.win.requestProperties(wp)

        return Task.done


app = game()
app.run()
```

**Comment by rdb** [comment]
We'll need more information about your window manager.  In dwm at least it seems to work fine.

**Comment by ArsThaumaturgis** [comment]
I'm not sure of what to add about it. ^^; What do you want to know, specifically?

Cinnamon is the default front-end for Linux Mint, I believe, but can also be used with Ubuntu. I think that I've read that it's somewhat popular (as far as Ubuntu front-ends go), but I'm not sure.

I can experiment with the Unity front-end and see whether it occurs there. I'll report back once I've done that, I intend.

**Comment by ArsThaumaturgis** [comment]
Aha! I think that I've found at least part of the problem!

As indicated above, I tried running the game using the Unity front-end. The problem didn't occur--but then, oddly, the window wasn't undecorated. A quick search to see whether Unity perhaps didn't support undecorated windows produced nothing. I found nothing of interest.

I did, however, notice that the window seemed to very briefly be undecorated before it was resized by my options system.

So I tried adding "setUndecorated(True)" to all my (relevant) window-property objects--I update various window properties in a number of places. And indeed, this seemed to result in the window remaining undecorated under the Unity front-end--and without freezing!

I returned to the Cinnamon front-end, and with the new code in place found that the game no longer froze there!

So, it looks as though the problem may be twofold: First, that when window-properties are changed via "requestProperties", the "undecorated" flag (at least as set in the PRC file) seems to be reset. And second, that when this happens to a window that was initially undecorated, under Cinnamon at least the computer hangs as described above.

The latter may well be an issue in Cinnamon. The former is somewhat surprising--if I'm not much mistaken, window-properties generally only change if they're explicitly requested.

**Comment by Moguri** [comment]
I do not get a crash with i3 nor Plasma (KDE5).

**Comment by ArsThaumaturgis** [comment]
Since my original post, I've updated to Ubuntu 18.04, and am using its Gnome windowing manager (if I recall the latter correctly). I just tested my example-code above, and the problem doesn't seem to occur for me any more: the window changes size and remains undecorated, and the computer remains responsive.

So, between the shift in my experience and what @Moguri reports above, it looks like it may be an issue with some windowing managers and/or versions of Linux: some freeze, some continue to work but make the window decorated, and some work as expected. o_0

**Comment by rdb** [comment]
Is there someone who uses Cinnamon who can try to reproduce the above problem?

**Comment by el-dee** [comment]
Tested on a Linux Mint derived from Ubuntu Xenial, Cinnamon 3.2.7 and latest 1.10.x branch: there is no crash or freeze.

However, as @Moguri  and @ArsThaumaturgis mentioned, the window becomes decorated when the window properties are updated.

**Comment by rdb** [comment]
This issue is four years old, does it still occur with the latest stable Panda3D version?

**Comment by ArsThaumaturgis** [comment]
I've long since ceased using Cinnamon as my front-end, but a quick test in Ubuntu 18.04 with a current version of Panda seems to show that the windows behaves just as expected: it resizes, remains undecorated, and produce no freeze.

I think that this can be closed now.

**Comment by rdb** [comment]
OK, thanks, we can reopen / refile if it affects someone else.
