### ISSUE TITLE
deadlock on TextNode::write 

### ISSUE THREAD

**Issue by yosagi** [panda3d/panda3d#431]
TextNode::write block and never returns. Traceback:
```
#1  0x00007f7c55549023 in __GI___pthread_mutex_lock (mutex=0x5568ab236b70) at ../nptl/pthread_mutex_lock.c:78
#2  0x00007f7c52a5cfc9 in TextNode::do_get_internal_geom() const () from /usr/lib/x86_64-linux-gnu/panda3d/libpanda.so.1.10
#3  0x00007f7c52a5d086 in TextNode::output(std::ostream&) const () from /usr/lib/x86_64-linux-gnu/panda3d/libpanda.so.1.10
#4  0x00007f7c526ac89d in PandaNode::write(std::ostream&, int) const () from /usr/lib/x86_64-linux-gnu/panda3d/libpanda.so.1.10
```
 TextNode::write recursively lock its mutex. 1st in TextNode::write https://github.com/panda3d/panda3d/blob/3b7b9cd18cc3c4e7b1ba8979c525a9f25c4547ea/panda/src/text/textNode.cxx#L294 and 2nd in TextNode::do_get_internal_geom called by TextNode::output https://github.com/panda3d/panda3d/blob/3b7b9cd18cc3c4e7b1ba8979c525a9f25c4547ea/panda/src/text/textNode.cxx#L731
I didn't dig into a detail of Mutex implementation, but is it recursive mutex?

Minimal code to reproduce this problem:
```
 from panda3d.core import *
 print TextNode('t')
```
Tested environment:
panda3d1.10-dev1865 on ubuntu 18.04 bionic

**Comment by rdb** [comment]
The default Mutex is non-reentrant.  Thanks for catching this!  The solution is to move the MutexHolder one line down.  I'll check this in shortly.
