### ISSUE TITLE
Python version in installer packages

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#441]
In 1.9.4, we only offically supported Python 2.7.  In 1.10, we support 2.7, 3.4, 3.5, 3.6, and 3.7.  That would be quite a bit of choice to be offering on the download page, and would confuse newcomers who are just getting started with Panda3D.

I think we should instead be offering only a single installer.  This means we have to make a choice of which Python versions we will support.  As of recently, we can support multiple Python versions in the same installer, at the cost of about 3-4 MB per Python version, expanding to 17 MB when extracted.

On Windows, we also ship a copy of Python in the installer, to make things easy for people who don't already have Python.  My suggestion here is that we only ship a copy of Python 3.7; we want to encourage people who get started to use the latest version.  People who have opinions about which Python version they want to use probably already have Python installed.  (Our Windows installer can detect which Python version is already installed and write a .pth file into its `site-packages` folder.)

One consideration is that Python drops support for Windows XP starting with Python 3.5, but supporting Windows XP out of the box in the SDK is arguably less important than in the wheel builds (which deploy-ng uses to make distributable games).

I would be reluctant not to include at least the Python 2.7 and 3.7 .pyds with the installer.  However, since each set of .pyds is only 3-4 MB compressed, we could simply ship *all* of them in the installer, but leave all but the latest unticked unless the installer detects that the corresponding version of Python is installed on the system.  It bloats the installer by a little bit, but it might be user-friendlier.

We could also ship a `panda3d\\__init__.py` file that displays a nice error message when the user is trying to use a version of Python with Panda3D that they didn't explicitly choose in the Panda3D installer.

On macOS, I think we can do something similar as on Windows, offering choices in the installer of which Python version to support and possibly automatically setting this based on detected versions of Python on the system.

In the Ubuntu debs, I think we should by default support both whichever Python version maps to `python2` and which one maps to `python3` on the distribution in question.  Alternatively, we have the option of splitting it out into `python3.6-panda3d`, etc. packages.  If we do this we would have to tell people to install from the [apt repository](https://archive.panda3d.org) instead of by downloading .deb files from the web site, though.

Thoughts?

**Comment by pythonengineer** [comment]
I think that Panda should guarantee support for & ship the latest versions of Python 2 and 3. If we don't support 2.4, 2.5, and 2.6, why provide special support for 3.4, 3.5, and 3.6?

**Comment by CFSworks** [comment]
> I would be reluctant not to include at least the Python 2.7 and 3.7 .pyds with the installer. However, since each set of .pyds is only 3-4 MB compressed, we could simply ship all of them in the installer, but leave all but the latest unticked unless the installer detects that the corresponding version of Python is installed on the system. It bloats the installer by a little bit, but it might be user-friendlier.

This would be my choice. The global average download speed these days is about 50 Mbps. Even with **5 extra sets** of .pyds at 4MB/set, that would only delay the installer download by about 3 additional seconds. Developers also tend to be more patient than end-users (after all, the latter doesn't have to deal with half-hour compile/test loops, eh?) so even if this meant a minute of extra downloading, it wouldn't be that bad and the user-friendliness would be worth it: people are more averse to the mental effort of extra choices than they are to a little extra waiting.

> I think that Panda should guarantee support for & ship the latest versions of Python 2 and 3. If we don't support 2.4, 2.5, and 2.6, why provide special support for 3.4, 3.5, and 3.6?

The (current) parallels between CPython's 2.x/3.x minor version numbers are unfortunate because they make this kind of reasoning easy to fall into. We should consider not only the _latest_ versions but also the versions still supported by the upstream CPython project. In other words, what makes 3.4 special over 2.4 is that 3.4 will still be supported for another ~1.5 years while support for 2.4 ended nearly a decade ago.

**Comment by rdb** [comment]
Then I would propose that we have the installer auto-detect which Python versions to install and write keys for `panda3d` and `direct` in the Registry to `HKCU\Software\Python\PythonCore\x.y\Modules` so that any Python installation with version `x.y` will be able to use Panda3D.

One issue is that Python 3.4 doesn't support those nifty `core.cp34-win_amd64.pyd` suffixes, so the `.pyd` files cannot be in the same directory as the ones for Python 2.7.  We could just forget about supporting 3.4 in the downloaded Windows SDK, since it is only going to be supported for 3 more months after Panda 1.10 is released, but it would be a bit of a shame since 3.4 is the last version to support Windows XP.

The way to support it would be to create a separate `panda3d-py3.4` directory specifically for Python 3.4 modules, or to add a hack to `panda3d/__init__.py` that registers the special suffix with the module loader.  But, I do wonder how many people would really be using the SDK with Python 3.4.

**Comment by Moguri** [comment]
I would lean against doing too much extra work to support Python 3.4. The lack of installer support for XP is a shame, but if people need XP support, they can still `pip install` a 3.4 wheel.

**Comment by rdb** [comment]
Closing this after having made the suggested changes:
* The Windows installer can install bindings for multiple Python versions, subject to user selection, with the default selection including the bindings for Python 2.7, the shipped version (3.7) and any versions installed on the system
* Same for the macOS installer, which by default selects bindings for Python 2.7 and any versions installed on the system
* The Ubuntu installer installs bindings for Python 2.7 and whatever version the `python3` package has on the distribution in question.
