### ISSUE TITLE
LINK_ALL_STATIC breaks Interrogate

### ISSUE THREAD

**Issue by darktohka** [panda3d/panda3d#442]
Enabling static builds using "--static" on latest master branch commit 6c5da232a400e9217608d21f3bf49a0e8a1cde64 breaks building interrogated CXX files, due to "imports" not being declared.

```
[T1] Building C++ object built/tmp/cpython-27mu/libp3dtoolutil_igate.o
built/tmp/libp3dtoolbase_igate.cxx:3711:87: error: ‘imports’ was not declared in this scope
 uct LibraryDef libp3dtoolbase_moddef = {python_simple_funcs, exports, imports};
                                                                       ^~~~~~~

built/tmp/libp3dtoolbase_igate.cxx:3711:87: note: suggested alternative: ‘exports’
 uct LibraryDef libp3dtoolbase_moddef = {python_simple_funcs, exports, imports};
                                                                       ^~~~~~~
                                                                       exports
The following command returned a non-zero value: g++ -std=gnu++11 -ftemplate-depth-70 -fPIC -c -o built/tmp/cpython-27mu/libp3dtoolbase_igate.o -Ibuilt/tmp -Ibuilt/include -I/usr/include/python2.7 -DLINK_ALL_STATIC= -Idtool/src/dtoolbase -pthread -fno-exceptions -msse2 -fno-strict-aliasing -ffast-math -fno-stack-protector -fno-finite-math-only -fno-unsafe-math-optimizations -O2 -Wall -Wno-unused-function -Wno-reorder built/tmp/libp3dtoolbase_igate.cxx
Storing dependency cache.
Elapsed Time: 37 sec
Build process aborting
```

The faulty lines in libp3dtoolbase_igate.cxx:

```
/**
 * Extern declarations for imported classes
 */
#ifndef LINK_ALL_STATIC
static Dtool_TypeDef imports[] = {
  {"TypeHandle", nullptr},
#define Dtool_Ptr_TypeHandle (imports[0].type)
  {nullptr, nullptr},
};
#endif
```

The code that's responsible for generating this portion of the interrogated file is at https://github.com/panda3d/panda3d/blob/master/dtool/src/interrogate/interfaceMakerPythonNative.cxx#L855.

**Comment by CFSworks** [comment]
Does reverting that named commit fix the issue, or are you mentioning the commit just to confirm your current version? (If the latter, are you conveniently able to bisect to identify the real offending commit?)

**Comment by rdb** [comment]
This is my fault—and I know what caused it.  I'm on it.

**Comment by darktohka** [comment]
@CFSworks: Just to confirm my current version - that commit is not the one causing the issue.

Thanks rdb!

**Comment by rdb** [comment]
Although, out of curiosity, have you modified makepanda to also build the Python modules statically?

It looks like the way `LINK_ALL_STATIC` behaves in interrogate expects the Python modules to all be linked together, whereas makepanda is actually building the Python modules dynamically.  So building statically in makepanda doesn't actually work as-is.

**Comment by darktohka** [comment]
That's correct, I also enabled static building for .pyd modules in makepandacore's FindLocation.
