### ISSUE TITLE
WindowProperty.size() method shadows WindowProperty.size property

### ISSUE THREAD

**Issue by Moguri** [panda3d/panda3d#444]
Accessing the `size` attribute on `WindowProperty` gives back the `size()` class method instead of the actual size.

I am not sure of a good way to solve this without breaking the API (i.g., renaming `WindowProperty.size()`).

**Comment by rdb** [comment]
I'm wondering if there is something we can do in the Python type system to ensure that it acts as a property when called on an instance, but acts as a static method when called on the type.

**Comment by CFSworks** [comment]
There's a few things:

1. Make the property callable, because you'll get the property object itself when pulling it off of a class rather than an instance.
2. Manually replace the `size` attr on instances.
3. Handle it with `__getattr__`

These are all very "magic" and against the spirit of Python: while its data model permits just about any trickery you'd like, the philosophy of the language holds that you shouldn't actually resort to that. (Namely, properties and methods should be seen as occupying one namespace.)

**Comment by wezu** [comment]
Wait, don't rename the property, `size` is just the right name for a property, the method should be `get_size()` or 'set_size()` ...but there are methods like that, only with a different signature and descriptions.. and apparently doing something else.

**Comment by rdb** [comment]
@wezu I agree the method would ideally be named differently, but the reason to rename the property and not the method would be that the property is relatively new, whereas `WindowProperties.size(x, y)` is already used in a lot of Panda3D code in existence.

**Comment by rdb** [comment]
@CFSworks: I think there is a slightly cleaner way to do it: properties are implemented as descriptors, and we can make the descriptor's __get__ also operate if it is used statically (noting that interrogate already supports static properties).  It could check whether it is given a null `self` pointer (ie. used statically) and if so, return a reference to the instancemethod, if not, return the instance's property value.

It would still feel a tad "magical" to me, but I might be OK with it if we deprecated `WindowProperties.size(x, y)` (for removal in a future Panda 2.0) and used this as a temporary compatibility solution.  It's a useful short-hand, but unfortunately named, whereas something like `WindowProperties(size=(x, y))` or `WindowProperties.from_size(x, y)` may be considered more intuitive.

**Comment by CFSworks** [comment]
> It would still feel a tad "magical" to me, but I might be OK with it if we deprecated `WindowProperties.size(x, y)` (for removal in a future Panda 2.0) and used this as a temporary compatibility solution.

I'm okay with temporary magic, as long as the more magical of the uses is deprecated (as you're suggesting).

> It's a useful short-hand, but unfortunately named, whereas something like `WindowProperties(size=(x, y))` or `WindowProperties.from_size(x, y)` may be considered more intuitive.

Oh man, I really like the look of `WindowProperties(size=(x, y))`. That form makes it very easy to combine with other shorthands.
