### ISSUE TITLE
Head is missing from resulting .egg from bam2egg

### ISSUE THREAD

**Issue by theclashingfritz** [panda3d/panda3d#464]
I recently discovered a head of a model did not output from bam2egg. I'm unsure if this was fixed in the past. Because if so it is no longer fixed. 

The model from the attached .zip is the file with the issue. And the .egg in the .zip is my result.

(link removed)

**Comment by rdb** [comment]
This might be the same problem as #237.

**Comment by theclashingfritz** [comment]
Looks like it probably would be, It also might be the cause of #434. If so. It'd have to break almost everything.

**Comment by Moguri** [comment]
Did the fix for #237 (c61b480a41ae5f83f06101aeedb10a41a2ee02bb) fix this issue too?

**Comment by rdb** [comment]
Please don't post copyrighted material to our issue tracker.  I'm closing this issue but will reopen it if you can reproduce this with your own models and post it in a comment here.
