### ISSUE TITLE
GSG crash when using setRenderModeThickness on MacOS with gl-version 32

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#466]
On MacOS 10.13.6 (High-Sierra), when using "gl-version 32" in prc, the GSG crashes when one tries to render an instance with a thickness different than 1, set using setRenderModeThickness().

Log output :

<pre>
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display:gsg:glgsg(error): at 7361 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid value
:display(error): Deactivating CocoaGraphicsStateGuardian.
</pre>

Tested with panda3d-1.10.0.dev2072-cp27-cp27m-macosx_10_6_x86_64.whl 

Minimal code to reproduce the problem :

<pre>
from direct.showbase.ShowBase import ShowBase
from panda3d.core import GeomVertexFormat, GeomVertexData, GeomVertexWriter
from panda3d.core import GeomPoints, Geom, GeomNode
from panda3d.core import loadPrcFileData

def makeGeom(points, colors):
    format = GeomVertexFormat.getV3c4()
    vdata = GeomVertexData('vdata', format, Geom.UHDynamic)
    vwriter = GeomVertexWriter(vdata, 'vertex')
    colorwriter = GeomVertexWriter(vdata, 'color')
    geompoints = GeomPoints(Geom.UHDynamic)
    index = 0
    for (point, color) in zip(points, colors):
        vwriter.addData3f(*point)
        colorwriter.addData4f(*color)
        geompoints.addVertex(index)
        geompoints.closePrimitive()
        index += 1
    geom = Geom(vdata)
    geom.addPrimitive(geompoints)
    return geom

loadPrcFileData("", "gl-version 32\n"
                    "gl-check-errors #t\n")

base = ShowBase()
base.disableMouse()
base.camera.setPos(0, -10, 0)
gnode = GeomNode('points')

geom = makeGeom([[0, 0, 0]], [[1, 1, 1, 1]])
gnode.addGeom(geom)
instance = render.attachNewNode(gnode)
instance.setRenderModeThickness(2)

base.run()
</pre>

Without gl-version, the point is correctly drawn with the right size and the GSG does not crash.

**Comment by rdb** [comment]
Hmm.  It looks like we are calling both `glLineWidth` and `glPointSize` with the value, but `glLineWidth` values higher than 1.0 were deprecated in OpenGL 3.2 (even though most vendors seem to support it just fine).  We should just clamp the `glLineWidth` value when using a core-only profile.  That should be an easy fix.

We might also need to add a check and add CPU emulation for rendering wide lines, similar to what we do when point sprites aren't supported.

FWIW, the correct setting is `gl-version 3 2` (with a space between major and minor version), though for the macOS renderer it happens to have the same effect.

**Comment by el-dee** [comment]
Just tested, no more GSG deactivation. Thanks !
