### ISSUE TITLE
sync-video 1 on macOS has no effect on recent development builds

### ISSUE THREAD

**Issue by treamology** [panda3d/panda3d#486]
It indeed works in the 1.9.4 release build. I've checked a few builds from several months ago and they all exhibit the same issue. Does anyone know of anything that could have caused this?

**Comment by el-dee** [comment]
FWIW sync-video seems to still work using recent devel builds on MacOS High-Sierra, but not on Mojave.

**Comment by treamology** [comment]
Yep, it looks like it's a regression in the 10.14 SDK :/

**Comment by Moguri** [comment]
Looks like SDL has a work around: https://discourse.libsdl.org/t/sdl2-no-renderer-vsync-on-macos-mojave/25169/23

**Comment by treamology** [comment]
It looks like using [CVDisplayLink](https://developer.apple.com/documentation/corevideo/cvdisplaylink) to trigger buffer flips will be a good solution to this issue. I'll look into this.

**Comment by rdb** [comment]
@treamology do you happen to remember whether this issue happens when *running* on 10.14+, or does it happen when compiling against the 10.14 SDK?
