### ISSUE TITLE
Fireflies sample is not illuminating scene

### ISSUE THREAD

**Issue by Moguri** [panda3d/panda3d#494]
OS: Arch Linux (kernel: 4.19.12-1-ck-skylake)
GPU: Intel HD Graphics 630 and AMD Vega M GL
Panda3D version: 5d74411c37d95b241459d7e7a23f3ebd31068347

When running the fireflies sample, the scene does not get illuminated, no matter the number or size of the fireflies.

![screenshot](http://pasteall.org/pic/show.php?id=9bd818d1ee9946b559857b4c81af76a6)

**Comment by Moguri** [comment]
[fireflies.trace.log](https://github.com/panda3d/panda3d/files/2717716/fireflies.trace.log)

Attached is an apitrace renamed to `.log` so it can be uploaded to GitHub.

**Comment by rdb** [comment]
This turns out to be the same issue as #495.
