### ISSUE TITLE
Instancing support on macOS

### ISSUE THREAD

**Issue by thetestgame** [panda3d/panda3d#497]
We have tried numerous attempts at instancing on macs. All ending in the same results. This is with setting gl-version to 3 2.

```
Known pipe types:
  CocoaGraphicsPipe
(all display modules loaded.)
2018-12-31 14:57:07.653 Python[10291:179368] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader instance.vert.glsl:
ERROR: instance.vert.glsl:1: '' :  version '150' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader instance.frag.glsl:
ERROR: instance.frag.glsl:1: '' :  version '150' is not supported
:display:gsg:glgsg(warning): Shader instance.frag.glsl produced the following warnings:
WARNING: Do not have an attached vertex shader to match BindAttributeLocation request for 'p3d_Vertex'.
WARNING: Do not have an attached vertex shader to match BindAttributeLocation request for 'p3d_Color'.
WARNING: Do not have an attached vertex shader to match BindAttributeLocation request for 'vertex'.
WARNING: Do not have an attached vertex shader to match BindAttributeLocation request for 'p3d_Normal'.
WARNING: Do not have an attached fragment shader to match FragDataBinding request for 'p3d_FragData'.
```

This is making is near impossible for us to continue with our game.  @AnythingTechPro can provide more info. Hes the primary mac developer on our team.

**Comment by thetestgame** [comment]
[example.zip](https://github.com/panda3d/panda3d/files/2719101/example.zip)

**Comment by el-dee** [comment]
I'm using hardware instancing in my application on MacOS without (much) trouble. The OpenGL driver on MacOS seems to not support all the versions of GLSL, with GLSL version 140 or 330 it works fine.

**Comment by thetestgame** [comment]
We have tried version 140. For the sake of being thorough we tried 330. Both result in the same error.

```
2019-01-01 11:01:22.860 Python[23035:441815] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader instance.vert.glsl:
ERROR: instance.vert.glsl:1: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader instance.frag.glsl:
ERROR: instance.frag.glsl:1: '' :  version '140' is not supported
:display:gsg:glgsg(warning): Shader instance.frag.glsl produced the following warnings:
WARNING: Do not have an attached vertex shader to match BindAttributeLocation request for 'p3d_Vertex'.
WARNING: Do not have an attached vertex shader to match BindAttributeLocation request for 'p3d_Color'.
WARNING: Do not have an attached vertex shader to match BindAttributeLocation request for 'vertex'.
WARNING: Do not have an attached vertex shader to match BindAttributeLocation request for 'p3d_Normal'.
WARNING: Do not have an attached fragment shader to match FragDataBinding request for 'p3d_FragData'.
```

We have been testing on 10.14/Mojave and 10.13/High Sierra. Both failed.

**Comment by rdb** [comment]
I'll take a look at this later, but FWIW, enabling GLSL 1.50 and above on macOS requires `gl-version 3 2` in Config.prc (and a reasonably recent Panda version).  This disables the fixed-function pipeline so does require all objects to have shaders.

**Comment by thetestgame** [comment]
These tests have been performed with ``gl-version 3 2`` set in the prc supplied in the example. Currently testing with panda build from source on new years eve 2018. Should be the latest or relatively close.

**Comment by thetestgame** [comment]
Thank you. That does solve our issue. The load_prc_file situation should maybe be looked into so it loads from a relative location.

**Comment by rdb** [comment]
@thetestgame Ah, that one's bitten me before.  The issue isn't that it fails to load the .prc file but that it loads the wrong one.  Panda will first try to resolve the given filename along the PRC path, but macOS uses a case-insensitive filesystem, so it will first find the `Config.prc` (capital C) that's shipped with Panda itself.

The easiest workaround is to just name your file something other than `config.prc`.
