### ISSUE TITLE
EggLoader: Box collision surfaces with non-global axes imported incorrectly

### ISSUE THREAD

**Issue by PointSource-xx** [panda3d/panda3d#506]
When creating collision geometry from an EggGroup (eggLoader.cxx, method `EggLoader::make_node()`), the code calls `make_collision_solids()`, then transform the solids into local space with
`node->xform(LCAST(PN_stdfloat, egg_group->get_vertex_to_node()));`
In the case of geometry that has non-global axes, the transform should be performed first before calculating the solids.

In my case, Box collision surfaces were created with incorrect dimensions due to the rotation that was applied to them. I suspect this may also be the case for other solids, but haven't tested them.

[simpleBox_collideAttr_30deg.zip](https://github.com/panda3d/panda3d/files/2726044/simpleBox_collideAttr_30deg.zip)
egg file

![boxmodel](https://user-images.githubusercontent.com/3308510/50674409-fa8c3000-1020-11e9-9d89-b932d1c8d6ed.png)
screenshot of file with `show()` called on CollisionNode, and `keep` flag on the Collide group attribute.

[makebox_localcoords.patch.txt](https://github.com/panda3d/panda3d/files/2726045/makebox_localcoords.patch.txt)
Workaround patch for `make_box()`

**Comment by rdb** [comment]
Sorry, I didn't notice there was a patch attached.  Could you file this as a pull request, and fix this to conform to coding style (space between `//` and comment, `snake_case` for variable names)?  Thanks!
