### ISSUE TITLE
Cannot prevent Ctrl-V from "pasting" clipboard text as keystroke events

### ISSUE THREAD

**Issue by Epihaius** [panda3d/panda3d#512]
To copy and paste text between my project and external programs I currently use tkinter to write to and read from the operating system's clipboard.
However, to handle cases where tkinter isn't installed, I'd like to implement a simple fallback to a local "clipboard" (just a variable to store some text). Sounds easy enough, but I hit a snag.
To handle keyboard input for a custom input field widget, I use a DirectObject to listen for keystroke events to catch special characters, while certain key combinations like Ctrl-C and Ctrl-V are handled separately so they can be used as the standard hotkeys for copying and pasting text. And here a problem arises:
when I type Ctrl-V, the contents of the OS clipboard (if it contains text) seems to be automatically sent as a sequence of keystroke events, effectively pasting that text, whether I want that or not. If I can write to the OS clipboard, then it's a very cool feature, but if the local clipboard is supposed to be used, this leads to the contents of both clipboards to be merged and pasted into the input field.

The following code should allow you to reproduce this:

```
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase, DirectObject

class MyApp(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)
        self.buttonThrowers[0].node().set_keystroke_event("keystroke")
        self._clipboard = "local_text"
        self._input = ""
        self._listener = DirectObject.DirectObject()
        self._listener.accept("keystroke", self.print_keystroke)

    def copy_text_to_clipboard(self):
        self._clipboard = "local_text"
        print("\nText was copied to local clipboard:", self._clipboard)

    def paste_text_from_clipboard(self):
        self._input += self._clipboard
        print("\nPasted from local clipboard.\nInput:\n    " + self._input)

    def print_keystroke(self, char):
        val = ord(char)

        if val == 3:  # Ctrl-C was pressed
            self.copy_text_to_clipboard()
        elif val == 22:  # Ctrl-V was pressed
            self.paste_text_from_clipboard()
        elif val in range(32, 255):
            self._input += char
            print("Input:\n    " + self._input)

app = MyApp()
app.run()
```

When running that code, make sure you copied some text using e.g. a text editor, let's say the word "clipboard"; then the output would be this after you press Ctrl-V:

```
Input:
    c
Input:
    cl
Input:
    cli
Input:
    clip
Input:
    clipb
Input:
    clipbo
Input:
    clipboa
Input:
    clipboar
Input:
    clipboard

Pasted from local clipboard.
Input:
    clipboardlocal_text
```

while it should just be "local_text".

Now I have two questions:

1. How reliable is the built-in paste mechanism? Does it work well on all platforms?
2. If the answer to the above is "yes", then would it be possible to also use Panda itself to write to the OS clipboard? No custom clipboard system would be needed then.

If the answer to either of these questions is "no", then would it at least be possible to turn off the built-in pasting feature (e.g. using a config variable)? Or perhaps not only send the Ctrl-V special character after the sequence of regular text characters from the clipboard (as is the case currently), but also right before that sequence, as a keystroke event? Then I could probably ignore keystroke events between two successive Ctrl-V events.

This issue happens on Windows.

**Comment by rdb** [comment]
Huh, I didn't realise that Panda had special handling for Ctrl+V on Windows.  It sounds like it should be possible to override this behaviour (especially as we don't have it on other platforms).

I'm just thinking out loud here, but maybe we should be handling pasting in a bit more integrated way.  Maybe instead of just implementing paste by emulating keystroke events at the window level, it should be possible to mark a specific MouseWatcherRegion as being "pastable" to allow it to be receptive to paste events?  This might also be important for handling pasting on eg. Android, where one has to long-press the input control and use a context menu to paste; we couldn't do that without telling the OS which controls on screen are pastable.

**Comment by Epihaius** [comment]
> Maybe instead of just implementing paste by emulating keystroke events at the window level, it should be possible to mark a specific MouseWatcherRegion as being "pastable" to allow it to be receptive to paste events?

Sounds good to me, as I use a MouseWatcherRegion for each of my widgets anyway.

But just to be clear: it really won't be possible to let Panda write (copy) to the OS clipboard (in a cross-platform way)?
Admittedly this wouldn't be very useful for games, but for other kinds of Panda-based projects it would be cool if the user could copy and paste data between them and other (desktop) programs like text editors.
Although there are third-party Python packages like Pyperclip available, that would be one more dependency, which I'd like to avoid.

Anyway, I'm looking forward to your proposed change. Thanks in advance!

**Comment by rdb** [comment]
I think it sounds like a reasonable feature request to have a method on `GraphicsWindow` to copy text to the OS clipboard.  Please open a new issue for that request, thanks!  Then we can use this issue to track the paste event support.

**Comment by rdb** [comment]
I added a config var to 1.10.3 called `paste-emit-keystrokes` which you can set to false to disable this behaviour.

I also started work on a proper paste event in the `paste-events` branch, but it's not very high on my priority list, so maybe someone else can pick up that work.
