### ISSUE TITLE
In python 3.7, awaiting load model errors with generator raised StopIteration

### ISSUE THREAD

**Issue by drewc5131** [panda3d/panda3d#513]
When running this basic line of code anywhere in a panda3d application with Python 3.7
`await loader.loadModel('MODEL', blocking = False)`
This traceback is thrown
`await loader.loadModel('MODEL', blocking = False)
RuntimeError: generator raised StopIteration`

This is because of PEP 479.

The only way I've found easy to get around this issue without putting a bunch of try/excepts is to change this line in direct.showbase.Loader
https://github.com/panda3d/panda3d/blob/master/direct/src/showbase/Loader.py#L93
from `raise exc` to `return result`
However, as the comment above this section of the code states, older python versions don't allow return statements with arguments, so this could create some incompatibility.

**Comment by rdb** [comment]
This sucks.  It looks like Python 3.7 just removed the ability to raise StopIteration with value without giving us a replacement that will not give a syntax error in Python 2.

I guess we'll have to just invent our own generators until we can drop Python 2 support next year, sigh.

**Comment by rdb** [comment]
I've checked in something that seems to work for now, but it's a fair amount of rework, and I have not tested all the corner cases (such as what happens when requests are cancelled).  Let me know if there are any issues with it in your testing.

**Comment by drewc5131** [comment]
Neat. I'll do some testing tomorrow and i'll get back
