### ISSUE TITLE
OSX Cocoa window doesn't close on destroy()

### ISSUE THREAD

**Issue by andyljones** [panda3d/panda3d#534]
Minimal example on OSX 10.14.1, Python 3.7.2, Panda3d 1.10.0:

```python
from direct.showbase.ShowBase import *
from time import *

base = ShowBase()
base.destroy()
sleep(5)
```

The expected behaviour - and the behaviour I see on my Linux box - is that a window appears momentarily, and then the process exits five seconds later. On OSX though, the window hangs around until the process exits five seconds later.

Here's a [log file](https://github.com/panda3d/panda3d/files/2751988/logs.txt) generated by this script:

```python

from panda3d.core import *
loadPrcFileData("", "notify-level spam")

from direct.showbase.ShowBase import *
from time import *

base = ShowBase()
print('Destroying...')
base.destroy()
print('Destroyed. Sleeping.')
sleep(5)
```

For context, my original problem is that I'd like to launch multiple, successive `ShowBase` from an interactive console. Having a blank display window hanging around isn't a showstopper, but it is a bit annoying.

**Comment by treamology** [comment]
Hmm, that's no good. I'll look into this.

**Comment by rdb** [comment]
This is just a stab in the dark, but maybe macOS is waiting for some events to be processed before it lets the window close?  If so, perhaps `GraphicsEngine::remove_all_windows()` needs to call `process_events()` on all the windows to let them close.  Or CocoaGraphicsWindow needs to do this in `close_window()`.

**Comment by treamology** [comment]
That was exactly the issue. Adding a `process_events()` call after doing `[_window close]` causes the window to close immediately.

**Comment by andyljones** [comment]
Well that was impressively quick. Thanks!
