### ISSUE TITLE
distributed: Aggressive memory leak within ConnectionRepository

### ISSUE THREAD

**Issue by ksmit799** [panda3d/panda3d#537]
I'm currently developing an MMOG utilizing several of the built in direct classes to provide logic (e.g. ClientRepositoryBase, ConnectionRepository, etc).

After providing all the foundation code, I was surprised to find that both the client and my AI/UD servers were using upwards of ~500mb of RAM within seconds of the programs starting (this number was rapidly increasing and soon caused each process to crash). I managed to narrow down the issue to the following code within ConnectionRepository (line 122):

```
if self.config.GetBool('gc-save-all', 1):
    gc.set_debug(gc.DEBUG_SAVEALL)
```

This is supposed to preserve every object in a gc cycle, including objects that should usually be freed automatically (assumingly for performance reasons). However, when running with Python 3 (I never had this issue with Python 2), it completely destroys garbage collection (note that this is enabled by default). This fixed the memory leaks for the AI/UD servers, however I'm still experiencing a small memory leak within the client (~1mb every second or two) when inheriting from ClientRepositoryBase.

The following code can be used to test these leaks for yourself. Note that these only manifest when using Python 3:

```
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase
from direct.distributed.ConnectionRepository import ConnectionRepository

class InternalRepository(ConnectionRepository):

	GameGlobalsId = 1

	def __init__(self, baseChannel, serverId=None, dcFileNames=None,
                 dcSuffix='', connectMethod=None, threadedNet=None):
		ConnectionRepository.__init__(self, connectMethod, config, hasOwnerView = False, threadedNet = threadedNet)

class MyApp(ShowBase):

	def __init__(self):
		ShowBase.__init__(self)
		self.test = InternalRepository(123123)

app = MyApp()
app.run()
```

**Comment by ksmit799** [comment]
I'm using Python 3.7.2, Panda 1.10.0 and both Windows 10 and MacOS Mojave.

Indeed, there are both leaks within ConnectionRepository and ClientRepositoryBase (I chose to use ConnectionRepository in the example as it is by far the worst leak).

**Comment by theclashingfritz** [comment]
This would explain alot in terms of Toontown AI starting up so slow, If this is a major leak it should be fixed asap.

**Comment by drewc5131** [comment]
Tested the code you put in 1.10.0 on python 3.7.0. I cannot reproduce this issue.

**Comment by ksmit799** [comment]
After further testing, the memory leaks I'm experiencing AFTER disabling `gc-save-all` are due to the multi-threaded render-pipeline. When running the client with `threading-model Cull/Draw`, I'm experiencing a leak of around ~1mb second. After disabling this, all the leaks I was experiencing stopped.

**Comment by rdb** [comment]
So, what do we do about this? Do we disable gc-save-all by default? For what it's worth, running your sample code does not spring any memory leaks for me, it's holding steady at 56.5 MB in Task Manager.

**Comment by ksmit799** [comment]
I'm going to assume this was being caused by some obscure bug long since fixed. Others would have noticed it by now if it was still in effect, although I do remember thoroughly testing it's reproducibility at the time on both Windows and MacOS.
