### ISSUE TITLE
`init_memory_hook()` not (necessarily) called before static initialization of interrogate.cxx's `CPPParser parser;`

### ISSUE THREAD

**Issue by CFSworks** [panda3d/panda3d#539]
This is a problem since `CPPParser` creates a `CPPPreprocessor`, which has a `pvector` which can attempt to perform array allocation before the `memory_hook` is initialized.

With #381, it seems like these come up now and then when compiled for debug. Is there any reason in particular the memory hook isn't lazy-initialized (via a `get_memory_hook()` or similar function)? It seems like it would mitigate all of the problems with static initializers needing to allocate memory before `memory_hook` has a chance to initialize.

**Comment by rdb** [comment]
I don't feel strongly on the lazy initialization check.  I guess it might hurt performance a bit.  If we don't do it, we have to at least put an assert there in debug builds.

**Comment by rdb** [comment]
Fixed this by making MemoryHook's constructor constexpr, initializing the default instance at constant init time, moving the DeletedBufferChain map to a static method on DeletedBufferChain (why was it on MemoryHook to begin with?)
