### ISSUE TITLE
Permissions on /usr/lib64/python3.x/site-packages directory in .rpm

### ISSUE THREAD

**Issue by JoelStienlet** [panda3d/panda3d#541]
Hello,
I've tried the latest version of the sources on fedora29, and the .rpm doesn't get installed:
$sudo rpm --nodeps -ivh ./panda3d-1.11.0-1.x86_64.rpm
file /usr/lib64/python3.7/site-packages from install of panda3d-1.11.0-1.x86_64 conflicts with file from package python3-libs-3.7.1-4.fc29.x86_64

The conflict comes from file permissions:
On my system I have:
$ ls -l /usr/lib64/python3.7
drwxr-xr-x. 85 root root  12288 Jan 19 12:03 site-packages

In the .rpm:
$rpm -qlpv ./From_Git/panda3d/panda3d-1.11.0-1.x86_64.rpm | grep site-packages
drwxrwxr-x    2 root    root                        0 Jan 17 21:22 /usr/lib64/python3.7/site-packages

I've tried to edit the rpm:
$EDITOR=nano; rpmrebuild -enp ./panda3d-1.11.0-1.x86_64.rpm
and set the permissions to 755.
After this change, the .rpm installs without any problem.

**Comment by rdb** [comment]
That's very strange.  We are explicitly using mode 0o755 when creating the directories.  Could you check the permissions inside the `targetroot` directory that makepanda built?

**Comment by JoelStienlet** [comment]
That's what I get in the targetroot:

[stienlet@localhost lib64]$ pwd
/home/stienlet/Programmation/Panda3D_clean/From_Git/panda3d/targetroot/usr/lib64
[stienlet@localhost lib64]$ ls -al
total 16
drwxrwxr-x. 4 stienlet stienlet 4096 Jan 20 22:53 .
drwxrwxr-x. 7 stienlet stienlet 4096 Jan 20 22:53 ..
drwxr-xr-x. 2 stienlet stienlet 4096 Jan 20 22:53 panda3d
drwxrwxr-x. 3 stienlet stienlet 4096 Jan 20 22:53 python3.7

So apparently it is 775 inside the targetroot too.

**Comment by JoelStienlet** [comment]
Apparently the directory is 775 inside the targetroot too:

[stienlet@localhost python3.7]$ pwd
/home/stienlet/Programmation/Panda3D_clean/From_Git/panda3d/targetroot/usr/lib64/python3.7
[stienlet@localhost python3.7]$ ls -al
total 12
drwxrwxr-x. 3 stienlet stienlet 4096 Jan 20 23:11 .
drwxrwxr-x. 4 stienlet stienlet 4096 Jan 20 23:11 ..
drwxrwxr-x. 4 stienlet stienlet 4096 Jan 20 23:11 site-packages

I didn't have this problem ~6month ago, but I've seen a lot of work has been done since then :)

**Comment by rdb** [comment]
Aha, it looks like I may have misunderstood how `mkdir -p` interacts with `-m`:
>     -p             Create intermediate directories as required.  If this
>                    option is not specified, the full path prefix of each
>                    operand must already exist.  On the other hand, with this
>                    option specified, no error will be reported if a directory
>                    given as an operand already exists.  Intermediate
>                    directories are created with permission bits of
>                    “rwxrwxrwx” (0777) as modified by the current umask, plus
>                    write and search permission for the owner.

So, the intermediate directories do not get set to the mode specified by `-m`.  This can be fixed easily by creating those directories one by one.

**Comment by JoelStienlet** [comment]
Thank you, interesting, didn't know that either, this is good to know!

**Comment by rdb** [comment]
Apparently `os.makedirs()` suffers from the same problem (as of python/cpython#799).  So, I've just used a custom function to make the directories.

Could you give it a try and check that it's fixed now?

**Comment by JoelStienlet** [comment]
I've tried it and it's working, so the issue is fixed. Thank you!
