### ISSUE TITLE
[Particle Panel UI Bug] Cannot Save File

### ISSUE THREAD

**Issue by ibispi** [panda3d/panda3d#543]
OS: Linux Ubuntu 18.04
Python Version: 3.6

This happens when you try to save a file after entering the file name and clicking on the save button:

> TypeError Exception in Tk callback
>   Function: <bound method ParticlePanel.saveParticleEffectToFile of <direct.tkpanels.ParticlePanel.ParticlePanel object at 0x7fdf810b0668>> (type: <class 'method'>)
>   Args: ()
> Traceback (innermost last):
>   File "/usr/local/lib/python3.6/dist-packages/Pmw/Pmw_2_0_1/lib/PmwBase.py", line 1776, in __call__
>     return self.func(*args)
>   File "/home/ibispi/.local/lib/python3.6/site-packages/direct/tkpanels/ParticlePanel.py", line 1295, in saveParticleEffectToFile
>     self.particleEffect.saveConfig(Filename(particleFilename))
>   File "/home/ibispi/.local/lib/python3.6/site-packages/direct/particles/ParticleEffect.py", line 168, in saveConfig
>     f.write('\n')
> TypeError: a bytes-like object is required, not 'str'

The file is created with the proper name but is completely blank, nothing is saved.

**Comment by tcdude** [comment]
This is because Python 3 does not allow to write `str` into files that are open for writing binary data.
Essentially, every string that gets written to the file has to be prefixed with the letter b (e.g. `b'foo bar'`)

I've already prepared a fix, but I first need to figure out how I can test and verify if my fix resolves the issue, before making a PR

**Comment by tcdude** [comment]
@ibispi: I created a fix and a PR is open for this issue. If you want to try it out, you can copy the `ParticleEffect.py` file from ["ParticleEffect.zip"](https://github.com/panda3d/panda3d/files/2845063/ParticleEffect.zip) to the `/usr/share/panda3d/direct/particles/` folder on your system. Make sure you make a copy of the local version of `ParticleEffect.py`, just in case.
It works for me in both Python 2.7 and 3.6 on Ubuntu 18.10

**Comment by ibispi** [comment]
I've just tried it out, it works.
It saves it properly, without any issues.
Thanks, @tcdude!
