### ISSUE TITLE
When can we drop Windows XP support?

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#548]
I realise that there are several people in the community who may still be using and targeting Windows XP, and that there is still a non-negligible audience for Windows XP.  I am creating this issue to collect feedback and get a sense of how long people still expect Panda3D to support Windows XP.

Windows XP does not properly support thread-safe magic statics.  Also, Windows Vista provides proper thread primitives that could really benefit the Panda codebase if we could drop support for Windows XP.  We can probably provide some compatibility layer, but I would want to know that it's worth the effort.

**Comment by pythonengineer** [comment]
Is there a specific upcoming feature that would break Windows XP support? If not, what would this entail? Just disabling the OS from being able to run makepanda/CMake, support removed from website builds, and not testing any major changes on XP in the future?

**Comment by rdb** [comment]
The change I'm most looking forward to when we can drop WinXP support is enabling full C++11 semantics for static variables as well as using the new lightweight threading mechanisms.  Once we enable that, this would cause the WinXP build to simply crash when run.

I expect we'll be keeping Windows XP support for a while, but it would be great to gather opinions on how long.

**Comment by montreal91** [comment]
@rdb we can create a warning in panda3d v1.11 release that windows xp support is deprecated and will be dropped in panda3d 1.12.

**Comment by drewc5131** [comment]
Personally I think it should just be dropped for the next release. 

Windows XP has an extremely low market share now. (About 3.9%). Honestly, probably 99% (if not all) of those users are not playing any type of games. Most windows xp usage is probably coming from public schools, libraries, etc. I don't see a reason for it to still be supported.

**Comment by rdb** [comment]
If 4% is "extremely low", then we should drop Linux support and 32-bit support before we drop Windows XP support.

Most of the Windows XP market share presumably comes from China, and the lowest estimate of WinXP market share there is around 11%, so I imagine it will be primarily those targeting the Chinese market that would be affected by such a change.

My biggest worry about dropping WinXP is that Panda does currently have a reputation for supporting very old hardware (we still support all the way back to OpenGL 1.0), so Panda may be able to serve a particular niche here.

But, if nobody comes forward indicating that they need Panda to keep supporting XP, I would have little objection to @montreal91's suggestion.

**Comment by theclashingfritz** [comment]
I don't need XP support in particular. However it still would be nice to see it supported in the future so games can support it if need be. Having an option is better then not having one.

**Comment by drewc5131** [comment]
While I understand what you are trying to say @rdb, I believe that windows xp and linux have VERY different userbases. I would imagine the majority of windows xp users for example in the US, would be from places like public schools which haven't upgraded yet, whereas it's much more likely that someone using linux would be much more likely to fit the demographic of someone to use panda3d than XP's userbase.

**Comment by rdb** [comment]
Python 3.4 is already EOL and Python 2.7 will be EOL at the end of the year.  Those are the last two Python releases to still support Windows XP.  So, I would suggest that by the end of the year we also drop Windows XP support from the public builds.

Do we for now still leave it possible to compile Panda from source with Windows XP?

**Comment by Moguri** [comment]
For further 1.10.x builds, I suspect we'll keep Windows XP support. However, I am doubtful that 1.11 will even ship by the end of the year, so maybe it's fine to remove Windows XP support in master? Maybe that also means removing Python 2 support from master?

If 1.11 *does* ship before the end of the year, we likely don't want to support Python 2 or Windows XP on further patch/bugfix releases, so it would be better to drop both for the initial 1.11 release.

**Comment by rdb** [comment]
I'm going to assume for now that 1.11 will not need to support Python 2.7 or Python 3.4.  That would just be a lot of extra work and we'd have to continue to support it throughout the 1.11 cycle.

I'm not in a hurry to drop support from master, though, since not everyone uses Panda from the public releases.  So I'm inclined to keep Python 2.7 and, by extension, Windows XP support in until the end of the year.  But, my inclination may change if it turns out to be too much of a pain.

**Comment by rdb** [comment]
I dropped Windows XP support in 1bb4a032aa7228dedf381bca6e720f687be419b7, and set the default SDK to the Windows 8.1 SDK in 4c1373b7213cb1c6921b9848b158f46c63f188be .  Bye WinXP!  I'm also stopping Python 3.4 builds since it is long EOL.  Python 2.7 support will be dropped soon as well.

We could jump straight ahead to Windows 7, since Windows Vista has a negligible market share.  However, upstream Python still supports Vista, and I don't see a compelling reason to drop it right now, so let's keep our minimum at Vista for now.  (Once we drop Vista, we can require the Windows 10 SDK.)
