### ISSUE TITLE
Particle Panel: Tk bug

### ISSUE THREAD

**Issue by tcdude** [panda3d/panda3d#552]
When running particle_panel.py on Ubuntu 18.10 with Panda3D 1.10.0 and Python 3.6.7 I get a flood of this error message:

> IndexError Exception in Tk callback
>   Function: <function MenuBar._addmenu.<locals>.<lambda> at 0x7fb4c3239158> (type: <class 'function'>)
>   Args: (<Motion event state=Mod2|Button1 x=33 y=42>,)
>   Event type: MotionNotify (type num: 6)
> Traceback (innermost last):
>   File "/home/tc/.local/lib/python3.6/site-packages/Pmw/Pmw_2_0_1/lib/PmwBase.py", line 1776, in __call__
>     return self.func(*args)
>   File "/home/tc/.local/lib/python3.6/site-packages/Pmw/Pmw_2_0_1/lib/PmwMenuBar.py", line 144, in <lambda>
>     self._menuHelp(menuName))
>   File "/home/tc/.local/lib/python3.6/site-packages/Pmw/Pmw_2_0_1/lib/PmwMenuBar.py", line 242, in _menuHelp
>     help = self._menuInfo[menuName][1][index]
> IndexError: list index out of range
> 
> ================================================
>   Event contents:
>     char: ??
>     delta: 0
>     height: ??
>     keycode: ??
>     keysym: ??
>     keysym_num: ??
>     num: ??
>     send_event: False
>     serial: 157709
>     state: 272
>     time: 224047487
>     type: Motion
>     widget: .!toplevel.!frame.!frame.!frame.!menubutton2.!menu
>     width: ??
>     x: 33
>     x_root: 3685
>     y: 42
>     y_root: 830

**Comment by tcdude** [comment]
Seems to be related to [this](https://discourse.panda3d.org/t/particles-samples-problems/10530) really old thread in the discourse, that doesn't seem to even go into the part where `Pmw` throws the `IndexError`.

**Comment by rdb** [comment]
This seems to occur when hovering the mouse over the items in the "File" menu.  It is caused by the code directly using Tkinter calls to insert items before the Quit item instead of going through the proper Pmw high-level calls, which do additional registration of help text.

I'll check in a fix shortly.
