### ISSUE TITLE
((Dtool_PyInstDef *)self)->_signature not defined when creating ShowBase

### ISSUE THREAD

**Issue by JoelStienlet** [panda3d/panda3d#554]
Running the demo shader-terrain with valgrind, he complains that "Conditional jump or move depends on uninitialised value(s)".
Apparently this is caused by :
((Dtool_PyInstDef *)self)->_signature 
not being defined for some object. (used in py_panda.h in DtoolInstance_Check() )

I tried to remove as much code as possible from the demo, and in fact just creating the ShowBase object already triggers the error:

from direct.showbase.ShowBase import ShowBase
demo = ShowBase()

**Comment by rdb** [comment]
What flags to valgrind are you using?  Any chance you may be able to isolate this further by copy-pasting the ShowBase constructor and finding out which step is doing this?

**Comment by JoelStienlet** [comment]
I just run valgrind with the default settings, but I've supplemented it with some prints to debug.
The problem happens at this line in ShowBase's __init__:

self.hidden = NodePath('hidden')

but **before** it enters in this constructor in nodePath.i :

INLINE NodePath::
NodePath(const std::string &top_node_name, Thread *current_thread) :
  _error_type(ET_ok)
{ ..... }

There are some calls to DTOOL_Call_GetPointerThisClass() in between, and these calls access an uninitialised value according to valgrind. Using some std::cerr prints, I found that it was an access to an undefined "_signature",  from py_panda.h:

#define DtoolInstance_Check(obj) \
  (Py_TYPE(obj)->tp_basicsize >= (int)sizeof(Dtool_PyInstDef) && \
   ((Dtool_PyInstDef *)obj)->_signature == PY_PANDA_SIGNATURE)

**Comment by rdb** [comment]
OK, I think I see what it's complaining about.  Panda relies on checking whether a certain bit of the instance structure contains a special signature value in order to do an efficient check whether it might be a Panda type.  If you pass in a non-Panda Python object (like str) that at that location happens to have some uninitialized memory, then you'd get this valgrind warning.

This is not *necessarily* worrying, but it *is* a bit of an ugly design decision in interrogate.  It's important that we have a fast check, though, that prevents us from having to walk the type hierarchy.  A way around this would be to ditch the signature check and instead hijack an unused bit in Python's typeflags enumeration.  This would be risky in terms of future-proofness (since Python could in a future version decide to use that bit for its own purposes), but at least we wouldn't be comparing against potentially uninitialized memory.

**Comment by JoelStienlet** [comment]
I've understood the problem now, thanks for the explanations.
Perhaps this would be too slow, but could we store the id() of all objects created by interrogate in a hash table? It would obviously be slower than checking "== PY_PANDA_SIGNATURE", but it wouldn't depend on uninitialized memory, or break on some future python upgrade.

**Comment by rdb** [comment]
Interesting idea; though rather than storing every object I would just store every type.  When someone creates an instance of a Python subclass of a C++ object we could make sure that subtype is also added to this set.

However, I still think it would probably be too slow to have to do a hash table look-up every time we want to check whether something is a Panda object.  I can't say whether it's slower than walking up the type hierarchy to find the first Panda type though.

I'm personally leaning towards using tpflags if we can't find something that doesn't decrease performance of the bindings.  If we're worrying about future breakage, we could hardcode a maximum Python version for which we've validated that the bit is unallocated, and fall back to a slower method if someone compiles with a newer Python version.

**Comment by JoelStienlet** [comment]
when reading the comments in "object.h" from python's source, it looks like they've indeed foreseen that tp_flags be used by "extension writers" : "Extensions can use the flags to indicate (and test) when a given type structure contains a new feature." and "the flag bit positions will need to be coordinated among all extension writers who publicly release their extensions".
So this would not even be a hack, as it is explicitly foreseen by the python team.
It seems very easy to check, for any future version of python, which "Py_TPFLAGS_" are defined in "object.h", and finding some unused bit.
But I don't know if they maintain a list of "extension writers" somewhere?  Or could we just assume that nobody will use Panda3d alongside another extension, so that bit conflicts wouldn't be a concern ?

**Comment by rdb** [comment]
We could submit a patch to the Python team to keep a bit reserved, though I'm somewhat doubtful that they would do this unless interrogate were a more widely-used tool.

The alternative is to just pick a bit at random and just check `object.h` every time a new Python release comes out to make sure that that bit hasn't been used.

I also wonder about other Python implementations, like PyPy, whether they have such a tpflags and whether they use different bit assignments.

**Comment by JoelStienlet** [comment]
I've found some information for Pypy: apparently they do substantial efforts to remain compatible with CPython in cpyext, through some kind of CPython API emulation. See in particular section "PyObject* in PyPy": [https://morepypy.blogspot.com/2018/09/inside-cpyext-why-emulating-cpython-c.html](url)
So even if they may not use the tp_flags internally, they should still behave the same way as with CPython.

**Comment by JoelStienlet** [comment]
I've tried to make the changes to py_panda.h this morning (list of changes at the bottom of this post).
I'll post a pull request of these once they're better tested, so that they'll be easier to insert for anybody interested.
My first test looks good, valgrind's output is no longer polluted by "_signature".

Apparently there is another read of an uninitialised value in XFileNode's constructor, but I'll post that as a separate bug report.

Changes made to dtool/src/interrogatedb/py_panda.h:

```
#define PY_PANDA_SIGNATURE 0xbeaf
replaced by:
#define PY_PANDA_FLAGS (1L<<36)

((Dtool_PyInstDef *)self)->_signature = PY_PANDA_SIGNATURE;
replaced by:
Py_TYPE(self)->tp_flags |= PY_PANDA_FLAGS;

and 

((Dtool_PyInstDef *)obj)->_signature == PY_PANDA_SIGNATURE
replaced by:
((Py_TYPE(obj)->tp_flags) & PY_PANDA_FLAGS) != 0
```

**Comment by JoelStienlet** [comment]
After running some demos with valgrind I found four more illegal memory accesses. I think we can debug these progressively. 

1) Conditional jump or move depends on uninitialised value(s):
   at XFileNode::XFileNode(XFile*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
 by XFile::XFile(bool)

2) Invalid read of size 1:
   at GeomVertexColumn::Packer::get_data1f(unsigned char const*)
   by Dtool_GeomVertexReader_get_data1f_1031(_object*, _object*)
   
3) Use of uninitialised value of size 8
Conditional jump or move depends on uninitialised value(s)
   in /usr/lib64/libstdc++.so.6.0.25
   by std::ostreambuf_iterator
   by .....
   by Dtool_Loader_load_sync_1626(_object*, _object*, _object*)
   
4) Conditional jump or move depends on uninitialised value(s)
  at void std::__insertion_sort<int*, __gnu_cxx::__ops::_Iter_comp_iter<SortByColliderSort> >(int*, int*, __gnu_cxx::__ops::_Iter_comp_iter<SortByColliderSort>)
  by CollisionTraverser::prepare_colliders_single(pvector<CollisionLevelState<BitMask<unsigned long, 64> > >&, NodePath const&)

**Comment by rdb** [comment]
Thanks for looking into this.  We can't use `1<<36` as `tp_flags` is `long`, which is 32-bit on Windows.

I think we could use `1L<11` or `1L<<22`, which are free in both Python 2.7 and 3.8.

The XFileNode issue is quite obvious from looking at it.  I can check in a fix for that (if you haven't already come up with a solution).  I think I'll need some more context for the others.

**Comment by JoelStienlet** [comment]
I have some more information about the Invalid read of size 1:
the invalid memory access itself happens in panda/src/gobj/geomVertexColumn.cxx:
in float GeomVertexColumn::Packer::get_data1f(const unsigned char *pointer) :
  case NT_uint8:
    return *(const uint8_t *)pointer; <--- the problem

called by: (in geomVertexReader.I )
INLINE float GeomVertexReader::get_data1f(){
  nassertr(has_column(), 0.0f);
  return _packer->get_data1f(inc_pointer()); <----
}

inc_pointer()  (in geomVertexReader.I ) returns the value stored in  _pointer (private member of GeomVertexReader).

Note that the problem happens at the very first call to get_data1f(), so that seems to indicate that  _pointer is not initialized correctly before this first call.
Apparently the content of _pointer is set somewhere, because when I add:
std::cerr << ((void *)_pointer) << std::endl;
in inc_pointer(), I get 0x17417650 as output, and valgrind doesn't complain about an invalid read of the pointer itself.
So although the value stored in "_pointer" is set somewhere, to memory address pointed by _pointer is not valid.

**Comment by rdb** [comment]
Which sample program does this happen with, in particular?  I'd like to see what the Python code in question is doing to invoke this.

**Comment by JoelStienlet** [comment]
this is obtained with the fractal-plants demo. (Sorry I've forgotten to mention this indeed)

**Comment by JoelStienlet** [comment]
Indeed, the error comes from drawReader.getData1f() != False 
in drawBody() from main.py in the demo.

**Comment by JoelStienlet** [comment]
The solution is to make this change:
    if (startRow != 0):
        ShallDrawTrunk = drawReader.getData1f()
    else:
        ShallDrawTrunk = False
    if ShallDrawTrunk:
I think the problem was a confusion between the way the expressions are evaluated inside the "if" in C and in python. Here  drawReader.getData1f() always got evaluated, even when startRow was zero.

**Comment by rdb** [comment]
Hmm, is this something we could catch with a debug assert on the C++ side?

**Comment by JoelStienlet** [comment]
Perhaps we could check if the value of row is positive in:
INLINE void GeomVertexReader::set_row(int row) 
?
There is also an unsafe version of set_row() that could omit this check.

**Comment by rdb** [comment]
We should probably make that method take a `size_t`, which is unsigned and would cause an OverflowError when given a negative number.

**Comment by JoelStienlet** [comment]
yes, and perhaps do the same for the other methods taking a row or a column as parameter too?

**Comment by rdb** [comment]
Sounds good.  I'll check in a fix for the fractal-plants demo to the 1.10 branch shortly; there's no reason why it should use `&` instead of `and`, but that whole part of the function can be preempted if `startRow` is 0 anyway.  We should do the parameter type changes on master since they change the ABI.

**Comment by JoelStienlet** [comment]
Another issue in threadPosixImpl:
You can reproduce it with the carousel or ball in maze demo, and I think any demo that is using the BAM cache.
The succession of function calls is as follows, when the models are NOT in cache:
in panda/src/pgraph/loader.cxx: call to: cache->store(record);
then in panda/src/putil/bamCache.cxx: in bool BamCache::store(BamCacheRecord *record) :
        string extension = current_thread->get_unique_id() + string(".tmp");
And then in panda/src/pipeline/ThreadPosixImpl.cxx: std::string ThreadPosixImpl::get_unique_id() :
         _thread is undefined.

It is normally set in: bool ThreadPosixImpl::start(ThreadPriority priority, bool joinable) by
      result = pthread_create(&_thread, &attr, &root_func, (void *)this);
 but the code never enters this function, so "_thread" is never set.

I **suppose** that this is because we only have the main thread in the demos, and because for the main thread we don't create a thread with pthread_create() (as we already have one), "_thread" remains undefined.  
So perhaps we could set "_thread" using pthread_self() called from the main thread in this case?

**Comment by rdb** [comment]
Hmm, yeah, the result of `Thread::get_unique_id()` is indeterminate because it relies on the `pthread_t` being initialized, but that is not the case for the main thread.

I think we should just be calling `pthread_self()` in `setup_main_thread()` (I am fairly certain this is guaranteed to be called from the main thread).  I'll check that in.

**Comment by JoelStienlet** [comment]
Hello,
Today I propose that we correct this bug:
In panda/src/collide/collisionTraverser.cxx : 
In void CollisionTraverser::prepare_colliders_single(CollisionTraverser::LevelStatesSingle &level_states,  const NodePath &root) : 

  // Create an indirect index array to walk through the colliders in sorted
  // order, without affect the actual collider order.
  int *indirect = (int *)alloca(sizeof(int) * num_colliders);
  int i;
  for (i = 0; i < num_colliders; ++i) {
    indirect[i] = i;
  }
  std::sort(indirect, indirect + num_colliders, SortByColliderSort(*this));

The sort is reading indirect[] out of bounds.

I suggest to add "-1" to num_colliders in the call to sort:
 std::sort(indirect, indirect + num_colliders-1, SortByColliderSort(*this));

Now another question: can "prepare_colliders_single" be called with num_colliders == 0?
If true, then perhaps we should also add something like:
if(num_colliders ==0) return; 
right after "int num_colliders = _colliders.size();" ?

**Comment by JoelStienlet** [comment]
( by the way f97ba90 seems to be working :) )

**Comment by rdb** [comment]
I'm not really sure why this change is necessary; the code looks correct to me at first glance.  Does `std::sort` not take an iterator to one element past the end of the array?

**Comment by JoelStienlet** [comment]
My suggestion is wrong indeed, as you say the last element should be past the end of the array, and not inside the array.
But then I don't now why valgrind complained about this part of the code. OK I'll try to find out.

**Comment by JoelStienlet** [comment]
New suggestion: add the initialization of "_collider_sort" in the copy constructor of "CollisionNode":
`CollisionNode::
CollisionNode(const CollisionNode &copy) :
  PandaNode(copy),
  _from_collide_mask(copy._from_collide_mask),
  _solids(copy._solids),
  _collider_sort(copy._collider_sort)
{
}`
There was an access to an uninitialized "_collider_sort", I hope this should fix it (my first tests no longer show this error anyway)

**Comment by JoelStienlet** [comment]
A more complete explanation: (to reproduce this you can run the "ball in maze" demo)
When the models are loaded from the cache, in "try_load_file()" (loader.cxx) it makes deep copies of the nodes, and this is where the copy constructor of "CollisionNode" is called.
However, "_collider_sort" is not copied by this copy constructor, so has an undefined value when  "prepare_colliders_single()" is sorting the colliders (hence the complaint of valgrind, that I first wrongly attributed to a bad std::sort index)
I think adding "_collider_sort" in the copy constructor may not harm, it will just get the same value as the object stored in the cache (instead of taking an undefined value). In fact if I understand this correctly, even if "_collider_sort" would be given a "bad" random value, that may just slow down the code, as this optimization would not be operating. The user has to explicitly call "setColliderSort()" to get the benefits of it. 
So even if it is not necessarily a genuine improvement of the code itself, at least that initialization will remove unnecessary noise from valgrind's output, hence I think it is useful.

**Comment by rdb** [comment]
Ah, good catch.  Yes, the copy constructor needs to copy that field.  Just checked that in.  Thanks!

**Comment by JoelStienlet** [comment]
Happy that this helps :) 
Today I will discuss another problem, in tests/test_nodepath.py:
in test_nodepath_empty(): 
`empty2 = pickle.loads(dumped).get_value()`
"pickle.loads(dumped)" is a ParamNodePath, and get_value() returns a reference to the NodePath stored in ParamNodePath (see paramNodePath.I L45)
The problem is that python (at least 3.7) considers that, as it is written here, the object ParamNodePath should not remain in memory, and frees it, so that any access to empty2 references a free'd memory block (valgrind complains that a free'd block is accessed, and I think this is the explanation)
When I change the test to store the ParamNodePath into a variable, by splitting up the line "pickle.loads(dumped).get_value()":
tmpPNP = pickle.loads(dumped)
empty2 = tmpPNP.get_value()
this time valgrind no longer complains about accesses to free'd memory.
I suppose that, because I've stored the object into a variable, python thinks the object will still be used, and doesn't discard it. And this time because the ParamNodePath is kept into memory, empty2 is still valid too.

**Comment by rdb** [comment]
Thanks; I will change `get_value()` to return a copy instead of a reference.
