### ISSUE TITLE
TextProperties not working

### ISSUE THREAD

**Issue by Nickan** [panda3d/panda3d#561]
I am trying to this: https://www.panda3d.org/manual/?title=Embedded_Text_Properties. I attached the snippet below, it is not working, what did I miss? Help is greatly appreciated, thanks.

>     textNode = self.textNode
>     textNode.setFont(Map.FONT_UBUNTU)
>     textNode.setAlign(TextProperties.A_center)
>     textNode.setWordwrap(Utils.NODE_SCALE.x * 1.4)
>     
>     tpRed = TextProperties()
>     tpRed.setTextColor(1, 0, 0, 1)
>     tpSlant = TextProperties()
>     tpSlant.setSlant(0.3)
> 
>     tpMgr = TextPropertiesManager.getGlobalPtr()
>     tpMgr.setProperties("red", tpRed)
>     tpMgr.setProperties("slant", tpSlant)
> 
>     textNode.setText("testing \1second\1 testing2\2 testing3\2")
>     self.text3d = NodePath(textNode)
>     self.text3d.reparentTo(nodePath)
>     self.text3d.setHpr(0, 90, 0)
>     self.text3d.setTwoSided(True)
>     self.text3d.setScale(2, 0.1, 2)
>     self.text3d.setAntialias(AntialiasAttrib.MAuto)

**Comment by rdb** [comment]
What you're missing is that you've called your properties `red` and `slant`, but you're referring to it using `\1second\1`.  Try renaming the properties in the `setProperties` call to `second`.

**Comment by Nickan** [comment]
Wow thanks, that works, I felt so stupid, hahah! I know it is not the right thread to ask question, let me know if I have to create a new thread or go to forum. Is there a way to detect single letter click detection?

**Comment by rdb** [comment]
The forums (https://discourse.panda3d.org) or the Discord channel are the usual places to ask support questions.  The GitHub issues are meant for issues with the engine itself.

As for detecting which letter is below the mouse cursor, this is described in the last question of the FAQ in the manual:
https://www.panda3d.org/manual/?title=FAQ#How_can_I_know_which_letter_is_below_the_pointer_when_I_click_on_a_TextNode.3F
