### ISSUE TITLE
Rendering window freezes randomly by "aadc62a96c" commit

### ISSUE THREAD

**Issue by bluekyu** [panda3d/panda3d#562]
By panda3d/panda3d@aadc62a96c commit, I experienced a rendering window freezing.
Are there any similar issues?
I tested my application on Windows 10 1809 and GTX 1080Ti.

**Comment by rdb** [comment]
Is this with or without the multithreaded pipeline enabled?

I wonder if without the multithreaded pipeline, the device manager poll is eating up important events from the main window.  It would be safer to just put the device poll in a thread of its own.

**Comment by bluekyu** [comment]
Probably, multithreaded pipeline is not enabled (`threading-model` was not set.)
Also, the problem happens in music-box sample with default config prc file.

**Comment by bluekyu** [comment]
I found more specific cases:
1. If the window is inactive, then the window is not responding.
2. If the window is active, rendering screen is blinking every 8 seconds.
In this case, `window_proc` function got following messages:
```
window_proc(0000018DFF8362E0, 0000000000320756, 70, 0, 437013968256
window_proc(0000018DFF8362E0, 0000000000320756, 131, 1, 437013968208
window_proc(0000018DFF8362E0, 0000000000320756, 133, 1359219784, 0
window_proc(0000018DFF8362E0, 0000000000320756, 20, 18446744072149340450, 0
window_proc(0000018DFF8362E0, 0000000000320756, 71, 0, 437013968256
window_proc(0000018DFF8362E0, 0000000000320756, 15, 0, 0
window_proc(0000018DFF8362E0, 0000000000320756, 133, 1, 0
window_proc(0000018DFF8362E0, 0000000000320756, 20, 18446744072149340450, 0
```
This issue does not happen if the codes do not exist.

**Comment by rdb** [comment]
As a temporary kludge we could check if we're using a separate window thread, if so, don't process the messages here.

A cleaner solution might just be to put the input device checking stuff into its own thread.

**Comment by tcopestake** [comment]
Came here to report the same (or similar) issue.

Even just running the basic "hello world" demo with no additional code, after making the window inactive for a certain period of time the window will "hang" and I get the "Python is not responding" popup. I have also experienced the issue of the screen flickering white every x seconds (I didn't time it, but 8 sounds about right).

**Comment by 2r2t** [comment]
I got the same issue too , and trying to solve it.
我也遇到这个问题了,正在尝试解决这个问题.

**Comment by rdb** [comment]
As soon as I find time I will make a new Panda release that uses a thread for device detection.

**Comment by 2r2t** [comment]
## In PySide2's QTimer.timeout function , my test code works fine :
``` python3
from PySide2.QtCore import QTimer
from PySide2.QtWidgets import QApplication
from panda3d.core import Point3
from direct.showbase.ShowBase import ShowBase
from direct.interval.LerpInterval import LerpHprInterval
class Panda(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)
        self.cam.setPos(0, -50, 10)
        self.testModel = loader.loadModel('panda')
        self.testModel.reparentTo(render)
        self.rotateInterval = LerpHprInterval(self.testModel, 3, Point3(360, 0, 0))
        self.rotateInterval.loop()
panda = Panda()
app = QApplication([])
pandaTimer = QTimer(app)
pandaTimer.timeout.connect(panda.taskMgr.step)
pandaTimer.start(1000/60)
app.exec_()
```

**Comment by rdb** [comment]
I have yet to make a new release; but in the meantime, you can grab the latest builds from the 1.10.x branch, which back out the offending change.  They don't have a complete fix yet, but just remove the offending code, so should work if you don't use the multithreaded pipeline or don't use the device system.

https://www.panda3d.org/download.php?version=devel&sdk&branch=release/1.10.x

Or if you use pip, you can install the latest builds with this:
```
pip install -i https://archive.panda3d.org/branches/release/1.10.x --pre -U panda3d
```

**Comment by rdb** [comment]
I've checked in new changes that use a threaded message loop instead.

@bluekyu (or someone else) could you please test whether the latest changes fix this issue?

**Comment by jwcotejr** [comment]
Issue is indeed fixed with these changes!

**Comment by bluekyu** [comment]
@rdb I checked the issue is resolved. Thanks!
