### ISSUE TITLE
Update Roaming Ralph to use CollisionHandlerPusher

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#565]
Roaming Ralph does not use best practices for colliding into obstacles.  It should be modified to use the CollisionHandlerPusher instead of the existing, inferior method, which can cause Ralph getting "stuck".

**Comment by Moguri** [comment]
I am thinking about taking on this task. Do we have a list of other things that should be done to the Roaming Ralph sample while someone is taking a look at it?

There is probably a larger discussion to be had about cleaning up and unifying the samples.

**Comment by rdb** [comment]
Feel free to take this on.  There are probably other things we can also improve about the samples, but we can file issues for them as they come up.

**Comment by rdb** [comment]
Thanks a lot!  Squashed and pushed with changes discussed in Discord.
