### ISSUE TITLE
Installation from source error Ubuntu 18.04

### ISSUE THREAD

**Issue by Nickan** [panda3d/panda3d#568]
Hi, I am trying to build from the source as I want to run LUI, but I am encountering the error below, I don't know what to do next, please help. Thanks

$ python makepanda/makepanda.py --everything --installer --no-egl --no-gles --no-gles2 --no-opencv --thread 4

> Version: 1.10.1
> Platform: linux-x86_64
> Using Python 3.6
> Target OS: linux
> Target arch: x86_64
> WARNING: Could not locate thirdparty package artoolkit, excluding from build
> WARNING: Could not locate thirdparty package fcollada, excluding from build
> WARNING: Could not locate thirdparty package fftw, excluding from build
> WARNING: Could not locate thirdparty package fmodex, excluding from build
> WARNING: Could not locate thirdparty package squish, excluding from build
> WARNING: Could not locate thirdparty package vrpn, excluding from build
> WARNING: Could not locate thirdparty package opus, excluding from build
> WARNING: Could not locate thirdparty package rocket, excluding from build
> Generating dependencies...
> WARNING: file depends on Python but is not in an ABI-specific directory: built/bin/p3dcparse
> WARNING: file depends on Python but is not in an ABI-specific directory: built/bin/deploy-stub
> Storing dependency cache.
> [100%] Building installer
> Python 3.6.5 :: Anaconda, Inc.
> Traceback (most recent call last):
>   File "makepanda/makepanda.py", line 6909, in <module>
>     runtime=RUNTIME, python_versions=python_versions)
>   File "/home/nickan/Downloads/panda3d-1.10.1/makepanda/makepackage.py", line 1030, in MakeInstaller
>     MakeInstallerLinux(version, **kwargs)
>   File "/home/nickan/Downloads/panda3d-1.10.1/makepanda/makepackage.py", line 275, in MakeInstallerLinux
>     sys_python3_ver = '.'.join(ReadFile(outputdir + "/tmp/python3_version.txt").strip().split(' ')[1].split('.')[:2])
> IndexError: list index out of range

**Comment by rdb** [comment]
Could you post the contents of the `built/tmp/python3_version.txt` file?

**Comment by Nickan** [comment]
It is empty.

**Comment by rdb** [comment]
And what is the output of the `python3 -V` command?  Do you have the `python3` package installed or are you running makepanda with a non-standard version of Python?

**Comment by Nickan** [comment]
The system was using Anaconda 3.6.5 python, I tried different methods to use the default python by it was always overridden by anaconda, so I uninstalled it(Perhaps just disabling it?) and successfully created installer. Thank you so much for the help.
