### ISSUE TITLE
Bullet demos: change order of addShape() and setMass()

### ISSUE THREAD

**Issue by JoelStienlet** [panda3d/panda3d#571]
Hello,
I tried to perform some code coverage tests recently, I recompiled bullet with the debug option, which enabled the execution of the assert() statements in bullet's code (version 2.85.1).
PandaBullet samples are taken from: https://www.panda3d.org/download/noversion/bullet-samples.zip

I got the following error:
python3: /home/stienlet/Programmation/Bullet_engine/bullet3-2.85.1/src/BulletCollision/CollisionShapes/btEmptyShape.cpp:46: virtual void btEmptyShape::calculateLocalInertia(btScalar, btVector3&) const: Assertion `0' failed.
The corresponding source is:
```
void	btEmptyShape::calculateLocalInertia(btScalar ,btVector3& ) const
{
	btAssert(0);
}
```
The problem (in the 01_Basics.py demo, but other demos may be affected too) is apparently that addShape() is called after setMass(), which causes bullet to compute the inertia of an undefined shape, which got detected by this assert().
=> I think that the solution is simply to invert the order between these two calls, set the shape first, then the mass. 

2) Another problem that I encountered was the reference to undefined symbols in the .so of panda bullet, referring to global variables not included in the .so.
I solved this other problem by adding  __attribute__ ((visibility ("default"))) to the symbols in question.

bulletWorld.cxx:
`
    PT(CallbackObject) bullet_contact_added_callback __attribute__ ((visibility ("default")));`

config_bullet.cxx:

```
    ConfigVariableBool bullet_enable_contact_events __attribute__ ((visibility ("default")))
        ("bullet-enable-contact-events", false,
          PRC_DESC("Specifies if events should be send when new contacts are "
         "created or existing contacts get remove. Warning: enabling "
         "contact events might create more load on the event queue "
         "then you might want! Default value is FALSE.")) ;
```
Tested with gcc 8.2.1, I think clang has these visibility attributes too. I don't know about windows/macos compilers though.

**Comment by rdb** [comment]
`EXPCL_BULLET` should contain the visibility macros already.  Could you confirm whether adding that in front of the declaration solves issue 2 too?

**Comment by rdb** [comment]
As for the first issue, I think we should just not be calling `calculateLocalInertia` before we've assigned a shape.  It will actually automatically call `do_set_mass()` again after assigning a shape.

For the record, unrelated issues should generally be filed as two separate issues so that they can be tracked individually—in some cases, one issue may be harder to solve than the other, so it's useful to be able to track them independently.

**Comment by JoelStienlet** [comment]
Compiling bulletWorld.cxx with:
`EXPCL_PANDABULLET PT(CallbackObject)  bullet_contact_added_callback;`
Works! (recompiled & runs fine)
EXPCL_PANDABULLET contains the visibility macro with my version of gcc (dtoolbase.h L492, pandasymbols.h L479)
So this should solve issue 2 indeed.

**Comment by JoelStienlet** [comment]
I tried your suggestion:
```
void BulletRigidBodyNode::
do_set_mass(PN_stdfloat mass) {

  btScalar bt_mass = mass;
  btVector3 bt_inertia(0.0, 0.0, 0.0);

  if (bt_mass > 0.0 && !_shapes.empty()) {
    _rigid->getCollisionShape()->calculateLocalInertia(bt_mass, bt_inertia);
  }

  _rigid->setMassProps(bt_mass, bt_inertia);
  _rigid->updateInertiaTensor();
}
```
The demos work with this change (with bullet in debug mode) now :)

**Comment by rdb** [comment]
I think `EXPCL_PANDABULLET` should only be added to the declaration in the .h file, not to the definition in the .cxx file.

**Comment by JoelStienlet** [comment]
Indeed, that's what they say too in https://gcc.gnu.org/wiki/Visibility:
"In your header files [...] place __attribute__ ((visibility ("default"))) [...] You don't need to specify it in the definition."
So I tested it again with the `EXPCL_PANDABULLET` in bulletWorld.h only, and that works as well.
