### ISSUE TITLE
Display information inaccurate under Ubuntu

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#575]
Under Ubuntu 18.04.2, "base.pipe.getDisplayInformation()" returns only a single available display mode, and that seems to match the full "desktop area" of the system--even when that spans two monitors.

(I had thought that this was specific to a dual-(or perhaps multi-)monitor setup, but quickly unplugging my HDMI cable suggests that it still occurs with only a single monitor present.)

When using a dual-monitor setup, the single available display mode is larger than either monitor alone--indeed, its horizontal resolution seems to be the sum of the horizontal resolutions of the two monitors.

That is, with my laptop monitor having a resolution of 1366x768, and my external monitor having a resolution of 1280x1024, calling "print (base.pipe.getDisplayWidth(), base.pipe.getDisplayHeight())" produces the output "2646 1058".

It is possible that this is an issue on my side--a bad driver, or some such. I'm using a Dell Inspiron 15 laptop with a GeForce 840M/PCIe/SSE2, and proprietary drivers installed.

A simple program that shows the issue on my machine:
```
from direct.showbase import ShowBase as showBase

class game(showBase.ShowBase):

    def __init__(self):
        showBase.ShowBase.__init__(self)

        self.accept("escape", self.userExit)

        info = base.pipe.getDisplayInformation()
        print (info.getTotalDisplayModes())
        print (info.getDisplayModeWidth(0), info.getDisplayModeHeight(0))
        print (base.pipe.getDisplayWidth(), base.pipe.getDisplayHeight())

app = game()
app.run()
```

**Comment by rdb** [comment]
We rely on the Xrandr extension.  Does the `xrandr` command properly list the supported extensions?  How did you install Panda3D—from pip, from .deb, or did you build it from source?

**Comment by Moguri** [comment]
If I recall correctly, the nvidia drivers have an option to treat multiple monitors as a single large monitor. Would you mind pasting your X.org configuration?

**Comment by ArsThaumaturgis** [comment]
> Does the xrandr command properly list the supported extensions?

When run from a terminal? It seems to--while I don't know what precise resolutions my monitors support, I'm seeing a listing for each monitor separately, and a variety of resolutions for each.

That said, I do note that it starts with the following text:

> Screen 0: minimum 8 x 8, current 2646 x 1058, maximum 16384 x 16384

Note that this mentions the same huge resolution as reported in Panda.

This is the full output, with the actual resolutions largely omitted for brevity:

> Screen 0: minimum 8 x 8, current 2646 x 1058, maximum 16384 x 16384
> eDP-1-1 connected primary 1366x768+0+290 (normal left inverted right x axis y axis) 309mm x 173mm
>    1366x768      60.00*+  47.98  
>    <...
> more resolutions here
> ...>
>    320x180       59.84    59.32  
> HDMI-1-1 connected 1280x1024+1366+0 (normal left inverted right x axis y axis) 338mm x 270mm
>    1280x1024     75.02*   60.02  
>    <...
> more resolutions here
> ...>
>    720x400       70.08
> 

> How did you install Panda3D—from pip, from .deb, or did you build it from source?

From pip, if I recall correctly.

Finally, a minor correction to my post above: I'm using the open-source NVidia drivers, I believe.

**Comment by ArsThaumaturgis** [comment]
> If I recall correctly, the nvidia drivers have an option to treat multiple monitors as a single large monitor. Would you mind pasting your X.org configuration?

Ah, sorry, I missed this before posting my comment above.

Where do I find that configuration, please?

**Comment by Moguri** [comment]
Try `/etc/X11/xorg.conf` or an appropriate looking file in `/etx/X11/xorg.conf.d` such as something like `40-nvidia-settings.conf`.

**Comment by ArsThaumaturgis** [comment]
... I'm not seeing any of those files, or even an "xorg.conf.d" folder in /etc/X11... :/

(I do have four "xorg.conf.<something else here>" files--in three cases the "<something else here>" is a long number; in the fourth it's "failsafe".)

**Comment by ArsThaumaturgis** [comment]
Update: I've found a few such files in "/usr/share/X11" instead. 

This is the contents of "/usr/share/x11/xorg.conf.d/10-nvidia.conf":

> Section "OutputClass"
>     Identifier "nvidia"
>     MatchDriver "nvidia-drm"
>     Driver "nvidia"
>     Option "AllowEmptyInitialConfiguration"
>     ModulePath "/usr/lib/x86_64-linux-gnu/xorg"
> EndSection
>

**Comment by ArsThaumaturgis** [comment]
After a bit of searching, I found this question-and-answer on StackExchange: https://stackoverflow.com/questions/8705814/get-display-count-and-resolution-for-each-display-in-python-without-xrandr

Running the code given there does seem to give a long list of resolutions on my machine, so perhaps it might be useful in fixing the problem?

**Comment by ArsThaumaturgis** [comment]
An updated version of the example program given above, to compare the output:

```
from direct.showbase import ShowBase as showBase

from Xlib import X, display
from Xlib.ext import randr

class game(showBase.ShowBase):

    def __init__(self):
        showBase.ShowBase.__init__(self)

        self.accept("escape", self.userExit)

        info = base.pipe.getDisplayInformation()
        print (info.getTotalDisplayModes())
        print (info.getDisplayModeWidth(0), info.getDisplayModeHeight(0))
        print (base.pipe.getDisplayWidth(), base.pipe.getDisplayHeight())

        d = display.Display()
        s = d.screen()
        window = s.root.create_window(0, 0, 1, 1, 1, s.root_depth)

        res = randr.get_screen_resources(window)
        for mode in res.modes:
            w, h = mode.width, mode.height
            print ("Width: {}, height: {}".format(w, h))

app = game()
app.run()
```

Also, I do note that this is in Python--I don't know how it might apply on the C++ side.

**Comment by Moguri** [comment]
Your `xorg.conf` files look fine to me. Panda should already be using xrandr, but I wonder if there is an issue with using xrandr in the manylinux1 wheels. What version of Panda are you running? Are you using an official build?

**Comment by ArsThaumaturgis** [comment]
According to "pip show panda3d", I have version 1.10.0. If there's another way to check the version number, please let me know! ^^;

And indeed, I'm using an official build, I believe, installed via pip.

But do note the link that I gave above! It seems to suggest not using "xrandr", but rather "randr", and the code that I posted above does actually list a variety of resolutions on my machine.

**Comment by Moguri** [comment]
Ah, I misspoke a bit, Panda does use randr, xrandr is the name of the CLI front-end to randr.

Could you give 1.10.1 a shot (`pip install -U panda3d`)? It fixed some other issues with X11 and GLX. I am wondering if this is a symptom of the same root issue.

**Comment by ArsThaumaturgis** [comment]
Ah, I actually tried to update Panda, but my inexperience with pip caused me to stumble--I just tried "pip install panda3d", which told me that the "Requirement [was] already satisfied". I have now upgraded, I believe!

Trying again, I'm afraid that I see the same result: a single display mode, with over-large size. :/

**Comment by Moguri** [comment]
Good to know. I do wonder if it is a similar issue.

**Comment by ArsThaumaturgis** [comment]
Indeed. I would imagine that it is, but I don't have the knowledge of these matters to speak confidently, I'm afraid.

**Comment by rdb** [comment]
If you add `notify-level-x11display debug` to Config.prc (needs to be set before a window is opened), do you see any error message like "cannot dlopen libXrandr.so.2"?

**Comment by ArsThaumaturgis** [comment]
Hmm... I presume that a PRC file loaded via "loadPrcFile" at the start of the "main" Python file, before class definitions or the call to "run", is fine?

If so, I don't see any such error messages, I'm afraid.

This is the full output that I see from a brief run (including my own printouts):

```
/usr/bin/python3.6 "/home/thaumaturge/Documents/My Game Projects/Boat/GameCore.py"
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
:display:x11display(debug): Raw mice not requested.
:device(warning): /dev/input/event6 is not readable, some features will be unavailable.
Loaded /home/thaumaturge/.local/share/NightRiver/options.dat
:display:x11display(debug): Loading Windows cursor Misc/cursor.cur
1
2646 1058
Saved /home/thaumaturge/.local/share/NightRiver/options.dat
Quitting!

Process finished with exit code 0
```
(The first line comes from the IDE, I think.)

**Comment by rdb** [comment]
I was mistaken earlier; on X11, `get_display_width` and `get_display_height` don't come from Xrandr but from the XDisplayWidth and XDisplayHeight calls, which return the width and height for a particular X screen.

This is different from the display mode listing, which does use Xrandr.  It's not entirely clear from your message what output you are getting from the display mode listing in Panda, since you have not included it.

(I do note that the Xrandr code in Panda3D is currently only checking screen 0, not any of the other screens, but from your xrandr output (it's not quite clear since you've clipped it) it seems you only have a screen 0, so this is probably not the issue.)

I will note that some drivers implement multi-monitor support exactly this way, by pretending there is a big virtual screen, so that windows can be moved freely between them.  We may want to study the source code of the xrandr command-line tools to figure out how it gets the real resolutions.

I'm not really sure whether `get_display_width` and `get_display_height` should return the size of the virtual screen or of the "default monitor", whatever that is.  I'm leaning towards the former, and then building a new API to query the sizes of individual monitors and make Panda windows aware of which monitor they are on.

If someone is using the display width/height to determine what resolution to set the window to in fullscreen, we can probably add in a hack to ensure that Panda interprets setting the window resolution to the display size as "use whatever the resolution for the monitor the window is on is".

**Comment by ArsThaumaturgis** [comment]
> This is different from the display mode listing, which does use Xrandr. It's not entirely clear from your message what output you are getting from the display mode listing in Panda, since you have not included it.

Ah, sorry, you're quite right. The following lines:

````
        info = base.pipe.getDisplayInformation()
        print (info.getTotalDisplayModes())
        print (info.getDisplayModeWidth(0), info.getDisplayModeHeight(0))
````

Produce the following output:

> 1
> 2646 1058

That is, I see a single "display mode", with over-large width and height, just as with base.pipe.getDisplayWidth/Height().

> ...  but from your xrandr output (it's not quite clear since you've clipped it) it seems you only have a screen 0, so this is probably not the issue.)

To the best of my recollection, the only things that I clipped were the additional resolution entries in the full listing--no other mentions of screens or monitors. I'll post the full output in the next comment, I think.

> We may want to study the source code of the xrandr command-line tools to figure out how it gets the real resolutions.

The Python Xlib library, which I mentioned above, might also be worth looking at. That seems to produce a significant listing of resolutions.

(However, I don't know enough about it to know how to determine which monitor it looks at, and have only managed to get one set of resolutions from it.)

> I'm not really sure whether get_display_width and get_display_height should return the size of the virtual screen or of the "default monitor", whatever that is. I'm leaning towards the former, and then building a new API to query the sizes of individual monitors and make Panda windows aware of which monitor they are on.

That sounds good to me, I think. ^_^

**Comment by ArsThaumaturgis** [comment]
Full xrandr command-line output:

> Screen 0: minimum 8 x 8, current 2646 x 1058, maximum 16384 x 16384
> eDP-1-1 connected primary 1366x768+0+290 (normal left inverted right x axis y axis) 309mm x 173mm
>    1366x768      60.00*+  47.98  
>    1360x768      59.80    59.96  
>    1280x720      60.00    59.99    59.86    59.74  
>    1024x768      60.04    60.00  
>    960x720       60.00  
>    928x696       60.05  
>    896x672       60.01  
>    1024x576      59.95    59.96    59.90    59.82  
>    960x600       59.93    60.00  
>    960x540       59.96    59.99    59.63    59.82  
>    800x600       60.00    60.32    56.25  
>    840x525       60.01    59.88  
>    864x486       59.92    59.57  
>    800x512       60.17  
>    700x525       59.98  
>    800x450       59.95    59.82  
>    640x512       60.02  
>    720x450       59.89  
>    700x450       59.96    59.88  
>    640x480       60.00    59.94  
>    720x405       59.51    58.99  
>    684x384       59.88    59.85  
>    680x384       59.80    59.96  
>    640x400       59.88    59.98  
>    576x432       60.06  
>    640x360       59.86    59.83    59.84    59.32  
>    512x384       60.00  
>    512x288       60.00    59.92  
>    480x270       59.63    59.82  
>    400x300       60.32    56.34  
>    432x243       59.92    59.57  
>    320x240       60.05  
>    360x202       59.51    59.13  
>    320x180       59.84    59.32  
> HDMI-1-1 connected 1280x1024+1366+0 (normal left inverted right x axis y axis) 338mm x 270mm
>    1280x1024     75.02*   60.02  
>    1280x720      60.00    59.94  
>    1024x768      75.03    70.07    60.00  
>    832x624       74.55  
>    800x600       72.19    75.00    60.32    56.25  
>    720x480       60.00    59.94  
>    640x480       75.00    72.81    66.67    60.00    59.94  
>    720x400       70.08

**Comment by rdb** [comment]
Which window manager are you using?  I wonder if different window managers produce different behaviour here.

I have tried to plug in a second monitor with i3 as window manager and everything in Panda works as expected; it reports a bunch of supported resolutions, including the extra-wide resolution representing both monitors, and I can switch to fullscreen using that extra-wide resolution.

I do notice that you used `get_screen_resources` in your Python code; we use a different call in Panda.  I'll see if we can use that call instead in Panda and see if we can get different results.

**Comment by ArsThaumaturgis** [comment]
I'm just using the default 18.04 window manager, which is Gnome, I believe.

In the forum thread, [serega-kkz pointed out](https://discourse.panda3d.org/t/fullscreen-acting-up-with-dual-monitors/24518/15?u=thaumaturge) that in their case the issue seemed to be specific to the use of NVidia drivers; the report that when the default drivers are used, the problem disappears.

**Comment by rdb** [comment]
I would prefer to reproduce this without having to install Ubuntu.  Please run this to find out which window manager you are using (may require `apt install wmctrl`):
```
wmctrl -m
```

Also, please run the following code and post the output:
```

from Xlib import X, display
from Xlib.ext import randr

d = display.Display()
s = d.screen()

print("GetScreenInfo on root window:")
res = randr.get_screen_info(s.root)
for size in res.sizes:
    w, h = size.width_in_pixels, size.height_in_pixels
    print ("Width: {}, height: {}".format(w, h))

print("GetScreenResources on root window:")
res = randr.get_screen_resources(s.root)
for mode in res.modes:
    w, h = mode.width, mode.height
    print ("Width: {}, height: {}".format(w, h))

window = s.root.create_window(0, 0, 1, 1, 1, s.root_depth)

print("GetScreenInfo on new window:")
res = randr.get_screen_info(window)
for size in res.sizes:
    w, h = size.width_in_pixels, size.height_in_pixels
    print ("Width: {}, height: {}".format(w, h))

print("GetScreenResources on new window:")
res = randr.get_screen_resources(window)
for mode in res.modes:
    w, h = mode.width, mode.height
    print ("Width: {}, height: {}".format(w, h))
```
Please also let me know if the output differs depending on which monitor you run it on.

**Comment by ArsThaumaturgis** [comment]
The output of "wmctrl -m":

> Name: GNOME Shell
> Class: N/A
> PID: N/A
> Window manager's "showing the desktop" mode: N/A

It might be worth noting that serega-kkz seems to be indicating that they see the same issue under Linux Mint, which I think may use a different window-manager.

Output of the program given above:
```
GetScreenInfo on root window:
Width: 2646, height: 1058
GetScreenResources on root window:
Width: 1366, height: 768
Width: 1366, height: 768
Width: 1360, height: 768
Width: 1360, height: 768
Width: 1280, height: 720
Width: 1280, height: 720
Width: 1280, height: 720
Width: 1280, height: 720
Width: 1024, height: 768
Width: 1024, height: 768
Width: 960, height: 720
Width: 928, height: 696
Width: 896, height: 672
Width: 1024, height: 576
Width: 1024, height: 576
Width: 1024, height: 576
Width: 1024, height: 576
Width: 960, height: 600
Width: 960, height: 600
Width: 960, height: 540
Width: 960, height: 540
Width: 960, height: 540
Width: 960, height: 540
Width: 800, height: 600
Width: 800, height: 600
Width: 800, height: 600
Width: 840, height: 525
Width: 840, height: 525
Width: 864, height: 486
Width: 864, height: 486
Width: 800, height: 512
Width: 700, height: 525
Width: 800, height: 450
Width: 800, height: 450
Width: 640, height: 512
Width: 720, height: 450
Width: 700, height: 450
Width: 700, height: 450
Width: 640, height: 480
Width: 640, height: 480
Width: 720, height: 405
Width: 720, height: 405
Width: 684, height: 384
Width: 684, height: 384
Width: 680, height: 384
Width: 680, height: 384
Width: 640, height: 400
Width: 640, height: 400
Width: 576, height: 432
Width: 640, height: 360
Width: 640, height: 360
Width: 640, height: 360
Width: 640, height: 360
Width: 512, height: 384
Width: 512, height: 288
Width: 512, height: 288
Width: 480, height: 270
Width: 480, height: 270
Width: 400, height: 300
Width: 400, height: 300
Width: 432, height: 243
Width: 432, height: 243
Width: 320, height: 240
Width: 360, height: 202
Width: 360, height: 202
Width: 320, height: 180
Width: 320, height: 180
Width: 1280, height: 1024
Width: 1280, height: 1024
Width: 1280, height: 720
Width: 1280, height: 720
Width: 1024, height: 768
Width: 1024, height: 768
Width: 832, height: 624
Width: 800, height: 600
Width: 800, height: 600
Width: 720, height: 480
Width: 720, height: 480
Width: 640, height: 480
Width: 640, height: 480
Width: 640, height: 480
Width: 640, height: 480
Width: 720, height: 400
GetScreenInfo on new window:
Width: 2646, height: 1058
GetScreenResources on new window:
Width: 1366, height: 768
Width: 1366, height: 768
Width: 1360, height: 768
Width: 1360, height: 768
Width: 1280, height: 720
Width: 1280, height: 720
Width: 1280, height: 720
Width: 1280, height: 720
Width: 1024, height: 768
Width: 1024, height: 768
Width: 960, height: 720
Width: 928, height: 696
Width: 896, height: 672
Width: 1024, height: 576
Width: 1024, height: 576
Width: 1024, height: 576
Width: 1024, height: 576
Width: 960, height: 600
Width: 960, height: 600
Width: 960, height: 540
Width: 960, height: 540
Width: 960, height: 540
Width: 960, height: 540
Width: 800, height: 600
Width: 800, height: 600
Width: 800, height: 600
Width: 840, height: 525
Width: 840, height: 525
Width: 864, height: 486
Width: 864, height: 486
Width: 800, height: 512
Width: 700, height: 525
Width: 800, height: 450
Width: 800, height: 450
Width: 640, height: 512
Width: 720, height: 450
Width: 700, height: 450
Width: 700, height: 450
Width: 640, height: 480
Width: 640, height: 480
Width: 720, height: 405
Width: 720, height: 405
Width: 684, height: 384
Width: 684, height: 384
Width: 680, height: 384
Width: 680, height: 384
Width: 640, height: 400
Width: 640, height: 400
Width: 576, height: 432
Width: 640, height: 360
Width: 640, height: 360
Width: 640, height: 360
Width: 640, height: 360
Width: 512, height: 384
Width: 512, height: 288
Width: 512, height: 288
Width: 480, height: 270
Width: 480, height: 270
Width: 400, height: 300
Width: 400, height: 300
Width: 432, height: 243
Width: 432, height: 243
Width: 320, height: 240
Width: 360, height: 202
Width: 360, height: 202
Width: 320, height: 180
Width: 320, height: 180
Width: 1280, height: 1024
Width: 1280, height: 1024
Width: 1280, height: 720
Width: 1280, height: 720
Width: 1024, height: 768
Width: 1024, height: 768
Width: 832, height: 624
Width: 800, height: 600
Width: 800, height: 600
Width: 720, height: 480
Width: 720, height: 480
Width: 640, height: 480
Width: 640, height: 480
Width: 640, height: 480
Width: 640, height: 480
Width: 720, height: 400
```
A quick test seems to indicate that the output is the same regardless of monitor. (Judging by the highest value given by "GetScreenResources", it looks like it might be reporting values for the laptop monitor.)

**Comment by rdb** [comment]
OK, it looks like XRRGetScreenResources *does* work properly on your system, so I guess we have to use that to obtain the list of supported resolutions.

It looks in fact like XRRGetScreenResolutions reports a list of resolutions supported by both monitors.  While this is not ideal (and an ideal solution would be to have an API to iterate through the supported monitors), at least if a game offers a resolution picker, the user can pick the right option corresponding to their desired monitor.

Switching to fullscreen on the correct monitor is trickier.  I'll need to make sure that switching to the "virtual" resolution (reported by get_display_width/height) remains possible, but it should just switch to native fullscreen on the current active CRTC rather than try to cover the entire "virtual" screen.

Say, could you try this?  This should open a window.  I'd be grateful if you could move it to a monitor of choice, and press Enter.  It should make the window cover the monitor in question.  Please try this for each of your monitors.

If that works correctly, I'd be grateful if you could also then change `undecorated=True` to `fullscreen=True` and note the behaviour that it produces.
```python
from direct.showbase.ShowBase import ShowBase
from panda3d.core import WindowProperties

from Xlib import X, display
from Xlib.ext import randr

base = ShowBase()

d = display.Display()
s = d.screen()

print("CRTCs:")
res = randr.get_screen_resources(s.root)
for crtc in res.crtcs:
    info = randr.get_crtc_info(s.root, crtc, res.config_timestamp)
    print(info.x, info.y, info.width, info.height)


def go_fullscreen():
    props = base.win.properties

    # Figure out which CRTC the window is on.
    res = randr.get_screen_resources(s.root)
    for crtc in res.crtcs:
        info = randr.get_crtc_info(s.root, crtc, res.config_timestamp)
        if props.origin.x >= info.x and props.origin.y >= info.y and props.origin.x < info.x + info.width and props.origin.y < info.y + info.height:
            print("Window is on CRTC:")
            print(info.x, info.y, info.width, info.height)
            break

    base.win.request_properties(WindowProperties(undecorated=True, origin=(info.x, info.y), size=(info.width, info.height), fixed_size=True))


base.accept('enter', go_fullscreen)

base.run()
```

**Comment by ArsThaumaturgis** [comment]
That actually works really well! It does indeed go to full-screen on the monitor on which it's run!

Without something rendering, it's hard to say whether it produces the "freezing" that I was seeing when I tried to put Night River into full-screen. But conversely, I note that the output seems to indicate that it's correctly identifying the monitor in question: the last two lines, starting with "Window is on CRTC:", seem to give the correct resolution of the monitor on which the program is run.

Output from the laptop monitor:
```
CRTCs:
0 290 1366 768
1366 0 1280 1024
0 0 0 0
Window is on CRTC:
0 290 1366 768
```
Output from the second monitor:
```
CRTCs:
0 290 1366 768
1366 0 1280 1024
0 0 0 0
Window is on CRTC:
1366 0 1280 1024
```

**Comment by rdb** [comment]
Okay, thanks!  And did you try changing `undecorated=True` to `fullscreen=True` and seeing if that changes the behaviour?  (It will probably say "no supported display resolutions", but just ignore that.)

**Comment by ArsThaumaturgis** [comment]
Ah, sorry--I was in a bit of a hurry when I did that test, and missed that bit! ^^;

I take it that the "undecorated" to change is the one in the parameters of "base.win.request_properties", at the end of the "go_fullscreen" method?

If so, then with those settings it seems to work as expected on the main laptop monitor, but not work properly on the second monitor.

To start with, the program output:

From the main laptop monitor:
```
CRTCs:
0 290 1366 768
1366 0 1280 1024
0 0 0 0
Window is on CRTC:
:display:x11display(error): Videocard has no supported display resolutions at specified res (1366 x 768)
0 290 1366 768
```
And from the second monitor:
```
CRTCs:
0 290 1366 768
1366 0 1280 1024
0 0 0 0
Window is on CRTC:
:display:x11display(error): Videocard has no supported display resolutions at specified res (1280 x 1024)
1366 0 1280 1024
```

As far as that goes, all seems well. However, its actual behaviour is less so.

As noted, all seems to be well when the window is left on the main laptop monitor.

However, when it's dragged from there to the second monitor, it instead seems to got to fullscreen on the main laptop monitor instead, but doesn't cover the entirety of the region. Specifically, it seems to leave a gap at the bottom, and on the right.

(My window-manager does have extensions installed that result in a Windows-style taskbar at the bottom of the screen. However, this doesn't seem to be a problem when the window starts on the laptop screen, or with the previous settings. It also may not explain the gap on the right, unless that's related to the window-manager's default placement of a similar bar on the left, but which isn't present under my current window-manager settings. However, I am doubtful that these window-manager matters are relevant--I mention them just in case.)

**Comment by rdb** [comment]
> However, when it's dragged from there to the second monitor, it instead seems to got to fullscreen on the main laptop monitor instead, but doesn't cover the entirety of the region. Specifically, it seems to leave a gap at the bottom, and on the right.

Okay, I think this is probably because Panda forces the origin to (0, 0) when going to fullscreen.

I think the fix is clear to me now:
* DisplayInformation will give the full list of display modes as returned by `XRRGetScreenResources`
* Switching fullscreen on X11 is going to check which CRTC the window is active on and then try to cover that.
* Passing in `pipe.get_display_width/height` as window size when going fullscreen is going to be code for "go fullscreen at native resolution on the current CRTC".

This isn't going to fully fix resolution-switching behaviour (when switching resolution, Panda seems to completely break the multi-monitor set-up), but I don't want to do that for 1.10.2, so I'll open a separate issue for that.

**Comment by rdb** [comment]
@ArsThaumaturgis Could you please install the latest from the `release/1.10.x` branch and try again with your game, as soon as you have time?  To do this with a pip install, you can do:
```
pip install -i https://archive.panda3d.org/release/1.10.x --pre -U panda3d
```
Or if you want to grab an SDK build instead:
https://www.panda3d.org/download.php?version=devel&sdk&branch=release/1.10.x

Thanks a lot!  I'm hoping to release 1.10.2 as soon as this is tested.  I'd be most grateful if you could try switching to fullscreen on each of your monitors.  You should be able to pass in either the monitor's respective size, or `pipe.display_width/height`.  (Switching fullscreen at a different resolution doesn't yet work quite right, I believe.)

**Comment by ArsThaumaturgis** [comment]
Hmm... That doesn't seem to work, I'm afraid. I even tried adding "setUndecorated(True)" to my requested window-properties, but to no avail. :/

This is the code that I was using:

```
props = WindowProperties()
props.setFullscreen(self.useFullscreen)

if self.useFullscreen:
	info = base.pipe.getDisplayInformation()
	print (info.getTotalDisplayModes())
	print (info.getDisplayModeWidth(0), info.getDisplayModeHeight(0))
	props.setSize(base.pipe.getDisplayWidth(), base.pipe.getDisplayHeight())
	props.setUndecorated(True)
else:
	props.setSize(1000, 700)
	props.setUndecorated(False)

self.win.requestProperties(props)
```

The closest that I got (in admittedly brief testing) was by essentially copying the your "base.win.request_properties" line, above, and passing in the width and height from "getDisplayInformation"--which seems to be the full, combined dual-monitor area. That produced a working full-screen mode, spanning both monitors. The resulting line looked like this:

`base.win.request_properties(WindowProperties(undecorated=True, origin=(0, 0), size=(info.getDisplayModeWidth(0), info.getDisplayModeHeight(0)), fixed_size=True))`

(In that version, I skipped the call to "requestProperties" found at the end of the code-chunk that I gave first in this post, I believe, instead moving it into the "else" section of that "if-else" block.)

**Comment by rdb** [comment]
Thanks for testing.  Firstly, could you confirm which Panda version you have by doing this?
```python
from panda3d.core import PandaSystem
print(PandaSystem.getGitCommit())
```
It should say "0e70997fbf627c9a7a7057df66497b53e8249869"; if it does not, stop reading here as we need to figure out why Panda did not upgrade properly.

I should mention that I added more debug information to `notify-level-x11display debug`; it would be helpful for you to set that and post its output in future tests.

What exactly did you mean by "doesn't work"?  Could you describe the effects when swiching to fullscreen mode (with getDisplayWidth/Height()) on either monitor?  (Forget about setting undecorated, fixed_size, or origin for now; I am purely interested in the fullscreen setting.)

Also, could you tell me whether the DisplayInformation mode list is now more complete?

**Comment by ArsThaumaturgis** [comment]
Hum, that is odd: I do get a different commit number. (Specifically, I get "87e0ff29eb456e0b213f3454bd78ebcac8f22558".) Perhaps the new commit hasn't yet become available?

Quickly re-running the pip command that you gave earlier indicates that pip thinks that Panda is up-to-date.

In case I've somehow messed up the command, let me copy-paste what I'm running in my terminal:

` sudo pip install -i https://archive.panda3d.org/branches/release/1.10.x --pre -U panda3d
`
(I'm using sudo because pip insists on the permissions.)

**Comment by rdb** [comment]
Instead of figuring out why it's not updating, let's just try a direct link.  Go here:
https://www.panda3d.org/download.php?platform=manylinux&version=devel&sdk&branch=release/1.10.x
And copy the link corresponding to your architecture and Python version, and then paste it into the pip command like so:
```python
sudo pip install http://buildbot.panda3d.org/downloads/0e70997fbf627c9a7a7057df66497b53e8249869/panda3d-1.10.2.dev28-cp36-cp36m-manylinux1_x86_64.whl
```

**Comment by ArsThaumaturgis** [comment]
Ah, wait! In fighting with pip over that command that you just gave, I realised what the problem was: I should be using "pip3", not "pip". Presumably I had previously downloaded the Python 2 version of Panda. >_<

Sorry, I fear that there are still a few points of using Python 3 on which I occasionally stumble. ^^;

Okay, going back to the simpler pip command that you gave earlier, but substituting "pip3" for "pip", I seem to have the proper version of Panda installed now.

And indeed, this version seems to work! It switches to fullscreen-mode successfully, and renders gameplay as expected. It doesn't even call for the "undecorated" setting. ^_^

The only problem is that it insists on entering fullscreen-mode on the primary laptop monitor, regardless of which monitor the non-fullscreen window is initially placed on. That, however, is a relatively minor issue compared to getting full-screen working at all! ^_^

**Comment by rdb** [comment]
Okay, great!  Could you do two more things for me:

1. Confirm whether the list of display modes returned by DisplayInformation is now more complete.
2. Check the console output with `notify-level-x11display debug` set (needs to be set before a window is opened), when switching fullcreen on both monitors.  I would like to know whether this is Panda placing the window on the wrong monitor, or whether it's your window manager being stubborn.

**Comment by ArsThaumaturgis** [comment]
1) 
I seem to get a much lengthier set of display modes now! ^_^ As before, it looks like it includes resolutions for both monitors.

I do note that the value for "bits per pixel" is "-1" in all cases--but that corresponds with what serega-kkz reported in the forum-thread related to this issue, I believe.

2)
Output when fullscreen is set with the window on the primary laptop monitor:
```
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
:display:x11display(debug): Found RandR extension 1.5
:display:x11display(debug): Using XRRScreenResources to obtain display modes
:display:x11display(debug): Raw mice not requested.
:device(warning): /dev/input/event6 is not readable, some features will be unavailable.
:display:x11display(debug): Setting window to fullscreen on CRTC 1366x768+0+290
```
Output when fullscreen is set with the window on the secondary monitor:
```
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
:display:x11display(debug): Found RandR extension 1.5
:display:x11display(debug): Using XRRScreenResources to obtain display modes
:display:x11display(debug): Raw mice not requested.
:device(warning): /dev/input/event6 is not readable, some features will be unavailable.
:display:x11display(debug): Setting window to fullscreen on CRTC 1280x1024+1366+0
```

Look at that, it appears that Panda is attempting to place the window as expected; perhaps it is indeed the window-manager fighting it, somehow.
