### ISSUE TITLE
Trust GXT 24 gamepad has incorrect mapping

### ISSUE THREAD

**Issue by cflavio** [panda3d/panda3d#576]
When I use Panda3D's example _samples/gamepad/gamepad.py_, my gamepad's inputs are wrongly mapped. It is a Trust Gxt 24 (VID_0079, PID_0006).

**Comment by rdb** [comment]
I've been looking into this, and unfortunately, this situation is a mess.  The VID and PID used for the Trust GXT 24 are the same as a whole bunch of cheap knock-off gamepads that are based on the DragonRise chipset, and the mapping between them is not always consistent.

SDL also struggles with this:
https://discourse.libsdl.org/t/duplicated-conflicting-guids-for-the-dragonrise-pc-twin-shock-controllers/24112
https://github.com/gabomdq/SDL_GameControllerDB/issues/202

I think I need to get myself a bunch of these gamepads second-hand and try to sort out what we could do to detect the individual cases.

**Comment by Moguri** [comment]
Is this an issue we intend to fix, or do we throw up our hands and call it an upstream issue?

**Comment by rdb** [comment]
I'm acquiring a bunch of these second-hand pads so I can figure out what we need to do to distinguish these gamepad types.
