### ISSUE TITLE
Tkinter resize/Configure event error

### ISSUE THREAD

**Issue by sheetcode** [panda3d/panda3d#586]
I'm getting error when I'm trying resize tkinter window, where panda exists:

```
Fatal Python error: PyEval_RestoreThread: NULL tstate

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
AL lib: (EE) alc_cleanup: 1 device not closed
```

![image](https://user-images.githubusercontent.com/16592902/54681246-2beaa700-4b0c-11e9-963c-ac5ff33d5e08.png)

Panda 1.10.2 
python 2.7 
Config.prc : want-tk           #t 

Here is standalone example app:
```
from direct.showbase.ShowBase import ShowBase
from panda3d.core import WindowProperties
import Tkinter

def resize_event(event):
    print event.height, event.width


base = ShowBase(windowType='none')


base.startTk()

frame = base.tkRoot
frame.geometry('800x600')
frame.bind("<Configure>", resize_event)


frame.update()
id = frame.winfo_id()
width = frame.winfo_width()
height = frame.winfo_height()

props = WindowProperties()
props.setParentWindow(id)
props.setOrigin(0, 50)
props.setSize(width, height-50)

base.makeDefaultPipe()
base.openDefaultWindow(props=props)

scene = base.loader.loadModel("environment")
scene.reparentTo(base.render)

base.run()
```

**Comment by rdb** [comment]
I looked into this recently and it *seems* to be caused by Panda sharing a message loop with Tkinter, but Tkinter assuming that its WinProc will only be invoked from its own message loop.

I'm not exactly sure how to solve this yet.  Maybe Panda needs to ignore events in the message loop that don't match its own windows, or we need a setting for renderFrame not to release the GIL, or something like that.

**Comment by rfiedorowicz** [comment]
@rdb 
Hope I'm not annoying you, but is there change to resolve this issue?

On python 3.7 and panda 1.10 I have errors like this:

```
Fatal Python error: PyEval_RestoreThread: NULL tstate

Current thread 0x00002470 (most recent call first):
  File "C:\Users\busker\AppData\Local\Programs\Python\Python37-32\lib\site-packages\direct\showbase\ShowBase.py", line 2002 in __igLoop
  File "C:\Users\busker\AppData\Local\Programs\Python\Python37-32\lib\site-packages\direct\task\Task.py", line 485 in step
  File "C:\Users\busker\AppData\Local\Programs\Python\Python37-32\lib\site-packages\direct\showbase\ShowBase.py", line 3065 in __tkTimerCallback
  File "C:\Users\busker\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 749 in callit
  File "C:\Users\busker\AppData\Local\Programs\Python\Python37-32\lib\site-packages\Pmw\Pmw_2_0_1\lib\PmwBase.py", line 1776 in __call__
  File "C:\Users\busker\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 1283 in mainloop
  File "C:\Users\busker\AppData\Local\Programs\Python\Python37-32\lib\site-packages\direct\showbase\ShowBase.py", line 3079 in tkRun
  File "c:/github/solar_panda/main copy.py", line 35 in <module>
```

**Comment by kostasmarkakis** [comment]
Hi, i am having the same problem but not when resizing. it happens in regular clicks as well.
@sheetcode did you had a ny luck solving it by the way?

**Comment by RafalFiedorowicz** [comment]
@kostasmarkakis 
Unfortunately not :(
I was continuing my project using 2 separate windows (one for tkinker and other for Panda).

**Comment by sheetcode** [comment]
@kostasmarkakis 
Unfortunately not :(
I was continuing using 2 separated windows

**Comment by kostasmarkakis** [comment]
@sheetcode 
well as i said in the Panda3D forum discussion [](https://discourse.panda3d.org/t/launch-a-panda3d-app-window-from-a-tkinter-based-python-app/25382/4)
the problem is not with resize but regular clicking as well. i have deactivated resizing for both Tkinter and Panda3D.

**Comment by rdb** [comment]
I decided to just do a hacky fix, since there may be no clean fix possible without risking side-effects in 1.10.5.  Panda will now disable its own message pump entirely when Tk support is enabled, since Tcl's own main loop will happily handle Panda's events (but not vice versa).

A variable `disable-message-loop true` can be set by the user to force this if the standard mechanism of launching Tkinter is not used.
