### ISSUE TITLE
Linux Hello World C++ tutorial not compiling 

### ISSUE THREAD

**Issue by Wolfman13** [panda3d/panda3d#587]
I'm currently running on Linux Ubuntu 18.10. 
I installed the Panda3d 1.10.2 SDK.

I tried to work through the Hello World tutorial but when I try to build the tutorial with the "g++ -c main.cxx -o main.o -std=gnu++11 -O2 -I{/usr/include/python2.7} -I{usr/include/panda3d/}"
I checked the directories that it is pointing to (the python2.7 and panda3d) and they are there, but when I run the command I get an error: "main.cxx:1:10: fatal error: pandaFramework.h: No such file or directory #include "pandaFramework.h" ".

So I checked the directory and there is no pandaFramework.h in the panda3d directory. Am I just doing it wrong? Is the tutorial just outdated?

Thank you

**Comment by rdb** [comment]
This is an issue tracker, not a support forum; Discourse is the appropriate place to ask this.

That said, I think the correct flag is supposed to be `-I/usr/include/panda3d` .

**Comment by Wolfman13** [comment]
Thanks and sorry. I was under the impression that because it possibly had to do with the installer not giving the installing the correct files that here is the right place. My bad
