### ISSUE TITLE
SparseArray: unexpected results when clearing range of bits

### ISSUE THREAD

**Issue by Epihaius** [panda3d/panda3d#588]
Consider the following code, which sets up two "on-ranges" (2-4) and (20-42), as well as an "off-range" (3-12) for a SparseArray:

```
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase


class MyApp(ShowBase):

    def __init__(self):

        ShowBase.__init__(self)

        s = SparseArray()
        # create two on-ranges
        s.set_range(2, 3)
        s.set_range(20, 23)
        print("s:", s)
        # attempt to set bits 3 and 4 off, while leaving the other bits
        # in both ranges on;
        # the following does not do that (note that the end of the range
        # to clear exceeds the first on-range)...
        s.clear_range(3, 10)
        # ...while the following does give the expected result (the end
        # of the off-range overlaps the start of the second on-range)
#        s.clear_range(3, 18)
        #...and so does clearing each bit individually
#        for i in range(3, 13):
#            s.clear_bit(i)
        print("s after clearing range:", s)
        print("bits:", {i: s.get_bit(i) for i in range(2, 5)})


app = MyApp()
app.run()
```

The result I expected is that bits 3 and 4 of the first on-range (2-4) would be set to "off" while bit 2 and the second on-range (20-42) would remain "on".
Yet, the output is this:

```
s: [ 2-4, 20-42, ]
s after clearing range: [ 2-1, 20-42, ]
bits: {2: False, 3: False, 4: False}
```

Not only is the entire first on-range set to off, but the new first range reads "2-1", which looks quite wrong to me; a range going from 2... to 1? Note that the off-range (3-12) exceeds the first on-range (i.e. the highest bit (12) is not part of that on-range); what seems to happen is that because of this, the resulting range is somehow reversed and also inverses the state of its bits.

Using a different off-range (3-20) does work as expected:

```
s: [ 2-4, 20-42, ]
s after clearing range: [ 2, 21-42, ]
bits: {2: True, 3: False, 4: False}
```

It turns off bits 3, 4 and 20, while leaving the other bits on. But in this case, the end of the off-range overlaps the second on-range, which might explain why it works differently.

Another thing that works for me is to set all bits in the range of 3 to 12 to off individually.

So unless I'm missing something, this looks like a bug.

**Comment by Epihaius** [comment]
On a side note, it appears that certain augmented assignments (e.g. `<<=`) are performed in-place, while others (like `|=`) are not:

```
from panda3d.core import SparseArray

s = t = SparseArray()
t.set_bit(2)
print("s after setting bit 2:", s)
t <<= 2  # performed in-place
print("s after <<= 2:", s)
u = SparseArray()
u.set_bit(10)
t |= u  # not performed in-place
print("s after |= u:", s)
print("t after |= u:", t)
```

Output:

```
s after setting bit 2: [ 2, ]
s after <<= 2: [ 4, ]
s after |= u: [ 4, ]
t after |= u: [ 4, 10, ]
```

Is there is particular reason for this (rather confusing) behaviour?

**Comment by rdb** [comment]
Looks like these are bugs.

Would you be willing to write a series of unit tests in `tests/putil/test_sparsearray.py` that expose the buggy behaviour (and also test some other configurations)?  This would allow me to provide fixes more quickly (while being confident that I'm not breaking other things) and also prevent these bugs from popping up again in the future.

**Comment by Epihaius** [comment]
> Looks like these are bugs.

Now that I look at it more closely, could the bitwise shift operations also be doing the wrong thing?
For example:

```
s.set_bit(2)
s <<= 2
```

Shouldn't that result in bit zero being on, instead of bit 4?

> Would you be willing to write a series of pytest unit tests

That would be the first time I do something like this; I guess I'd need to do the following:

1. create a fork of the panda repository;
2. create a "topic branch" in that fork (named something like "sparse_array_tests");
3. push "tests/putil/test_sparsearray.py" as a commit to that branch;
4. open a new pull request in the original panda repository;
5. request a pull request review?

Here's some work in progress:

```
from panda3d import core


def test_sparse_array_clear_range():
    """Tests SparseArray behavior for clear_range."""

    s = core.SparseArray()
    s.set_range(2, 3)
    s.clear_range(3, 3)
    assert s.get_bit(2)
    assert not s.get_bit(3)


def test_sparse_array_augm_assign_shift_left():
    """Tests SparseArray behavior for <<=."""

    s = t = core.SparseArray()
    s.set_bit(2)
    t <<= 2
    assert s.get_bit(4)


def test_sparse_array_augm_assign_shift_right():
    """Tests SparseArray behavior for >>=."""

    s = t = core.SparseArray()
    s.set_bit(4)
    t >>= 2
    assert s.get_bit(2)


def test_sparse_array_augm_assign_bitwise_or():
    """Tests SparseArray behavior for |=."""

    s = t = core.SparseArray()
    u = core.SparseArray()
    u.set_bit(10)
    t |= u
    assert s.get_bit(10)


def test_sparse_array_augm_assign_bitwise_and():
    """Tests SparseArray behavior for &=."""

    s = t = core.SparseArray()
    u = core.SparseArray()
    t.set_bit(10)
    u.set_bit(10)
    u.set_bit(11)
    t &= u
    assert s.get_bit(10)
    assert not s.get_bit(11)
```

Should I test all available SparseArray methods, or some in particular?

**Comment by rdb** [comment]
> That would be the first time I do something like this; I guess I'd need to do the following:

Yes, sounds good.  No need to explicitly request review; we'll take care of that when you open the PR.

> Should I test all available SparseArray methods, or some in particular?

Whatever you have time for.  We at least need to cover the methods that are buggy so that we know we've fixed the bugs if the tests pass.
