### ISSUE TITLE
Need way to request multisamples in FilterManager

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#599]
After having opened a window without multisamples, there is no way in FilterManager to create a buffer that does have multisamples, as it's not possible to change `FrameBufferProperties.get_default()` and no way to override it.

This is unfortunate, because in most games with postprocessing effects you don't need multisamples on the main window, which would be a waste, and recreating the FilterManager buffers is a great way of toggling multisamples at runtime (eg. in an options menu).

**Comment by el-dee** [comment]
It would be great to be able to request any FB properties when using FilterManager in an easy way, one of which would be MSAA.

 In my application I had to make a copy of FilterManager to be able to activate floating point buffer, sRGB, MSAA, depth and so on... and the method signature is now ridiculously long! So there should be new methods to create the buffer or the intermediate quad which accept a FrameBufferProperties (or similar) as parameter. And the legacy renderSceneInto() and renderQuadInto() should just be wrappers around the new methods.

**Comment by rdb** [comment]
@el-dee Hmm, rather than add every single possible property as argument, maybe we could simply add a FrameBufferProperties argument, and the properties specified therein would override the default FrameBufferProperties?

**Comment by el-dee** [comment]
That's what I was suggesting, but way better worded :)

**Comment by el-dee** [comment]
Thanks, this is most welcomed (and I've learned that addProperties() exists). Could fbprobs parameter also be added to renderQuadInto() ? (Or is there a reason it should not be done ?)

**Comment by rdb** [comment]
No particular reason, other than that I did not see a use case.  Do you have a use case for this?

**Comment by el-dee** [comment]
If I remember correctly, if I need the intermediate buffer to be a floating point buffer it requires modifying the properties, same if I need the depth buffer to be floating point.

Btw, the sRGB property is hardcoded in create buffer, line 300, I believe this should be removed to allow configuration of the sRGB via fbprops.

**Comment by rdb** [comment]
Sounds sensible enough, I suppose.  I see no good reason not to have it in `renderQuadInto` as well for consistency.

There's no sRGB property hardcoded; it just uses `setRgbColor` in that line, not `setSrgbColor`.  Even if it did, setting it to False the custom FramebufferProperties would override it properly.

**Comment by el-dee** [comment]
You're right, I read the code too fast and added an S in my mind :)
