### ISSUE TITLE
Emit warning about dropping Python 2.7 support

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#602]
We need to have a plan for getting people off Python 2.7, which is EOL by the end of the year, and is becoming increasingly difficult to support.  We are pouring significant amounts of labour into continuing to support Python 2 when we have more important things (such as PBR) we should be getting to.

I propose that we help make people aware of this by emitting a loud warning about Python 2 being dropped soon when importing any panda3d module in Python 2, possibly with a link to documentation to help them through the upgrade process.

**Comment by CFSworks** [comment]
For posterity: While discussing this on Discord, I took the position in favor of actually making the warning a fatal error which must be silenced by setting a PRC flag.

**Comment by rdb** [comment]
I did the following:
* Added a prominent warning in 1.10.3 when running makepanda with Python 2.7
* Added a prominent warning in 1.10.3 when running deploy-ng with Python 2.7
* Added a warning on master when importing `panda3d` with Python 2.7
* I made a post reminding people to upgrade, including a poll on :
https://discourse.panda3d.org/t/have-you-upgraded-to-python-3-yet/24727

I'm not yet quite motivated to explicitly sabotage users who are using Python 2.7 at this point, or do anything that might discourage people from upgrading to 1.10.3, but I'm not entirely closed to the idea.
