### ISSUE TITLE
Shadows appear to cause a Memory Leak

### ISSUE THREAD

**Issue by hypoid** [panda3d/panda3d#605]
Python version: 3.6.7
Panda3d version: 1.10.1

Problem: Memory leaks at a rate of about 3mb per 1k frames/steps with the following code:
https://github.com/hypoid/l_sim/tree/master/simple_test

I'm sorry it is so long (I did try to simplify it as much as possible).
Any help is appreciated, even if it doesn't use the methods that I've used.

**Comment by rdb** [comment]
Thanks.  When filing a bug it's usually a good idea to check whether the latest bugfix release has fixed this issue.  As it happens, 1.10.2 is a strongly recommended upgrade that includes a fix for a memory leak in the release notes.  Could you upgrade and let me know whether the problem still occurs in 1.10.2?

**Comment by hypoid** [comment]
Will do. Thanks.

**Comment by hypoid** [comment]
I can confirm that with 1.10.2 it is still leaking and at the same rate.

Oddly, the memory leak appears to stop if the spotlight stops moving. Does this help?

**Comment by hypoid** [comment]
I was wrong, shadows don't appear to cause this. I've been able to simplify it more and reduce the memory leak from 3mb to 0.8mb per 1k steps.
https://github.com/hypoid/l_sim/blob/master/simple_test/simple_version_offscreen.py

For anyone interested, this started as a post here:
https://discourse.panda3d.org/t/render-on-demand-to-numpy-array-ai-reinforcement-learning/24583/11

**Comment by hypoid** [comment]
It appears that if I use the task manager the leak goes away:
https://github.com/hypoid/l_sim/blob/master/simple_test/simple_version_tskMgr.py

**Comment by hypoid** [comment]
I think I've found it. Garbage collection has to be be called using:
        TransformState.garbageCollect()
        RenderState.garbageCollect()
Example:
https://github.com/hypoid/l_sim/blob/master/simple_test/simple_version_garbage_collect.py
Closing this issue. Thanks all.

**Comment by rdb** [comment]
Alternative to garbage collection is to disable state cache and transform cache by setting `state-cache false` and `transform-cache false` in Config.prc.  Whether this is more efficient for your application or not depends on your specific use case.

**Comment by hypoid** [comment]
Nice, thanks.
