### ISSUE TITLE
Segmentation fault when using "fullscreen 1" in prc file

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#618]
When I want to start my application in fullscreen mode on Linux using :

    loadPrcFileData("", "fullscreen 1")

I get the following crash :

```
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Assertion failed: has_size() at line 140 of built/include/windowProperties.I
Assertion failed: has_origin() at line 73 of built/include/windowProperties.I
:display:x11display(error): BadWindow (invalid Window parameter)
Segmentation fault
```

Edit: This happens using vanilla Panda3D 1.10.2

Edit 2: Forgot to add that switching to fullscreen at runtime using WindowProperties works fine

**Comment by rdb** [comment]
Thanks, I have a fix for this.  I had not tested the initial-fullscreen case when I improved the runtime fullscreen switching code.
