### ISSUE TITLE
KeyboardButton::ascii_key won't accept Python3 string

### ISSUE THREAD

**Issue by CFSworks** [panda3d/panda3d#626]
Issue encountered by @momojohobo over on the community Discord:
```
>>> from panda3d.core import KeyboardButton
>>> forward = KeyboardButton.asciiKey("w")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ascii_key() argument must be a byte string of length 1, not str
```

The declaration of this method is `static ButtonHandle ascii_key(char ascii_equivalent);`, which appears to be correct (it wants a single ASCII char for its parameter), but Interrogate seems to be misunderstanding `char` as "1-byte bytestring," not "1-character ASCII string" as is intended in this case.

Should the semantics of Interrogate be changed? I think `unsigned char` implies "byte" while `char` just means "ASCII character" but I also haven't investigated what else would be affected by such a change.

**Comment by rdb** [comment]
I guess we could say that `char` always takes a 1-character string but throw an exception if non-ASCII characters are passed in?  `char32_t` would more unambiguously be a character, but that makes less sense in this situation.

As for `unsigned char`, I think that should remain an integer for two reasons:
* C++ does not allow us to distinguish between `uint8_t` and `unsigned char` (unless we of course strayed from C++ in interrogate).
* Python also thinks a "character in a byte string" is an integer, as exemplified by `b"ABC"[0] == 65` and `bytes([65]) == b"A"`.

**Comment by CFSworks** [comment]
I'm not suggesting any change to `unsigned char`, because that one *does* imply byte (which is a numerical unit). An implicit conversion from length-1 bytestrings may or may not be appropriate, but as a return value it still makes sense to be an integer.

However, `char` in the C/C++ sense is trying to communicate "ASCII character" (as is the case with `ascii_key`). It's fine if an integral ASCII value is passed in, or a one-byte bytestring (since ASCII makes no distinction between 'byte' and 'character'), but we should really be accepting one-character ASCII strings too.

The big question is, which one is the canonical representation of `char`? Do we have any `PUBLISHED:` functions that return `char`? What's the semantic meaning of these?

**Comment by rdb** [comment]
Apparently we wrap `char` return values as a 1-character string:
https://github.com/panda3d/panda3d/blob/8e4add0326292b398ef99f5c0f9033efdba21ff4/dtool/src/interrogatedb/py_panda.I#L305-L311

Which I guess pretty much settles it.
