### ISSUE TITLE
OdeJoint does not accept None

### ISSUE THREAD

**Issue by xMakerx** [panda3d/panda3d#633]
It appears that with the latest version of Panda (version 1.10.2) and Python 3.7.5, OdeJoint no longer accepts None as an argument.

https://www.panda3d.org/manual/?title=Attaching_Bodies_using_Joints

Use the code above as a test case to recreate the issue. Thanks!

**Comment by rdb** [comment]
Thanks, will fix.  As a workaround:
```python
# These two lines are equivalent:
joint.attach(body1, None)
joint.attach_body(body1, 0)

# So are these two:
joint.attach(None, body2)
joint.attach_body(body2, 1)
```
