### ISSUE TITLE
opengl: Better detection of an invalid OpenGL context

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#643]
OpenGL GraphicStateGuardian does not always report a failure to the application, in that case the GSG is deactivated and no longer running, however the application does not receive an error code or an exception when opening a window or a buffer.

This has been detected on a AMD graphic card which actually does not support some features the list of supported extensions claimed to support, see https://discourse.panda3d.org/t/better-detection-of-not-supported-gl-version/24677

**Comment by rdb** [comment]
I'm actually not quite sure we can do much about the general problem of detecting a malfunctioning OpenGL context; what I'm going to be fixing here is the more specific issue of misdetecting a core/compat OpenGL profile.
