### ISSUE TITLE
OpenGL/MacOS: Invalid shader causes GSG deactivation

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#645]
On MacOS, an invalid shader program (due to not supported feature or syntax error) causes the GSG to be deactivated.

(It is quite similar to https://github.com/panda3d/panda3d/issues/644, so feel free to close this if this is the same root cause)

<pre>
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader created-shader:
ERROR: created-shader:5: Use of undeclared identifier 'dummy'
:display:gsg:glgsg(warning): Shader created-shader produced the following warnings:
WARNING: Could not find vertex shader attribute 'p3d_Color' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'vertex' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'p3d_Normal' to match BindAttributeLocation request.
WARNING: Do not have an attached fragment shader to match FragDataBinding request for 'p3d_FragData'.

:display:gsg:glgsg(warning): Shader created-shader produced the following warnings:
Validation Failed: Program does not contain fragment shader. Results will be undefined.

:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display:gsg:glgsg(error): at 4946 of panda/src/glstuff/glGraphicsStateGuardian_src.cxx : invalid operation
:display(error): Deactivating CocoaGraphicsStateGuardian.
</pre>

Sample code to reproduce this :

```python
#!/usr/bin/env python

from direct.showbase.ShowBase import ShowBase
from panda3d.core import Shader
from panda3d.core import load_prc_file_data

load_prc_file_data("", "gl-version 3 2\n"
                       "gl-check-errors #t\n"
                  )

def shader():
    return Shader.make(Shader.SL_GLSL,
                       vertex="""
#version 410
in vec4 p3d_Vertex;
uniform mat4 p3d_ProjectionMatrix;
uniform mat4 p3d_ModelViewMatrix;

void main() {
    gl_Position = p3d_ProjectionMatrix * (p3d_ModelViewMatrix * p3d_Vertex);
}
""",
                       fragment="""
#version 410
out vec4 frag_color;
void main() {
    frag_color = vec4(1.0, 1.0, 1.0, 1.0); dummy;
}
""")

base = ShowBase()
np = loader.loadModel('box')
np.reparent_to(render)
np.set_shader(shader())
np2 = loader.loadModel('box')
np2.reparent_to(render)
np2.set_pos(1, 1, 0)
base.cam.set_pos(0, 0, 10)
base.cam.look_at(np)
base.run()
```

**Comment by rdb** [comment]
Apparently macOS considers the link to succeed even if an attached shader failed to compile.  This has an easy fix.
