### ISSUE TITLE
Community Website Down?

### ISSUE THREAD

**Issue by yhu9** [panda3d/panda3d#661]
Hi I'm looking to use panda3d as it supports python and I would like to use it with deep learning libraries such as tensorflow and pytorch. However, I'm finding a lack of help on asset creation and it seems the community website is down? Need someone to just point me in a direction where I can find more help.

**Comment by yhu9** [comment]
https://discourse.panda3d.org

**Comment by Moguri** [comment]
Yes, it went down yesterday and we are working on trying to figure out why. I would recommend checking out the [Discord server](https://discord.gg/UyepRMm) or the `#panda3d` IRC channel on FreeNode.

**Comment by rdb** [comment]
It's back up, so I'm closing this.  Thanks for letting us know.
