### ISSUE TITLE
Particle Panel: Sliders can crash the program

### ISSUE THREAD

**Issue by xordspar0** [panda3d/panda3d#672]
Some of the fields in the particle panel can easily crash the program if you click on the "slider" button and drag to the right.

* The pool size causes memory usage to rise sharply until the program gets OOM killed.
* The fields that are integer-type (e.g. litter spread, litter size) can overflow the size of integers, causing a stack trace.

It's nice that the Particle Panel is such a simple and raw interface to the particle system, but it's also unfortunate that a slight flick of the mouse can crash the program.

**Comment by rdb** [comment]
Thanks.  I've set proper maximum values for the sliders.  I've limited the pool size to 2 million for now.
