### ISSUE TITLE
Flickering GUI elements in DirectScrolledFrame

### ISSUE THREAD

**Issue by fireclawthefox** [panda3d/panda3d#681]
DirectGui elements are sometimes not correctly or not at all rendered. This occurs especially often if there are many scrolled frames used.
Resizing the window or somehow else redrawing the UI will make the GUI elements flicker and sometimes reappear and render correctly.

**Comment by Moguri** [comment]
Do you have a sample demonstrating this problem? I imagine this could be difficult to reproduce without a demo/sample.

**Comment by fireclawthefox** [comment]
A simple sample where this will happen at least after the window is resized would be this:

```
from direct.showbase.ShowBase import ShowBase
from direct.gui.DirectScrolledFrame import DirectScrolledFrame
from direct.gui.DirectLabel import DirectLabel
from random import random

app = ShowBase()

pos = [-0.85, -0.25, 0.25, 0.85]

for y in range(4):
    for x in range(4):
        r = random();g = random();b = random()
        frm=DirectScrolledFrame(
            frameColor=(r,g,b,1),
            frameSize=(-0.2,0.2,-0.2,0.2),
            canvasSize=(-1,1,-1,1),
            pos=(pos[x], 0, pos[y]))
        DirectLabel(
            pos=(-1,0,0.8),
            text='test',
            text_align=0,
            scale=0.1,
            parent=frm.getCanvas())

app.run()
```

**Comment by rdb** [comment]
I've observed this issue as well.  Thank you for providing sample code.

**Comment by ArsThaumaturgis** [comment]
I've seen similar with, and suspect that it may be related to, the use of ScissorEffects in DirectGUI. (From what I've seen, it appears that DirectScrolledFrame uses a ScissorEffect to clip its contents.) See the following forum-post, with example-code:
https://discourse.panda3d.org/t/scissoreffect-flickering/24836/4

**Comment by rdb** [comment]
@ArsThaumaturgis Thanks for pointing me in the right direction; it did indeed have something to do with scissoring.  Turns out to be an easy bugfix, though it was not easy to find.  I will check in a fix momentarily.
