### ISSUE TITLE
encryptString not working in Py3

### ISSUE THREAD

**Issue by rileykwok** [panda3d/panda3d#684]
I have encounter an error with encryptString when I upgrade my project from Py2 to Py3. 

`from panda3d.core import *`
`encryptString('123','abc')`

error:

`Traceback (most recent call last):
File “”, line 1, in 
UnicodeDecodeError: ‘utf-8’ codec can’t decode byte 0xdc in position 8: invalid continuation byte`

**Comment by rdb** [comment]
It's because this function returns a `str` when it should be returning a `bytes` object.  A fix will be made.

In the meantime, this workaround function can be used:
```python
from panda3d.core import *

def encryptString(source, password, algorithm="", key_length=-1, iteration_count=-1):
    src = StringStream(source.encode('utf-8'))
    dst = StringStream()
    if not encryptStream(src, dst, password, algorithm, key_length, iteration_count):
        return b''
    return dst.data

print(encryptString('123', 'abc'))
```
