### ISSUE TITLE
DisplayColorManagement.dll: Parameter error

### ISSUE THREAD

**Issue by RobinCodeX** [panda3d/panda3d#685]
Platform: Windows 10 (1903)
Panda3D version: 1.10.3

Hi,
I’m trying to c++ coding, I have successfully run my program, but I have encountered an exit exception when I close window to exit, I found a loaded error from `Windows.Internal.Graphics.Display.DisplayColorManagement.dll`, the message displayed means the parameter is wrong.

```
'Panda.exe' (Win32): Loaded 'C:\Windows\System32\Windows.Internal.Graphics.Display.DisplayColorManagement.dll'. Symbols loaded.
onecoreuap\windows\core\color\moderncolor\winrt\displaycolormanagement\lib\displaycolormanagement.cpp(31)\Windows.Internal.Graphics.Display.DisplayColorManagement.dll!00007FFF55273C5D: (caller: 00007FFF687F4F26) ReturnHr(1) tid(35b8) 80070057 参数错误。
Exception thrown at 0x00007FFF72F3A839 (KernelBase.dll) in Panda.exe: WinRT originate error - 0x80070057 : '参数错误。'.
Exception thrown at 0x00007FFF72F3A839 in Panda.exe: Microsoft C++ exception: winrt::hresult_invalid_argument at memory location 0x000000A6D0CFDDD0.
'Panda.exe' (Win32): Unloaded 'C:\Windows\System32\Windows.Internal.Graphics.Display.DisplayColorManagement.dll'
```
My c++ code and build from Release x64.:
```c
int main(int argc, char *argv[]) {
    PandaFramework framework;
    framework.open_framework(argc, argv);
    framework.set_window_title("Hello World!");

    WindowFramework *window = framework.open_window();
    framework.main_loop();

    framework.close_framework();
    return (0);
}
```
![image](https://user-images.githubusercontent.com/8408783/60994857-ecc6b700-a383-11e9-9f85-2b5eff99d991.png)
![image](https://user-images.githubusercontent.com/8408783/60994861-f05a3e00-a383-11e9-8afa-d6a285a17ccb.png)

Discourse issue: https://discourse.panda3d.org/t/displaycolormanagement-dll-parameter-error/24938

**Comment by rdb** [comment]
Are you able to test whether f989bce584ac4169f76b6e26384a772f54676ccc resolves the problem for you?

**Comment by RobinCodeX** [comment]
Yes, I have clone and compile from release/1.10.x, no exit exception has been thrown in c++.

**Comment by rdb** [comment]
Thanks.  I'm going to close this despite that the actual issue is only worked around (the crash can now only occur if someone explicitly changes the gamma), though if someone runs into that and needs to change gamma, we can reopen the issue.
