### ISSUE TITLE
pip not working on Windows

### ISSUE THREAD

**Issue by tuknuzardi** [panda3d/panda3d#690]
Windows 10 64 bit, Panda3D 1.10.3.

You haven't set the path to be absolute before compilation, rdb. It expects a subfolder with your username on it.

![Untitled](https://user-images.githubusercontent.com/53223381/61714239-650d7f00-ad6b-11e9-96fd-64fe97c5d128.png)

This issue has been around for months, surprised it hasn't been reported and fixed already.

**Comment by rdb** [comment]
Hmm, odd, I'll look into this when I build 1.10.4.  Does `ppython -m pip` work, though?

**Comment by rdb** [comment]
Apparently the .exe wrappers that setuptools generates are not relocatable.  I'll just remove pip and have the installer run ensurepip instead.

**Comment by rdb** [comment]
As a workaround, you can "repair" pip by forcing it to be reinstalled using `ppython -m pip install -U --force-reinstall pip` .
