### ISSUE TITLE
F_sluminance* textures are not supported in core profile OpenGL

### ISSUE THREAD

**Issue by lachbr** [panda3d/panda3d#693]
Possible solution would be to duplicate the channels out to F_srgb.

**Comment by rdb** [comment]
Actually, which video card are you using?  I was making a test case for this and sluminance textures seem to work fine in a core-only profile.

**Comment by lachbr** [comment]
I’m using a Nvidia GTX 1060 on Windows 10.

**Comment by rdb** [comment]
Yeah, interesting, NVIDIA drivers have an issue with it but Intel don't.

Could someone with an AMD card run this and let me know whether it errors, or displays a grey screen without errors?
```
from panda3d.core import *
load_prc_file_data("", """
gl-version 3 2
gl-debug true
""")

from direct.directbase import DirectStart

print("Video card: ", base.win.gsg.driver_renderer)

cm = CardMaker("")
cm.set_frame_fullscreen_quad()
card = render2d.attach_new_node(cm.generate())

img = PNMImage(32, 32, 1)
img.set_color_space(CS_sRGB)
img.fill(0.5)

tex = loader.load_texture("grayscale.png")
tex.load(img)
tex.set_format(Texture.F_sluminance)
card.set_texture(tex)

base.run()
```

**Comment by rdb** [comment]
Annoyingly, the NVIDIA drivers return `true` when I check for `glGetInternalformativ(GL_TEXTURE_2D, GL_SLUMINANCE8, GL_INTERNALFORMAT_SUPPORTED, 1, &param)`.  I might report this as a driver bug.

**Comment by el-dee** [comment]
It doesn't work either on Mac with AMD card :

<pre>
Using deprecated DirectStart interface.
Known pipe types:
  CocoaGraphicsPipe
(all display modules loaded.)
:display:gsg:glgsg(warning): gl-debug enabled, but NOT supported.
Panda version: 1.10.3 (adaf9ee4aa908cef4d2e99895132b716f3f21b2a)
Video card:  AMD Radeon Pro 555X OpenGL Engine
:display:gsg:glgsg(warning): Shader created-shader produced the following warnings:
WARNING: Could not find vertex shader attribute 'vertex' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'p3d_Normal' to match BindAttributeLocation request.
WARNING: Could not find fragment shader output 'p3d_FragData' to match FragDataBinding request.

:display:gsg:glgsg(error): GL texture creation failed for smiley : invalid enumerant
:display:gsg:glgsg(error): Could not load smiley
</pre>

(using smiley.rgb as there is no grayscale.png shipped with Panda 1.10.3)

**Comment by rdb** [comment]
@lachbr this is implemented, could you test it and let me know whether it is working in your use case?  Thanks!

**Comment by lachbr** [comment]
Great. I'm going to build Panda right now and let you know as soon as I can.

**Comment by lachbr** [comment]
@rdb Works perfectly, thanks a lot!
