### ISSUE TITLE
JupyterHub integration

### ISSUE THREAD

**Issue by DDeol** [panda3d/panda3d#694]
Hi , we have a Jupyter Hub environment deployed on RHEL. Is there way I can integrate the panda3d there. The ask is installed the library using pip install and then write the code inside Juypter Notebook. We tried this but we are getting "No window" found error because this is no X window setup no RHEL server.

Is there any option available to do this.

Thanks

**Comment by rdb** [comment]
OpenGL requires an X server to be run.  If you want to run OpenGL on a headless server that has a video card, it is possible to run a headless X server (I've managed to do so before with an NVIDIA card at least).

Alternatively, you can switch Panda to use its built-in software renderer by setting `load-display p3tinydisplay` in Config.prc, however, the rendering quality and performance will not be great.

**Comment by DDeol** [comment]
Hi , thanks for the quick reply. let me try this option. 

 On different note I was going through this link http://rdb.name/panda3d-webgl/editor.html      
  Thanks for putting this together.
         
Is it possible to run this on prem because of some senstivities of data we want to try this editor on prem also. Is it possible to get the code and run this web server on prem?

**Comment by Moguri** [comment]
I don't know if @rdb has a more nicely packaged version of that editor, but I'm pretty sure it's all HTML, CSS, and JavaScript so you can just download the files (editor.html, editor2.js, editor2.js.mem, ace) and try to run them locally. You'll probably need a local web server, in which case [Python's http.server](https://docs.python.org/3/library/http.server.html) should work well enough.

**Comment by rdb** [comment]
I'm going to close this as this is not actionable (and @Moguri has helpfully already answered the remaining question).  For further discussion, please use the [discussion boards](https://discourse.panda3d.org/).
