### ISSUE TITLE
Filename-related Texture properties return None instead of Filename('')

### ISSUE THREAD

**Issue by Epihaius** [panda3d/panda3d#705]
The filename-related `Texture` properties `filename`, `alpha_filename`, `fullpath` and `alpha_fullpath` return `None` when the corresponding file path is the empty string, while their `get_*()` method counterparts return `Filename('')` in this case.
The latter seems more useful, as Filename methods like `to_os_specific()` can be called on this result without causing problems, while it becomes necessary to check for `None` when using the properties.

```
from panda3d.core import Texture, Filename

tex = Texture("")
print("tex.get_filename():", [tex.get_filename()])
print("tex.filename:", [tex.filename])
print("tex.get_alpha_filename():", [tex.get_alpha_filename()])
print("tex.alpha_filename:", [tex.alpha_filename])
print("tex.get_fullpath():", [tex.get_fullpath()])
print("tex.fullpath:", [tex.fullpath])
print("tex.get_alpha_fullpath():", [tex.get_alpha_fullpath()])
print("tex.alpha_fullpath:", [tex.alpha_fullpath])
```
The code above yields the following output:

```
tex.get_filename(): [Filename('')]
tex.filename: [None]
tex.get_alpha_filename(): [Filename('')]
tex.alpha_filename: [None]
tex.get_fullpath(): [Filename('')]
tex.fullpath: [None]
tex.get_alpha_fullpath(): [Filename('')]
tex.alpha_fullpath: [None]
```

If only for the sake of consistency, I hope this can be fixed such that the properties will also return `Filename('')` in the case of an empty file path.

Thanks in advance!

**Comment by rdb** [comment]
This is intentional, since checking that it is not `None` is intended to be analogous to calling `has_xyz()` prior to calling `get_xyz()`.  To that end, the function of the `xyz` property encompasses both of those function calls.

In what situation is this causing a problem?  Don't you have to check whether it is empty anyway before doing anything with it?

**Comment by Epihaius** [comment]
Well, as I mentioned before, I call `to_os_specific()` on the result, which I can do on an empty `Filename` object, but obviously not on `None`. (The aim is to be able to store OS-specific filenames, such that the user can display them in my program when they want to know what textures are applied to a loaded model, if any.)

But perhaps this is not a typical use case and I guess checking for None is not such a big deal anyway.
The main reason for this issue report is that I was honestly surprised to find a difference in property and getter results, but since this is intended behaviour, I'll close this then.
