### ISSUE TITLE
ffmpegVideoCursor.cxx falls back to missing `img_convert`

### ISSUE THREAD

**Issue by CFSworks** [panda3d/panda3d#711]
When building without HAVE_SWSCALE, the ffmpegVideoCursor.cxx file throws this error:
`'img_convert': identifier not found`

This is another drive-by bug report for me so I haven't yet done heavy investigating, but a quick web search suggests that `img_convert` is deprecated/removed.

**Comment by rdb** [comment]
Well, the simple answer is "don't build without HAVE_SWSCALE".

The backstory of this is that `img_convert` was removed from FFmpeg and replaced with another library, libswscale.  So the assumption by makepanda was that if you have FFmpeg but not libswscale, you must be using an old version of FFmpeg that still had img_convert.

At this point I don't think we still even support FFmpeg versions that ship without swscale, so we should just remove the ability to toggle this flag independently.

**Comment by rdb** [comment]
Come to think of it, I suppose one valid use case for compiling without libswscale is if all your videos already have a directly-supported pixel format (eg. BGR24 instead of, say, YUV), and you want to avoid the extra bloat.

I'll check in a proper fallback in this case.
