### ISSUE TITLE
cling based C++ as scripting language / hot code reload

### ISSUE THREAD

**Issue by blockspacer** [panda3d/panda3d#713]
cling based C++ as scripting language / hot code reload
Why? Able to run C++ script in runtime or compile it for max speed ( as in example https://github.com/derofim/cling-cmake )

> **HOT code reload**
> possible approaches:
> 
> store app state
> fix cling undo for files
> https://root-forum.cern.ch/t/loading-unloading-class-as-interpreted-macro-in-cling-multiple-times/32976/2
> 
> execute cling code to change callbacks & variables
> nested cling::Interpreter with multiple cling::MetaProcessor
> IDK how to do it, but you can create child cling::Interpreter

**Comment by rdb** [comment]
Hi, thanks so much for sharing this project!  Though, I am not sure I see an actionable item here for developers to fix; did you mean to introduce this in the discussion boards?

https://discourse.panda3d.org/

**Comment by blockspacer** [comment]
> Hi, thanks so much for sharing this project! Though, I am not sure I see an actionable item here for developers to fix; did you mean to introduce this in the discussion boards?
> 
> https://discourse.panda3d.org/

Yes, it is feature request

**Comment by blockspacer** [comment]
Panda3D supports WebGL Port
cling may be also usefull for:

> web builds (emscripten) without scripting size engine overhead, only C++ to WASM
> embedded builds without scripting engine size overhead, only C++
> cling requires no/very minimal binding to C++
> tooling may be optional (dev/devCling/release/e.t.c.)
> You can use cling for fastest debug (dev) builds, than for release builds you will get compiled C++
> HOT code reload - edit code without closing app

**Comment by rdb** [comment]
Are you experiencing bugs using Panda3D with cling?  From what I can tell, it should be possible out of the box, without specific support needed.

**Comment by blockspacer** [comment]
No bugs bugs related to Panda3D. Thanks for answers.
Is it possible to migrate github feature request to discourse.panda3d.org ?

**Comment by Moguri** [comment]
There is no automated way to move GitHub issues into a Discourse post. Discourse supports Markdown, so you could copy and paste some stuff from this issue to create a post.

Since I see nothing actionable (a specific feature or bug), I am going to close this report. It can be reopened if there is something specific that Panda is missing.
