### ISSUE TITLE
Feature suggestion: Have The Build System Use "loader.loadModel"

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#714]
[Link to originating forum thread.](https://discourse.panda3d.org/t/the-build-system-and-large-models/25084)

In order to prevent the build-system from re-converting egg-files on subsequent builds, perhaps have it use "loader.loadModel" followed by "writeBamFile"--thus making use of the model-cache--instead of invoking "egg2bam".

(Credit to rdb for suggesting this specific solution!)

**Comment by rdb** [comment]
I agree; and this also is less prone to failure than invoking an external process, since I've seen one instance where this caused problems due to an egg2bam being found of a conflicting version of Panda3D.

This should not be hard to implement, is there anyone willing to take this on?

**Comment by Moguri** [comment]
I also agree that we should be doing this. It's on my radar to implement this, so I plan to get to it eventually, however others should feel free to implement this and not wait for me. I will assign this task to myself if/when I begin working on it.

In addition to using `loadModel()` for EGG files, we should register this handler for more file types. I don't know if we want to register it for "all supported types" (maybe we could query the loader registry for this?) or just a handful of well supported types. At the very least, we should add `egg.pz`.

**Comment by rdb** [comment]
`egg.pz` (and `egg.gz`) is supported as of 2e03eb405b00a61543a36e2b82a0200be9ae742c, for the record.

I think it makes sense to query the loader registry for all supported types.  This would also allow people to use .gltf models seamlessly if they have `panda3d-gltf` installed, for example.

**Comment by rdb** [comment]
Will be in 1.10.13.  You will need to add the key `'bam_model_extensions': ['.egg']` to your setup.py file to activate this in 1.10, whereas in 1.11, this will be switched by default.
