### ISSUE TITLE
igate: forcetype and dup signatures

### ISSUE THREAD

**Issue by pmp-p** [panda3d/panda3d#722]
When using forcetype to re-export C++ headers toward C bindings 
with ( -S includes removed) 
`interrogate -promiscuous -string -fnames -assert -c -v -S /usr/include --oc ./build/interrogate_temp.cpp -srcdir ./lib -nomangle -od ./build/interrogate.in -module  -library  -DINTERROGATE -DCPPPARSER -D__STDC__=1 -D__cplusplus=201103L -D__attribute__\(x\)= -D__x86_64__ -D_LP64 lib.h lib.cxx`

export often breaks on those kind of error :

forcetype NodePath
> Internal error!  Function signature NodePath::get_node(int, Thread *) const repeated!

forcetype PandaSystem
> Internal error!  Function signature PandaSystem::get_system(std::size_t) const repeated!

forcetype ConfigPage
> Internal error!  Function signature ConfigPage::modify_declaration(std::size_t) repeated!

forcetype Camera
> Internal error!  Function signature Camera::get_display_region(std::size_t) const repeated!

is it at least possible to let exports continue, skipping the dup, since anyway using C ffi bindings would probably operate on a reduced api set  and a simplified framework ?

use case: micropython ffi bindings with https://github.com/pmp-p/panda3d-interrogator

**Comment by rdb** [comment]
Ah, I think it has to do with the MAKE_SEQ_PROPERTY system, since all of those are properties used in a MAKE_SEQ_PROPERTY.  As a workaround, you can redefine MAKE_SEQ_PROPERTY to nothing.

**Comment by rdb** [comment]
This was actually caused by some vestigial code in interrogate that can be removed.  I can get a fix into 1.10.5.

**Comment by pmp-p** [comment]
fix is good
