### ISSUE TITLE
Triangulator.triangulate out of memory error

### ISSUE THREAD

**Issue by dlcruz** [panda3d/panda3d#737]
I ran into the following out of memory error calling `panda.code`'s `Triangulator.triangulate()`.
```
Out of memory allocating 17179869184 bytes
Aborted (core dumped)
```
I am able to reproduce this error with the snippet of code below: 
```
from panda3d.core import LVector2
from panda3d.core import Triangulator

class Polygon:
    def __init__(self, points=None):
        self._triangulator = Triangulator()

        if points is not None:
            for point in points:
                self.add_poly_vertex(point)

    def add_poly_vertex(self, point):
        vertex_id = self._triangulator.addVertex(point.x, point.y)
        self._triangulator.addPolygonVertex(vertex_id)

    def create(self):
        self._triangulator.triangulate()

points = [
    LVector2(-0.07, 1.0),
    LVector2(-0.39, 0.88),
    LVector2(1.1, 0.97), 
    LVector2(0.9, 0.99), 
    LVector2(0.8, 0.9)]

polygon = Polygon(points=points)
polygon.create()
```

It looks like in `triangulator::triangulate_single_polygon` from panda/src/mathutil/triangulator.cxx there is a while loop which doesn't seem to terminate, and keeps pushing back to a vector, eventually hitting OOM.

**Comment by rdb** [comment]
Hi, thanks for the bug report!

Of course Panda should not be going in an infinite allocation loop here, but I do want to point out that the polygon in question is a very strangely self-overlapping polygon:
![image](https://user-images.githubusercontent.com/194842/65146985-74344480-da1d-11e9-84da-83089dd9d80b.png)

That said, maybe it's about time we replaced the triangulation algorithm with something simpler, such as ear clipping.

**Comment by rdb** [comment]
I've checked in a workaround that will prevent Panda3D from entering an infinite loop and running out of memory.  However, I believe the result will not be correct for an overlapping polygon like this.

I still think the triangulation algorithm must be replaced by something more robust, but I think that is a separate issue.

Thanks again for the report, and especially for the simple test case!
