### ISSUE TITLE
Remove obj2egg

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#738]
The ptloader plug-in will implicitly load .obj files via obj2egg.  However, this is a very rudimentary converter that does not even support textures, making the Assimp-based loader clearly superior.

To reduce user confusion, I move that we either remove obj2egg entirely, or at the very least, make sure that it is not being automatically registered as an .obj loader by ptloader.

**Comment by Moguri** [comment]
I am all for not registering the ptloader's obj importer. Keeping obj2egg around may be useful, but I could also see it being confusing.

Obj support is really useful, and it could make sense to improve ptloader's support of it instead of relying on Assimp for this. Of course, we could also go the other direction and try to leverage Assimp more heavily and shrink ptloader.

**Comment by rdb** [comment]
ptloader converts everything via .egg and therefore I'm not really keen on spending effort there that could be spent on, say, a native glTF loader (though of course as long as obj2egg is around, we can welcome PRs).

Unless Assimp really struggles to represent .obj in particular for some reason, if the Assimp loader doesn't work with a particular .obj file, I think we would gain much more from spending effort in fixing the Assimp loader.

**Comment by Moguri** [comment]
I forgot that ptloader is all EGG-based. So, +1 to spending more time on glTF and Assimp rather than EGG/ptloader.

**Comment by BMaxV** [comment]
I have not read up on the details but that seems like some tool that should be used during setup of the project, not every time panda runs. Panda uses .egg for geometry? Then egg should be the only format panda interacts with by default.

**Comment by rdb** [comment]
With the Assimp support improved further, I'm just going to go ahead and disable obj2egg from the ptloader, while keeping it in the distribution (there is a caveat added to the manual now).
