### ISSUE TITLE
Borderless undecorated fullscreen windows on Linux

### ISSUE THREAD

**Issue by Yonnji** [panda3d/panda3d#739]
The Panda3D uses NET_WM_SPLASH for the borderless/undecorated windows. I think it was designed for splash windows with a short lifespan, but not for the games - https://specifications.freedesktop.org/wm-spec/1.4/ar01s05.html

Those windows have some problems:
- They are ignoring the taskbar, so you can't click an icon and switch to Panda3D window.
- They are not listed in windows lists, so you can't switch to Panda3D window with Alt+Tab hotkey.
- They can't be moved (or drag&dropped) to another monitor or virtual desktop.

Comparing to Firefox I thinks there are possibilities to use the better approach.
Firefox can switch between fullscreen and window mode with F11 hotkey or with a video player, like YouTube. Firefox window can be moved around and it's also listed in a taskbar.

I think it should be here, but I'm not sure - https://github.com/mozilla/gecko-dev/blob/master/widget/gtk/nsWindow.cpp

**Comment by rdb** [comment]
I'm not sure what you mean with the reference to Firefox, are you comparing Panda's undecorated mode to Firefox's fullscreen mode?  They are not the same thing.

Unfortunately this is generally a window manager specific thing.  Each window manager can interpret the hints that Panda provides differently.  What window manager are you using that produces the problems?

**Comment by Yonnji** [comment]
It's a GNOME 3.32.1 on Ubuntu 19.04

**Comment by Yonnji** [comment]
Looks like it's not Panda-related issue. This is just the Linux desktops are completely broken on multiple monitors setup.
