### ISSUE TITLE
makepanda: --static and dtool_config.h redefines

### ISSUE THREAD

**Issue by pmp-p** [panda3d/panda3d#743]
when specifying --static to makepanda you get quite a lot
```
../panda3d-webgl-port.em/include/dtool_config.h:71:9: warning: 'LINK_ALL_STATIC' macro redefined [-Wmacro-redefined]
#define LINK_ALL_STATIC 1
        ^
<command line>:8:9: note: previous definition is here
#define LINK_ALL_STATIC 
```

**Comment by rdb** [comment]
I guess we should only be specifying this in dtool_config.h, not on the compiler command-line, since it's a property of the build.

**Comment by rdb** [comment]
This only occurred on the webgl-port branch and is fixed now.
