### ISSUE TITLE
Deploying/Packaging doesn't work from inside a virtualenv

### ISSUE THREAD

**Issue by tcdude** [panda3d/panda3d#747]
When trying to use what was formerly known as deployng to package my game for win_amd64/win32, I was unable to get the program to work when running inside a `virtualenv`.

The build would complete with the usual warnings but my game would crash when launched on windows, with this traceback:

```
Traceback (most recent call last):
  File run_game.py, line 68, in <module>
  File /home/tc/VSCodeProjects/pyweek28/game/__init__.py, line 32, in main
  File /home/tc/VSCodeProjects/pyweek28/game/app.py, line 74, in __init__
  File /home/tc/VSCodeProjects/pyweek28/game/world.py, line 60, in __init__
  File /home/tc/VSCodeProjects/pyweek28/game/world.py, line 257, in setup_terrain
  File /home/tc/VSCodeProjects/pyweek28/build/__whl_cache__/Pillow-6.1.0-cp37-cp37m-win_amd64.whl/PIL/Image.py, line 2060, in save
  File /home/tc/VSCodeProjects/pyweek28/build/__whl_cache__/Pillow-6.1.0-cp37-cp37m-win_amd64.whl/PIL/Image.py, line 393, in preinit
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 1035, in _handle_fromlist
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 219, in _call_with_frames_removed
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 983, in _find_and_load
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 967, in _find_and_load_unlocked
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 677, in _load_unlocked
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 819, in exec_module
  File /home/tc/VSCodeProjects/pyweek28/build/__whl_cache__/Pillow-6.1.0-cp37-cp37m-win_amd64.whl/PIL/JpegImagePlugin.py, line 41, in <module>
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 1035, in _handle_fromlist
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 219, in _call_with_frames_removed
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 983, in _find_and_load
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 967, in _find_and_load_unlocked
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 677, in _load_unlocked
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 819, in exec_module
  File /home/tc/VSCodeProjects/pyweek28/build/__whl_cache__/Pillow-6.1.0-cp37-cp37m-win_amd64.whl/PIL/TiffImagePlugin.py, line 57, in <module>
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 983, in _find_and_load
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 953, in _find_and_load_unlocked
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 219, in _call_with_frames_removed
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 983, in _find_and_load
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 967, in _find_and_load_unlocked
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 677, in _load_unlocked
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap.py, line 819, in exec_module
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/distutils/__init__.py, line 35, in <module>
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap_external.py, line 724, in exec_module
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap_external.py, line 859, in get_code
  File /home/tc/VSCodeProjects/pyweek28/venv/lib/python3.7/importlib/_bootstrap_external.py, line 916, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\tc\Desktop\Devils Tower\distutils\__init__.py'
```
At first I suspected `Pillow` to be the culprit, but after repeating the steps of deploying/packaging on a global interpreter level instead of a virtualenv, it just worked.

I'll try to create a minimal example to replicate this behavior to narrow down the problem.

**Comment by Moguri** [comment]
I always build apps from within a virtualenv, so that in itself is not broken. However, it's been a while since I have built anything much more complicated than the asteroids sample, so there may be an issue with pulling in certain dependencies. Hopefully your minimal example can help shed some light on what's going on.

**Comment by Moguri** [comment]
@tcdude Did you get anywhere with a minimal example?

**Comment by tcdude** [comment]
@Moguri thanks for reminding me, I haven't gotten around to it yet, but will do so shortly. I had unexpected health issues and was regaining my strength over the last couple of weeks, so my focus was elsewhere.

**Comment by tcdude** [comment]
I managed to reproduce the problem with a minimal example:
[p3dtest.zip](https://github.com/panda3d/panda3d/files/3841419/p3dtest.zip)
*it simply starts ShowBase and accepts the `a` key, which leads to it crashing when built inside a virtualenv*

The problem can be narrowed down to saving images with Pillow. When using a `virtualenv`, the app crashes upon pressing the `a`-key with pretty much the same error message as evident in my first post, whilst when building on a global interpreter level, the error doesn't occur and everything behaves correctly.

Let me know if you need more information regarding this issue.

**Comment by Moguri** [comment]
So, I think this is still related to PIL/Pillow. In other words, I think Pillow isn't working when package from a virtualenv. I did test the supplied sample file, and I can confirm that the package application is not running correctly.

**Comment by tcdude** [comment]
Quick update, since on Discord it was mentioned that it possibly could be related to how Ubuntu has some custom patches for `pip`: I just tried the same using a fresh Manjaro 18.1.3 install with the same result.
I guess it's safe to say that PIL/Pillow is the culprit here.

**Comment by tcdude** [comment]
I also tested this now on Windows, with pretty much the same results, though strangely enough, @rdb was successful in building from inside a `virtualenv` with Python 3.7 and the problem didn't appear, whereas I encountered the same problem with both Python 3.6 and 3.7 on Windows.

To reiterate: The problem only results when building/deploying from inside a `virtualenv` and the `Image.save()` method from `Pillow` is being called (in the above example program, when the `a`-key is being pressed!!)

**Comment by rdb** [comment]
I finally managed to reproduce the error after realising that I made the false assumption that the built-in `venv` was used, instead of the `virtualenv` package which apparently exists on PyPI and is still available for Python 3.

Apparently, this `virtualenv` package inserts a custom version of `distutils/__init__.py` that does some really bizarre monkey patching before trying to find the original distutils (which no longer exists in our deployed build).  Worse, it expects the original distutils to exist in source form.

Based on this I strongly recommend using the built-in ` venv` instead of the `virtualenv` on PyPI.  But, perhaps we can detect that `virtualenv` is being used in `build_apps`, and then apply a hack like (this)[https://stackoverflow.com/a/33438148].

**Comment by tcdude** [comment]
This is good enough for me. Knowing that it behaves correctly when using the built-in `venv` is acceptable, since it implies only a slight change in my workflow. I think it would be good to add a note/warning in the documentation, that `virtualenv`can lead to problems, such as this.

Thank you for your time and energy.
