### ISSUE TITLE
Detect Homebrew python on MacOS

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#755]
On MacOS, if Python is installed using Homebrew, Panda installed from the SDK is not available. this is because Homebrew install Python in /usr/local and ignores /Developer/Panda3D.

The installer should detect if Python from Homebrew is installed and, in that case, copy Panda3D.pth into /usr/local/lib/python3.7/site-packages (Or any other version of Python installed)

(See forum thread https://discourse.panda3d.org/t/cant-import-panda3d-with-homebrew-python-on-mac/25227)

**Comment by rdb** [comment]
Thank you for filing the report.  I think 4ceb49412757b6a4b49098f26e33e96ce37d079d should fix it, but I have admittedly not tested it.

**Comment by rdb** [comment]
Would you mind testing out this dev build to see if it works?
https://buildbot.panda3d.org/downloads/984d70e8e0e84dec1848965fd336648672b7731d/Panda3D-SDK-1.10.5-984d70e.dmg

**Comment by el-dee** [comment]
Tested on a fresh system, it works like a charm  :)
