### ISSUE TITLE
dcparser no longer compiles outside of panda

### ISSUE THREAD

**Issue by ksmit799** [panda3d/panda3d#759]
Commit e4f493b included the use of ```vector_uchar.h```, which is internal to panda. The entire dcparser module is designed to be compiled outside of the panda environment (without ```WITHIN_PANDA``` defined). However, when attempting to compile the dcparser outside of panda (for a native panda otp server) that's no longer possible.

**Comment by rdb** [comment]
This has no high priority for us, but a patch would be welcome and easy to make.  Just a matter of moving the include to dcbase.h under the WITHIN_PANDA case, and in the else case, defining `typedef std::vector<unsigned char> vector_uchar;`.

**Comment by rdb** [comment]
I've committed some fixes for this, it was straightforward enough.
