### ISSUE TITLE
setuptools: PACKAGE_DATA_DIRS in dist/commands.py is not used

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#779]
In dist/commands.y a variable PACKAGE_DATA_DIRS contains extra dirs for cefpython3 matplotlib, ...  

https://github.com/panda3d/panda3d/blob/f1b235e06594f4c0a2c028adfe2ef2241e4091e0/direct/src/dist/commands.py#L102

However it is never used, so when including cefpython3 one has to copy the entries in their own setup.py file.

**Comment by Moguri** [comment]
I noticed this yesterday as well, and I was hoping I could get a fix in before someone else noticed. Loos like I wasn't fast enough. :)

Assigning this to myself to fix.
