### ISSUE TITLE
Frame image is upside down when accessed via Texture.getRamImage()

### ISSUE THREAD

**Issue by mbait** [panda3d/panda3d#789]
```python
import numpy as np
from cv2 import cv2
from direct.showbase.ShowBase import ShowBase


class ShowCase(ShowBase):
	def __init__(self, **kwargs):
		ShowBase.__init__(self, **kwargs)

		cube = self.loader.loadModel('misc/rgbCube')
		cube.reparent_to(self.render)
		cube.set_pos(0, 5, 0)
		cube.set_hpr(45, 45, 0)

		self.accept('1', self._screenshot1)
		self.accept('2', self._screenshot2)

	def _screenshot1(self):
		dp = self.camNode.getDisplayRegion(0)
		dp.save_screenshot('/run/shm/image-normal.jpg')

	def _screenshot2(self):
		dp = self.camNode.getDisplayRegion(0)
		data = memoryview(dp.get_screenshot().get_ram_image())
		width, height = dp.get_pixel_width(), dp.get_pixel_height()
		rgba = np.reshape(data, (height, width, 4))
		rgb = rgba[:, :, 0:3]
		cv2.imwrite('/run/shm/image-flipped.jpg', rgb)


ShowCase().run()
```
![image-normal](https://user-images.githubusercontent.com/160226/69191235-f5b85980-0ad6-11ea-8c54-cf91c8fb454c.jpg)
![image-flipped](https://user-images.githubusercontent.com/160226/69191238-f81ab380-0ad6-11ea-8eba-cca25b579a71.jpg)

**Comment by mbait** [comment]
Tested on _1.10.5.dev92_

**Comment by mbait** [comment]
Sorry, I've edited the title multiple times, because wasn't sure about where the problem is exactly. But in an additional test where an off-screen buffere was created the problem persisted. That code sample is larger then the one above, but can get a gist of it at https://discourse.panda3d.org/t/stereo-off-screen-buffer/25312/3?u=mbait

**Comment by mbait** [comment]
Note, that I (unintentionally) chose that given orientation of the cube that shows it's not RGB vs. BGR problem. If it had been so, the red face would have been flipped.

**Comment by el-dee** [comment]
According to the documentation, when copying the content of a visible window into a texture, the image is stored as returned by the GSG.

You can check if the returned image is inverted by using ```base.win.getGsg().getCopyTextureInverted()``` and invert it yourself or you can force Panda to invert the image by using ```loadPrcFileData('','copy-texture-inverted 1')```

As save_screenshot() is a high-level user-friendly method, I guess it perform the image flipping for you.

**Comment by mbait** [comment]
@el-dee Thank you for clarifing! Why is the texture stored inverted though? Is it something GPU related or is it for better performance? Is it Panda3D only related or is it something I would find in other game/graphics engines?

**Comment by mbait** [comment]
Nevermind. A quick search answered my question.

**Comment by rdb** [comment]
For the benefit of anyone else finding this question via Google: Panda3D does not store textures upside down, but textures are mapped to the screen / geometry according to the OpenGL convention, which places the origin of textures in the lower-left corner.  Some other software may follow the Direct3D convention, which places the origin in the upper-left corner.  Neither convention is "correct", and there should not be any noticeable issues if the same convention is used everywhere, but if you convert the texture to a different piece of software that expects a different convention, flipping the image may be required.

**Comment by zachgates** [comment]
Use `np.flip` ?

```python
rgba = np.reshape(data, (height, width, 4))
rgb = np.flip(rgba[:, :, 0:3], axis = 0)
```
