### ISSUE TITLE
MacOS: Catalina: Actual application occupies a quarter of the window

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#794]
As seen on the screenshot below, Panda application on Catalina are confined to the lower left quarter of the window. I guess this is related to the HiDPI scaling of the Retina monitor and that somehow it's no longer applied properly.

<img width="912" alt="Screenshot" src="https://user-images.githubusercontent.com/44778133/69766431-3750a080-1178-11ea-90ff-a0709bcd29f0.png">

**Comment by el-dee** [comment]
Problem is linked with the default value of setWantsBestResolutionOpenGLSurface which seems to have been changed in Catalina, the default mode is HiDPI ON now. Godot and SDL had the same problem, their fix are:

SDL : https://hg.libsdl.org/SDL/rev/46b094f7d20e

Godot : https://github.com/godotengine/godot/pull/32809

**Comment by rdb** [comment]
Could it be that Cocoa is giving the OpenGL window a smaller window size than is actually in existence?  In other words, would it be fixed if we doubled the window size that Cocoa reports?

**Comment by el-dee** [comment]
Not exactly, from what I learned, until Catalina, an app had to specify that it support scaling on the OpenGL frame buffer (backing surface in the Apple lingo). If not activated (the default mode), a pixel in the frame buffer is rendered as a pixel on the screen. If scaling is activated, the frame buffer is magnified or scaled down according to the scaling factor, see https://developer.apple.com/documentation/appkit/nsview/1414938-wantsbestresolutionopenglsurface#declarations

From Catalina onwards, OpenGL app have the scaling automatically activated, even if the app does not support it. Sadly, there is no information from Apple about this change, but you see many OpenGL based application having that change performed the last month due to Catalina.

**Comment by el-dee** [comment]
Even with the fix, the problem occurs if you switch your application to fullscreen. Worse, if you switch back to windowed mode, the window is moved out of the screen and so no longer reachable, though still visible if you ask the desktop to show all the windows of the app.

I also tested a panda application not compiled on Catalina; in windowed mode there is no problem even without the workaround, but the fullscreen issue is present too.

**Comment by el-dee** [comment]
The problem is that in https://github.com/panda3d/panda3d/blob/71dfc51f8a7d9adf65347f092baf6bf13eb2debe/panda/src/cocoadisplay/cocoaGraphicsWindow.mm#L1109 only the display size is used to find the new mode, the new mode should also have the same scaling factor as the current view (or we have to recreate a new view and switch over it, or something like that)

**Comment by el-dee** [comment]
Don't close this one yet,  I will have soon a patch to fix the issue with the fullscreen scale.

**Comment by el-dee** [comment]
I'm struggling to have an identical behaviour between Panda3D on Mojave or older and Catalina...

On Mojave (or older), the underlying graphic engine does the scaling and coordinate adaptation for the application if it does not support HiDPI. If I start the application, on a retina screen, there is a 2x scaling factor automatically applied (a 800x600 window is rendered on a 1600x1200 rect on screen). If I switch to fullscreen in app using WindowProperties, the app with the current code switch to a non scaled mode but the view coordinates are updated by the underlying graphic engine. This is the first weirdness.

On Catalina, the coordinate update is no longer done by the graphic engine (or at least I can't find anywhere how to trigger it), so my patch to avoid scaling or cropping is to select the display mode with the required dimensions and with the same scaling factor as the current view. So, contrary to Mojave, the display mode for fullscreen will also be upscaled if the original window was already upscaled, and if the selected display mode dimension does not exist with the scaling factor the app had at startup the fullscreen can not be activated.

If the difference in behaviour is acceptable I will create a PR with the patch.

**Comment by rdb** [comment]
I wonder, should we perhaps be using [`[_view enterFullscreenMode]`](https://developer.apple.com/documentation/appkit/nsview/1483780-enterfullscreenmode) instead of the current CGLSetFullScreenOnDisplay-based approach on Catalina?  I believe that the current method is deprecated (but then, all of OpenGL is deprecated, so I don't know how much that actually means).

**Comment by el-dee** [comment]
Many GC methods that Panda uses are also deprecated so I would say that in Panda 1.11 a good clean up will be needed, especially following the end of support of 10.6 SDK

I can give [_view enterFullscreenMode] a try, but it might be a non trivial modification. Another possibility is to use CGContextScaleCTM to apply the scaling on the context and emulate Mojave behaviour, though I'm not sure if it works with non-layered context...

**Comment by rdb** [comment]
Unfortunately cleaning out all deprecated things means abandoning OpenGL and adopting Metal, which is not at all a trivial endeavour, so we're stuck with picking and choosing our deprecated APIs for the forseeable future.

I appreciate that you're looking into this!  If it turns out to be non-trivial, certainly your proposed fix sounds like it would still be better than having the game cover only a quarter of the window in fullscreen mode.

**Comment by el-dee** [comment]
I did a quick test with enterFullScreenMode, first it does not seem to allow to specify the fullscreen resolution (or it is hidden in one of the sub options) and there are still scaling issues (though they might be resolved by specifying the drawable size of the attached layer of the view, but this is not really well documented).
There is another problem, using this method further  keyboard and mouse events are lost once I click or press a key. So this does not look good for a quick fix.

I will try and test CGContextScaleCTM this week-end.

**Comment by el-dee** [comment]
Well, CGContextScaleCTM is a dead end, I tried again with enterFullScreenMode bu I could not fix the problem with the input event (I made sure that the view was still the first responder, tried also with makeKeyAndOrderFront, ... but to no avail).

Panda3D does a lot of the view and event management internally, so it might conflict with what the higher level API from apple does (though it's pure guesswork).
