### ISSUE TITLE
Android build how to not in the manual

### ISSUE THREAD

**Issue by BMaxV** [panda3d/panda3d#798]
Someone linked how to build for Android in the IRC chat and said the info was in the manual. It's not. At least I could not easily find it.

Here is the repo that was linked:

https://github.com/pmp-p/pydk

**Comment by rdb** [comment]
Instructions for building for Android are in the README.md in the GitHub repository.
If you feel that it should be in the manual, you should file a bug in the bug tracker for the manual:
https://github.com/panda3d/panda3d-docs/issues

Thanks.
