### ISSUE TITLE
Particle Panel: stack trace when cancelling Load Params

### ISSUE THREAD

**Issue by xordspar0** [panda3d/panda3d#811]
I'm running Panda3D 1.10.4.1 with Python 3.7 on macOS.

When I start to load a file in the particle panel, but then change my mind and click "cancel" in the native file selection dialog that pops up, I get a stack trace:

```
OSError Exception in Tk callback
  Function: <bound method ParticlePanel.loadParticleEffectFromFile of <direct.tkpanels.ParticlePanel.ParticlePanel object at 0x113d83350>> (type: <class 'method'>)
  Args: ()
Traceback (innermost last):
  File "/usr/local/lib/python3.7/site-packages/Pmw/Pmw_2_0_1/lib/PmwBase.py", line 1776, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.7/site-packages/direct/tkpanels/ParticlePanel.py", line 1278, in loadParticleEffectFromFile
    Filename.fromOsSpecific(particleFilename))
  File "/usr/local/lib/python3.7/site-packages/direct/particles/ParticleEffect.py", line 203, in loadConfig
    data = vfs.readFile(filename, 1)
OSError: Failed to read file: 'None'
```

I edited ParticlePanel.py to add the following line after getting the filename:

```python
        print(repr(particleFilename))
```

askopenfilename is indeed returning the string `'None'`.

For context, here's where the problem is occurring in Panda3d's code:

https://github.com/panda3d/panda3d/blob/2c9d16f62e2a60ae1437d2b725beefcb27c3f55a/direct/src/tkpanels/ParticlePanel.py#L1269-L1281

I draw two conclusions from this:

1. There might be a bug in tkinter and/or the Mac file dialog.
2. The particle panel should check if the file that gets returned by the file picker actually exists. This would also fix race conditions where real files got deleted before we have a chance to read them.

**Comment by rdb** [comment]
I went to the Particle Panel, clicked File > Load Params, and then clicked Cancel, and no error was displayed anywhere.  Did you follow different steps?  Perhaps the Mac version of tkinter is doing something odd by returning "Null" instead of None?

**Comment by rdb** [comment]
Your error message says that it's trying to load "None" instead of "Null", which one is it?

**Comment by xordspar0** [comment]
Oops, my mistake. Replace all places where I said Null with None.

**Comment by xordspar0** [comment]
> no error was displayed anywhere. Did you follow different steps?

Nope, I can reproduce this with the steps above on a Mac. On my main Ubuntu machine it seems fine. Sometimes the error popup is delayed a few seconds, but usually it pops up right away.
