### ISSUE TITLE
Stereo rendering works incorrectly with pandagles2 display

### ISSUE THREAD

**Issue by mbait** [panda3d/panda3d#815]
Below are examples of stereo rendering of the same scene in Panda3D with two different pipelines:
**eglGraphicsPipe**
![stereo-eglGraphicsPipe](https://user-images.githubusercontent.com/160226/71033065-816bd880-20cb-11ea-9556-303d9382ca96.png)
**glxGraphicsPipe**
![stereo-glxGraphicsPipe](https://user-images.githubusercontent.com/160226/71033066-829d0580-20cb-11ea-97b1-b334dd7c731b.png)
**Source code**
```python
import numpy as np
from cv2 import cv2
from direct.showbase.ShowBase import ShowBase
from panda3d.core import *

#load_prc_file_data("", "load-display pandagles2")

base = ShowBase(windowType='offscreen')
base.camNode.get_display_region(0).set_active(False)

props = FrameBufferProperties()
# Request 8 RGB bits, no alpha bits, and a depth buffer.
props.set_rgba_bits(8, 8, 8, 0)
props.set_rgb_color(True)
props.set_depth_bits(16)
props.set_stereo(True)

# Create a WindowProperties object set to 512x512 size.
win_prop = WindowProperties.size(512, 512)

# Don't open a window - force it to be an offscreen buffer.
flags = GraphicsPipe.BFFbPropsOptional | GraphicsPipe.BF_refuse_window
#flags = GraphicsPipe.BFFbPropsOptional

buffer = base.graphicsEngine.make_output(base.pipe, "stereo buffer", -100,
                                         props,
                                         win_prop, flags, base.win.getGsg(),
                                         base.win)
texture = Texture()
buffer.addRenderTexture(texture, GraphicsOutput.RTM_copy_ram)

lens = PerspectiveLens()
lens.setFov(54.611362)
lens.setFocalLength(1.37795276)
lens.set_interocular_distance(50)
lens.set_convergence_distance(float('inf'))

render = NodePath('stereo')
cam = base.makeCamera(buffer)
cam.node().setLens(lens)
cam.node().setScene(render)
dp = buffer.makeDisplayRegion()
dp.setCamera(cam)

# scene = StrawberryPlant.create_random()
# ModelAssembly(render, scene)

base.camera.set_pos(100, -500, 0)
cube = base.loader.loadModel('misc/rgbCube')
cube.reparent_to(render)
cube.set_scale(100)
cube.set_z(100)

def stereo1():
    base.graphicsEngine.renderFrame()
    image = np.asarray(memoryview(texture.getRamImage())).reshape(1024, 512, 3)
    left = image[0:512, ...]
    right = image[512:1024, ...]
    #cv2.imshow('left-right', np.vstack((left, right)))
    cv2.imwrite('stereo.png', np.vstack((left, right)))
    cv2.waitKey(0)

if __name__ == '__main__':
    import timeit
    # built-in: 0.0171750984987
    # manual: 0.0173542866707
    stereo1()

    # timer = timeit.Timer('stereo1()', 'from __main__ import stereo1')
    # print sum(timer.repeat(30, 100)) / 3000
```

**Comment by mbait** [comment]
I ran that on _25217d9f7329d27206a991f8b8249cdced3d36d3_.

**Comment by rdb** [comment]
The GLES port was done before GLES supported multiple FBO attachments, so some of the code (particularly the bits that select which render attachment to render to) is ifdeffed out for OpenGL ES.

I'm unable to test it myself, but could you perhaps see if 3c3eee22955d80824d2daa366e24ac25c1ad70ce fixes it?

**Comment by mbait** [comment]
Yes, it does! Thank you for such prompt fix.

**Comment by mbait** [comment]
Sorry, I didn't notice at first, but now both eyes contain left view, so the bug is still there:
![stereo](https://user-images.githubusercontent.com/160226/71112195-db2dda80-217f-11ea-990b-c018ee95c227.png)

**Comment by rdb** [comment]
OK, I see that the missing piece is that we aren't calling `glReadBuffer` properly.  Will check in a fix shortly.

**Comment by mbait** [comment]
@rdb After pulling from fresh master I still see the problem. Can't see the button to re-open this issue.

**Comment by rdb** [comment]
How is this evident in your testing?  I am using your code, except with the stereo1 method modified to the following:
```python
def stereo1():
    base.graphicsEngine.renderFrame()
    texture.write("stereoL.png", 0, 0, False, False)
    texture.write("stereoR.png", 1, 0, False, False)
```
I am seeing a stereoL.png and stereoR.png being written, which show the box being in different X positions.

If this is not what you are seeing, could you please capture and attach an apitrace .trace file, using a command like the following:
```
apitrace trace --api=egl python test.py
```

For the record, I'm testing on ArchLinux with an NVIDIA GeForce MX150.

**Comment by mbait** [comment]
Are you sure you use _eglGraphicsPipeline_?

**Comment by rdb** [comment]
Quite.

**Comment by mbait** [comment]
What is the commit hash you're testing on?

**Comment by rdb** [comment]
I'm testing on 3755e157bf1b84fab733ac9465b0604c8c5c499f, the latest master.  Of course, I also verified that the fix was effective back when I checked in fccffb4932fd6c0808673b999064ddd51ca9b509.

I'd like to see the output with `notify-level-gles2gsg debug` (or spam) set for you, and if you can, the .trace file generated by the command I mentioned earlier.

**Comment by mbait** [comment]
[tracelog.zip](https://github.com/panda3d/panda3d/files/4020815/tracelog.zip)

**Comment by rdb** [comment]
The log shows that it reports the presence of the needed extensions, and the API trace shows that it does query the pointer of glDrawBuffers.  However, it does not show an attempt to query the glReadBuffer functionality.  That strongly suggests to me that your build does not include fccffb4932fd6c0808673b999064ddd51ca9b509; could you double-check that you have pulled and built the latest changes?

**Comment by mbait** [comment]
Sorry, that was my bad. I fetched changes from upstream to my work, and it started to work as expected.

**Comment by mbait** [comment]
Thank you for your help and patience!

**Comment by rdb** [comment]
Great, thank you for verifying.
