### ISSUE TITLE
Panda3D using wrong path if it built from source

### ISSUE THREAD

**Issue by kergalym** [panda3d/panda3d#818]
I built panda3d 1.10.4.1 from source and...

    $find /usr -name libp3framework.so.1.10
    /usr/lib64/panda3d/libp3framework.so.1.10
    $ldd /usr/bin/pview
    	linux-vdso.so.1 (0x00007ffed5eeb000)
    	libp3framework.so.1.10 => not found
    	libpandaegg.so.1.10 => not found
    	libpanda.so.1.10 => not found
    	libpandaexpress.so.1.10 => not found
    	libp3dtool.so.1.10 => not found
    	libp3dtoolconfig.so.1.10 => not found
    	libdl.so.2 => /lib64/libdl.so.2 (0x00007f0c86c81000)
    	libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libstdc++.so.6 (0x00007f0c86a09000)
    	libm.so.6 => /lib64/libm.so.6 (0x00007f0c868be000)
    	libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libgcc_s.so.1 (0x00007f0c868a4000)
    	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0c86881000)
    	libc.so.6 => /lib64/libc.so.6 (0x00007f0c866b1000)
    	/lib64/ld-linux-x86-64.so.2 (0x00007f0c86cf3000)

Looks like /lib is symlink to /lib64 while panda installed to /usr/lib64, so panda executables tries to find *.so files in /lib64 instead of /usr/lib64.
Doing `sudo ln -sv /usr/lib64/panda3d/libp3framework.so.1.10 /lib64/` makes it work but I don't know if it's makepanda bug.
I built panda with `python makepanda/makepanda.py --everything --no-artoolkit --no-fcollada --no-fmodex --no-opencv --no-squish --no-tiff --no-vrpn --no-rocket --no-eigen --no-fftw --threads 4  `and then `sudo python makepanda/installpanda.py --prefix /usr`

I'm not sure if it's abug or not a bug, you're feel to close it.

I reproduce same issue in clean Manjaro Linux, but my main system is Gentoo.

**Comment by rdb** [comment]
You should definitely not be creating symlinks in /lib64, so I would suggest removing those right away.

As stated in my response on IRC, this feels like an XY problem; what is the original problem that made you look at ldd?

Perhaps you forgot to run ldconfig to update the ld cache after installing Panda3D?

**Comment by kergalym** [comment]
I just forgot to do sudo ldconfig. Issue should be closed, I think.
