### ISSUE TITLE
Crash when vertex buffer is resized on DirectX

### ISSUE THREAD

**Issue by MDTech-us-MAN** [panda3d/panda3d#824]
When I play a specific particle effect when using DirectX, panda3d crashes. There are no crashes when using OpenGL.

Crash: 
![image](https://user-images.githubusercontent.com/1660330/71447886-7b48ae00-2702-11ea-9257-9eb62359110d.png)

Call Stack:
![image](https://user-images.githubusercontent.com/1660330/71449339-3b8cc100-2718-11ea-9e8d-4078e746e30e.png)

Code:
https://gist.github.com/MDTech-us-MAN/fc5556e74c4b3353816c86d7f9229909

(press the "P" key to trigger the effect)

**Comment by rdb** [comment]
It happens when resizing any vertex buffer without using the appropriate `modify_()` calls.  This is a more isolated sample that does not involve the particle system:
```python
# Press space several times
from panda3d.core import *
import sys

f = GeomVertexFormat.get_v3()
gvd = GeomVertexData('vdata', f, Geom.UH_dynamic)
gvd.set_num_rows(60)

gp = GeomPoints(Geom.UH_static)
gp.add_next_vertices(1)

g = Geom(gvd)
g.add_primitive(gp)
gp = None

gn = GeomNode("test")
gn.add_geom(g)
gn.set_bounds(OmniBoundingVolume())
gn.set_final(True)


def resize_gvd():
    rows = gvd.get_num_rows() + 1
    print("Resizing to " + str(rows) + " rows")
    gvd.set_num_rows(rows)
    sys.stdout.flush()


load_prc_file_data("", "load-display pandadx9")

from direct.directbase.DirectStart import base
np = base.render.attach_new_node(gn)
base.accept('space', resize_gvd)

sys.stdout.flush()
base.run()
```
