### ISSUE TITLE
Wrong material display when using PBR in egg file

### ISSUE THREAD

**Issue by jpgemble** [panda3d/panda3d#828]
When using the metallic scalar in egg material, the ambient light is forced to white when loading bam file (or cache).

In the [egg_PBR_material_bug.zip](https://github.com/panda3d/panda3d/files/4020814/egg_PBR_material_bug.zip) file you'll find:
- simplest.py: a python Panda3D simple project that shows the issue
- simplest_NOT_WORKING.egg: an egg file that shows the issue
- simplest_WORKING.egg: an egg file that shows how to use a workaround (not using PBR)

To reproduce the bug, rename simplest_NOT_WORKING.egg to simplest.egg and execute simplest.py.
The first time it works: a black form is displayed (it uses egg file), but next times it doesn't work: a white form is displayed (it uses cache bam file).
The expected behavior is to always show a black form.

I believe that, to solve the issue, the set_base_color method should be used in place of the _base_color property assignment in the Material class fillin method of the src/gobj/material.cxx file.
But I've not coded nor tested this fix.

**Comment by rdb** [comment]
Thanks for reporting and for pointing us at the right fix!  I'll check in a fix shortly, which will be part of the upcoming 1.10.5 release.
