### ISSUE TITLE
setuptools: Can not integrate CEFPython on macOS

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#833]
I'm trying to add CEFPython in an app bundle on macOS, but there is one piece of CEF that is not copied properly ```Chromium Embedded Framework.framework/Chromium Embedded Framework```

I added it explicitly in PACKAGE_DATA_DIRS (and discovered a small bug, see #832), 

            ('cefpython3/Chromium Embedded Framework.framework/Chromium Embedded Framework', '', {'PKG_DATA_MAKE_EXECUTABLE'}),

However the file ```Chromium Embedded Framework``` is directly copied under Frameworks/ in the bundle, not as ```Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework```

And the wrapping library looks for that relative path :

    cefpython3.cefpython_py37.so:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libc++abi.dylib (compatibility version 1.0.0, current version 49.1.0)
	@rpath/Chromium Embedded Framework.framework/Chromium Embedded Framework (compatibility version 31774.13.31, current version 31774.13.31)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)

I'm not sure how to solve this (and hopefully still for 1.10.5)

**Comment by el-dee** [comment]
I tried to apply the same thing as ```@loader_path```and actually it solves the problem, see #834

**Comment by rdb** [comment]
Thanks so much for all the fixes!  Much obliged if you could test one of the builds from here and let me know whether everything is working OK now.
https://buildbot.panda3d.org/downloads/f09ee925820f510d5498dfb27f99c6a7a928acfa/

**Comment by el-dee** [comment]
It works fine on macOS and Linux, all three targets (manylinux, macos, win_amd64) are generated successfully. I tested the apps on Linux and macOS, CEFPython is properly loaded and working (though it crashes on mac, but that's another problem).

I will test the binary on Windows if my VM starts up again.

**Comment by el-dee** [comment]
And it works perfectly fine on Windows also (it was not the topic of this issue but it's good to know).

**Comment by rdb** [comment]
Thanks so much!

**Comment by rdb** [comment]
As for why it crashes, it might have something to do with the fact that it's built with libc++.  If we were to build 10.9 wheels for all Python versions (rather than just 3.6-3.8 like we do now), and if you were to specify `macosx_10_9_x86_64` as platform, the problem might go away.

**Comment by el-dee** [comment]
For once libstdc++ was not the culprit!

The problem is that CEF is extremely sensitive on how to configure the path to all of its components (pak files, icudtl.dat, subprocess, ...) Even a '../' in a path causes a crash !

I managed to make it work, but this will requires changes in cefpanda to set up properly the framework_dir_path, resources_dir_path, ...

There is one remaining problem, there is a program, subprocess, which is shipped with CEF. The problem is that it still contains a @rpath/ reference to ```@rpath/Chromium Embedded Framework.framework/Chromium Embedded Framework``` As it is not an explicit dependency to the main program or any lib it is simply copied without having its references flattened.

If I modify the file manually in the bundle, I can get CEF working without problem in the bundled app, so there is hope :)

So the question is how to force the code to call copy_with_dependencies() or copy_dependencies() on that standalone file ?

**Comment by rdb** [comment]
I suppose there should be a hiddenLibraries (or something similar) dictionary defined somewhere.  We don't really have a way to define these right now.

**Comment by rdb** [comment]
Either that, or we should make the PACKAGE_DATA_DIRS mechanism use copy_with_dependencies if a certain flag was specified (or generally, if it detects that an executable file is given).

**Comment by el-dee** [comment]
I took the easy path and modified commands.py to use copy_with_dependencies() for all files flagged with 'PKG_DATA_MAKE_EXECUTABLE'.

I will shortly make a PR for cefpython to fix the paths of the resources and this should be the end if this one :)
