### ISSUE TITLE
PRC_DIR envvar is not honored

### ISSUE THREAD

**Issue by Fak3** [panda3d/panda3d#842]
Panda3d version: panda3d==1.10.5 (installed with pip3)
OS: openSUSE Tumbleweed linux, 64bit
Python version: 3.7.3

I have installed panda3d with pip, then created simple app from tutorial:
main.py
```python
import os
print(f'Using PRC_DIR {os.environ["PRC_DIR"]}')

from direct.showbase.ShowBase import ShowBase


class MyApp(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)
        self.scene = self.loader.loadModel("models/environment")
        self.scene.reparentTo(self.render)
        self.scene.setScale(0.25, 0.25, 0.25)
        self.scene.setPos(-8, 42, 0)

app = MyApp()
app.run()
```
Then I followed instructions at https://raw.githubusercontent.com/panda3d/panda3d/release/1.10.x/panda/src/doc/howto.use_config.txt and created Debug.prc file in the current directory (same as main.py):
```
notify-level spam
default-directnotify-level spam 
```
Then I launched app with ```PRC_DIR=`pwd` python3 main.py```. But I did not have any spam output, and it looks like my Debug.prc was not picked up by panda3d. The output was:
``` 
$ PRC_DIR=`pwd` python3 main.py
Using PRC_DIR /home/z/pproj/panda_tut2
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
```
To check, I tried to manually edit the file `/usr/lib64/python3.7/site-packages/panda3d/etc/Config.prc`, and it did has effect, I got a lot of spam in the console when app is launched (`:pgraph(debug): Destructing 0x56492848f000, cam2dp`, etc).

**Comment by rdb** [comment]
This directory is called by default `PANDA_PRC_DIR`.  We should update the documentation.

**Comment by rdb** [comment]
Have you had luck with using `PANDA_PRC_DIR`?

**Comment by Fak3** [comment]
Yes, it worked. Although it overrides system  prc dir completely, and I had to copy system prc files into current dir for this to work - that was not clear from the documentation

**Comment by rdb** [comment]
You can use `PANDA_PRC_PATH` instead of `PANDA_PRC_DIR` to be able to read .prc files from multiple locations.
