### ISSUE TITLE
Textures with clear color but without RAM image are stripped when loading from BAM

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#844]
A texture created using set_clear_color() has no ram image associated with it, but should still be applied on nodes as it contains a uniform color and so is not empty.

See https://github.com/Moguri/panda3d-gltf/issues/47 : a fallback texture, normal-fallback, is applied on the node. When printing out the Attribs it is correctly displayed, but when listing the TextureStages applied on the node it is not present.

**Comment by rdb** [comment]
Could you create a sample to demonstrate this?

**Comment by el-dee** [comment]
With a trivial example, using CardMaker and directly applying the texture or the TexAttrib, there is no problem, so I will try and replicate how panda3d-gltf builds the model and applies the material and textures.

**Comment by el-dee** [comment]
Ok, I struggled to find the root cause, as it was not at all where I thought is was. Actually the problem is that the bam exporter (or loader) strips the textures without ram image. Without going through a bam file, there is no problem at all !

```
from panda3d.core import *

from direct.showbase.ShowBase import ShowBase

import tempfile

base = ShowBase()

texture = Texture()
texture = Texture('texture')
texture.setup_2d_texture(1, 1, Texture.T_unsigned_byte, Texture.F_rgb)
texture.set_clear_color(LColor(1, 0, 0, 1))

#texture.make_ram_image()

cm = CardMaker('card')
nproot = NodePath(cm.generate())
nproot.set_texture(texture)

print(nproot.findAllTextureStages())

with tempfile.NamedTemporaryFile(suffix='.bam') as bamfile:
    bamfilepath = Filename.from_os_specific(bamfile.name)
    bamfilepath.make_true_case()
    nproot.write_bam_file(bamfilepath)

    cube = loader.load_model(bamfilepath)

cube.reparent_to(render)
base.cam.set_pos(0, -6, 0)
base.cam.look_at(cube)

print(cube.findAllTextureStages())

base.run()
```

**Comment by rdb** [comment]
There are two problems here:
(1) Clear colors are not written to .bam files
(2) Textures without filenames are not loaded, as indicated by the info message:
```
:gobj: Cannot create texture 'texture' with no filename.
```

I think the short-term solution has to be that a RAM image is created for images with a clear color, until we can introduce a new .bam version in 1.11.  This means that the loaded texture no longer has a clear color set, but instead has a raw image containing the clear color.

**Comment by rdb** [comment]
This is fixed.  The textures are no longer stripped, and a RAM image is automatically generated by default.  I've also added support for just storing the clear colors in the .bam file, instead of generating a RAM image, but due to compatibility considerations, you need to explicitly set `bam-version 6 45` in Config.prc (noting that this makes your .bam files incompatible with Panda3D 1.10.5 and below).
