### ISSUE TITLE
Crash when used in python 3.8 with hmac

### ISSUE THREAD

**Issue by eduardomezencio** [panda3d/panda3d#851]
**Edit: I renamed the issue now that I found that bezier is not needed to reproduce the problem. Please, see my next comment.**

It's quite difficult to point who's to blame for this issue, but I'm reporting here since panda3d is one of the packages involved.

Using python 3.8.1, panda3d 1.10.5, bezier 2020.1.14 in arch linux.

The problem is that if I import the bezier package before I instantiate ShowBase, nothing wrong happens. Importing it after causes a crash with message "malloc(): invalid size (unsorted)"

The problem happens while importing bezier, so it makes more sense to report to that package, but the fact that it only happens in this specific situation involving panda3d bugs me. It does not happen with python 3.7, so may be something wrong with python 3.8.

Example without error:
```
import bezier

from direct.showbase.ShowBase import ShowBase
base = ShowBase()
base.run()
```

Example with error:
```
from direct.showbase.ShowBase import ShowBase
base = ShowBase()

import bezier

base.run()
```

**Comment by eduardomezencio** [comment]
After getting in touch with the bezier package developer, he found that the problem happened when importing the default python package hmac, thus removing the bezier package from the equation. 

He also found that the error cannot be reproduced on macos, but happens in arch linux and ubuntu 18.04. I still have no idea about windows.

Now here's the more minimal error example:
```
from direct.showbase.ShowBase import ShowBase
base = ShowBase()
import hmac
```

**Comment by dhermes** [comment]
Howdy, maintainer of `bezier` here. I saw [the report][1] and got interested. I traced the issue down to a [single line][2] in `hashlib.py` in the standard library. The import of `hashlib.py` boils down to any (or all) of the following 5 lines:

```python
import _hashlib


_hashlib.openssl_md5()
_hashlib.openssl_sha1()
_hashlib.openssl_sha224()
_hashlib.openssl_sha256()
_hashlib.openssl_sha384()
```

[1]: https://github.com/dhermes/bezier/issues/186
[2]: https://github.com/python/cpython/blob/v3.8.1/Lib/hashlib.py#L131

**Comment by CFSworks** [comment]
I've been trying very hard to replicate this in an Arch container and have gotten nowhere so far:

```
# python
Python 3.8.1 (default, Jan  8 2020, 23:09:20) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from direct.showbase.ShowBase import ShowBase
>>> base = ShowBase()
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
:display:x11display(warning): Couldn't open input method.
:device(error): Error adding inotify watch on /dev/input: No such file or directory
:device(error): Error opening directory /dev/input: No such file or directory
:audio(error): Couldn't open default OpenAL device
:audio(error): OpenALAudioManager: No open device or context
:audio(error):   OpenALAudioManager is not valid, will use NullAudioManager
:audio(error): Couldn't open default OpenAL device
:audio(error): OpenALAudioManager: No open device or context
:audio(error):   OpenALAudioManager is not valid, will use NullAudioManager
>>> 
>>> import bezier
>>> 
```

Panda does use OpenSSL, so it's not out of the realm of possibility that there's a conflict with how Panda initializes OpenSSL vs. how `_hashlib` wants OpenSSL to be initialized, but without seeing this malloc error myself, I can't offer much more than that speculation. :(

@eduardomezencio would you be willing to run the problem snippet with Python running under [valgrind](https://www.archlinux.org/packages/extra/x86_64/valgrind/)? This sounds like memory mismanagement and Valgrind's memcheck tool (the default) is very good at sniffing that out.

**Comment by rdb** [comment]
I can't reproduce this on Arch Linux with my normal source build, but I get this with a pip-installed build of Panda3D:
```
free(): invalid pointer
Aborted (core dumped)
```
Did you also use a pip-installed build?

It is worth noting that when installing the manylinux wheel from pip, Panda uses an old version of OpenSSL (1.0.2), which may not match the version of OpenSSL that `_hashlib` was built against.  I wonder if that is the source of our trouble.

**Comment by eduardomezencio** [comment]
@rdb, yes, I'm using panda3d installed from pip. My process to reproduce the error was simply to create a virtual environment with python 3.8.1, install panda3d (1.10.5) in this environment using pip and run the code above.

@CFSworks, I tried running it with valgrind, and the output is quite big, so I'll attach it here. I don't know exactly what to look for in this output to check it myself, but it does report errors.

[valgrind-output.txt](https://github.com/panda3d/panda3d/files/4087021/valgrind-output.txt)

**Comment by rdb** [comment]
Apparently, according to `nm`, OpenSSL symbols are being exported from the Panda libraries.  I think we have to compile with the `-Wl,--exclude-libs,ALL` option to isolate our version of OpenSSL.

**Comment by dhermes** [comment]
Is this project using [`auditwheel`][1] when creating `manylinux` wheels? I expected to see a `.libs` directory in your packaged wheel (I'm looking at `panda3d-1.10.5-cp38-cp38-manylinux1_x86_64.whl`).

Also, I recently realized `manylinux1` support is effectively discontinued and starting using `manylinux2010` (image is CentOS 6 vs. CentOS 5 for `manylinux1`).

[1]: https://github.com/pypa/auditwheel

**Comment by rdb** [comment]
We don't use auditwheel to produce our wheels, but have our own script to do effectively the same thing that auditwheel does.  The use of a `.libs` directory is a numpy convention and is not mentioned in PEP 513.

The dependencies you are seeing come from optional tools and third-party plug-ins that are included, that require more recent Linux versions.  Most of what you pasted is a result of the inclusion of the `pstats` tool, which requires GTK and a host of other dependencies that we can't possibly package in a self-contained way (so we don't bother, and include it on an as-is basis).  The core libraries, on the other hand, are manylinux1-compliant, so we still tag it manylinux1.

We don't have a compelling reason to upgrade to manylinux2010 at the moment.  manylinux1 is still being updated.  When building for manylinux1 becomes a hassle, we will probably upgrade.

**Comment by dhermes** [comment]
>  The use of a `.libs` directory is a numpy convention and is not mentioned in PEP 513.

I'm not sure when the usage of `.libs` originated, but it's now "standard" since `auditwheel repair` is a recommended part of the build process and it has a flag `--lib-sdir` that defaults to `.libs`.

**Comment by rdb** [comment]
Back on topic: I produced a build of Panda that linked statically to OpenSSL 1.0.2, and indeed, it crashed when running @dhermes' example code.

Then I set the following:
```
export LDFLAGS="-Wl,--exclude-libs,libssl.a -Wl,--exclude-libs,libcrypto.a"
```
…and produced another build of Panda.  It no longer crashed, which simultaneously proved my guess about the source of the issue and validated a potential solution.

The catch is that building Panda with this setting increased the total size of the Panda libraries and binaries by a whopping 5%, because OpenSSL is used by several components of Panda, and it ends up duplicated a bunch this way.

I'll keep looking to see if there are ways to avoid this, but we may have to just eat the 5% increase until we move things around a bit more within Panda.

**Comment by el-dee** [comment]
This commit breaks the build on macOS, clang ld does not support option --exclude-libs

**Comment by rdb** [comment]
I noticed the buildbot failure, I'm on it :)

**Comment by rdb** [comment]
I managed to offset the loss by using `-Wl,--exclude-libs,` on other third-party libraries.  My change introduces a savings of a few hundred KB.  Deployed games will not need to ship `make-prc-key` of course, so there will be an additional 1384 KB saved there.

| Old (KB) | New (KB) | Difference | Library
|------:|------:|-------:|------------------------------|
| 13916 | 12208 | - 1708 | lib/libp3assimp.so
|  1848 |  1572 | -  276 | lib/libp3dtoolconfig.so.1.10
| 15604 | 15268 | -  336 | lib/libp3ffmpeg.so.1.10
|   996 |   984 | -   12 | lib/libp3openal_audio.so
|   168 |   364 | +  196 | lib/libp3vision.so.1.10
|   328 |   264 | -   64 | lib/libp3vrpn.so.1.10
|  1916 |  3200 | + 1284 | lib/libpandaexpress.so.1.10
| 20400 | 19320 | - 1080 | lib/libpanda.so.1.10
|   152 |  1536 | + 1384 | bin/make-prc-key

You can grab a fixed wheel from the buildbot:
https://buildbot.panda3d.org/downloads/4f4b14dd2b13b420f6641181abdab8455a9b1680/

Thanks to all for helping to track down this issue!
