### ISSUE TITLE
Mouse position in relative mode

### ISSUE THREAD

**Issue by hoba87** [panda3d/panda3d#876]
I want to report a strange behaviour of the mouseWatcherNode.getMouseX() and ...Y():
Considering the following code, pressing control activates the relative mouse mode, and then the mouse position is logged in mouse_move. However, although the mouse position is set to the center in the control_down function, the first execution of mouse_move gives x and y values different from 0. For further iterations, x and y are 0.
This happens on Windows and MacOS, on MacOS the y value keeps constantly slightly different from 0.
(Everything without moving the mouse.)
```
        def control_down(self):
            props = WindowProperties()
            props.setCursorHidden(True)
            props.setMouseMode(WindowProperties.M_relative)
            base.win.requestProperties(props)

            props = base.win.getProperties()
            base.win.movePointer(0,
                                 props.getXSize() // 2,
                                 props.getYSize() // 2)
            base.taskMgr.add(self.mouse_move, "mouse move task")

        def mouse_move(self, task):
            mw = base.mouseWatcherNode
            if mw.hasMouse():
                x, y = mw.getMouseX(), mw.getMouseY()

                props = base.win.getProperties()
                base.win.movePointer(0,
                                     props.getXSize() // 2,
                                     props.getYSize() // 2)
            return Task.cont
```

**Comment by ArsThaumaturgis** [comment]
What size is your window? (It might be worth checking repeatedly (via "getXSize" and "getYSize") during a test-run, in case window-management or some other matter causes it to change slightly.) I seem to recall encountering something similar when a window had a dimension that didn't divide exactly by two.

**Comment by rdb** [comment]
Note that requestProperties works asynchronously, so the movePointer you do right after that may still be happening in absolute mode.

**Comment by hoba87** [comment]
@ArsThaumaturgis The window size is set to 2000x1500. 
@rdb If I introduce a time.sleep(1) after requestProperties, the problem persists, so I guess the asynchronuous call should be not the problem here.

The only workaround I found so far, is to introduce a flag variable, which allows to ignore the first run of mouse_move.

**Comment by ArsThaumaturgis** [comment]
> The window size is set to 2000x1500.

It might still be worth checking that it _remains_ at that size, especially on MacOS given the behaviour described there.

**Comment by rdb** [comment]
By "asynchronous" I don't mean "runs in the background", I mean that it may happen in the next frame.  Adding `time.sleep(1)` will not do anything to apply the properties.  Calling `base.graphicsEngine.renderFrame()` might.  You'd have to check the actual window properties to see what changed.

Do you have a complete, runnable sample to demonstrate the problem?

**Comment by rdb** [comment]
Oh, I just noticed in your code you are combining getting the mouse position from MouseWatcher and setting it via the GraphicsWindow interface.  Those two are not updated at the same time, so I strongly recommend using `base.win.getPointer(0)` instead, which will return a more up-to-date mouse position.

**Comment by hoba87** [comment]
Yes, with using getPointer(0) the issue is gone. (The MacOS specific issue I will check soon)
