### ISSUE TITLE
Support pickling SparseArray and BitArray

### ISSUE THREAD

**Issue by Epihaius** [panda3d/panda3d#886]
When trying to pickle a SparseArray, I get the following error:

```
TypeError: can't pickle panda3d.core.SparseArray objects
```

Test code to reproduce:

```python
from panda3d.core import SparseArray
import pickle

a = SparseArray()
pickle.dumps(a, -1)
```

My current workaround is to convert the SparseArray to a list containing `(subrange_begin, subrange_end)` tuples and pickle that instead, but it would be nice if I could just pickle the SparseArray itself.

This happens with Panda3D 1.10.6.
Looks like it's related to Python 3 as it works with an old Panda version that uses Python 2.7.

**Comment by rdb** [comment]
Does pickling a SparseArray actually work with Python 2?  How does it do that?  There is no pickling protocol implemented for SparseArray.

**Comment by Epihaius** [comment]
Ah, that's strange. I tested this by simply printing the pickled value, which yields this output:

`'\x80\x02cpanda3d.core\nSparseArray\nq\x00)\x81q\x01.'`

This made me think it actually worked, but when I try to print the result of the unpickled value, the Python interpreter crashes. Funny that neither pickling nor unpickling throw any errors, though.

I'd also like to mention that the same thing happens with a BitArray. Should I open a separate issue for that one?

**Comment by rdb** [comment]
I get this when I unpickle your string:
```
❯ python -m pickle test
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/pickle.py", line 1805, in <module>
    pprint.pprint(obj)
  File "/usr/lib/python3.8/pprint.py", line 53, in pprint
    printer.pprint(object)
  File "/usr/lib/python3.8/pprint.py", line 148, in pprint
    self._format(object, self._stream, 0, 0, {}, 0)
  File "/usr/lib/python3.8/pprint.py", line 170, in _format
    rep = self._repr(object, context, level)
  File "/usr/lib/python3.8/pprint.py", line 404, in _repr
    repr, readable, recursive = self.format(object, context.copy(),
  File "/usr/lib/python3.8/pprint.py", line 417, in format
    return _safe_repr(object, context, maxlevels, level, self._sort_dicts)
  File "/usr/lib/python3.8/pprint.py", line 569, in _safe_repr
    rep = repr(object)
TypeError: C++ object is not yet constructed, or already destructed.
```
This is what the pickle actually contains:
```
❯ python -m pickletools test
    0: \x80 PROTO      2
    2: c    GLOBAL     'panda3d.core SparseArray'
   28: q    BINPUT     0
   30: )    EMPTY_TUPLE
   31: \x81 NEWOBJ
   32: q    BINPUT     1
   34: .    STOP
highest protocol among opcodes = 2
```

I think it's just treating it like a Python class that it can set the instance dictionary of, without needing to call `__init__`, so it never gets initialized properly.

I think we just need to provide `__getstate__` and `__setstate__`.  No need in this case to file a separate issue for BitArray.

**Comment by Epihaius** [comment]
OK, thanks in advance!

**Comment by rdb** [comment]
I've made BitArray, SparseArray, and BitMask (including DoubleBitMask and QuadBitMask) pickleable.  Sorry for the delay, I was busy with PyWeek last week.

BitArray is actually pickled as a Python long integer, which seemed like the most efficient way to pack it.  By extension, a BitArray can now be constructed from a Python long int.

**Comment by Epihaius** [comment]
Thank you very much for these enhancements!

**Comment by Epihaius** [comment]
@rdb To my surprise I just discovered that these changes weren't picked up for the current release (1.10.7).
Would it be possible to include them in the next Panda version (1.10.8), or is there a special reason you have set 1.11.0 as target milestone?

Without these changes, the users of my project will experience a crash when creating certain types of objects, unless they use an old [development version](http://buildbot.panda3d.org/downloads/94571aac93b5948adf0f4530cd6e6690408c6230/).

**Comment by rdb** [comment]
There are substantial API changes in there that are not appropriate for a bugfix release.

I'll have to think about how I can backport the pickling changes specifically to be able to go in 1.10.8.

**Comment by Epihaius** [comment]
Ah, sorry for the inconvenience!

Should it not work out, I'll inform my project's users that they should either wait for the next stable release or just put up with the development version.

Thanks in any case for wanting to fix this!
