### ISSUE TITLE
Shadow Maps stop updating when FilterManager.cleanup() is called

### ISSUE THREAD

**Issue by Moguri** [panda3d/panda3d#890]
When calling `FilterManager.cleanup()`, shadow maps stop updating for me. The textures appear to still be around. I have narrowed things down a bit to the `self.engine.removeWindow()` call in `FilterManager.cleanup()`. I believe the light's sbuffers become somehow unusable, but the array is not cleared out, so `GraphicsStateGuardian::get_shadow_map()` does not create a new sbuffer. The following code on a light will get the shadow maps to update again:
```python
light.set_shadow_caster(False)
light.set_shadow_caster(True)
```

This problem can be seen with a modified version of the basic shadow sample:
```diff
index 722aeb0643,722aeb0643..28e7e7ec44
--- a/samples/shadows/basic.py
+++ b/samples/shadows/basic.py
@@@ -9,6 -9,6 +9,7 @@@ from direct.interval.IntervalGlobal imp
  from direct.gui.DirectGui import OnscreenText
  from direct.showbase.DirectObject import DirectObject
  from direct.actor import Actor
++from direct.filter.FilterManager import FilterManager
  from random import *
  
  # Function to put instructions on the screen.
@@@ -117,6 -117,6 +118,11 @@@ class World(DirectObject)
          self.incrementCameraPosition(0)
          self.incrementLightPosition(0)
  
++        manager = FilterManager(base.win, base.cam)
++        Texture.setTexturesPower2(ATS_none)
++        manager.renderSceneInto(colortex=Texture())
++        self.accept("space", manager.cleanup)
++
      def toggleInterval(self, ival):
          if ival.isPlaying():
              ival.pause()
```

**Comment by rdb** [comment]
This is a regression in 7ee9467f8da4211b82e9f40dd194f8204271cf78, which causes it to no longer propagate the host output.  In other words, it has used the buffer as host instead of the actual host window.

We might also want the code to automatically recreate the buffer if it has become invalid, as extra redundancy.

**Comment by rdb** [comment]
> We might also want the code to automatically recreate the buffer if it has become invalid, as extra redundancy.

I tried this but this is not trivial under the current architecture; just adding an `is_valid()` check will fail as the buffer is still being created the first time around.  I have left this for now to revisit later if we run into a similar issue again.  The issue in question is fixed, anyhow.
