### ISSUE TITLE
pstats missing from 1.10.6.post1 manylinux1_x86_64 wheel

### ISSUE THREAD

**Issue by Moguri** [panda3d/panda3d#891]
The 1.10.6.post1 manylinux1_x86_64 wheel is missing pstats. 1.10.6 still includes pstats, which should narrow things down. I do not know if wheels for other platforms are missing pstats as well.

**Comment by rdb** [comment]
Odd, looks like gtk2 was installed but makepanda couldn't find it.  I wonder what changed.  I'll look into it.

**Comment by rdb** [comment]
Ah, it's because I installed an updated X11 in the container, which caused this error to be generated:
```
# pkg-config --libs gtk+-2.0
Package xcb was not found in the pkg-config search path.
Perhaps you should add the directory containing `xcb.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xcb', required by 'X11', not found
```
I'll fix this.

**Comment by rdb** [comment]
Panda3D 1.10.6.post2 manylinux wheels, including pstats, are up on PyPI.
