### ISSUE TITLE
Sample in 18_Vehicle.py tire is wobbly when accelerating and turning

### ISSUE THREAD

**Issue by Nickan** [panda3d/panda3d#896]
Hi,

I attached 2 images which makes tire wobbly, I haven't modify the code, what could be the reason why? I am running on Ubuntu 18.04LTS, Intel graphics HD 630, installed Panda3D using pip.

![Screenshot from 2020-04-01 11-41-42](https://user-images.githubusercontent.com/3498992/78097473-f363f580-740e-11ea-8638-e89ff5d2d057.png)
![Screenshot from 2020-04-01 11-41-22](https://user-images.githubusercontent.com/3498992/78097476-f6f77c80-740e-11ea-9b5f-ee6c774b824a.png)

**Comment by rdb** [comment]
When did you install panda3d from pip, exactly?  Shortly after we released 1.10.6, we realised that we built it against an unstable version of Bullet, so we uploaded new wheels to PyPI.  It would be great if you could verify that you have the latest by doing `pip install panda3d==1.10.6.post2`.

**Comment by Nickan** [comment]
It was weeks ago, I wasn't interested using Bullet way back then, but your suggestion solved the glitch. Thank you very much!

**Comment by rdb** [comment]
Glad to hear it was solved with the upgrade.  Closing this issue.
