### ISSUE TITLE
SegFault when creating CollisionPolygon

### ISSUE THREAD

**Issue by fireclawthefox** [panda3d/panda3d#908]
Creating a CollisionPolygon with only the begin and end points results in a segmentation fault crash.
**Note:** Adding the two points that would've been passed to the 4 arguments constructor to a list fixes the segmentation fault problem but it still seems the polygon won't be created correct.

```
from panda3d.core import CollisionPolygon, Point3
# uncommenting the following line fixes the segfault
#points = [Point3(-1, -1, 0), Point3(-1, 1, 0)]
CollisionPolygon(Point3(1, 1, 0), Point3(-1, -1, 0))
```

**Comment by rdb** [comment]
It's because that form of the constructor expects a C array, but is erroneously exposed to Python. We just need to un-expose it.

**Comment by Epihaius** [comment]
> It's because that form of the constructor expects a C array, but is erroneously exposed to Python. We just need to un-expose it.

Shouldn't [this form of `verify_points`](https://github.com/panda3d/panda3d/blob/7d94f601dbe8e3c1fda06dbbce9745a4200e71b7/panda/src/collide/collisionPolygon.cxx#L99) be un-exposed then, too?

**Comment by rdb** [comment]
Thanks, fixed.
