### ISSUE TITLE
ShaderGenerator ignores material alpha

### ISSUE THREAD

**Issue by Epihaius** [panda3d/panda3d#912]
Hi,

[This forum topic](https://discourse.panda3d.org/t/material-with-transparency-working-in-pview-but-not-in-game/25918) has revealed an apparent issue with material alpha being disregarded by the ShaderGenerator, where the fixed-function pipeline does seem to do the expected thing.

It does not seem to be related to any of the other ShaderGenerator/alpha issues I reported in the past (although it could be, even if only indirectly), hence this new report.

Anyway, here is some code that should create some transparency in this matter:

```python
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase


class MyApp(ShowBase):

    def __init__(self):

        ShowBase.__init__(self)

        dir_light = DirectionalLight("light")
        dir_light.set_color((1., 1., 1., 1.))
        light_np = self.render.attach_new_node(dir_light)
        light_np.set_hpr(-20., -20., 0.)
        self.render.set_light(light_np)
        self.render.set_shader_input("light", light_np)
        # activate the ShaderGenerator
        self.render.set_shader_auto()

        model = self.loader.load_model("smiley").get_child(0)
        model.set_y(4.)

        # create a copy of the smiley model to show through the transparent model
        model.copy_to(self.render)

        model.reparent_to(self.render)
        model.set_y(3.)
        # clear the render state of the model to remove its texture
        model.node().set_geom_state(0, RenderState.make_empty())
        mat = Material()
        mat.set_diffuse((0., 1., 0., .5))
#        model.set_alpha_scale(.5)
        model.set_material(mat)
        model.set_transparency(TransparencyAttrib.M_alpha)

app = MyApp()
app.run()
```

These are the results that I am getting:

* using the ShaderGenerator: a fully opaque sphere;
* using the FFP: the sphere is transparent such that the smiley behind it shows through.

Workarounds include setting an explicit alpha scale or transparent texture on the model, although I'm not convinced that either of these should effectively be a requirement.

Tested with Panda3D version 1.10.6 on Windows 10.

**Comment by Moguri** [comment]
I believe [this code](https://github.com/panda3d/panda3d/blob/master/panda/src/pgraphnodes/shaderGenerator.cxx#L1485):
```
    // Combine in alpha, which bypasses lighting calculations.  Use of lerp
    // here is a workaround for a radeon driver bug.                       
    if (key._calc_primary_alpha) {                                         
      if (key._color_type == ColorAttrib::T_vertex) {      
        text << "\t result.a = l_color.a;\n";                              
      } else if (key._color_type == ColorAttrib::T_flat) {                 
        text << "\t result.a = attr_color.a;\n";                           
      } else {                                                             
        text << "\t result.a = 1;\n";                                      
      }                                                                    
    }                                                                      
```

If I add a branch to for the material alpha into there, I can get the supplied sample program to work. However, I am not quite sure what the correct behavior should be:

* Use the material alpha if the F_diffuse flag is present?
* Multiply the material alpha with the vertex alpha if F_diffuse is present?
* Only make use of the material alpha if the alpha is < 1.0?

I am leaning toward always multiplying in the material alpha if the diffuse color is available. Thoughts?

**Comment by Moguri** [comment]
I went ahead and uploaded a PR (PR #925) for multiplying in the material color. If this is not what we want to do, then go ahead and reject/close the PR. I figured I might as well upload what I was playing with.
