### ISSUE TITLE
setuptools: Numpy libraries have been moved in version 1.18.3

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#914]
Until now, the numpy c-extension libraries were stored in .libs at the root of the wheel package. However since numpy 1.18.3, they have been moved to numpy.libs instead, which break the existing support in setuptools.

https://github.com/panda3d/panda3d/blob/9e80282affb4ce19430fdd3e16d4b3ec4d49e2b8/direct/src/dist/commands.py#L675

The current workaround is to add in one's setup.py :

            'package_data_dirs':
            {
             'numpy': [('numpy.libs/*', '', {'PKG_DATA_MAKE_EXECUTABLE'})],
            },

A fix would be to add to PACKAGE_LIB_DIRS something like

    'numpy':  ['numpy.libs']

**Comment by rdb** [comment]
Hmm, if this is a general pattern that other libraries are following, perhaps we can automatically pick up packagename+'.libs'.  Otherwise, the suggested fix makes sense.

**Comment by rdb** [comment]
Pillow also appears to have adopted this pattern.  Going to make this a general case.

**Comment by rdb** [comment]
Fix checked in as d659a3b0ffc13770feb05da07662f9c116a86845, wheels are available, testing would be appreciated!

**Comment by el-dee** [comment]
Tested with numpy-1.19.0, it works fine now without any workaround needed :)
