### ISSUE TITLE
Built tools for macOS: File format does not match file name

### ISSUE THREAD

**Issue by Feuermurmel** [panda3d/panda3d#920]
To build Panda3D from source, I've downloaded the built tools for macOS linked in the [build instructions for macOS](https://github.com/panda3d/panda3d#macos). That section contains the following link:

`https://www.panda3d.org/download/panda3d-1.10.6/panda3d-1.10.6-tools-mac.tar.gz`

Trying to download and decompress it yields an error.

```
$ wget 'https://www.panda3d.org/download/panda3d-1.10.6/panda3d-1.10.6-tools-mac.tar.gz'
--2020-04-26 13:26:23--  https://www.panda3d.org/download/panda3d-1.10.6/panda3d-1.10.6-tools-mac.tar.gz
Resolving www.panda3d.org (www.panda3d.org)... 128.2.236.121
Connecting to www.panda3d.org (www.panda3d.org)|128.2.236.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 610836480 (583M) [application/x-gzip]
Saving to: ‘panda3d-1.10.6-tools-mac.tar.gz’

panda3d-1.10.6-tool 100%[===================>] 582.54M  6.91MB/s    in 93s     

2020-04-26 13:27:57 (6.26 MB/s) - ‘panda3d-1.10.6-tools-mac.tar.gz’ saved [610836480/610836480]

$ tar -xzf panda3d-1.10.6-tools-mac.tar.gz 
gzip: unknown compression format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

It seems that this is not a GZIP-compressed file, as the file name suggests. The file is actually an uncompressed TAR archive and extracting it as such works:

```
$ file panda3d-1.10.6-tools-mac.tar.gz 
panda3d-1.10.6-tools-mac.tar.gz: POSIX tar archive (GNU)
$ tar -xf panda3d-1.10.6-tools-mac.tar.gz
```

So, two points:

- The file name does not match the file format, so my standard tooling had trouble dealing with it.
- The file _could_ be compressed to save some space (about 75%).

**Comment by rdb** [comment]
Oops, I might have just mistyped the `tar` command.  My bad.
