### ISSUE TITLE
egg loader crashes python

### ISSUE THREAD

**Issue by kostasmarkakis** [panda3d/panda3d#923]
Hello
i am facing a very annoying problem when trying to load a particular egg (sorry i dont see a file uploader here in order to provide you with the file). my python crashes with:

**Process finished with exit code -1073741571 (0xC00000FD)**

The egg file itself is fine, i was able to open it with pview. my program crashes only on this particular egg not in others. my trace shows that the library responsible is libpandaegg.dll. 

raising the issue on the panda3d forum i was able to find out that the problem is caused only in windows (i am using windows 10). With python 3.6.9 and panda3d 1.10.6 it works on linux but not on windows 10.

This egg is created with the obj2egg.exe program and the original obj is created in blender. Now, creating the file in the fbx format and reading directly the fbx in panda3d fixed my problem. so i am dicumenting the problem for future reference.

cheers

**Comment by rdb** [comment]
You will need to send the .egg file somehow for us to be able to reproduce this error.

Are you using a 32-bit or 64-bit build of Python+Panda3D?

**Comment by kostasmarkakis** [comment]
i am using 64-bit for both.

**Comment by rdb** [comment]
You will need to attach the .egg file or we will have no choice but to close this issue.

**Comment by Moguri** [comment]
Closing this. Please feel free to re-open this report if/when you have an EGG file we can look at.
