### ISSUE TITLE
codesign --remove-signature sometimes grows files into the gigabyte-range

### ISSUE THREAD

**Issue by Feuermurmel** [panda3d/panda3d#927]
I started building custom wheels of Panda3D from the `release/1.10.x` branch and came across a strange issue. Some files from the wheel where quite large after installation into the virtualenv (hundreds of MB to 1 or 2 GB). Turns out, `codesign --remove-signature`, added in 783c721cefa32d56b440605f776678634a013a28, is growing those files, seemingly at random. Others have also run into this issue: https://stackoverflow.com/questions/7500381/bug-in-codesign-remove-signature-feature

I'm running macOS 10.13.6 and have Xcode 10.1 installed.

My suggestion is to instead use `codesign` to add an ad-hoc signature to the binaries in question, e.g.:

```diff
@@ -444,7 +444,7 @@ class WheelFile(object):
 
                 # Remove the codesign signature if we modified the library.
                 if remove_signature:
-                    subprocess.call(["codesign", "--remove-signature", temp.name])
+                    subprocess.call(["codesign", "--force", "--sign", "-", temp.name])
             else:
                 # On other unixes, we just add dependencies normally.
                 for dep in deps:
```

Sadly, I lack the knowledge to assess the implications of this. From my understanding, an ad-hoc signature should not change the behavior for the end user compared to no signature at all. There's some more info in this AskDifferent answer: [Should I sign open source code myself?](https://apple.stackexchange.com/questions/343912/should-i-sign-open-source-code-myself/343934#343934)

**Comment by rdb** [comment]
Firstly, is this only growing files that didn't have a signature, or even the ones that did have a signature?

Secondly, if we re-sign them, we should test whether that has any effect on the installability of binaries deployed with build_apps.

**Comment by Feuermurmel** [comment]
> Firstly, is this only growing files that didn't have a signature, or even the ones that did have a signature?

The massively increased file size happened for me with the following files:

```
_curses_panel.cpython-38-darwin.so
_ssl.cpython-38-darwin.so
deploy-stubw
libpandaai.1.10.dylib
libpanelw.5.dylib
libpython3.8.dylib
libssl.1.1.dylib
readline.cpython-38-darwin.so
x2egg
```

Some of these do have signatures, e.g. `libpython3.8.dylib`, others do not, e.g. `x2egg`.

> Secondly, if we re-sign them, we should test whether that has any effect on the installability of binaries deployed with build_apps.

What I did test was that I built an app using `build_apps`, copied it to another Mac running macOS 10.13.6 and opened it there. The behavior was the same with or without my proposed change (needing to go through _Security $ Privacy_ preference pane). But I don't know what all the scenarios are, that need to be tested, especially in regards to more recent macOS releases.

**Comment by rdb** [comment]
I suggest we do two things:
1. On release/1.10.x branch, add a check that if the binary has no signature, `codesign --remove-signature` is not run on it
2. On the master branch, we sign everything with an ad-hoc signature, using `codesign -f -s -`.

I don't know how else to address this (without causing a potentially significant change in behaviour in a stable release).  It won't solve the problem for the Python dylibs, but it doesn't seem to be a problem for the official wheels at least.
