### ISSUE TITLE
Webcam Render on face

### ISSUE THREAD

**Issue by gauravgola96** [panda3d/panda3d#933]
How can I open webcam and render objects on the face and change its texture from a UV map png. 
Cannot find any such example. 
TIA

**Comment by rdb** [comment]
Hi, it looks like this is a support question, it would be better to ask this in the forums:
https://discourse.panda3d.org/
For what it's worth, you probably want to look at the WebcamVideo class and use it with a MovieTexture to get the webcam video as texture, which you can apply to an UV-mapped head model.
