### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [panda3d/panda3d#934]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [LwoToEggConverter::cleanup](https://github.com/panda3d/panda3d/blob/371e60c768cfd1a1383c5b05f1cab2078014ccea/pandatool/src/lwoegg/lwoToEggConverter.cxx#L195 "LwoToEggConverter::cleanup")
- [MeshDrawer2D::begin](https://github.com/panda3d/panda3d/blob/371e60c768cfd1a1383c5b05f1cab2078014ccea/panda/src/grutil/meshDrawer2D.cxx#L86 "MeshDrawer2D::begin function")
- [Time_Accumulator](https://github.com/panda3d/panda3d/blob/371e60c768cfd1a1383c5b05f1cab2078014ccea/panda/src/nativenet/time_accumulator.h#L44 "Destructor for Time_Accumulator")

**Comment by elfring** [comment]
Thanks for [your small source code improvements](https://github.com/panda3d/panda3d/commit/1ff11c1e164cbe36e44e045f350c40047b0da5af "Removal of a few unnecessary checks").

* [Were any update candidates left over](https://github.com/panda3d/panda3d/blob/371e60c768cfd1a1383c5b05f1cab2078014ccea/panda/src/grutil/meshDrawer.cxx#L106 "Update candidate: MeshDrawer::begin()")?
* How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by rdb** [comment]
I've cleaned up another bunch of "update candidates".

I'm not opposed in principle to something like clang-tidy, but I do not want anyone to spend a disproportionate amount of time doing cleanups (especially if these do not measurably hurt code performance or readability).

**Comment by elfring** [comment]
Thanks for [further source code improvements](https://github.com/panda3d/panda3d/commit/e4573ef0fe524d90f1563e8740e932ef7f22cd93 "Removal of some unnecessary checks").

**Comment by rdb** [comment]
It actually looks like these changes were quite harmful, and caused our test suites to crash, because until C++14 the standard does not promise that the deallocator is not called if custom allocators are used.

I'm going to see if we can handle this in our custom deallocators, or if we need to back these changes out again.
