### ISSUE TITLE
Node becomes unflattenable once a python tag is set.

### ISSUE THREAD

**Issue by janEntikan** [panda3d/panda3d#936]
Take the following code. The cards are flatten-able until set_python_tag() is called. Clearing the tag with clear_python_tag() afterwards does not fix this. 

```
from panda3d.core import NodePath, CardMaker
 
 
cardmaker = CardMaker("card")
cards = NodePath("cards")
a = cards.attach_new_node(cardmaker.generate())
b = cards.attach_new_node(cardmaker.generate())
a.set_python_tag("cardmaker", cardmaker)
a.clear_python_tag("cardmaker")
cards.flatten_strong()
cards.ls()
```

**Comment by rdb** [comment]
This is because of the way that tags are stored; the C++ code can't know that the tags on the Python end have been removed.

I want to revisit the way Python tags are stored.  In the meantime, I think I can come up with a workaround for this case.

**Comment by janEntikan** [comment]
A solution could also be to discard the tags when flattened with flatten_strong() (which is what I initially expected to happen)
