### ISSUE TITLE
deploy-ng: Flush stdout and stderr when exception occurs

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#946]
On Windows when a binary app generated using deploy-ng exits, the stdout and stderr streams are not flushed and as the output is aggressively buffered, up to 4KB of logs are lost.

See this old post (that I just remembered :) ) https://discourse.panda3d.org/t/deploy-ng-stdout-is-not-present-in-log-on-windows/24676/11

**Comment by rdb** [comment]
Seems easy enough.  Could have sworn I already had done this.

**Comment by rdb** [comment]
I checked this in a while ago, would you be willing to test this sometime to see if it works?  Any recent wheels from the release branch will have contained this fix.

**Comment by el-dee** [comment]
Just tested with the latest 1.10.7.dev wheel, but my app immediately crashes at start up without any log except the "known pipe types" log from Panda... (It still works like a charm with 1.10.6 though). If the crash is caused by a Python exception, it is not flushed to the output.log file.

I will investigate this problem by switching the app to console mode, but I need to reinstall a dev environment on my window partition first.

**Comment by el-dee** [comment]
I rebuilt the dist today using exactly the same wheel (1.10.7.dev48) and it works fine, but the dist of yesterday still crashes. Comparing the two, only panda3d.core.pyd, direct.pyd and egg.pyd are different. Copying panda3d.core.pyd from the new to the old dist makes it work again... So, there might have been a file corruption somewhere.

The good news is that the fix for the log flushing seems to work :)

**Comment by rdb** [comment]
That *is* rather odd, hmm.  But glad that the fix works, and thanks for testing!
