### ISSUE TITLE
DirectionalLight in headless rendering

### ISSUE THREAD

**Issue by zdens** [panda3d/panda3d#956]
Hi all,
I'm a bit confused due to DirectionalLight is not affecting models in the scene in case of rendering to texture without opening window.

Using the code below I obtain the total brightness of all image pixels
```python
from panda3d.core import *
loadPrcFileData("", "window-type none")
loadPrcFileData("", "load-display pandagles2")
from direct.showbase.ShowBase import ShowBase

class MyApp(ShowBase):

    def __init__(self):
        ConfigVariableString('window-type', 'none').setValue('none')

        self.base = ShowBase(windowType='offscreen')

        quat = LQuaternionf()
        quat.setFromAxisAngle(3*np.pi/4, LVector3f(0, 0, 1))

        directional_light = DirectionalLight('directionalLight')
        directional_light_np = self.base.render.attachNewNode(directional_light)
        self.base.render.setLight(directional_light_np)
        directional_light_np.setQuat(quat)
        print('{}'.format(quat.getHpr()))
       
        geom, points, connectivity = self.get_object_to_render()
        node = GeomNode('gnode')
        node.addGeom(geom)

        nodePath = NodePath(node)
        nodePath.reparentTo(self.base.render)
        nodePath.setPos(LPoint3f(0, 5, 0))
        directional_light_np.lookAt(nodePath)

        self.base.setBackgroundColor(0, 0, 0, 1)
        self.base.graphicsEngine.renderFrame()
        self.base.graphicsEngine.flipFrame()
        pnmimage = PNMImage()
        if self.base.win.getScreenshot(pnmimage):
            pnmimage.write("test_screenshot.png")
            x = pnmimage.getReadXSize()
            y = pnmimage.getReadYSize()
            pic_intensity = get_intensity(pnmimage, x, y)
            print("image_0 intensity: {}".format(pic_intensity))
```

Despite of the value of angle the total brightness obtained is about 709 and is not changed with changes in `quat.setFromAxisAngle(3*np.pi/4, LVector3f(0, 0, 1))`.

But if I use the same algorithm with the windowed script the image is strongly connected with the direction of light and if the angle is greater than or equaled to PI/2 the object is not seen.

What am I doing wrong?

**Comment by zdens** [comment]
@rdb , could you please take a look at this issue? can this problem be fixed somehow or is there any workaround?

**Comment by zdens** [comment]
ok, after about a week of digging I seem found an error.
`setFromAngleAxis` accepts angle in degrees that's why I didn't see any changes with my code.

**Comment by rdb** [comment]
You should probably switch to pandagl.  If you use pandagles2, you need to use custom shaders to make lights visible, because OpenGL ES 2 doesn't have a fixed-function pipeline.  In general, our desktop OpenGL renderer is much better.

**Comment by zdens** [comment]
if I understood correctly pandagl uses libGl.so which wants in turn for X11 to be installed. Yes?

**Comment by rdb** [comment]
See #557 — I recently checked in a change to the master branch that lets you run makepanda with the `--no-x11` flag, and it will build libpandagl with the context creation done by EGL rather than GLX.  Then it will work without a running X11 server.

**Comment by zdens** [comment]
I was wondering if installation of dependent libGL.so.1 requires for all X11 to be installed, but it don't.
so, pandagl seems to be a workaround for now.
I'll think about custom shaders, thank you.
