### ISSUE TITLE
Xbox game bar does not work in full screen

### ISSUE THREAD

**Issue by n33rj** [panda3d/panda3d#958]
Hello there,
I was running the hello world tutorials in windowed mode and used Xbox Game Bar (WinKey + G on windows 10) to check the frame rate.

When i did the same thing with Panda3D in full screen mode, it greeted me with this:
![Screenshot](https://user-images.githubusercontent.com/46842565/85201384-7fa1fc80-b31c-11ea-948f-167b76f28a60.jpg)

I tried changing config.prc to the following:
`undecorated 1'
'win-fixed-size 1'
but I got the same message.
Game bar worked well when using with pyglet in full screen. So IMO panda3d can change the way it goes full screen so that it is compatible with game bar.

**Comment by rdb** [comment]
fullscreen mode in Panda3D is "true" fullscreen.  It looks like it wants emulated fullscreen mode.  So you need to set `undecorated 1` and set the origin to 0, 0 and the size to your desktop size, without setting the fullscreen flag.

We could add a built-in borderless fullscreen mode for convenience.

**Comment by n33rj** [comment]
Hi, I thought I should let you know,
I played with different configuration settings and setting the window size as display size automatically toggles full screen mode. giving same results
However setting the origin with a 1 pixel offset keeps it in windowed mode and game bar works
'win-origin 0 1'
but it introduces a row of uncovered pixels at the top which becomes clearly visible if whatever is open behind the panda3d window has a bright color.

 Similarly setting the origin to 0 0 and resolution to 1366 767 (1 pixel less than height) also works with a row of uncovered pixels at the bottom

**Comment by n33rj** [comment]
Hi @rdb,
As stated [here](https://www.reddit.com/r/xboxinsiders/comments/eynk13/questions_regarding_xbox_game_bar_on_windows_10/) by Xbox staff:

> Game Bar cannot run over OpenGL or Vulkan games when they're in true full screen. Both of them rely on the driver for implementation so the behavior of Game Bar over them can change across different games and even different driver versions.

And for my previous comment about it going to fullscreen automatically:

> ... if you specify that an OpenGL run in fullscreen windows, the driver may choose to run it in true FS anyway. So windowed with borders is often the only way to get Game Bar running over it.

For general cases windowed undecorated works flawlessly and needs no attention.

Since the issue is with Xbox game bar itself and has nothing to do with panda3d, I close this issue.
Thank you for immediate support. 😃
